Repository scaleway/ultraviolet, pull requests merged in 2021-06, with the labels that each got.

#386 docs: improves documentation for components from l to n CNS-3985
  src/components/Label/__stories__/index.stories.mdx
  src/components/Label/index.js
  src/components/Link/__stories__/index.stories.mdx
  src/components/MarkDown/__stories__/index.stories.mdx
  src/components/MarkDown/__stories__/markdown_example.js
  src/components/MenuIcon/__stories__/index.stories.mdx
  src/components/Modal/__stories__/index.stories.mdx
  src/components/Modal/index.js
  src/components/Notice/__stories__/index.stories.mdx
  src/components/NotificationBar/__stories__/index.stories.mdx
  src/components/NotificationBar/index.js
Labels: documentation

#385 feat(accessibility): enable storybook accessibility
  .storybook/main.js
  .storybook/preview.js
  package.json
  yarn.lock
Labels: enhancement

#387 docs: updated all C components doc
  src/components/CategoryIcon/__stories__/index.stories.mdx
  src/components/Chart/__stories__/index.stories.mdx
  src/components/Chart/index.js
  src/components/Checkbox/__stories__/index.stories.mdx
  src/components/Checkbox/__tests__/index.js
  src/components/Checkbox/index.js
  src/components/Command/__stories__/index.stories.mdx
  src/components/Container/__stories__/index.stories.mdx
  src/components/Container/index.js
  src/components/Counter/__stories__/index.stories.mdx
  src/components/Counter/index.js
Labels: documentation

#383 docs: updated all B components doc
  src/components/Badge/__stories__/index.stories.mdx
  src/components/BorderedBox/__stories__/index.stories.mdx
  src/components/BorderedBox/index.js
  src/components/Box/__stories__/index.stories.mdx
  src/components/Boxer/__stories__/index.stories.mdx
  src/components/Boxer/index.js
  src/components/Breadcrumbs/__stories__/index.stories.mdx
  src/components/Breadcrumbs/index.js
  src/components/BulletList/__stories__/index.stories.mdx
  src/components/BulletList/index.js
  src/components/Button/__stories__/index.stories.mdx
  src/components/Button/index.js
Labels: documentation

#411 fix: richselect innerRef
  src/components/RichSelect/index.js
Labels: bug

#395 docs: updated all P components doc
  src/components/PasswordCheck/__stories__/index.stories.mdx
  src/components/PasswordCheck/index.js
  src/components/PasswordStrengthMeter/__stories__/index.stories.mdx
  src/components/PasswordStrengthMeter/index.js
  src/components/Pentagon/__stories__/index.stories.mdx
  src/components/PhoneInput/__stories__/index.stories.mdx
  src/components/PhoneInput/index.js
  src/components/Placeholder/__stories__/index.stories.mdx
  src/components/Placeholder/__tests__/index.js
  src/components/Placeholder/index.js
  src/components/Popper/__stories__/index.stories.mdx
  src/components/Popper/index.js
  src/components/Progress/__stories__/index.stories.mdx
  src/components/Progress/index.js
  src/components/ProgressBar/__stories__/index.stories.mdx
  src/components/ProgressBar/index.js
  src/components/ProgressCircle/__stories__/index.stories.mdx
  src/components/ProgressCircle/index.js
  src/components/ProgressionButton/__stories__/index.stories.mdx
  src/components/ProgressionButton/index.js
Labels: documentation

#403 feat: merge ProgressCircle into ActivityIndicator
  src/components/ActivityIndicator/__stories__/index.stories.mdx
  src/components/ActivityIndicator/__tests__/__snapshots__/index.js.snap
  src/components/ActivityIndicator/__tests__/index.js
  src/components/ActivityIndicator/index.js
  src/components/Button/__tests__/__snapshots__/index.js.snap
  src/components/Button/index.js
  src/components/Checkbox/__tests__/__snapshots__/index.js.snap
  src/components/Checkbox/index.js
  src/components/ProgressCircle/__stories__/index.stories.mdx
  src/components/ProgressCircle/__tests__/__snapshots__/index.js.snap
  src/components/ProgressCircle/__tests__/index.js
  src/components/ProgressCircle/index.js
  src/components/RichSelect/__stories__/index.stories.mdx
  src/components/Table/__tests__/__snapshots__/index.js.snap
  src/components/Table/index.js
  src/components/Tag/index.js
  src/components/index.js
Labels: enhancement

#415 chore(lint): sort keys ont rollup config file
  rollup.config.mjs
Labels: refactor

#416 fix(button): button with as link doesn t forward disabled property
  src/components/Button/__stories__/index.stories.mdx
  src/components/Button/__tests__/__snapshots__/index.js.snap
  src/components/Button/__tests__/index.js
  src/components/Button/index.js
  src/components/Modal/__stories__/index.stories.mdx
Labels: bug

#420 feat(menu): add menu component
  src/components/Menu/Item.js
  src/components/Menu/__stories__/index.stories.mdx
  src/components/Menu/__tests__/__snapshots__/index.js.snap
  src/components/Menu/__tests__/index.js
  src/components/Menu/index.js
  src/components/index.js
Labels: enhancement

#442 fix(separator): add role and aria-orientation
  src/components/DateInput/__tests__/__snapshots__/index.test.js.snap
  src/components/Menu/__tests__/__snapshots__/index.js.snap
  src/components/Placeholder/__tests__/__snapshots__/index.js.snap
  src/components/Separator/__tests__/__snapshots__/index.js.snap
  src/components/Separator/index.js
  src/components/TextBox/__tests__/__snapshots__/index.test.js.snap
Labels: enhancement

#441 refactor: adds extra color into SWUI
  src/theme/colors.js
Labels: migration

#443 docs(menu): add description
  src/components/Menu/__stories__/index.stories.mdx
Labels: documentation

#447 fix(Slider): correct drag image object
  src/components/Slider/index.js
Labels: bug

#391 feat: add FlexBox component
  src/__stories__/Customization.stories.mdx
  src/components/Badge/__stories__/index.stories.mdx
  src/components/Chart/__tests__/__snapshots__/index.js.snap
  src/components/Container/__tests__/__snapshots__/index.js.snap
  src/components/Container/index.js
  src/components/Counter/__stories__/index.stories.mdx
  src/components/DotSteps/__tests__/__snapshots__/index.js.snap
  src/components/DotSteps/index.js
  src/components/FlexBox/__stories__/index.stories.mdx
  src/components/FlexBox/__tests__/__snapshots__/index.js.snap
  src/components/FlexBox/__tests__/index.js
  src/components/FlexBox/index.js
  src/components/IconMessage/__tests__/__snapshots__/index.js.snap
  src/components/IconMessage/index.js
  src/components/Information/__stories__/index.stories.mdx
  src/components/MenuIcon/__stories__/index.stories.mdx
  src/components/Pentagon/__stories__/index.stories.mdx
  src/components/Popper/__stories__/index.stories.mdx
  src/components/RadioBorderedBox/__tests__/__snapshots__/index.js.snap
  src/components/RadioBorderedBox/__tests__/index.js
  src/components/RadioBorderedBox/index.js
  src/components/RichSelect/__stories__/index.stories.mdx
  src/components/Separator/__stories__/index.stories.mdx
  src/components/TagsPoplist/__tests__/__snapshots__/index.js.snap
  src/components/TagsPoplist/index.js
  src/components/Tooltip/__stories__/index.stories.mdx
  src/components/Tooltip/__tests__/__snapshots__/index.js.snap
  src/components/Tooltip/index.js
  src/components/TooltipIcon/__tests__/__snapshots__/index.js.snap
  src/components/index.js
Labels: enhancement

#453 feat(icons): add sun - moon and github svg icons
  src/components/Icon/index.js
Labels: enhancement

#461 docs: add i documentation
  src/components/Icon/__stories__/index.stories.mdx
  src/components/Icon/index.js
  src/components/IconMessage/__stories__/index.stories.mdx
  src/components/IconMessage/index.js
  src/components/Image/__stories__/index.stories.mdx
  src/components/Information/__stories__/index.stories.mdx
Labels: documentation

#459 docs: add e and g documentation
  src/components/Expandable/__stories__/index.stories.mdx
  src/components/Expandable/index.js
  src/components/ExtendedReminder/__stories__/index.stories.mdx
  src/components/ExtendedReminder/index.js
  src/components/Grid/Col.js
  src/components/Grid/Grid.js
  src/components/Grid/Row.js
  src/components/Grid/__stories__/index.stories.mdx
Labels: documentation

#467 refactor: merge icon, menuicon and categoryicon
  src/components/CategoryIcon/__stories__/index.stories.mdx
  src/components/CategoryIcon/__tests__/__snapshots__/index.js.snap
  src/components/CategoryIcon/__tests__/index.js
  src/components/CategoryIcon/index.js
  src/components/Icon/__stories__/index.stories.mdx
  src/components/Icon/__tests__/__snapshots__/index.js.snap
  src/components/Icon/index.js
  src/components/MenuIcon/__stories__/index.stories.mdx
  src/components/MenuIcon/__tests__/__snapshots__/index.js.snap
  src/components/MenuIcon/__tests__/index.js
  src/components/MenuIcon/index.js
  src/components/index.js
Labels: enhancement, refactor

#471 feat: d components documentation
  src/components/DateInput/__stories__/index.stories.mdx
  src/components/DateInput/index.js
  src/components/Description/__stories__/index.stories.mdx
  src/components/Description/index.js
  src/components/Dot/__stories__/index.stories.mdx
  src/components/Dot/index.js
  src/components/DotSteps/__stories__/index.stories.mdx
  src/components/DotSteps/index.js
Labels: documentation

#454 feat: add pagination
  .eslintrc
  src/components/List/SelectBar.js
  src/components/List/__stories__/index.stories.mdx
  src/components/List/__tests__/__snapshots__/index.js.snap
  src/components/List/__tests__/index.js
  src/components/List/index.js
  src/components/Pagination/__stories__/ExampleChildren.js
  src/components/Pagination/__stories__/index.stories.mdx
  src/components/Pagination/__tests__/__snapshots__/index.test.js.snap
  src/components/Pagination/__tests__/getPageNumbers.test.js
  src/components/Pagination/__tests__/index.test.js
  src/components/Pagination/getPageNumbers.js
  src/components/Pagination/index.js
  src/components/Pagination/usePaginatedData.js
  src/mocks/list.js
Labels: enhancement
