Repository scaleway/ultraviolet, pull requests merged in 2021-12, with the labels that each got.

#954 feat(icon): add serverless icon
  src/components/Icon/index.tsx
Labels: enhancement

#951 fix: a11y badge tests
  src/__tests__/a11y.test.tsx
  src/components/ActivityIndicator/__stories__/index.stories.tsx
  src/components/Badge/__tests__/__snapshots__/index.tsx.snap
  src/components/Badge/index.tsx
  src/components/ExtendedReminder/__tests__/__snapshots__/index.tsx.snap
  src/components/RadioBorderedBox/__tests__/__snapshots__/index.tsx.snap
Labels: accessibility

#919 feat: remove some of unnecessary boxes
  src/components/ActionBar/__tests__/__snapshots__/index.test.tsx.snap
  src/components/ActionBar/index.tsx
  src/components/Breadcrumbs/__tests__/__snapshots__/index.tsx.snap
  src/components/Breadcrumbs/index.tsx
  src/components/BulletList/__tests__/__snapshots__/index.tsx.snap
  src/components/BulletList/index.tsx
  src/components/Checkbox/__tests__/__snapshots__/index.tsx.snap
  src/components/Checkbox/index.tsx
  src/components/Container/__tests__/__snapshots__/index.tsx.snap
  src/components/Container/index.tsx
  src/components/CreationProgress/__tests__/__snapshots__/index.test.tsx.snap
  src/components/CreationProgress/index.tsx
  src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap
  src/components/DateInput/index.tsx
  src/components/Image/__tests__/__snapshots__/index.tsx.snap
  src/components/Image/index.tsx
  src/components/LineChart/CustomLegend.tsx
  src/components/LineChart/__tests__/__snapshots__/index.tsx.snap
  src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  src/components/List/index.tsx
  src/components/List/variantProduct.tsx
  src/components/MarkDown/__tests__/__snapshots__/index.tsx.snap
  src/components/MarkDown/index.tsx
  src/components/Notice/__tests__/__snapshots__/index.tsx.snap
  src/components/Pagination/__tests__/__snapshots__/index.test.tsx.snap
  src/components/Pagination/index.tsx
  src/components/PasswordStrengthMeter/__stories__/index.stories.tsx
  src/components/PasswordStrengthMeter/__tests__/__snapshots__/index.test.tsx.snap
  src/components/PasswordStrengthMeter/index.tsx
  src/components/Placeholder/Block.tsx
  src/components/Placeholder/__tests__/__snapshots__/index.tsx.snap
  src/components/RadioBorderedBox/__tests__/__snapshots__/index.tsx.snap
  src/components/RadioBorderedBox/index.tsx
  src/components/Reminder/__tests__/__snapshots__/index.tsx.snap
  src/components/RichSelect/__tests__/__snapshots__/index.tsx.snap
  src/components/RichSelect/index.tsx
  src/components/TagsPoplist/__stories__/index.stories.tsx
  src/components/TagsPoplist/__tests__/__snapshots__/index.tsx.snap
  src/components/TagsPoplist/__tests__/index.tsx
  src/components/TagsPoplist/index.tsx
  src/components/TextBox/__tests__/__snapshots__/index.test.tsx.snap
  src/components/TextBox/index.tsx
  src/components/TimeInput/__tests__/__snapshots__/index.tsx.snap
  src/components/UnitInput/__tests__/__snapshots__/index.tsx.snap
  src/components/VerificationCode/__tests__/__snapshots__/index.tsx.snap
  src/components/VerificationCode/index.tsx
  src/components/VolumeSize/__tests__/__snapshots__/index.tsx.snap
  src/components/VolumeSize/index.tsx
  src/theme/index.ts
Labels: refactor

#957 fix: a11y for counter
  src/__tests__/a11y.test.tsx
  src/components/Counter/__tests__/__snapshots__/index.test.tsx.snap
  src/components/Counter/__tests__/index.test.tsx
  src/components/Counter/index.tsx
Labels: accessibility

#959 feat(theme): creating new theme colors
  .eslintrc
  src/__stories__/Customization.stories.mdx
  src/__stories__/Index.stories.mdx
  src/components/ActivityIndicator/index.tsx
  src/components/Avatar/index.tsx
  src/components/Badge/__tests__/__snapshots__/index.tsx.snap
  src/components/Badge/index.tsx
  src/components/Button/__tests__/__snapshots__/index.tsx.snap
  src/components/Button/index.tsx
  src/components/Dot/index.tsx
  src/components/Icon/index.tsx
  src/components/Link/index.tsx
  src/components/List/variantExplorer.tsx
  src/components/List/variantProduct.tsx
  src/components/List/variantTable.tsx
  src/components/Pentagon/index.tsx
  src/components/PieChart/Legends.tsx
  src/components/Popper/index.tsx
  src/components/ProgressBar/index.tsx
  src/components/ProgressionButton/index.tsx
  src/components/Reminder/index.tsx
  src/components/Separator/index.tsx
  src/components/Sphere/index.tsx
  src/components/StatusIndicator/index.tsx
  src/components/Switch/index.tsx
  src/components/Typography/index.tsx
  src/index.ts
  src/theme/__tests__/index.ts
  src/theme/colors/contrasts.ts
  src/theme/colors/index.ts
  src/theme/deprecated/colors.ts
  src/theme/index.ts
Labels: enhancement

#978 fix(theme): fix neutral weak border color
  src/theme/__tests__/index.ts
  src/theme/colors/contrasts.ts
  src/theme/colors/index.ts
Labels: bug

#981 fix: update neutral colors once again
  src/components/Button/__tests__/__snapshots__/index.tsx.snap
  src/theme/__tests__/index.ts
  src/theme/colors/index.ts
Labels: bug

#997 fix(theme): updated neutral background color
  src/components/Badge/__tests__/__snapshots__/index.tsx.snap
  src/components/Button/__tests__/__snapshots__/index.tsx.snap
  src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  src/components/Pagination/__tests__/__snapshots__/index.test.tsx.snap
  src/theme/__tests__/index.ts
  src/theme/colors/index.ts
Labels: migration

#977 refactor: migrate ActionBar, ActivityIndicator, Alert, Avatar deprecated color with new system
  src/components/ActionBar/__tests__/__snapshots__/index.test.tsx.snap
  src/components/ActionBar/index.tsx
  src/components/ActivityIndicator/__stories__/index.stories.tsx
  src/components/ActivityIndicator/__tests__/__snapshots__/index.test.tsx.snap
  src/components/ActivityIndicator/index.tsx
  src/components/Alert/index.tsx
  src/components/Avatar/__stories__/index.stories.tsx
  src/components/Avatar/__tests__/__snapshots__/index.tsx.snap
  src/components/Avatar/index.tsx
  src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  src/theme/index.ts
Labels: refactor, migration

#1004 fix(theme): border colors
  src/components/Container/index.tsx
  src/theme/__tests__/index.ts
  src/theme/colors/contrasts.ts
  src/theme/colors/index.ts
Labels: migration

#987 refactor(theme): migrated colors of DotSteps ExtReminder Label…
  src/components/DotSteps/index.tsx
  src/components/ExtendedReminder/index.tsx
  src/components/Label/__tests__/__snapshots__/index.tsx.snap
  src/components/Label/index.tsx
  src/components/LineChart/CustomLegend.tsx
  src/components/LineChart/__tests__/__snapshots__/index.tsx.snap
  src/components/LineChart/index.tsx
  src/components/Link/__tests__/__snapshots__/index.tsx.snap
  src/components/Link/index.tsx
Labels: migration

#982 refactor(theme): colors migration Button, Breadcrumbs, BulletList…
  src/components/Breadcrumbs/__tests__/__snapshots__/index.tsx.snap
  src/components/Breadcrumbs/index.tsx
  src/components/BulletList/index.tsx
  src/components/Checkbox/__tests__/__snapshots__/index.tsx.snap
  src/components/Checkbox/index.tsx
  src/components/LineChart/__tests__/__snapshots__/index.tsx.snap
  src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  src/theme/__tests__/index.ts
  src/theme/colors/index.ts
Labels: migration

#1006 refactor(theme): revert border colors
  src/theme/__tests__/index.ts
  src/theme/colors/index.ts
Labels: migration

#1003 refactor: use new colors Notice, PasswordCheck,PasswordStrengthMeter, Pentagon, PhoneInput, PieChart
  src/components/Notice/index.tsx
  src/components/PasswordCheck/__tests__/__snapshots__/index.test.tsx.snap
  src/components/PasswordCheck/index.tsx
  src/components/PasswordStrengthMeter/__stories__/index.stories.tsx
  src/components/PasswordStrengthMeter/__tests__/__snapshots__/index.test.tsx.snap
  src/components/PasswordStrengthMeter/__tests__/index.test.tsx
  src/components/PasswordStrengthMeter/index.tsx
  src/components/Pentagon/__stories__/index.stories.tsx
  src/components/Pentagon/index.tsx
  src/components/PhoneInput/index.tsx
  src/components/PieChart/__tests__/__snapshots__/index.tsx.snap
  src/components/PieChart/index.tsx
Labels: refactor, migration

#976 refactor: less stories boilerplate
  .eslintrc
  src/__stories__/utils/decorators.tsx
  src/__stories__/utils/index.ts
  src/__stories__/utils/story.ts
  src/components/ActivityIndicator/__stories__/index.stories.tsx
  src/components/UnitInput/__tests__/__snapshots__/index.tsx.snap
  src/components/UnitInput/index.tsx
Labels: refactor

#979 feat: migrate badge, barchart, barstack to new colors
  src/components/BarChart/__tests__/__snapshots__/index.tsx.snap
  src/components/BarChart/index.tsx
  src/components/BarStack/__tests__/__snapshots__/index.test.tsx.snap
  src/components/BarStack/index.tsx
  src/components/LineChart/__tests__/__snapshots__/index.tsx.snap
  src/helpers/legend.ts
Labels: refactor, migration

#1007 fix(theme): colors
  src/components/Alert/index.tsx
  src/components/RadioBorderedBox/index.tsx
  src/components/Range/index.tsx
  src/theme/__tests__/index.ts
  src/theme/colors/index.ts
Labels: migration

#1005 refactor: colors on list menu modal navigationstepper components
  src/components/List/SelectBar.tsx
  src/components/List/__stories__/index.stories.tsx
  src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  src/components/List/__tests__/index.test.tsx
  src/components/List/variantExplorer.tsx
  src/components/List/variantProduct.tsx
  src/components/List/variantTable.tsx
  src/components/Menu/Item.tsx
  src/components/Menu/__tests__/__snapshots__/index.tsx.snap
  src/components/Menu/index.tsx
  src/components/Modal/__tests__/__snapshots__/index.tsx.snap
  src/components/Modal/index.tsx
  src/components/NavigationStepper/__tests__/__snapshots__/index.test.tsx.snap
  src/components/NavigationStepper/index.tsx
Labels: refactor

#1011 fix: button color
  src/components/Button/__tests__/__snapshots__/index.tsx.snap
  src/components/Button/index.tsx
  src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  src/components/Pagination/__tests__/__snapshots__/index.test.tsx.snap
Labels: bug, migration

#1012 refactor: colors for sphere statusindicator stealthcopiable stepper
  src/components/Dot/index.tsx
  src/components/Sphere/index.tsx
  src/components/StealthCopiable/index.tsx
  src/components/Stepper/__tests__/__snapshots__/index.tsx.snap
  src/components/Stepper/index.tsx
Labels: refactor

#1024 fix: list expandable color
  src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  src/components/List/variantProduct.tsx
Labels: bug

#1029 fix: a11y for stealthcopiable
  src/__tests__/a11y.test.tsx
  src/components/StealthCopiable/__tests__/__snapshots__/index.tsx.snap
  src/components/StealthCopiable/index.tsx
Labels: accessibility

#1008 refactor(theme): migration colors of Typography, VerificationCode, VolumeSize
  src/components/Typography/index.tsx
  src/components/VerificationCode/__tests__/__snapshots__/index.tsx.snap
  src/components/VerificationCode/index.tsx
  src/components/VolumeSize/__tests__/__snapshots__/index.tsx.snap
  src/components/VolumeSize/index.tsx
Labels: migration

#1017 feat: migrate switch to new colors
  src/components/Switch/__stories__/index.stories.tsx
  src/components/Switch/__tests__/__snapshots__/index.tsx.snap
  src/components/Switch/index.tsx
Labels: bug, enhancement

#1028 feat(toaster): add a11y
  src/__tests__/a11y.test.tsx
  src/components/Toaster/__tests__/__snapshots__/index.tsx.snap
  src/components/Toaster/index.tsx
Labels: accessibility

#1023 refactor(theme): new colors for Tag, Tags, TagsPoplist and TextBox
  src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap
  src/components/Tag/index.tsx
  src/components/Tags/__tests__/__snapshots__/index.tsx.snap
  src/components/Tags/index.tsx
  src/components/TagsPoplist/index.tsx
  src/components/TextBox/__tests__/__snapshots__/index.test.tsx.snap
  src/components/TextBox/index.tsx
  src/components/UnitInput/__tests__/__snapshots__/index.tsx.snap
  src/theme/__tests__/index.ts
  src/theme/colors/index.ts
Labels: migration

#1031 fix: a11y for placeholder
  src/__tests__/a11y.test.tsx
  src/components/Placeholder/__stories__/index.stories.tsx
  src/components/Placeholder/__tests__/__snapshots__/index.tsx.snap
  src/components/Placeholder/index.tsx
Labels: accessibility

#1039 fix: box sizing property on switch component
  src/components/Switch/__tests__/__snapshots__/index.tsx.snap
  src/components/Switch/index.tsx
Labels: bug

#1033 refactor(tags): add a11y
  src/__tests__/a11y.test.tsx
  src/components/Tag/index.tsx
  src/components/Tags/__tests__/__snapshots__/index.tsx.snap
  src/components/Tags/index.tsx
Labels: accessibility

#1027 refactor(theme): migrate colors for Toaster, Tooltip, TooltipIcon, UnitInput
  src/components/Toaster/index.tsx
  src/components/Tooltip/__tests__/__snapshots__/index.test.tsx.snap
  src/components/Tooltip/index.tsx
  src/components/TooltipIcon/__tests__/__snapshots__/index.tsx.snap
  src/components/UnitInput/index.tsx
  src/theme/__tests__/index.ts
  src/theme/colors/index.ts
Labels: migration

#1040 refactor(extended-reminder): add a11y
  src/__tests__/a11y.test.tsx
  src/components/ExtendedReminder/__tests__/__snapshots__/index.tsx.snap
  src/components/ExtendedReminder/index.tsx
Labels: accessibility

#1037 fix: a11y for markdown but mostly due to reminder
  src/__tests__/a11y.test.tsx
  src/components/MarkDown/__tests__/__snapshots__/index.tsx.snap
  src/components/MarkDown/index.tsx
  src/components/Reminder/__tests__/__snapshots__/index.tsx.snap
Labels: accessibility

#1043 docs(theme): updated theme and colors documentation
  .storybook/preview.js
  src/__stories__/Customization.stories.mdx
  src/__stories__/Theme.stories.mdx
Labels: documentation

#1032 refactor(a11y): stepper and a11y tests fix
  src/__tests__/a11y.test.tsx
  src/components/Stepper/__stories__/index.stories.tsx
  src/components/Stepper/__tests__/__snapshots__/index.tsx.snap
  src/components/Stepper/index.tsx
Labels: accessibility

#1052 feat: migrate tabgroup and table to new ds
  src/components/TabGroup/Tab.tsx
  src/components/TabGroup/__tests__/Tab.test.tsx
  src/components/TabGroup/__tests__/TabGroup.test.tsx
  src/components/TabGroup/__tests__/__snapshots__/Tab.test.tsx.snap
  src/components/TabGroup/__tests__/__snapshots__/TabGroup.test.tsx.snap
  src/components/TabGroup/index.tsx
  src/components/Table/__tests__/__snapshots__/index.tsx.snap
  src/components/Table/index.tsx
Labels: enhancement, refactor

#1036 refactor(a11y): volumeSize
  src/components/VolumeSize/__tests__/__snapshots__/index.tsx.snap
  src/components/VolumeSize/index.tsx
Labels: accessibility

#1071 fix: alert width to allow dismiss button
  src/components/Alert/__tests__/__snapshots__/index.test.tsx.snap
  src/components/Alert/index.tsx
  src/components/Toaster/__tests__/__snapshots__/index.tsx.snap
Labels: enhancement
