Repository scaleway/ultraviolet, pull requests merged in 2021-08, with the labels that each got.

#589 chore: start migration to typescript
  .eslintrc
  package.json
  src/components/ActionBar/__tests__/__snapshots__/index.test.tsx.snap
  src/components/ActionBar/__tests__/index.test.tsx
  src/components/ActionBar/index.tsx
  src/components/ActivityIndicator/__tests__/__snapshots__/index.test.tsx.snap
  src/components/ActivityIndicator/__tests__/index.test.tsx
  src/components/ActivityIndicator/index.tsx
  src/components/Tooltip/__tests__/__snapshots__/index.test.tsx.snap
  src/components/Tooltip/__tests__/index.test.tsx
  src/components/Tooltip/index.tsx
  src/components/Typography/__tests__/__snapshots__/index.test.tsx.snap
  src/components/Typography/__tests__/index.test.tsx
  src/components/Typography/index.js
  src/components/Typography/index.tsx
  src/emotion.d.ts
  src/theme/colors.js
  src/theme/colors.ts
  src/theme/index.ts
  tsconfig.json
  types/global.d.ts
  yarn.lock
Labels: typescript

#593 feat: migration utils and theme to typescript
  package.json
  src/theme/index.ts
  src/utils/animations.ts
  src/utils/ids.js
  src/utils/ids.ts
  src/utils/index.ts
  src/utils/orderBy.js
  src/utils/orderBy.ts
  src/utils/responsive/Breakpoint.tsx
  src/utils/responsive/__tests__/Breakpoint.test.tsx
  src/utils/responsive/__tests__/__snapshots__/Breakpoint.test.tsx.snap
  src/utils/responsive/__tests__/__snapshots__/utilities.js.snap
  src/utils/responsive/index.ts
  src/utils/responsive/utilities.js
  src/utils/responsive/utilities.ts
  types/emotion.d.ts
Labels: typescript

#600 feat(a11y): add tabs arrow navigation
  README.md
  src/components/TabGroup/Tab.js
  src/components/TabGroup/__tests__/TabGroup.test.js
  src/components/TabGroup/__tests__/__snapshots__/Tab.test.js.snap
  src/components/TabGroup/__tests__/__snapshots__/TabGroup.test.js.snap
  src/components/TabGroup/index.js
Labels: documentation, enhancement

#595 feat: typescript migration of alert and icon
  package.json
  src/components/ActionBar/index.tsx
  src/components/ActivityIndicator/index.tsx
  src/components/Alert/__tests__/__snapshots__/index.test.tsx.snap
  src/components/Alert/__tests__/index.test.tsx
  src/components/Alert/index.tsx
  src/components/Avatar/__tests__/__snapshots__/index.tsx.snap
  src/components/Avatar/__tests__/index.tsx
  src/components/Avatar/index.tsx
  src/components/Badge/__tests__/__snapshots__/index.tsx.snap
  src/components/Badge/__tests__/index.tsx
  src/components/Badge/index.tsx
  src/components/Box/__tests__/__snapshots__/index.tsx.snap
  src/components/Box/__tests__/index.tsx
  src/components/Box/index.js
  src/components/Box/index.tsx
  src/components/Boxer/__tests__/__snapshots__/index.tsx.snap
  src/components/Boxer/__tests__/index.tsx
  src/components/Boxer/index.js
  src/components/Boxer/index.tsx
  src/components/Breadcrumbs/__tests__/__snapshots__/index.tsx.snap
  src/components/Breadcrumbs/__tests__/index.tsx
  src/components/Breadcrumbs/index.tsx
  src/components/BulletList/__tests__/__snapshots__/index.tsx.snap
  src/components/BulletList/__tests__/index.tsx
  src/components/BulletList/index.tsx
  src/components/Icon/__tests__/__snapshots__/index.test.tsx.snap
  src/components/Icon/__tests__/index.test.tsx
  src/components/Icon/index.tsx
  src/components/Link/__tests__/__snapshots__/index.tsx.snap
  src/components/Link/__tests__/index.tsx
  src/components/Link/index.tsx
  src/components/Tooltip/index.tsx
  src/components/Typography/index.tsx
  src/components/UniversalLink/__tests__/__snapshots__/index.tsx.snap
  src/components/UniversalLink/__tests__/index.tsx
  src/components/UniversalLink/index.tsx
  src/components/index.ts
  src/theme/index.ts
  types/assets.d.ts
  types/global.d.ts
  yarn.lock
Labels: typescript

#612 chore: migrate highly depended on components to typescript
  src/components/Box/index.tsx
  src/components/Checkbox/__tests__/__snapshots__/index.js.snap
  src/components/DateInput/__tests__/__snapshots__/index.test.js.snap
  src/components/Expandable/__tests__/__snapshots__/index.tsx.snap
  src/components/Expandable/__tests__/index.tsx
  src/components/Expandable/index.js
  src/components/Expandable/index.tsx
  src/components/Grid/Col.tsx
  src/components/Grid/Grid.js
  src/components/Grid/Grid.tsx
  src/components/Grid/Row.js
  src/components/Grid/Row.tsx
  src/components/Grid/__tests__/__snapshots__/index.tsx.snap
  src/components/Grid/__tests__/index.tsx
  src/components/Grid/index.ts
  src/components/List/__tests__/__snapshots__/index.js.snap
  src/components/List/context.ts
  src/components/MarkDown/__tests__/__snapshots__/index.tsx.snap
  src/components/MarkDown/__tests__/index.tsx
  src/components/MarkDown/index.js
  src/components/MarkDown/index.tsx
  src/components/Notice/__tests__/__snapshots__/index.tsx.snap
  src/components/Notice/__tests__/index.tsx
  src/components/Notice/index.tsx
  src/components/Placeholder/Line.js
  src/components/Placeholder/Line.tsx
  src/components/Placeholder/__tests__/__snapshots__/index.js.snap
  src/components/Reminder/__tests__/__snapshots__/index.js.snap
  src/components/RichSelect/__tests__/__snapshots__/index.js.snap
  src/components/Separator/__tests__/__snapshots__/index.tsx.snap
  src/components/Separator/__tests__/index.tsx
  src/components/Separator/index.tsx
  src/components/TextBox/__tests__/__snapshots__/index.test.js.snap
  src/components/TimeInput/__tests__/__snapshots__/index.js.snap
  src/components/UnitInput/__tests__/__snapshots__/index.js.snap
  src/components/UniversalLink/__tests__/index.tsx
  src/theme/index.ts
  src/utils/__tests__/__snapshots__/index.tsx.snap
  src/utils/__tests__/index.tsx
  src/utils/responsive/__tests__/__snapshots__/utilities.ts.snap
  src/utils/responsive/__tests__/utilities.ts
Labels: typescript

#626 feat: migrate Slider, Sphere, StealthCopiable, Switch and SwitchButton to typescript
  src/components/Slider/index.tsx
  src/components/Sphere/__tests__/__snapshots__/index.tsx.snap
  src/components/Sphere/__tests__/index.tsx
  src/components/Sphere/index.tsx
  src/components/StealthCopiable/__tests__/__snapshots__/index.tsx.snap
  src/components/StealthCopiable/__tests__/index.tsx
  src/components/StealthCopiable/index.tsx
  src/components/Switch/__tests__/__snapshots__/index.tsx.snap
  src/components/Switch/__tests__/index.tsx
  src/components/Switch/index.tsx
  src/components/SwitchButton/__tests__/__snapshots__/index.tsx.snap
  src/components/SwitchButton/__tests__/index.tsx
  src/components/SwitchButton/index.tsx
  src/helpers/renderWithTheme.tsx
  src/helpers/shouldMatchEmotionSnapshot.ts
  src/helpers/shouldMatchEmotionSnapshotWithPortal.ts
Labels: typescript

#635 refactor(typescript): popper, button & placeholder components
  .github/workflows/size-limit.yml
  src/components/Alert/index.tsx
  src/components/Box/index.tsx
  src/components/Button/index.tsx
  src/components/Icon/index.tsx
  src/components/Placeholder/Block.tsx
  src/components/Placeholder/Blocks.tsx
  src/components/Placeholder/BoxWithIcon.js
  src/components/Placeholder/BoxWithIcon.tsx
  src/components/Placeholder/Donut.tsx
  src/components/Placeholder/List.tsx
  src/components/Placeholder/Slider.tsx
  src/components/Placeholder/__tests__/__snapshots__/index.tsx.snap
  src/components/Placeholder/__tests__/index.tsx
  src/components/Placeholder/index.tsx
  src/components/Popper/__tests__/__snapshots__/index.tsx.snap
  src/components/Popper/__tests__/index.tsx
  src/components/Popper/index.js
  src/components/Popper/index.tsx
  src/components/Separator/index.tsx
  types/global.d.ts
Labels: typescript

#632 feat: migrate some components to typescript
  package.json
  src/components/Image/index.js
  src/components/Image/index.tsx
  src/components/Label/__tests__/__snapshots__/index.tsx.snap
  src/components/Label/__tests__/index.tsx
  src/components/Label/index.js
  src/components/Label/index.tsx
  src/components/Pentagon/__tests__/__snapshots__/index.tsx.snap
  src/components/Pentagon/__tests__/index.tsx
  src/components/Pentagon/index.js
  src/components/Pentagon/index.tsx
  src/components/PhoneInput/__tests__/__snapshots__/index.tsx.snap
  src/components/PhoneInput/__tests__/index.tsx
  src/components/PhoneInput/index.tsx
  src/components/ProgressBar/__tests__/__snapshots__/index.tsx.snap
  src/components/ProgressBar/__tests__/index.tsx
  src/components/ProgressBar/index.tsx
  src/components/ProgressionButton/__tests__/__snapshots__/index.tsx.snap
  src/components/ProgressionButton/__tests__/index.tsx
  src/components/ProgressionButton/index.tsx
  src/components/StateBar/__tests__/__snapshots__/index.tsx.snap
  src/components/StateBar/__tests__/index.tsx
  src/components/StateBar/index.tsx
  types/assets.d.ts
  yarn.lock
Labels: typescript

#648 fix(container): some props was forward to the DOM
  src/components/Container/index.tsx
Labels: bug

#631 refactor(typescript): migrate VolumeSize, VerificationCode, TooltipIcon, Toaster, Table, TabGroup
  package.json
  src/components/Alert/index.tsx
  src/components/Box/index.tsx
  src/components/Button/__tests__/__snapshots__/index.tsx.snap
  src/components/Button/__tests__/index.tsx
  src/components/Icon/index.tsx
  src/components/Image/__tests__/__snapshots__/index.tsx.snap
  src/components/Image/__tests__/index.tsx
  src/components/TabGroup/Tab.tsx
  src/components/TabGroup/__tests__/Tab.test.tsx
  src/components/TabGroup/__tests__/TabGroup.test.tsx
  src/components/TabGroup/__tests__/__snapshots__/Tab.test.tsx.snap
  src/components/TabGroup/__tests__/__snapshots__/TabGroup.test.tsx.snap
  src/components/TabGroup/index.js
  src/components/TabGroup/index.tsx
  src/components/Table/__tests__/__snapshots__/index.tsx.snap
  src/components/Table/__tests__/index.tsx
  src/components/Table/index.tsx
  src/components/Toaster/__tests__/__snapshots__/index.tsx.snap
  src/components/Toaster/__tests__/index.tsx
  src/components/Toaster/index.tsx
  src/components/TooltipIcon/__tests__/__snapshots__/index.tsx.snap
  src/components/TooltipIcon/__tests__/index.tsx
  src/components/TooltipIcon/index.js
  src/components/TooltipIcon/index.tsx
  src/components/VerificationCode/__tests__/__snapshots__/index.tsx.snap
  src/components/VerificationCode/__tests__/index.tsx
  src/components/VerificationCode/index.tsx
  src/components/VolumeSize/__tests__/__snapshots__/index.tsx.snap
  src/components/VolumeSize/__tests__/index.tsx
  src/components/VolumeSize/index.tsx
Labels: migration, typescript

#642 refactor(typescript): touchable, textbox, tag components
  src/components/Box/index.tsx
  src/components/Button/index.tsx
  src/components/DateInput/__tests__/__snapshots__/index.test.js.snap
  src/components/Image/index.tsx
  src/components/Modal/__tests__/__snapshots__/index.js.snap
  src/components/Notice/index.tsx
  src/components/Stepper/__tests__/__snapshots__/index.js.snap
  src/components/Tag/__tests__/__snapshots__/index.tsx.snap
  src/components/Tag/__tests__/index.tsx
  src/components/Tag/index.tsx
  src/components/Tags/__tests__/__snapshots__/index.js.snap
  src/components/TagsPoplist/__tests__/__snapshots__/index.js.snap
  src/components/TextBox/__stories__/index.stories.mdx
  src/components/TextBox/__tests__/__snapshots__/index.test.tsx.snap
  src/components/TextBox/__tests__/index.test.tsx
  src/components/TextBox/index.tsx
  src/components/Touchable/__tests__/__snapshots__/index.tsx.snap
  src/components/Touchable/__tests__/index.tsx
  src/components/Touchable/index.js
  src/components/Touchable/index.tsx
  src/components/UnitInput/__tests__/__snapshots__/index.js.snap
Labels: refactor, typescript

#670 refactor(menu): migration typescript
  src/components/Button/index.tsx
  src/components/Menu/Item.tsx
  src/components/Menu/__tests__/__snapshots__/index.tsx.snap
  src/components/Menu/__tests__/index.tsx
  src/components/Menu/index.tsx
  src/components/Popper/__stories__/index.stories.mdx
  src/components/Popper/__tests__/__snapshots__/index.tsx.snap
  src/components/Popper/__tests__/index.tsx
  src/components/Popper/index.tsx
  src/helpers/shouldMatchEmotionSnapshotWithPortal.ts
Labels: typescript

#660 feat: migration typescript chart stepper statusindicator
  src/components/Chart/Donut.tsx
  src/components/Chart/Legends.tsx
  src/components/Chart/Tooltip.tsx
  src/components/Chart/__tests__/__snapshots__/index.tsx.snap
  src/components/Chart/__tests__/index.tsx
  src/components/Chart/index.tsx
  src/components/Chart/patterns.tsx
  src/components/Chart/types.tsx
  src/components/StatusIndicator/__tests__/__snapshots__/index.tsx.snap
  src/components/StatusIndicator/__tests__/index.tsx
  src/components/StatusIndicator/index.tsx
  src/components/Stepper/__tests__/__snapshots__/index.tsx.snap
  src/components/Stepper/__tests__/index.tsx
  src/components/Stepper/index.tsx
  src/helpers/numbers.ts
Labels: typescript

#682 feat: add rocket icon
  src/components/Icon/__tests__/__snapshots__/index.test.tsx.snap
  src/components/Icon/index.tsx
Labels: enhancement
