Repository scaleway/ultraviolet, pull requests merged in 2021-11, with the labels that each got.

#858 refactor: migrate Pagination, PasswordCheck, PasswordStrengthMeter, Pentagon stories to tsx
  .eslintrc
  package.json
  src/components/Pagination/__stories__/index.stories.mdx
  src/components/Pagination/__stories__/index.stories.tsx
  src/components/PasswordCheck/__stories__/index.stories.tsx
  src/components/PasswordCheck/index.tsx
  src/components/PasswordStrengthMeter/__stories__/index.stories.mdx
  src/components/PasswordStrengthMeter/__stories__/index.stories.tsx
  src/components/Pentagon/__stories__/index.stories.mdx
  src/components/Pentagon/__stories__/index.stories.tsx
  src/components/Pentagon/index.tsx
  yarn.lock
Labels: refactor

#854 refactor: migrate stories to tsx for PhoneInput, Placeholder, Popper, ProgressBar
  src/components/PhoneInput/__stories__/index.stories.mdx
  src/components/PhoneInput/__stories__/index.stories.tsx
  src/components/PhoneInput/index.tsx
  src/components/Placeholder/__stories__/index.stories.mdx
  src/components/Placeholder/__stories__/index.stories.tsx
  src/components/Placeholder/index.tsx
  src/components/Popper/__stories__/index.stories.tsx
  src/components/Popper/index.tsx
  src/components/ProgressBar/__stories__/index.stories.mdx
  src/components/ProgressBar/__stories__/index.stories.tsx
  src/components/ProgressBar/index.tsx
Labels: refactor

#859 refactor: migrate menu modal navigationstepper and notice stories to tsx
  src/components/Menu/__stories__/index.stories.mdx
  src/components/Menu/__stories__/index.stories.tsx
  src/components/Modal/__stories__/index.stories.mdx
  src/components/Modal/__stories__/index.stories.tsx
  src/components/Modal/index.tsx
  src/components/NavigationStepper/__stories__/index.stories.tsx
  src/components/NavigationStepper/index.tsx
  src/components/Notice/__stories__/index.stories.tsx
  src/components/Notice/index.tsx
Labels: refactor

#878 fix: correct some components types
  src/components/FlexBox/index.tsx
  src/components/Grid/Col.tsx
  src/components/Grid/Grid.tsx
  src/components/Grid/Row.tsx
  src/components/Switch/index.tsx
  src/components/TabGroup/__tests__/__snapshots__/TabGroup.test.tsx.snap
  src/components/TabGroup/index.tsx
Labels: typescript

#874 refactor: migrate ProgressionButton, Radio, RadioBorderedBox, Range stories to tsx
  src/components/ProgressionButton/__stories__/index.stories.mdx
  src/components/ProgressionButton/__stories__/index.stories.tsx
  src/components/ProgressionButton/index.tsx
  src/components/Radio/__stories__/index.stories.tsx
  src/components/Radio/index.tsx
  src/components/RadioBorderedBox/__stories__/index.stories.tsx
  src/components/RadioBorderedBox/index.tsx
  src/components/Range/__stories__/index.stories.mdx
  src/components/Range/__stories__/index.stories.tsx
  src/components/Range/index.tsx
Labels: refactor

#886 refactor: migrate StealthCopiable, Stepper, Switch stories to tsx
  src/components/StealthCopiable/__stories__/index.stories.mdx
  src/components/StealthCopiable/__stories__/index.stories.tsx
  src/components/StealthCopiable/index.tsx
  src/components/Stepper/__stories__/index.stories.mdx
  src/components/Stepper/__stories__/index.stories.tsx
  src/components/Stepper/index.tsx
  src/components/Switch/__stories__/index.stories.mdx
  src/components/Switch/__stories__/index.stories.tsx
  src/components/Switch/index.tsx
Labels: refactor

#877 refactor: migrate Reminder, RichSelect, ScrollView stories to tsx
  src/components/Reminder/__stories__/index.stories.mdx
  src/components/Reminder/__stories__/index.stories.tsx
  src/components/Reminder/index.tsx
  src/components/RichSelect/__stories__/index.stories.mdx
  src/components/RichSelect/__stories__/index.stories.tsx
  src/components/ScrollView/__stories__/index.stories.mdx
  src/components/ScrollView/__stories__/index.stories.tsx
  src/components/ScrollView/index.tsx
Labels: refactor

#887 feat(global-style): remove GlobalStyle component
  .storybook/preview.js
  README.md
  src/components/GlobalStyle/__tests__/__snapshots__/index.test.tsx.snap
  src/components/GlobalStyle/__tests__/index.test.tsx
  src/components/GlobalStyle/index.tsx
  src/components/index.ts
Labels: refactor

#905 feat: add expand icon
  src/components/Icon/__tests__/__snapshots__/index.test.tsx.snap
  src/components/Icon/index.tsx
Labels: enhancement

#894 fix(tooltip-icon): fixed vertical align
  src/components/TooltipIcon/index.tsx
Labels: enhancement

#904 feat: migrate stories of Tooltip, TooltipIcon, Touchable, Typography
  src/components/Box/index.tsx
  src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap
  src/components/FlexBox/index.tsx
  src/components/Modal/__tests__/__snapshots__/index.tsx.snap
  src/components/Stepper/__tests__/__snapshots__/index.tsx.snap
  src/components/Tags/__tests__/__snapshots__/index.tsx.snap
  src/components/TextBox/__tests__/__snapshots__/index.test.tsx.snap
  src/components/Tooltip/__stories__/index.stories.tsx
  src/components/Tooltip/index.tsx
  src/components/TooltipIcon/__stories__/index.stories.mdx
  src/components/TooltipIcon/__stories__/index.stories.tsx
  src/components/TooltipIcon/index.tsx
  src/components/Touchable/__stories__/index.stories.mdx
  src/components/Touchable/__stories__/index.stories.tsx
  src/components/Touchable/__tests__/__snapshots__/index.tsx.snap
  src/components/Touchable/index.tsx
  src/components/Typography/__stories__/index.stories.mdx
  src/components/Typography/__stories__/index.stories.tsx
  src/components/Typography/index.tsx
Labels: typescript

#897 refactor: migrate unitinput universallink verificationcode and volumesize and delete unselectable
  src/components/StealthCopiable/__tests__/__snapshots__/index.tsx.snap
  src/components/StealthCopiable/index.tsx
  src/components/UnitInput/__stories__/index.stories.mdx
  src/components/UnitInput/__stories__/index.stories.tsx
  src/components/UnitInput/index.tsx
  src/components/UniversalLink/__stories__/index.stories.mdx
  src/components/UniversalLink/__stories__/index.stories.tsx
  src/components/UniversalLink/index.tsx
  src/components/Unselectable/__stories__/index.stories.mdx
  src/components/Unselectable/__tests__/__snapshots__/index.tsx.snap
  src/components/Unselectable/__tests__/index.tsx
  src/components/Unselectable/index.tsx
  src/components/VerificationCode/__stories__/index.stories.mdx
  src/components/VerificationCode/__stories__/index.stories.tsx
  src/components/VerificationCode/index.tsx
  src/components/VolumeSize/__stories__/index.stories.mdx
  src/components/VolumeSize/__stories__/index.stories.tsx
  src/components/VolumeSize/index.tsx
  src/components/index.ts
Labels: refactor

#900 chore(storybook): migration BulletList, SwitchButton, TabGroup, Table, Tag, Tags mdx to tsx (#895)
  src/__stories__/components/ControlValue.ts
  src/components/ActionBar/__stories__/index.stories.tsx
  src/components/BulletList/__stories__/index.stories.mdx
  src/components/BulletList/__stories__/index.stories.tsx
  src/components/DateInput/__stories__/index.stories.tsx
  src/components/Radio/__stories__/index.stories.tsx
  src/components/Switch/__stories__/index.stories.tsx
  src/components/SwitchButton/__stories__/index.stories.mdx
  src/components/SwitchButton/__stories__/index.stories.tsx
  src/components/SwitchButton/index.tsx
  src/components/TabGroup/__stories__/index.stories.mdx
  src/components/TabGroup/__stories__/index.stories.tsx
  src/components/TabGroup/index.tsx
  src/components/Table/__stories__/index.stories.mdx
  src/components/Table/__stories__/index.stories.tsx
  src/components/Tag/__stories__/index.stories.mdx
  src/components/Tag/__stories__/index.stories.tsx
  src/components/Tag/index.tsx
  src/components/Tags/__stories__/index.stories.mdx
  src/components/Tags/__stories__/index.stories.tsx
  src/components/Tags/index.tsx
Labels: documentation

#896 refactor: migrate TagsPoplist, TextBox, TimeInput, Toaster stories to tsx
  src/components/TagsPoplist/__stories__/index.stories.mdx
  src/components/TagsPoplist/__stories__/index.stories.tsx
  src/components/TagsPoplist/index.tsx
  src/components/TextBox/__stories__/index.stories.mdx
  src/components/TextBox/__stories__/index.stories.tsx
  src/components/TextBox/index.tsx
  src/components/TimeInput/__stories__/index.stories.tsx
  src/components/TimeInput/index.tsx
  src/components/Toaster/__stories__/index.stories.tsx
  src/components/Toaster/index.tsx
Labels: refactor

#908 feat(rich-select): description and inline description
  src/components/RichSelect/__stories__/index.stories.tsx
  src/components/RichSelect/__tests__/__snapshots__/index.tsx.snap
  src/components/RichSelect/__tests__/index.tsx
  src/components/RichSelect/index.tsx
Labels: enhancement

#899 feat: migrate to tsx stories Separator, Slider, Sphere, StateBar, StatusIndicator
  src/components/Separator/__stories__/index.stories.mdx
  src/components/Separator/__stories__/index.stories.tsx
  src/components/Separator/index.tsx
  src/components/Slider/__stories__/index.stories.mdx
  src/components/Slider/__stories__/index.stories.tsx
  src/components/Slider/index.tsx
  src/components/Sphere/__stories__/index.stories.mdx
  src/components/Sphere/__stories__/index.stories.tsx
  src/components/Sphere/index.tsx
  src/components/StateBar/__stories__/index.stories.mdx
  src/components/StateBar/__stories__/index.stories.tsx
  src/components/StateBar/__tests__/__snapshots__/index.tsx.snap
  src/components/StateBar/index.tsx
  src/components/StatusIndicator/__stories__/index.stories.mdx
  src/components/StatusIndicator/__stories__/index.stories.tsx
  src/components/StatusIndicator/index.tsx
Labels: typescript

#923 refactor(a11y): alert
  .github/workflows/ci.yml
  .jest/a11y.config.ts
  .jest/unit.config.ts
  README.md
  package.json
  src/__tests__/a11y.test.tsx
  src/components/Alert/__tests__/__snapshots__/index.test.tsx.snap
  src/components/Alert/__tests__/index.test.tsx
  src/components/Alert/index.tsx
  src/components/Toaster/__tests__/__snapshots__/index.tsx.snap
  src/components/Toaster/__tests__/index.tsx
Labels: enhancement, accessibility

#949 feat: add tooltip and background
  src/components/BarStack/__stories__/index.stories.tsx
  src/components/BarStack/__tests__/__snapshots__/index.test.tsx.snap
  src/components/BarStack/index.tsx
Labels: enhancement
