Repository scaleway/ultraviolet, pull requests merged in 2021-05, with the labels that each got.

#310 chore(template): add template bug and feature request
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#312 doc(licence): add apache 2.0 licence
  LICENSE
Labels: documentation

#311 docs(code-of-conduct): add code of conduct
  CODE_OF_CONDUCT.md
Labels: documentation

#358 fix: checkbox text alignement
  src/components/Checkbox/__stories__/index.stories.mdx
  src/components/Checkbox/__tests__/__snapshots__/index.js.snap
  src/components/Checkbox/__tests__/index.js
  src/components/Checkbox/index.js
Labels: bug

#362 fix: export RichSelectTags
  src/components/index.js
Labels: bug, migration

#359 docs: index and customization pages
  .storybook/preview.js
  src/__stories__/Customization.stories.mdx
  src/__stories__/Index.stories.mdx
  src/__stories__/Migration.stories.mdx
Labels: documentation

#368 docs: add story documentation on a components
  src/components/Action/__stories__/index.stories.mdx
  src/components/Action/index.js
  src/components/ActionBar/__stories__/index.stories.mdx
  src/components/ActionBar/index.js
  src/components/ActivityIndicator/__stories__/index.stories.mdx
  src/components/Alert/__stories__/index.stories.mdx
  src/components/Alert/index.js
  src/components/Avatar/__stories__/index.stories.mdx
  src/components/Avatar/index.js
Labels: documentation

#376 fix(stepper): fixed border and added tests event
  src/components/Stepper/__tests__/__snapshots__/index.js.snap
  src/components/Stepper/__tests__/index.js
  src/components/Stepper/index.js
Labels: bug

#375 fix: textbox story not working
  src/components/TextBox/__stories__/index.stories.mdx
Labels: bug

#372 fix: rich select issues
  src/components/RichSelect/__stories__/index.stories.mdx
  src/components/RichSelect/__tests__/__snapshots__/index.js.snap
  src/components/RichSelect/__tests__/index.js
  src/components/RichSelect/index.js
  src/components/RichSelectTags/__tests__/__snapshots__/index.js.snap
  src/components/Tags/index.js
  src/components/TimeInput/__tests__/__snapshots__/index.js.snap
  src/components/UnitInput/__stories__/index.stories.mdx
  src/components/UnitInput/__tests__/__snapshots__/index.js.snap
  src/components/UnitInput/__tests__/index.js
Labels: bug

#380 feat: ssr safe rendering
  src/components/RichSelect/__stories__/index.stories.mdx
  src/components/RichSelect/__tests__/__snapshots__/index.js.snap
  src/components/RichSelect/__tests__/index.js
  src/components/RichSelect/index.js
  src/components/Slider/index.js
  src/components/Toaster/index.js
Labels: enhancement

#401 fix: richselect option
  src/components/RichSelect/index.js
Labels: bug
