Repository scaleway/ultraviolet, pull requests merged in 2021-07, with the labels that each got.

#495 fix: export of pagination and list
  src/components/index.js
Labels: bug

#496 fix: list and pagination integration
  src/components/List/__tests__/__snapshots__/index.js.snap
  src/components/List/index.js
  src/components/Pagination/__tests__/__snapshots__/index.test.js.snap
  src/components/Pagination/__tests__/index.test.js
  src/components/Pagination/index.js
  src/components/index.js
Labels: enhancement

#500 feat: add some accessibility, customization on list and pagination
  src/components/List/__stories__/index.stories.mdx
  src/components/List/__tests__/__snapshots__/index.js.snap
  src/components/List/__tests__/index.js
  src/components/List/index.js
  src/components/Pagination/__tests__/__snapshots__/index.test.js.snap
  src/components/Pagination/__tests__/index.test.js
  src/components/Pagination/index.js
Labels: enhancement

#473 fix(merge): merged NotificationBar, IconMessage, Information into Alert
  src/components/Alert/__stories__/index.stories.mdx
  src/components/Alert/__tests__/__snapshots__/index.js.snap
  src/components/Alert/__tests__/index.js
  src/components/Alert/index.js
  src/components/IconMessage/__stories__/index.stories.mdx
  src/components/IconMessage/__tests__/__snapshots__/index.js.snap
  src/components/IconMessage/__tests__/index.js
  src/components/IconMessage/index.js
  src/components/Information/__stories__/index.stories.mdx
  src/components/Information/__tests__/__snapshots__/index.js.snap
  src/components/Information/__tests__/index.js
  src/components/Information/index.js
  src/components/NotificationBar/__stories__/index.stories.mdx
  src/components/NotificationBar/__tests__/__snapshots__/index.js.snap
  src/components/NotificationBar/__tests__/index.js
  src/components/NotificationBar/index.js
  src/components/Toaster/__tests__/__snapshots__/index.js.snap
  src/components/Toaster/index.js
  src/components/index.js
Labels: migration

#501 fix: pagination control infinite rendering
  src/components/Pagination/index.js
Labels: bug

#491 docs: add u and v components
  src/components/UnitInput/__stories__/index.stories.mdx
  src/components/UnitInput/index.js
  src/components/UniversalLink/__stories__/index.stories.mdx
  src/components/Unselectable/__stories__/index.stories.mdx
  src/components/VerificationCode/__stories__/index.stories.mdx
  src/components/VerificationCode/index.js
  src/components/VolumeSize/__stories__/index.stories.mdx
  src/components/VolumeSize/index.js
Labels: documentation

#504 fix(menu): disabled props wasn t forward to component
  src/components/Menu/Item.js
  src/components/Menu/__tests__/__snapshots__/index.js.snap
Labels: bug

#508 fix: tooltip display
  src/components/Button/__tests__/__snapshots__/index.js.snap
  src/components/Button/__tests__/index.js
  src/components/Button/index.js
  src/components/Chart/__tests__/__snapshots__/index.js.snap
  src/components/List/__tests__/__snapshots__/index.js.snap
  src/components/Tooltip/__stories__/index.stories.mdx
  src/components/Tooltip/__tests__/__snapshots__/index.js.snap
  src/components/Tooltip/__tests__/index.js
  src/components/Tooltip/index.js
  src/components/TooltipIcon/__tests__/__snapshots__/index.js.snap
Labels: bug

#494 docs: r components
  src/components/List/__stories__/index.stories.mdx
  src/components/Pagination/__stories__/index.stories.mdx
  src/components/Radio/__stories__/index.stories.mdx
  src/components/Radio/__tests__/__snapshots__/index.js.snap
  src/components/Radio/index.js
  src/components/RadioBorderedBox/__stories__/index.stories.mdx
  src/components/RadioBorderedBox/__tests__/__snapshots__/index.js.snap
  src/components/RadioBorderedBox/index.js
  src/components/Range/__stories__/index.stories.mdx
  src/components/Reminder/__stories__/index.stories.mdx
  src/components/Reminder/__tests__/__snapshots__/index.js.snap
  src/components/Reminder/index.js
  src/components/RichSelect/__stories__/index.stories.mdx
  src/components/RichSelect/index.js
Labels: documentation

#511 feat: access pagination from list render props
  src/components/List/index.js
Labels: enhancement

#512 fix: tooltip flexbox drop
  src/components/Button/__tests__/__snapshots__/index.js.snap
  src/components/Chart/__tests__/__snapshots__/index.js.snap
  src/components/List/__tests__/__snapshots__/index.js.snap
  src/components/Tooltip/__tests__/__snapshots__/index.js.snap
  src/components/Tooltip/index.js
  src/components/TooltipIcon/__stories__/index.stories.mdx
  src/components/TooltipIcon/__tests__/__snapshots__/index.js.snap
  src/components/TooltipIcon/index.js
Labels: bug

#520 feat: list and pagination improvement
  src/components/List/__stories__/index.stories.mdx
  src/components/List/__tests__/__snapshots__/index.js.snap
  src/components/List/__tests__/index.js
  src/components/List/index.js
  src/components/Pagination/__stories__/ExampleChildren.js
  src/components/Pagination/__stories__/index.stories.mdx
  src/components/Pagination/__tests__/__snapshots__/index.test.js.snap
  src/components/Pagination/__tests__/index.test.js
  src/components/Pagination/index.js
  src/components/Pagination/usePaginatedData.js
  src/components/Pagination/usePagination.js
  src/components/index.js
Labels: enhancement

#521 fix(menu): allow toggle props
  src/components/Alert/__stories__/index.stories.mdx
  src/components/Menu/Item.js
  src/components/Menu/__stories__/index.stories.mdx
  src/components/Menu/__tests__/__snapshots__/index.js.snap
  src/components/Menu/index.js
Labels: bug, enhancement

#505 feat: merge progressbar into breadcrumbs
  src/components/Breadcrumbs/__stories__/index.stories.mdx
  src/components/Breadcrumbs/__tests__/__snapshots__/index.js.snap
  src/components/Breadcrumbs/index.js
  src/components/Progress/__stories__/index.stories.mdx
  src/components/Progress/__tests__/__snapshots__/index.js.snap
  src/components/Progress/__tests__/index.js
  src/components/Progress/index.js
  src/components/index.js
Labels: enhancement

#536 perf(size): adding size script and workflow
  .github/workflows/size-limit.yml
  package.json
  yarn.lock
Labels: github_actions

#542 fix: list empty component
  src/components/List/index.js
Labels: bug

#497 docs(s): updated all S components docs
  src/components/ScrollView/__stories__/index.stories.mdx
  src/components/Separator/__stories__/index.stories.mdx
  src/components/Slider/__stories__/index.stories.mdx
  src/components/Slider/index.js
  src/components/Sphere/__stories__/index.stories.mdx
  src/components/StateBar/__stories__/index.stories.mdx
  src/components/StateBar/index.js
  src/components/StatusIndicator/__stories__/index.stories.mdx
  src/components/StealthCopiable/__stories__/index.stories.mdx
  src/components/Stepper/__stories__/index.stories.mdx
  src/components/Stepper/index.js
  src/components/Switch/__stories__/index.stories.mdx
  src/components/Switch/index.js
  src/components/SwitchButton/__stories__/index.stories.mdx
Labels: documentation

#532 docs(storybook): fixed argstable
  src/components/Boxer/index.js
  src/components/Container/__tests__/__snapshots__/index.js.snap
  src/components/DotSteps/__tests__/__snapshots__/index.js.snap
  src/components/FlexBox/__tests__/__snapshots__/index.js.snap
  src/components/FlexBox/index.js
  src/components/Label/index.js
  src/components/Modal/index.js
  src/components/Pentagon/index.js
  src/components/Popper/index.js
  src/components/ScrollView/index.js
  src/components/TagsPoplist/__tests__/__snapshots__/index.js.snap
Labels: documentation

#583 refactor: kickstart typescript migration
  .eslintrc
  package.json
  rollup.config.mjs
  src/components/Unselectable/__tests__/__snapshots__/index.tsx.snap
  src/components/Unselectable/__tests__/index.tsx
  src/components/Unselectable/index.tsx
  src/components/index.ts
  tsconfig.json
Labels: typescript

#580 docs: updated all t components documentation
  src/components/TabGroup/__stories__/index.stories.mdx
  src/components/Table/__stories__/index.stories.mdx
  src/components/Table/index.js
  src/components/Tag/__stories__/index.stories.mdx
  src/components/Tags/__stories__/index.stories.mdx
  src/components/TagsPoplist/__stories__/index.stories.mdx
  src/components/TagsPoplist/index.js
  src/components/TextBox/__stories__/index.stories.mdx
  src/components/TimeInput/__stories__/index.stories.mdx
  src/components/Toaster/__stories__/index.stories.mdx
  src/components/Tooltip/__stories__/index.stories.mdx
  src/components/TooltipIcon/__stories__/index.stories.mdx
  src/components/Touchable/__stories__/index.stories.mdx
  src/components/Touchable/index.js
  src/components/Typography/__stories__/index.stories.mdx
  src/components/Typography/__tests__/__snapshots__/index.js.snap
  src/components/Typography/index.js
Labels: documentation

#588 refactor: migrate src/helpers to typescript
  babel.config.json
  src/helpers/__tests__/index.ts
  src/helpers/isJSON.ts
  src/helpers/keycode.ts
  src/helpers/numbers.ts
  src/helpers/recursivelyGetChildrenString.ts
  src/helpers/renderWithTheme.tsx
  src/helpers/shouldMatchEmotionSnapshot.js
  src/helpers/shouldMatchEmotionSnapshot.ts
  src/helpers/shouldMatchEmotionSnapshotWithPortal.ts
Labels: typescript

#587 fix(theme): fixed background richSelect for theming
  src/components/RichSelect/__tests__/__snapshots__/index.js.snap
  src/components/RichSelect/index.js
Labels: bug
