Repository scaleway/ultraviolet, pull requests merged in 2021-09, with the labels that each got.

#675 feat: navigationstepper component
  package.json
  src/components/NavigationStepper/__stories__/index.stories.mdx
  src/components/NavigationStepper/__tests__/__snapshots__/index.test.tsx.snap
  src/components/NavigationStepper/__tests__/index.test.tsx
  src/components/NavigationStepper/index.tsx
  src/components/index.ts
  src/helpers/jestMockMatchMedia.ts
  yarn.lock
Labels: enhancement

#666 refactor(date-input): migration typescript
  package.json
  src/components/Box/index.tsx
  src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap
  src/components/DateInput/__tests__/index.test.js
  src/components/DateInput/__tests__/index.test.tsx
  src/components/DateInput/index.tsx
  src/components/Separator/index.tsx
  yarn.lock
Labels: refactor, typescript

#683 feat(DotSteps): update component dots style
  src/components/Dot/__tests__/__snapshots__/index.tsx.snap
  src/components/Dot/__tests__/index.tsx
  src/components/DotSteps/__tests__/__snapshots__/index.js.snap
  src/components/DotSteps/index.tsx
Labels: enhancement

#704 fix: avoid to declare emotion Theme typings
  README.md
  emotion.d.ts
  src/index.ts
  src/theme/index.ts
  tsconfig.json
Labels: typescript

#712 fix: radioborderedbox add xstyledprops
  src/components/RadioBorderedBox/index.tsx
Labels: bug

#705 fix(modal): onBeforeClose & ExtendReminder CustomLink
  src/components/ExtendedReminder/__tests__/__snapshots__/index.tsx.snap
  src/components/ExtendedReminder/__tests__/index.tsx
  src/components/ExtendedReminder/index.tsx
  src/components/Modal/__tests__/__snapshots__/index.tsx.snap
  src/components/Modal/__tests__/index.tsx
  src/components/Modal/index.tsx
Labels: refactor

#691 feat: pagination to typescript
  src/components/List/__tests__/__snapshots__/index.js.snap
  src/components/List/__tests__/index.js
  src/components/Pagination/__stories__/index.stories.mdx
  src/components/Pagination/__tests__/__snapshots__/index.test.tsx.snap
  src/components/Pagination/__tests__/getPageNumbers.test.ts
  src/components/Pagination/__tests__/index.test.tsx
  src/components/Pagination/getPageNumbers.ts
  src/components/Pagination/index.js
  src/components/Pagination/index.tsx
  src/components/Pagination/types.ts
  src/components/Pagination/usePagination.ts
Labels: typescript

#708 feat: migrate list to typescript
  src/components/ActionBar/index.tsx
  src/components/Box/index.tsx
  src/components/Icon/__tests__/__snapshots__/index.test.tsx.snap
  src/components/Icon/index.tsx
  src/components/List/Cell.tsx
  src/components/List/SelectBar.js
  src/components/List/SelectBar.tsx
  src/components/List/SortIcon.tsx
  src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  src/components/List/__tests__/index.test.tsx
  src/components/List/context.ts
  src/components/List/index.tsx
  src/components/List/types.ts
  src/components/List/variantExplorer.tsx
  src/components/List/variantProduct.tsx
  src/components/List/variantTable.tsx
  src/components/Pagination/index.tsx
Labels: typescript

#752 fix(navigationstepper): update border width according to feebacks
  commitlint.config.js
  src/components/NavigationStepper/__tests__/__snapshots__/index.test.tsx.snap
  src/components/NavigationStepper/index.tsx
Labels: enhancement

#756 fix(menu): allow to not render inside menu when it s not necessary
  src/components/Menu/__tests__/__snapshots__/index.tsx.snap
  src/components/Menu/__tests__/index.tsx
  src/components/Menu/index.tsx
Labels: enhancement
