Repository scaleway/ultraviolet, pull requests merged in 2022-04, with the labels that each got.

#1338 fix: background overlay and elevated colors
  src/components/ActionBar/index.tsx
  src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap
  src/components/DateInput/index.tsx
  src/components/Menu/index.tsx
  src/components/Modal/__tests__/__snapshots__/index.tsx.snap
  src/components/Modal/index.tsx
  src/components/RichSelect/index.tsx
Labels: refactor, design system

#1345 fix(colors): fixed neutral text strong and disabled colors
  scripts/tokensExtension.json
  src/theme/tokens/dark.ts
  src/theme/tokens/light.ts
Labels: design system

#1346 test: improve coverage
  src/components/ActivityIndicator/__tests__/__snapshots__/index.test.tsx.snap
  src/components/ActivityIndicator/__tests__/index.test.tsx
  src/components/BarChart/Tooltip.tsx
  src/components/BarChart/__stories__/index.stories.tsx
  src/components/BarChart/__tests__/Tooltip.tsx
  src/components/BarChart/__tests__/__snapshots__/Tooltip.tsx.snap
  src/components/BarChart/__tests__/index.tsx
  src/components/Breadcrumbs/__tests__/__snapshots__/index.tsx.snap
  src/components/Breadcrumbs/__tests__/index.tsx
  src/components/Counter/index.tsx
  src/components/DotSteps/__tests__/__snapshots__/index.tsx.snap
  src/components/DotSteps/__tests__/index.tsx
  src/components/ExtendedReminder/__tests__/__snapshots__/index.tsx.snap
  src/components/ExtendedReminder/__tests__/index.tsx
  src/components/Tags/__tests__/index.tsx
Labels: enhancement

#1355 feat: colors updated for dark theme
  .loki/reference/chrome_laptop_Components_Data_Display_Chart_PieChart_Legends.png
  .loki/reference/chrome_laptop_Components_Data_Display_Chart_PieChart_Popper_Details.png
  .loki/reference/chrome_laptop_Components_Data_Display_Chart_PieChart_Strikethrough.png
  .loki/reference/chrome_laptop_Components_Data_Entry_Checkbox_Errors.png
  .loki/reference/chrome_laptop_Components_Data_Entry_Checkbox_Validation.png
  .loki/reference/chrome_laptop_Components_Data_Entry_RadioBorderedBox_Error.png
  .loki/reference/chrome_laptop_Components_Data_Entry_Radio_Error.png
  .loki/reference/chrome_laptop_Components_Data_Entry_Radio_Valid.png
  .loki/reference/chrome_laptop_Components_Data_Entry_TextBox_Required.png
  .loki/reference/chrome_laptop_Components_Data_Entry_TextBox_Valid.png
  .loki/reference/chrome_laptop_Components_Token_Icon_Color.png
  src/components/BarChart/Tooltip.tsx
  src/components/BarChart/__tests__/__snapshots__/Tooltip.tsx.snap
  src/components/Checkbox/__tests__/__snapshots__/index.tsx.snap
  src/components/Icon/index.tsx
  src/components/PieChart/Legends.tsx
  src/components/PieChart/Tooltip.tsx
  src/components/PieChart/__tests__/__snapshots__/index.tsx.snap
  src/components/PieChart/index.tsx
  src/components/Radio/__tests__/__snapshots__/index.tsx.snap
  src/components/RadioBorderedBox/__tests__/__snapshots__/index.tsx.snap
  src/components/TextBox/__tests__/__snapshots__/index.test.tsx.snap
  src/components/VerificationCode/__tests__/__snapshots__/index.tsx.snap
  src/components/VerificationCode/index.tsx
Labels: enhancement, design system

#1385 refactor: dotsteps component
  src/components/DotSteps/__tests__/__snapshots__/index.tsx.snap
  src/components/DotSteps/index.tsx
Labels: refactor, design system

#1374 feat: new bullet component
  .loki/reference/chrome_laptop_Components_Data_Display_Bullet_Default.png
  .loki/reference/chrome_laptop_Components_Data_Display_Bullet_Icons.png
  .loki/reference/chrome_laptop_Components_Data_Display_Bullet_Sizes.png
  .loki/reference/chrome_laptop_Components_Data_Display_Bullet_Text.png
  .loki/reference/chrome_laptop_Components_Data_Display_Bullet_Tooltip.png
  .loki/reference/chrome_laptop_Components_Data_Display_Bullet_Variants.png
  src/__tests__/a11y.test.tsx
  src/components/Bullet/__stories__/index.stories.tsx
  src/components/Bullet/__tests__/__snapshots__/index.tsx.snap
  src/components/Bullet/__tests__/index.tsx
  src/components/Bullet/index.tsx
  src/components/index.ts
Labels: design system

#1396 fix: dark theme support for phone input component
  .loki/reference/chrome_laptop_Components_Data_Entry_PhoneInput_Default.png
  .loki/reference/chrome_laptop_Components_Data_Entry_PhoneInput_Disabled.png
  .loki/reference/chrome_laptop_Components_Data_Entry_PhoneInput_Flag_Dropdown_Disabled.png
  .loki/reference/chrome_laptop_Components_Data_Entry_PhoneInput_Prefilled_Indicator.png
  .loki/reference/chrome_laptop_Components_Data_Entry_PhoneInput_Prefilled_Number.png
  src/components/PhoneInput/__tests__/__snapshots__/index.tsx.snap
  src/components/PhoneInput/index.tsx
Labels: bug, design system

#1397 fix: removed and fixed notice proptypes
  src/components/Notice/index.tsx
Labels: bug
