Repository scaleway/ultraviolet, pull requests merged in 2022-06, with the labels that each got.

#1543 fix: svg size bug on radio
  src/components/Radio/__tests__/__snapshots__/index.tsx.snap
  src/components/Radio/index.tsx
  src/components/RadioBorderedBox/__tests__/__snapshots__/index.tsx.snap
Labels: bug

#1544 feat(checkbox): refactor checkbox and some animations
  .loki/reference/chrome_laptop_Components_Data_Display_Chart_LineChart_Multiple_Series_With_Custom_Legend.png
  .loki/reference/chrome_laptop_Components_Data_Entry_Checkbox_Checked.png
  .loki/reference/chrome_laptop_Components_Data_Entry_Checkbox_Default.png
  .loki/reference/chrome_laptop_Components_Data_Entry_Checkbox_Disabled.png
  .loki/reference/chrome_laptop_Components_Data_Entry_Checkbox_Errors.png
  .loki/reference/chrome_laptop_Components_Data_Entry_Checkbox_Progress.png
  .loki/reference/chrome_laptop_Components_Data_Entry_Checkbox_Sizes.png
  .loki/reference/chrome_laptop_Components_Data_Entry_Checkbox_Value.png
  .loki/reference/chrome_laptop_Components_List_Animated.png
  .loki/reference/chrome_laptop_Components_List_Disabled.png
  .loki/reference/chrome_laptop_Components_List_Explorer_Variant.png
  .loki/reference/chrome_laptop_Components_List_Loading.png
  .loki/reference/chrome_laptop_Components_List_Multiselect.png
  .loki/reference/chrome_laptop_Components_List_Pagination_Loading.png
  .loki/reference/chrome_laptop_Components_List_Pagination_Loading_Page_Count.png
  .loki/reference/chrome_laptop_Components_List_Pagination_Prefetched_Data.png
  .loki/reference/chrome_laptop_Components_List_Ref.png
  .loki/reference/chrome_laptop_Components_List_Row_Variants.png
  .loki/reference/chrome_laptop_Components_List_Table_Variant.png
  src/components/Checkbox/__stories__/index.stories.tsx
  src/components/Checkbox/__tests__/__snapshots__/index.tsx.snap
  src/components/Checkbox/index.tsx
  src/components/LineChart/__tests__/__snapshots__/index.tsx.snap
  src/components/List/SelectBar.tsx
  src/components/List/__stories__/index.stories.tsx
  src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  src/components/List/variantProduct.tsx
  src/components/Radio/__tests__/__snapshots__/index.tsx.snap
  src/components/Radio/index.tsx
  src/components/RadioBorderedBox/__tests__/__snapshots__/index.tsx.snap
  src/utils/animations.ts
Labels: enhancement

#1541 feat: text component
  .loki/reference/chrome_laptop_Components_Fondation_Text_As.png
  .loki/reference/chrome_laptop_Components_Fondation_Text_Color.png
  .loki/reference/chrome_laptop_Components_Fondation_Text_Default.png
  .loki/reference/chrome_laptop_Components_Fondation_Text_One_Line.png
  .loki/reference/chrome_laptop_Components_Fondation_Text_Prominence.png
  .loki/reference/chrome_laptop_Components_Fondation_Text_Variants.png
  src/components/Text/__stories__/index.stories.tsx
  src/components/Text/__tests__/__snapshots__/index.test.tsx.snap
  src/components/Text/__tests__/index.test.tsx
  src/components/Text/index.tsx
  src/components/Typography/__stories__/index.stories.tsx
  src/components/Typography/index.tsx
  src/theme/index.ts
Labels: design system

#1575 refactor: drop dot component
  src/components/Dot/__stories__/index.stories.tsx
  src/components/Dot/__tests__/__snapshots__/index.tsx.snap
  src/components/Dot/__tests__/index.tsx
  src/components/Dot/index.tsx
  src/components/DotSteps/__tests__/__snapshots__/index.tsx.snap
  src/components/DotSteps/index.tsx
  src/components/StatusIndicator/__tests__/__snapshots__/index.tsx.snap
  src/components/StatusIndicator/index.tsx
  src/components/index.ts
Labels: refactor

#1564 refactor: popper component moved to Menu
  README.md
  src/components/Button/__stories__/index.stories.tsx
  src/components/Menu/__stories__/index.stories.tsx
  src/components/Menu/__tests__/__snapshots__/index.tsx.snap
  src/components/Menu/index.tsx
  src/components/Popper/__stories__/index.stories.tsx
  src/components/Popper/__tests__/__snapshots__/index.tsx.snap
  src/components/Popper/__tests__/index.tsx
  src/components/Popper/index.tsx
  src/components/UniversalLink/__tests__/__snapshots__/index.tsx.snap
  src/components/UniversalLink/__tests__/index.tsx
  src/components/index.ts
Labels: refactor

#1580 feat(Switch, SwitchButton): fix a11y issues
  src/__tests__/a11y.test.tsx
  src/components/Switch/__stories__/index.stories.tsx
  src/components/Switch/__tests__/__snapshots__/index.tsx.snap
  src/components/Switch/index.tsx
  src/components/SwitchButton/__tests__/__snapshots__/index.tsx.snap
  src/components/SwitchButton/index.tsx
Labels: accessibility

#1570 feat: reduce bundle size
  .loki/reference/chrome_laptop_Components_Data_Display_Avatar_Image.png
  .loki/reference/chrome_laptop_Components_Data_Entry_PhoneInput_Default.png
  .loki/reference/chrome_laptop_Components_Data_Entry_PhoneInput_Disabled.png
  .loki/reference/chrome_laptop_Components_Data_Entry_PhoneInput_Flag_Dropdown_Disabled.png
  .loki/reference/chrome_laptop_Components_Data_Entry_PhoneInput_Prefilled_Indicator.png
  .loki/reference/chrome_laptop_Components_Data_Entry_PhoneInput_Prefilled_Number.png
  global.d.ts
  src/components/Avatar/__stories__/avatar.svg
  src/components/Avatar/__stories__/index.stories.tsx
  src/components/Avatar/__tests__/__snapshots__/index.tsx.snap
  src/components/Avatar/index.tsx
  src/components/PhoneInput/__tests__/__snapshots__/index.tsx.snap
  src/components/PhoneInput/flags.png
  src/components/PhoneInput/flags@2x.png
  src/components/PhoneInput/index.tsx
Labels: enhancement

#1592 fix(phone-input): rollback on png
  .loki/reference/chrome_laptop_Components_Data_Entry_PhoneInput_Default.png
  .loki/reference/chrome_laptop_Components_Data_Entry_PhoneInput_Disabled.png
  .loki/reference/chrome_laptop_Components_Data_Entry_PhoneInput_Flag_Dropdown_Disabled.png
  .loki/reference/chrome_laptop_Components_Data_Entry_PhoneInput_Prefilled_Indicator.png
  .loki/reference/chrome_laptop_Components_Data_Entry_PhoneInput_Prefilled_Number.png
  global.d.ts
  src/components/PhoneInput/__tests__/__snapshots__/index.tsx.snap
  src/components/PhoneInput/flags.png
  src/components/PhoneInput/index.tsx
Labels: bug

#1590 fix(pagination): real pagination index by page number
  .loki/.gitignore
  .loki/reference/chrome_laptop_Components_List_Pagination_Data.png
  src/components/List/__stories__/index.stories.tsx
  src/components/Pagination/usePagination.ts
Labels: bug

#1596 fix: popper component working with a function disclosure
  .loki/reference/chrome_laptop_Components_Navigation_Menu_Borderless.png
  .loki/reference/chrome_laptop_Components_Navigation_Menu_Default.png
  .loki/reference/chrome_laptop_Components_Navigation_Menu_Function_Disclosure.png
  .loki/reference/chrome_laptop_Components_Navigation_Menu_Variants.png
  src/components/Menu/__stories__/index.stories.tsx
  src/components/Menu/__tests__/__snapshots__/index.tsx.snap
  src/components/Menu/__tests__/index.tsx
  src/components/Menu/index.tsx
Labels: bug

#1586 docs(theme): updated theme documentation
  src/__stories__/Documentation.stories.mdx
  src/__stories__/Migration.stories.mdx
  src/__stories__/Theme.stories.mdx
  src/__stories__/story.example
Labels: documentation

#1566 feat(tooltip): new tooltip homemade
  .loki/reference/chrome_laptop_Components_Feedback_TooltipIcon_Default.png
  .loki/reference/chrome_laptop_Components_Feedback_Tooltip_Default.png
  .loki/reference/chrome_laptop_Components_Feedback_Tooltip_Max_Width.png
  .loki/reference/chrome_laptop_Components_Feedback_Tooltip_Placement.png
  src/components/BarStack/index.tsx
  src/components/Bullet/index.tsx
  src/components/Button/__tests__/__snapshots__/index.tsx.snap
  src/components/Button/index.tsx
  src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  src/components/List/variantExplorer.tsx
  src/components/List/variantProduct.tsx
  src/components/List/variantTable.tsx
  src/components/Modal/__tests__/__snapshots__/index.tsx.snap
  src/components/Modal/index.tsx
  src/components/PieChart/__tests__/__snapshots__/index.tsx.snap
  src/components/SelectNumber/__tests__/__snapshots__/index.tsx.snap
  src/components/SelectNumber/__tests__/index.tsx
  src/components/Tooltip/__stories__/index.stories.tsx
  src/components/Tooltip/__tests__/__snapshots__/index.test.tsx.snap
  src/components/Tooltip/__tests__/index.test.tsx
  src/components/Tooltip/index.tsx
  src/components/TooltipIcon/__tests__/__snapshots__/index.tsx.snap
  src/components/TooltipIcon/index.tsx
Labels: enhancement

#1600 fix(tooltip): generatedId into aria-describedby
  src/components/PieChart/__tests__/__snapshots__/index.tsx.snap
  src/components/PieChart/__tests__/index.tsx
  src/components/Tooltip/__tests__/__snapshots__/index.test.tsx.snap
  src/components/Tooltip/__tests__/index.test.tsx
  src/components/Tooltip/index.tsx
Labels: bug

#1579 fix(component): add Text export and sort export name
  src/components/index.ts
Labels: bug

#1618 refactor: remove some colorsDeprecated
  .loki/reference/chrome_laptop_Components_Button_ProgressionButton_Custom.png
  .loki/reference/chrome_laptop_Components_Button_ProgressionButton_Default.png
  src/components/ProgressionButton/__tests__/__snapshots__/index.tsx.snap
  src/components/ProgressionButton/index.tsx
Labels: refactor

#1635 fix: status indicator deprecated
  src/components/StatusIndicator/__stories__/index.stories.tsx
  src/components/StatusIndicator/index.tsx
Labels: documentation

#1642 feat(deps): update react monorepo to v18 (major) (#1314)
  .eslintrc
  .loki/reference/chrome_laptop_Components_Container_Container_Right_Title.png
  .storybook/preview.tsx
  package.json
  pnpm-lock.yaml
  src/components/Avatar/__tests__/__snapshots__/index.tsx.snap
  src/components/Avatar/__tests__/index.tsx
  src/components/Button/index.tsx
  src/components/Container/__stories__/index.stories.tsx
  src/components/Counter/__tests__/index.test.tsx
  src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap
  src/components/LineChart/CustomLegend.tsx
  src/components/List/SelectBar.tsx
  src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  src/components/List/__tests__/index.test.tsx
  src/components/List/index.tsx
  src/components/List/variantExplorer.tsx
  src/components/List/variantProduct.tsx
  src/components/List/variantTable.tsx
  src/components/Menu/__tests__/__snapshots__/index.tsx.snap
  src/components/Menu/__tests__/index.tsx
  src/components/Menu/index.tsx
  src/components/Modal/__tests__/__snapshots__/index.tsx.snap
  src/components/Modal/index.tsx
  src/components/NavigationStepper/__tests__/index.test.tsx
  src/components/Pagination/index.tsx
  src/components/RichSelect/__stories__/index.stories.tsx
  src/components/SwitchButton/index.tsx
  src/components/Tooltip/__stories__/index.stories.tsx
  src/components/Tooltip/__tests__/index.test.tsx
  src/components/Tooltip/index.tsx
  src/components/TooltipIcon/__stories__/index.stories.tsx
  src/components/Typography/index.tsx
  src/helpers/jestHelpers.tsx
Labels: enhancement
