Repository scaleway/ultraviolet, pull requests merged in 2022-12, with the labels that each got.

#2079 refactor(alert): change alert default icon size to 24px
  src/components/Alert/__stories__/IconSize.stories.tsx
  src/components/Alert/__stories__/Variants.stories.tsx
  src/components/Alert/__stories__/index.stories.tsx
  src/components/Alert/__tests__/__snapshots__/index.test.tsx.snap
  src/components/Alert/__tests__/index.test.tsx
  src/components/Alert/index.tsx
  src/components/Toaster/__tests__/__snapshots__/index.tsx.snap
  src/components/Toaster/index.tsx
Labels: refactor

#2074 refactor(menu): replaced css by styled
  src/components/Menu/Item.tsx
  src/components/Menu/__tests__/__snapshots__/index.tsx.snap
  src/components/Tabs/__tests__/__snapshots__/index.test.tsx.snap
Labels: refactor

#2069 fix(website): update component usages
  src/theme/index.ts
  website/emotion.d.ts
  website/global.d.ts
  website/public/fonts/asap/Asap-Bold.woff2
  website/public/fonts/asap/Asap-Medium.woff2
  website/public/fonts/asap/Asap-Regular.woff2
  website/public/fonts/jetbrains/JetBrainsMono-Regular.woff2
  website/src/assets/illustrations/introduction.svg
  website/src/components/Card.tsx
  website/src/components/CopyBoxCommand.tsx
  website/src/components/Footer.tsx
  website/src/components/GithubAndDocumentationButtons.tsx
  website/src/components/GlobalStyle.tsx
  website/src/components/Header.tsx
  website/src/components/Logo.tsx
  website/src/pages/_app.tsx
  website/src/pages/home/AdvancedUseCases.tsx
  website/src/pages/home/GettingStarted.tsx
  website/src/pages/home/Introduction.tsx
  website/src/pages/home/OpenSource.tsx
  website/src/pages/home/index.tsx
  website/tsconfig.json
Labels: enhancement

#2086 refactor: rewrite stories toggle tooltipicon unitinput
  .storybook/preview.tsx
  package.json
  pnpm-lock.yaml
  src/components/Toggle/__stories__/ComplexLabel.stories.tsx
  src/components/Toggle/__stories__/Disabled.stories.tsx
  src/components/Toggle/__stories__/Label.stories.tsx
  src/components/Toggle/__stories__/LabelPosition.stories.tsx
  src/components/Toggle/__stories__/Playground.stories.tsx
  src/components/Toggle/__stories__/Sizes.stories.tsx
  src/components/Toggle/__stories__/Template.stories.tsx
  src/components/Toggle/__stories__/Tooltip.stories.tsx
  src/components/Toggle/__stories__/index.stories.tsx
  src/components/Toggle/index.tsx
  src/components/TooltipIcon/__stories__/Colors.stories.tsx
  src/components/TooltipIcon/__stories__/Playground.stories.tsx
  src/components/TooltipIcon/__stories__/Sizes.stories.tsx
  src/components/TooltipIcon/__stories__/Template.stories.tsx
  src/components/TooltipIcon/__stories__/index.stories.tsx
  src/components/UnitInput/__stories__/CustomOptions.stories.tsx
  src/components/UnitInput/__stories__/Disabled.stories.tsx
  src/components/UnitInput/__stories__/Playground.stories.tsx
  src/components/UnitInput/__stories__/Sizes.stories.tsx
  src/components/UnitInput/__stories__/Template.stories.tsx
  src/components/UnitInput/__stories__/index.stories.tsx
Labels: refactor

#2092 fix(list): tooltip never disapear after hover on disabled checkbox
  src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  src/components/List/variants/variantExplorer.tsx
  src/components/List/variants/variantProduct.tsx
  src/components/List/variants/variantTable.tsx
Labels: bug

#2100 fix(tabs): vertical scroll triggred on page load
  src/components/Tabs/index.tsx
Labels: bug

#2098 fix(RichSelect, ScrollView): clean stories
  src/components/RichSelect/__stories__/LoadingExample.stories.tsx
  src/components/ScrollView/__stories__/Playground.stories.tsx
Labels: refactor

#2102 feat: new list component
  src/components/List/__stories__/index.stories.tsx
  src/components/List/index.tsx
  src/components/ListV2/ListBody.tsx
  src/components/ListV2/ListCell.tsx
  src/components/ListV2/ListContext.tsx
  src/components/ListV2/ListExpandable.tsx
  src/components/ListV2/ListHeader.tsx
  src/components/ListV2/ListHeaderRow.tsx
  src/components/ListV2/ListHeaders.tsx
  src/components/ListV2/ListLoadingPlaceholder.tsx
  src/components/ListV2/ListRow.tsx
  src/components/ListV2/__stories__/AutoCloseRowExpandable.stories.tsx
  src/components/ListV2/__stories__/CheckboxDisabled.stories.tsx
  src/components/ListV2/__stories__/Loading.stories.tsx
  src/components/ListV2/__stories__/Playground.stories.tsx
  src/components/ListV2/__stories__/RowExpandable.stories.tsx
  src/components/ListV2/__stories__/RowExpandableWithAction.stories.tsx
  src/components/ListV2/__stories__/Selectable.stories.tsx
  src/components/ListV2/__stories__/SelectableWithActionBar.stories.tsx
  src/components/ListV2/__stories__/Sortable.stories.tsx
  src/components/ListV2/__stories__/Template.stories.tsx
  src/components/ListV2/__stories__/Variants.stories.tsx
  src/components/ListV2/__stories__/index.stories.tsx
  src/components/ListV2/__stories__/resources.ts
  src/components/ListV2/__tests__/__snapshots__/index.test.tsx.snap
  src/components/ListV2/__tests__/index.test.tsx
  src/components/ListV2/index.tsx
  src/components/index.ts
  src/index.ts
Labels: enhancement, design system

#2095 refactor(alert): type to variant prop
  src/__stories__/theme/colors.stories.mdx
  src/components/Alert/__stories__/Icon.stories.tsx
  src/components/Alert/__stories__/Title.stories.tsx
  src/components/Alert/__stories__/Variants.stories.tsx
  src/components/Alert/__stories__/index.stories.tsx
  src/components/Alert/__tests__/__snapshots__/index.test.tsx.snap
  src/components/Alert/__tests__/index.test.tsx
  src/components/Alert/index.tsx
  src/components/Container/__stories__/Header.stories.tsx
  src/components/Toaster/__tests__/__snapshots__/index.tsx.snap
  src/components/Toaster/index.tsx
Labels: refactor

#2101 fix(Checkbox): remove margin when empty
  src/components/Checkbox/__stories__/EmptyText.stories.tsx
  src/components/Checkbox/__stories__/Template.stories.tsx
  src/components/Checkbox/__stories__/index.stories.tsx
  src/components/Checkbox/__tests__/__snapshots__/index.tsx.snap
  src/components/Checkbox/__tests__/index.tsx
  src/components/Checkbox/index.tsx
  src/components/LineChart/__tests__/__snapshots__/index.tsx.snap
  src/components/List/SelectBar.tsx
  src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  src/components/List/variants/variantExplorer.tsx
  src/components/List/variants/variantProduct.tsx
  src/components/List/variants/variantTable.tsx
  src/components/ListV2/ListHeaderRow.tsx
  src/components/ListV2/ListRow.tsx
  src/components/ListV2/__tests__/__snapshots__/index.test.tsx.snap
  src/components/SelectableCard/__tests__/__snapshots__/index.tsx.snap
Labels: bug

#2109 fix: action bar display
  src/components/ActionBar/__tests__/__snapshots__/index.test.tsx.snap
  src/components/ActionBar/index.tsx
  src/components/List/__tests__/__snapshots__/index.test.tsx.snap
Labels: bug

#2103 docs: properties usages
  .storybook/preview.tsx
  src/__stories__/ComponentState/ComponentState.tsx
  src/__stories__/ComponentState/index.stories.mdx
  src/__stories__/GetStarted.stories.mdx
  src/__stories__/Properties/Properties.tsx
  src/__stories__/Properties/index.stories.mdx
  src/__stories__/Testing.stories.mdx
  tsconfig.json
Labels: documentation

#2112 refactor: remove polished dependency
  package.json
  pnpm-lock.yaml
  src/__stories__/components/Colors.tsx
  src/components/BarStack/__tests__/__snapshots__/index.test.tsx.snap
  src/components/BarStack/index.tsx
  src/components/Button/__tests__/__snapshots__/index.tsx.snap
  src/components/Button/index.tsx
  src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap
  src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  src/components/Pagination/__tests__/__snapshots__/index.test.tsx.snap
  src/components/PaginationV2/__tests__/__snapshots__/index.test.tsx.snap
Labels: enhancement, refactor

#2118 fix(toaster): wrong variant for error
  src/components/Toaster/__tests__/__snapshots__/index.tsx.snap
  src/components/Toaster/index.tsx
Labels: bug

#2119 fix: rerender loop
  src/components/ListV2/ListContext.tsx
  src/components/ListV2/__tests__/__snapshots__/index.test.tsx.snap
  src/components/ListV2/__tests__/index.test.tsx
Labels: bug

#2120 fix(menu): border radius and color on dark mode
  src/components/Menu/Item.tsx
  src/components/Menu/__tests__/__snapshots__/index.tsx.snap
  src/components/Menu/index.tsx
  src/components/Tabs/__tests__/__snapshots__/index.test.tsx.snap
Labels: bug

#2123 fix(actionBar): display flex is missing for alignement
  src/components/List/SelectBar.tsx
  src/components/List/__tests__/__snapshots__/index.test.tsx.snap
Labels: bug

#2117 fix: remove box list
  src/components/List/Cell.tsx
  src/components/List/__stories__/Template.stories.tsx
  src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  src/components/List/index.tsx
  src/components/List/types.ts
  src/components/List/variants/variantExplorer.tsx
  src/components/List/variants/variantProduct.tsx
  src/components/List/variants/variantTable.tsx
Labels: refactor

#2139 feat: remove Box and xstyled
  package.json
  pnpm-lock.yaml
  src/components/Box/__stories__/index.stories.tsx
  src/components/Box/__tests__/__snapshots__/index.tsx.snap
  src/components/Box/__tests__/index.tsx
  src/components/Box/index.tsx
  src/components/Tags/__tests__/__snapshots__/index.tsx.snap
  src/components/Tags/index.tsx
  website/src/pages/_document.tsx
Labels: refactor

#2129 fix(label): update label properties
  src/components/Label/__tests__/__snapshots__/index.tsx.snap
  src/components/Label/index.tsx
Labels: enhancement

#2137 fix(Icon): merge add and remove icons
  src/components/Alert/__tests__/__snapshots__/index.test.tsx.snap
  src/components/Alert/index.tsx
  src/components/Expandable/__stories__/Controlled.stories.tsx
  src/components/Icon/__tests__/__snapshots__/index.test.tsx.snap
  src/components/Icon/__tests__/index.test.tsx
  src/components/Icon/index.tsx
  src/components/PasswordCheck/index.tsx
  src/components/StepList/__tests__/__snapshots__/index.tsx.snap
  src/components/StepList/__tests__/index.tsx
  src/components/Toaster/__tests__/__snapshots__/index.tsx.snap
Labels: enhancement

#2125 fix(Tags): revert focusing input onChange
  src/components/Tags/__tests__/__snapshots__/index.tsx.snap
  src/components/Tags/__tests__/index.tsx
  src/components/Tags/index.tsx
Labels: bug

#2136 fix(Button): remove Link animation when using href
  src/components/Button/__tests__/__snapshots__/index.tsx.snap
  src/components/Button/index.tsx
  src/components/Menu/__tests__/__snapshots__/index.tsx.snap
Labels: bug

#2149 docs(form): re-organizition of stories title
  packages/form/src/__stories__/Changelog.stories.mdx
  packages/form/src/__stories__/Introduction.stories.mdx
  packages/form/src/components/CheckboxField/__stories__/index.stories.tsx
  packages/form/src/components/DateField/__stories__/index.stories.tsx
  packages/form/src/components/Form/__stories__/Playground.stories.tsx
  packages/form/src/components/Form/__stories__/index.stories.tsx
  packages/form/src/components/RadioField/__stories__/index.stories.tsx
  packages/form/src/components/RichSelectField/__stories__/index.stories.tsx
  packages/form/src/components/SelectNumberField/__stories__/index.stories.tsx
  packages/form/src/components/SelectableCardField/__stories__/index.stories.tsx
  packages/form/src/components/Submit/__stories__/index.stories.tsx
  packages/form/src/components/SubmitErrorAlert/__stories__/index.stories.tsx
  packages/form/src/components/TagsField/__stories__/index.stories.tsx
  packages/form/src/components/TextBoxField/__stories__/index.stories.tsx
  packages/form/src/components/TimeField/__stories__/index.stories.tsx
  packages/form/src/components/ToggleField/__stories__/index.stories.tsx
Labels: documentation

#2147 fix(tagsFields): initialValues was not working
  packages/form/src/components/TagsField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/TagsField/__tests__/index.spec.tsx
  packages/form/src/components/TagsField/index.tsx
  packages/ui/src/components/Tags/index.tsx
Labels: bug
