Repository scaleway/ultraviolet, pull requests merged in 2022-09, with the labels that each got.

#1828 feat: change loader by placeholder in List
  .loki/reference/chrome_laptop_Components_Data_Display_Placeholder_List.png
  .loki/reference/chrome_laptop_Components_List_Loading.png
  src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  src/components/List/index.tsx
  src/components/Placeholder/List.tsx
  src/components/Placeholder/__tests__/__snapshots__/index.tsx.snap
Labels: enhancement

#1807 feat: new tabs components
  .loki/reference/chrome_laptop_Components_Navigation_Tabs_Default.png
  .loki/reference/chrome_laptop_Components_Navigation_Tabs_Disabled.png
  .loki/reference/chrome_laptop_Components_Navigation_Tabs_Menu_Disabled.png
  .loki/reference/chrome_laptop_Components_Navigation_Tabs_Menu_Show_Case.png
  .loki/reference/chrome_laptop_Components_Navigation_Tabs_Showcase.png
  .loki/reference/chrome_laptop_Components_Navigation_Tabs_With_Badges.png
  .loki/reference/chrome_laptop_Components_Navigation_Tabs_With_Menu.png
  src/components/Menu/Item.tsx
  src/components/Menu/index.tsx
  src/components/TabGroup/Tab.tsx
  src/components/TabGroup/__stories__/index.stories.tsx
  src/components/TabGroup/__tests__/Tab.test.tsx
  src/components/TabGroup/__tests__/TabGroup.test.tsx
  src/components/TabGroup/__tests__/__snapshots__/Tab.test.tsx.snap
  src/components/TabGroup/__tests__/__snapshots__/TabGroup.test.tsx.snap
  src/components/TabGroup/index.tsx
  src/components/Tabs/Tab.tsx
  src/components/Tabs/TabMenu.tsx
  src/components/Tabs/TabMenuItem.tsx
  src/components/Tabs/TabsContext.ts
  src/components/Tabs/__stories__/index.stories.tsx
  src/components/Tabs/__tests__/__snapshots__/index.test.tsx.snap
  src/components/Tabs/__tests__/index.test.tsx
  src/components/Tabs/index.tsx
  src/components/Tooltip/index.tsx
  src/components/index.ts
Labels: enhancement, design system

#1840 ci: add tolerence to fix M1 test update
  .loki/reference/chrome_laptop_Components_Data_Display_BarStack_Basic.png
  .loki/reference/chrome_laptop_Components_Data_Display_BarStack_With_Max.png
  .loki/reference/chrome_laptop_Components_Data_Display_Placeholder_Block.png
  .loki/reference/chrome_laptop_Components_Data_Display_Placeholder_Blocks.png
  .loki/reference/chrome_laptop_Components_Data_Display_Placeholder_Box.png
  .loki/reference/chrome_laptop_Components_Data_Display_Placeholder_Default.png
  .loki/reference/chrome_laptop_Components_Data_Display_Placeholder_Donut.png
  .loki/reference/chrome_laptop_Components_Data_Display_Placeholder_Line.png
  .loki/reference/chrome_laptop_Components_Data_Display_Placeholder_List.png
  .loki/reference/chrome_laptop_Components_Data_Display_Placeholder_Slider.png
  .loki/reference/chrome_laptop_Components_Data_Display_ProgressBar_Progress.png
  .loki/reference/chrome_laptop_Components_Data_Display_Slider_Default.png
  .loki/reference/chrome_laptop_Components_Data_Display_StateBar_Progress.png
  .loki/reference/chrome_laptop_Components_Data_Entry_Range_Default.png
  .loki/reference/chrome_laptop_Components_Data_Entry_Range_Single_Value.png
  .loki/reference/chrome_laptop_Components_Data_Entry_Range_Two_Values.png
  .loki/reference/chrome_laptop_Components_Data_Entry_TextBox_Disabled.png
  .loki/reference/chrome_laptop_Components_List_Loading.png
  .loki/reference/chrome_laptop_Components_Touchable_Disabled.png
  package.json
Labels: enhancement, ci

#1841 fix(Text): italic & underline missing semicolon
  src/components/Text/__tests__/__snapshots__/index.test.tsx.snap
  src/components/Text/index.tsx
Labels: bug

#1838 refactor(FlexBox): remove from library
  .loki/reference/chrome_laptop_Components_Foundation_FlexBox_Child.png
  .loki/reference/chrome_laptop_Components_Foundation_FlexBox_Default.png
  .loki/reference/chrome_laptop_Components_Foundation_FlexBox_Nested.png
  src/components/FlexBox/__stories__/index.stories.tsx
  src/components/FlexBox/__tests__/__snapshots__/index.tsx.snap
  src/components/FlexBox/__tests__/index.tsx
  src/components/FlexBox/index.tsx
  src/components/index.ts
Labels: refactor

#1839 fix(PlaceHolder): make it compatible dark theme
  src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  src/components/Placeholder/__tests__/__snapshots__/index.tsx.snap
  src/components/Placeholder/index.tsx
Labels: enhancement

#1832 fix(RadioBorderedBox): remove from library
  .loki/reference/chrome_laptop_Components_Data_Entry_RadioBorderedBox_Badge.png
  .loki/reference/chrome_laptop_Components_Data_Entry_RadioBorderedBox_Controlled.png
  .loki/reference/chrome_laptop_Components_Data_Entry_RadioBorderedBox_Default.png
  .loki/reference/chrome_laptop_Components_Data_Entry_RadioBorderedBox_Disabled.png
  .loki/reference/chrome_laptop_Components_Data_Entry_RadioBorderedBox_Error.png
  .loki/reference/chrome_laptop_Components_Data_Entry_RadioBorderedBox_Label.png
  src/components/RadioBorderedBox/__stories__/index.stories.tsx
  src/components/RadioBorderedBox/__tests__/__snapshots__/index.tsx.snap
  src/components/RadioBorderedBox/__tests__/index.tsx
  src/components/RadioBorderedBox/index.tsx
  src/components/index.ts
Labels: refactor

#1837 fix(richselect): multi value padding without top label
  .loki/reference/chrome_laptop_Components_Data_Entry_RichSelect_Multi_Disabled.png
  src/components/RichSelect/__tests__/__snapshots__/index.tsx.snap
  src/components/RichSelect/index.tsx
Labels: bug

#1863 fix(linechart): select chart even when provided asynchronously
  src/components/LineChart/__tests__/__snapshots__/index.tsx.snap
  src/components/LineChart/__tests__/index.tsx
  src/components/LineChart/index.tsx
Labels: enhancement

#1844 feat(switchbutton): add animation
  .loki/reference/chrome_laptop_Components_Data_Entry_SwitchButton_Default.png
  src/components/SwitchButton/FocusOverlay.tsx
  src/components/SwitchButton/__tests__/__snapshots__/index.tsx.snap
  src/components/SwitchButton/__tests__/index.tsx
  src/components/SwitchButton/index.tsx
Labels: enhancement

#1872 feat(status): add better animation for status
  .loki/reference/chrome_laptop_Components_Data_Display_Status_Animated.png
  src/components/Status/__stories__/index.stories.tsx
  src/components/Status/__tests__/__snapshots__/index.tsx.snap
  src/components/Status/index.tsx
  src/utils/animations.ts
Labels: enhancement

#1874 fix: ci for production deployment
  .github/workflows/deploy-storybook.yml
  .github/workflows/deploy-website.yml
  .github/workflows/teardown_pull_request.yml
Labels: ci

#1857 feat(tooltip): dymanic position
  pnpm-lock.yaml
  src/components/Tooltip/__stories__/index.stories.tsx
  src/components/Tooltip/__tests__/index.test.tsx
  src/components/Tooltip/helpers.ts
  src/components/Tooltip/index.tsx
Labels: enhancement

#1881 fix(status): animation container
  .loki/reference/chrome_laptop_Components_Data_Display_Status_Tooltip.png
  src/components/Status/__tests__/__snapshots__/index.tsx.snap
  src/components/Status/index.tsx
Labels: bug

#1835 fix(SelectableCard): encapsulate children into div and add label
  .loki/reference/chrome_laptop_Components_Data_Display_Chart_LineChart_Multiple_Series_With_Custom_Legend.png
  .loki/reference/chrome_laptop_Components_Data_Entry_Checkbox_Checked.png
  .loki/reference/chrome_laptop_Components_Data_Entry_Checkbox_Default.png
  .loki/reference/chrome_laptop_Components_Data_Entry_Checkbox_Disabled.png
  .loki/reference/chrome_laptop_Components_Data_Entry_Checkbox_Errors.png
  .loki/reference/chrome_laptop_Components_Data_Entry_Checkbox_Progress.png
  .loki/reference/chrome_laptop_Components_Data_Entry_Checkbox_Sizes.png
  .loki/reference/chrome_laptop_Components_Data_Entry_Checkbox_Value.png
  .loki/reference/chrome_laptop_Components_Data_Entry_Radio_Controlled.png
  .loki/reference/chrome_laptop_Components_Data_Entry_Radio_Default.png
  .loki/reference/chrome_laptop_Components_Data_Entry_Radio_Disabled.png
  .loki/reference/chrome_laptop_Components_Data_Entry_Radio_Error.png
  .loki/reference/chrome_laptop_Components_Data_Entry_SelectableCard_Children.png
  .loki/reference/chrome_laptop_Components_Data_Entry_SelectableCard_Controlled.png
  .loki/reference/chrome_laptop_Components_Data_Entry_SelectableCard_Default.png
  .loki/reference/chrome_laptop_Components_Data_Entry_SelectableCard_Disabled.png
  .loki/reference/chrome_laptop_Components_Data_Entry_SelectableCard_Is_Error.png
  .loki/reference/chrome_laptop_Components_Data_Entry_SelectableCard_Show_Tick.png
  .loki/reference/chrome_laptop_Components_Data_Entry_SelectableCard_Tooltip.png
  .loki/reference/chrome_laptop_Components_Data_Entry_SelectableCard_Type.png
  .loki/reference/chrome_laptop_Components_Data_Entry_SwitchButton_Default.png
  .loki/reference/chrome_laptop_Components_List_Animated.png
  .loki/reference/chrome_laptop_Components_List_Disabled.png
  .loki/reference/chrome_laptop_Components_List_Explorer_Variant.png
  .loki/reference/chrome_laptop_Components_List_Loading.png
  .loki/reference/chrome_laptop_Components_List_Multiselect.png
  .loki/reference/chrome_laptop_Components_List_Pagination_Data.png
  .loki/reference/chrome_laptop_Components_List_Pagination_Loading.png
  .loki/reference/chrome_laptop_Components_List_Pagination_Loading_Page_Count.png
  .loki/reference/chrome_laptop_Components_List_Pagination_Prefetched_Data.png
  .loki/reference/chrome_laptop_Components_List_Ref.png
  .loki/reference/chrome_laptop_Components_List_Row_Variants.png
  .loki/reference/chrome_laptop_Components_List_Table_Variant.png
  src/__tests__/a11y.test.tsx
  src/components/Checkbox/__tests__/__snapshots__/index.tsx.snap
  src/components/Checkbox/__tests__/index.tsx
  src/components/Checkbox/index.tsx
  src/components/LineChart/__tests__/__snapshots__/index.tsx.snap
  src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  src/components/Radio/__tests__/__snapshots__/index.tsx.snap
  src/components/Radio/index.tsx
  src/components/SelectableCard/__stories__/index.stories.tsx
  src/components/SelectableCard/__tests__/__snapshots__/index.tsx.snap
  src/components/SelectableCard/index.tsx
  src/components/SwitchButton/__tests__/__snapshots__/index.tsx.snap
  src/components/SwitchButton/index.tsx
Labels: bug

#1887 fix(ci): persist deployments in pull requests
  .github/workflows/deploy-storybook.yml
  .github/workflows/deploy-website.yml
  .github/workflows/teardown_pull_request.yml
Labels: ci

#1888 fix(status): classname on container
  src/components/Status/__tests__/__snapshots__/index.tsx.snap
  src/components/Status/__tests__/index.tsx
  src/components/Status/index.tsx
Labels: bug

#1893 fix(radio): correct primary color when activated
  .loki/reference/chrome_laptop_Components_Data_Entry_Radio_Controlled.png
  .loki/reference/chrome_laptop_Components_Data_Entry_SelectableCard_Show_Tick.png
  src/components/Radio/__tests__/__snapshots__/index.tsx.snap
  src/components/Radio/index.tsx
  src/components/SelectableCard/__tests__/__snapshots__/index.tsx.snap
  src/components/SwitchButton/__tests__/__snapshots__/index.tsx.snap
Labels: bug

#1898 fix: radio and checkbox input
  .loki/reference/chrome_laptop_Components_Data_Entry_Radio_Controlled.png
  .loki/reference/chrome_laptop_Components_Data_Entry_Radio_Default.png
  .loki/reference/chrome_laptop_Components_Data_Entry_Radio_Disabled.png
  .loki/reference/chrome_laptop_Components_Data_Entry_Radio_Error.png
  .loki/reference/chrome_laptop_Components_Data_Entry_SelectableCard_Children.png
  .loki/reference/chrome_laptop_Components_Data_Entry_SelectableCard_Controlled.png
  .loki/reference/chrome_laptop_Components_Data_Entry_SelectableCard_Default.png
  .loki/reference/chrome_laptop_Components_Data_Entry_SelectableCard_Disabled.png
  .loki/reference/chrome_laptop_Components_Data_Entry_SelectableCard_Is_Error.png
  .loki/reference/chrome_laptop_Components_Data_Entry_SelectableCard_Show_Tick.png
  .loki/reference/chrome_laptop_Components_Data_Entry_SelectableCard_Tooltip.png
  .loki/reference/chrome_laptop_Components_Data_Entry_SelectableCard_Type.png
  .loki/reference/chrome_laptop_Components_Data_Entry_SwitchButton_Default.png
  src/components/Checkbox/__tests__/__snapshots__/index.tsx.snap
  src/components/Checkbox/index.tsx
  src/components/LineChart/__tests__/__snapshots__/index.tsx.snap
  src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  src/components/Radio/__tests__/__snapshots__/index.tsx.snap
  src/components/Radio/index.tsx
  src/components/SelectableCard/__tests__/__snapshots__/index.tsx.snap
  src/components/SwitchButton/__tests__/__snapshots__/index.tsx.snap
Labels: bug

#1901 feat(list): add correct type in SelectBar props
  src/components/List/SelectBar.tsx
  src/components/List/index.tsx
Labels: enhancement

#1894 feat: make pagination easy to use
  .loki/reference/chrome_laptop_Components_Navigation_PaginationV2_Basic.png
  .loki/reference/chrome_laptop_Components_Navigation_PaginationV2_Default.png
  .loki/reference/chrome_laptop_Components_Navigation_PaginationV2_Disabled.png
  src/components/PaginationV2/__stories__/index.stories.tsx
  src/components/PaginationV2/__tests__/__snapshots__/index.test.tsx.snap
  src/components/PaginationV2/__tests__/getPageNumbers.test.ts
  src/components/PaginationV2/__tests__/index.test.tsx
  src/components/PaginationV2/getPageNumbers.ts
  src/components/PaginationV2/index.tsx
  src/components/index.ts
Labels: enhancement

#1902 fix(pagination): do not update max page when list is loading
  src/components/List/index.tsx
  src/components/Pagination/usePagination.ts
Labels: enhancement

#1903 refactor(typography): remove typography
  .loki/reference/chrome_laptop_Components_Data_Display_StealthCopiable_Complex_Children.png
  .loki/reference/chrome_laptop_Components_Fondation_Typography_Alignment.png
  .loki/reference/chrome_laptop_Components_Fondation_Typography_Colored_Command.png
  .loki/reference/chrome_laptop_Components_Fondation_Typography_Default.png
  .loki/reference/chrome_laptop_Components_Fondation_Typography_Ellipsis.png
  .loki/reference/chrome_laptop_Components_Fondation_Typography_Max_Lines.png
  .loki/reference/chrome_laptop_Components_Fondation_Typography_Variants.png
  .loki/reference/chrome_laptop_Components_MarkDown_Default.png
  .loki/reference/chrome_laptop_Components_MarkDown_Link_Target.png
  src/components/MarkDown/__tests__/__snapshots__/index.tsx.snap
  src/components/MarkDown/index.tsx
  src/components/StealthCopiable/__stories__/index.stories.tsx
  src/components/Typography/__stories__/index.stories.tsx
  src/components/Typography/__stories__/migration.stories.mdx
  src/components/Typography/__tests__/__snapshots__/index.test.tsx.snap
  src/components/Typography/__tests__/index.test.tsx
  src/components/Typography/index.tsx
  src/components/index.ts
Labels: refactor

#1883 fix(menu): show args and valid code snippets in menu doc
  .loki/reference/chrome_laptop_Components_Navigation_Menu_Function_Disclosure.png
  .loki/reference/chrome_laptop_Components_Navigation_Menu_Playground.png
  .loki/reference/chrome_laptop_Components_Navigation_Menu_With_Modal.png
  src/components/Menu/__stories__/Borderless.tsx
  src/components/Menu/__stories__/ChildrenProps.tsx
  src/components/Menu/__stories__/FunctionDisclosure.tsx
  src/components/Menu/__stories__/Playground.tsx
  src/components/Menu/__stories__/Template.tsx
  src/components/Menu/__stories__/Variants.tsx
  src/components/Menu/__stories__/WithModal.tsx
  src/components/Menu/__stories__/index.stories.tsx
Labels: enhancement

#1904 fix: radio checkbox and selectable card visible input
  .loki/reference/chrome_laptop_Components_Data_Entry_Radio_Controlled.png
  .loki/reference/chrome_laptop_Components_Data_Entry_Radio_Default.png
  .loki/reference/chrome_laptop_Components_Data_Entry_Radio_Disabled.png
  .loki/reference/chrome_laptop_Components_Data_Entry_Radio_Error.png
  .loki/reference/chrome_laptop_Components_Data_Entry_SelectableCard_Children.png
  .loki/reference/chrome_laptop_Components_Data_Entry_SelectableCard_Controlled.png
  .loki/reference/chrome_laptop_Components_Data_Entry_SelectableCard_Default.png
  .loki/reference/chrome_laptop_Components_Data_Entry_SelectableCard_Disabled.png
  .loki/reference/chrome_laptop_Components_Data_Entry_SelectableCard_Is_Error.png
  .loki/reference/chrome_laptop_Components_Data_Entry_SelectableCard_Show_Tick.png
  .loki/reference/chrome_laptop_Components_Data_Entry_SelectableCard_Tooltip.png
  .loki/reference/chrome_laptop_Components_Data_Entry_SelectableCard_Type.png
  .loki/reference/chrome_laptop_Components_Data_Entry_SwitchButton_Default.png
  src/components/Checkbox/__tests__/__snapshots__/index.tsx.snap
  src/components/Checkbox/index.tsx
  src/components/LineChart/__tests__/__snapshots__/index.tsx.snap
  src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  src/components/Radio/__tests__/__snapshots__/index.tsx.snap
  src/components/Radio/index.tsx
  src/components/SelectableCard/__tests__/__snapshots__/index.tsx.snap
  src/components/SelectableCard/index.tsx
  src/components/SwitchButton/__tests__/__snapshots__/index.tsx.snap
Labels: bug

#1895 feat(list): better loading placeholder
  .loki/reference/chrome_laptop_Components_List_Loading.png
  .loki/reference/chrome_laptop_Components_List_Pagination_Lazy_Loading.png
  src/components/List/LoadingPlaceholder.tsx
  src/components/List/__stories__/index.stories.tsx
  src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  src/components/List/context.ts
  src/components/List/index.tsx
  src/components/List/variants/index.ts
  src/components/List/variants/variantExplorer.tsx
  src/components/List/variants/variantProduct.tsx
  src/components/List/variants/variantTable.tsx
Labels: enhancement

#1908 feat: new component Stack
  .loki/reference/chrome_laptop_Components_Container_Stack_Align_Items.png
  .loki/reference/chrome_laptop_Components_Container_Stack_Classname.png
  .loki/reference/chrome_laptop_Components_Container_Stack_Direction.png
  .loki/reference/chrome_laptop_Components_Container_Stack_Gap.png
  .loki/reference/chrome_laptop_Components_Container_Stack_Horizontal.png
  .loki/reference/chrome_laptop_Components_Container_Stack_Justify_Content.png
  .loki/reference/chrome_laptop_Components_Container_Stack_Playground.png
  src/__tests__/a11y.test.tsx
  src/components/Stack/__stories__/AlignItems.tsx
  src/components/Stack/__stories__/Classname.tsx
  src/components/Stack/__stories__/Direction.tsx
  src/components/Stack/__stories__/Gap.tsx
  src/components/Stack/__stories__/JustifyContent.tsx
  src/components/Stack/__stories__/Playground.tsx
  src/components/Stack/__stories__/Template.tsx
  src/components/Stack/__stories__/index.stories.tsx
  src/components/Stack/__tests__/__snapshots__/index.tsx.snap
  src/components/Stack/__tests__/index.tsx
  src/components/Stack/index.tsx
  src/components/index.ts
Labels: design system
