Repository scaleway/ultraviolet, pull requests merged in 2022-10, with the labels that each got.

#1910 docs: make pagination deprecated
  src/components/Pagination/__stories__/index.stories.tsx
  src/components/Pagination/index.tsx
Labels: documentation

#1919 ci: make sync tokens triggerable
  .github/workflows/sync-design-tokens.yml
Labels: ci

#1921 refactor(statebar): use stack
  .loki/reference/chrome_laptop_Components_Data_Display_StateBar_Default.png
  .loki/reference/chrome_laptop_Components_Data_Display_StateBar_Progress.png
  .loki/reference/chrome_laptop_Components_Data_Display_StateBar_Unlimited.png
  src/components/StateBar/__tests__/__snapshots__/index.tsx.snap
  src/components/StateBar/index.tsx
Labels: enhancement

#1917 fix(list): ignore 0 page count
  src/components/Pagination/usePagination.ts
Labels: enhancement

#1920 fix(PieChart): vertical scroll auto
  src/components/PieChart/Legends.tsx
  src/components/PieChart/__tests__/__snapshots__/index.tsx.snap
Labels: enhancement

#1928 fix: force text align in counter
  src/components/Tabs/Tab.tsx
  src/components/Tabs/__tests__/__snapshots__/index.test.tsx.snap
Labels: bug

#1925 fix: updated theme documentation and extendTheme function
  .storybook/preview.tsx
  src/__stories__/Theme.stories.mdx
  src/__stories__/theme/colors.stories.mdx
  src/__stories__/theme/darkMode.stories.mdx
  src/__stories__/theme/shadows.stories.mdx
  src/__stories__/theme/spacesAndRadii.stories.mdx
  src/__stories__/theme/typography.stories.mdx
  src/index.ts
  src/theme/index.ts
  website/src/pages/_app.tsx
Labels: documentation

#1932 fix(tooltip): apply className on tooltip instead of children
  src/components/Tooltip/index.tsx
Labels: bug

#1935 docs: remove decorators from code snippets - global configuration
  .storybook/preview.tsx
  src/components/Menu/__stories__/index.stories.tsx
Labels: enhancement

#1931 fix(TextBox): required icon color
  .loki/reference/chrome_laptop_Components_Data_Entry_TextBox_Required.png
  src/components/TextBox/__tests__/__snapshots__/index.test.tsx.snap
  src/components/TextBox/index.tsx
Labels: bug

#1929 ci: fix flacky ci and remove unsed code
  src/__tests__/a11y.test.tsx
Labels: enhancement, ci

#1930 fix(list): show placeholder when data length is unknown
  src/components/List/LoadingPlaceholder.tsx
  src/components/List/index.tsx
Labels: bug

#1941 fix: improve story writing
  .eslintrc
  src/components/Menu/__stories__/FunctionDisclosure.tsx
  src/components/Menu/__stories__/Variants.tsx
  src/components/Toggle/__stories__/index.stories.tsx
Labels: enhancement

#1950 fix(Tabs): counter will be displayed if value is zero
  .loki/reference/chrome_laptop_Components_Navigation_Tabs_With_Counter.png
  src/components/Tabs/Tab.tsx
  src/components/Tabs/__stories__/index.stories.tsx
  src/components/Tabs/__tests__/__snapshots__/index.test.tsx.snap
  src/components/Tabs/__tests__/index.test.tsx
Labels: bug

#1942 refactor(menu): improve stories snippet parsing
  src/components/Menu/__stories__/Borderless.stories.tsx
  src/components/Menu/__stories__/ChildrenProps.stories.tsx
  src/components/Menu/__stories__/ChildrenProps.tsx
  src/components/Menu/__stories__/FunctionDisclosure.stories.tsx
  src/components/Menu/__stories__/FunctionDisclosure.tsx
  src/components/Menu/__stories__/Playground.stories.tsx
  src/components/Menu/__stories__/Template.stories.tsx
  src/components/Menu/__stories__/Variants.stories.tsx
  src/components/Menu/__stories__/WithModal.stories.tsx
  src/components/Menu/__stories__/index.stories.tsx
  src/components/Menu/index.tsx
Labels: enhancement

#1945 refactor(expandable): remove box
  src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap
  src/components/Expandable/__tests__/__snapshots__/index.tsx.snap
  src/components/Expandable/index.tsx
  src/components/RichSelect/__tests__/__snapshots__/index.tsx.snap
  src/components/RichSelect/index.tsx
  src/components/TextBox/__tests__/__snapshots__/index.test.tsx.snap
  src/components/TextBox/index.tsx
  src/components/TimeInput/__tests__/__snapshots__/index.tsx.snap
  src/components/UnitInput/__tests__/__snapshots__/index.tsx.snap
Labels: refactor

#1960 docs: fix description not display in storybook
  .storybook/components/DocsContainer.tsx
Labels: bug, documentation

#1944 refactor(selectnumber): remove box
  src/components/SelectNumber/__stories__/index.stories.tsx
  src/components/SelectNumber/__tests__/__snapshots__/index.tsx.snap
  src/components/SelectNumber/index.tsx
Labels: refactor

#1949 refactor: stories for Badge, Bullet, Borderedbox
  .loki/reference/chrome_laptop_Components_Container_BorderedBox_Playground.png
  .loki/reference/chrome_laptop_Components_Data_Display_Badge_Playground.png
  .loki/reference/chrome_laptop_Components_Data_Display_Badge_Prominences.png
  .loki/reference/chrome_laptop_Components_Data_Display_Badge_Sizes.png
  .loki/reference/chrome_laptop_Components_Data_Display_Bullet_Icon.png
  .loki/reference/chrome_laptop_Components_Data_Display_Bullet_Playground.png
  .loki/reference/chrome_laptop_Components_Data_Display_Bullet_Sizes.png
  .loki/reference/chrome_laptop_Components_Data_Display_Bullet_Text.png
  .loki/reference/chrome_laptop_Components_Data_Display_Bullet_Variants.png
  src/components/Badge/__stories__/Disabled.stories.tsx
  src/components/Badge/__stories__/Icon.stories.tsx
  src/components/Badge/__stories__/Playground.stories.tsx
  src/components/Badge/__stories__/Prominences.stories.tsx
  src/components/Badge/__stories__/Sizes.stories.tsx
  src/components/Badge/__stories__/Template.tsx
  src/components/Badge/__stories__/Variants.stories.tsx
  src/components/Badge/__stories__/index.stories.tsx
  src/components/BorderedBox/__stories__/Playground.stories.tsx
  src/components/BorderedBox/__stories__/Template.tsx
  src/components/BorderedBox/__stories__/index.stories.tsx
  src/components/Bullet/__stories__/Icon.stories.tsx
  src/components/Bullet/__stories__/Playground.stories.tsx
  src/components/Bullet/__stories__/Sizes.stories.tsx
  src/components/Bullet/__stories__/Template.tsx
  src/components/Bullet/__stories__/Text.stories.tsx
  src/components/Bullet/__stories__/Tooltip.stories.tsx
  src/components/Bullet/__stories__/Variants.stories.tsx
  src/components/Bullet/__stories__/index.stories.tsx
Labels: documentation

#1946 refactor(icon): remove box
  src/components/Alert/__tests__/__snapshots__/index.test.tsx.snap
  src/components/Avatar/__tests__/__snapshots__/index.tsx.snap
  src/components/Avatar/index.tsx
  src/components/Badge/__tests__/__snapshots__/index.tsx.snap
  src/components/Bullet/__tests__/__snapshots__/index.tsx.snap
  src/components/Button/__tests__/__snapshots__/index.tsx.snap
  src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap
  src/components/DateInput/index.tsx
  src/components/Icon/__stories__/index.stories.tsx
  src/components/Icon/__tests__/__snapshots__/index.test.tsx.snap
  src/components/Icon/index.tsx
  src/components/Link/__tests__/__snapshots__/index.tsx.snap
  src/components/List/SortIcon.tsx
  src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  src/components/List/__tests__/index.test.tsx
  src/components/MarkDown/__tests__/__snapshots__/index.tsx.snap
  src/components/Modal/__tests__/__snapshots__/index.tsx.snap
  src/components/NavigationStepper/__tests__/__snapshots__/index.test.tsx.snap
  src/components/Notice/__tests__/__snapshots__/index.tsx.snap
  src/components/Notice/index.tsx
  src/components/Pagination/__tests__/__snapshots__/index.test.tsx.snap
  src/components/PaginationV2/__tests__/__snapshots__/index.test.tsx.snap
  src/components/PasswordCheck/__tests__/__snapshots__/index.test.tsx.snap
  src/components/RichSelect/__tests__/__snapshots__/index.tsx.snap
  src/components/RichSelect/index.tsx
  src/components/SelectNumber/__tests__/__snapshots__/index.tsx.snap
  src/components/Separator/__tests__/__snapshots__/index.tsx.snap
  src/components/StepList/__tests__/__snapshots__/index.tsx.snap
  src/components/Stepper/__tests__/__snapshots__/index.test.tsx.snap
  src/components/Tabs/__tests__/__snapshots__/index.test.tsx.snap
  src/components/Tag/__tests__/__snapshots__/index.tsx.snap
  src/components/Tags/__tests__/__snapshots__/index.tsx.snap
  src/components/TextBox/__tests__/__snapshots__/index.test.tsx.snap
  src/components/TextBox/index.tsx
  src/components/TimeInput/__tests__/__snapshots__/index.tsx.snap
  src/components/Toaster/__tests__/__snapshots__/index.tsx.snap
  src/components/Toaster/index.tsx
  src/components/TooltipIcon/__tests__/__snapshots__/index.tsx.snap
  src/components/TooltipIcon/index.tsx
  src/components/UnitInput/__tests__/__snapshots__/index.tsx.snap
  src/components/VolumeSize/__tests__/__snapshots__/index.tsx.snap
Labels: refactor

#1959 docs: update storybook doc status, switchbutton and text
  .loki/reference/chrome_laptop_Components_Data_Entry_SwitchButton_Playground.png
  .loki/reference/chrome_laptop_Components_Fondation_Text_Playground.png
  src/components/Status/__stories__/Animated.stories.tsx
  src/components/Status/__stories__/Playground.stories.tsx
  src/components/Status/__stories__/Template.stories.tsx
  src/components/Status/__stories__/Tooltip.stories.tsx
  src/components/Status/__stories__/Variants.stories.tsx
  src/components/Status/__stories__/index.stories.tsx
  src/components/SwitchButton/__stories__/Playground.stories.tsx
  src/components/SwitchButton/__stories__/Template.stories.tsx
  src/components/SwitchButton/__stories__/index.stories.tsx
  src/components/Text/__stories__/As.stories.tsx
  src/components/Text/__stories__/Color.stories.tsx
  src/components/Text/__stories__/Disabled.stories.tsx
  src/components/Text/__stories__/Italic.stories.tsx
  src/components/Text/__stories__/OneLine.stories.tsx
  src/components/Text/__stories__/Playground.stories.tsx
  src/components/Text/__stories__/Prominence.stories.tsx
  src/components/Text/__stories__/Template.stories.tsx
  src/components/Text/__stories__/Underline.stories.tsx
  src/components/Text/__stories__/Variants.stories.tsx
  src/components/Text/__stories__/index.stories.tsx
Labels: documentation

#1970 fix(tabs): incorrect tab type
  src/components/Tabs/Tab.tsx
Labels: bug

#1966 refactor: update storybook action bar / alert / avatar
  .loki/reference/chrome_laptop_Components_ActionBar_Playground.png
  .loki/reference/chrome_laptop_Components_Data_Display_Avatar_Lock.png
  .loki/reference/chrome_laptop_Components_Data_Display_Avatar_Playground.png
  .loki/reference/chrome_laptop_Components_Data_Display_Avatar_Text_Size.png
  .loki/reference/chrome_laptop_Components_Feedback_Alert_Icon.png
  .loki/reference/chrome_laptop_Components_Feedback_Alert_Playground.png
  .loki/reference/chrome_laptop_Components_Feedback_Alert_Types.png
  .loki/reference/chrome_laptop_Components_Feedback_Alert_Variants.png
  src/components/ActionBar/__stories__/Playground.stories.tsx
  src/components/ActionBar/__stories__/Ranks.stories.tsx
  src/components/ActionBar/__stories__/Template.stories.tsx
  src/components/ActionBar/__stories__/index.stories.tsx
  src/components/Alert/__stories__/AdvancedChildren.stories.tsx
  src/components/Alert/__stories__/Icon.stories.tsx
  src/components/Alert/__stories__/IconSize.stories.tsx
  src/components/Alert/__stories__/Playground.stories.tsx
  src/components/Alert/__stories__/Template.stories.tsx
  src/components/Alert/__stories__/Title.stories.tsx
  src/components/Alert/__stories__/Types.stories.tsx
  src/components/Alert/__stories__/Variants.stories.tsx
  src/components/Alert/__stories__/index.stories.tsx
  src/components/Alert/__tests__/__snapshots__/index.test.tsx.snap
  src/components/Alert/index.tsx
  src/components/Avatar/__stories__/BackgroundColor.stories.tsx
  src/components/Avatar/__stories__/Image.stories.tsx
  src/components/Avatar/__stories__/Lock.stories.tsx
  src/components/Avatar/__stories__/Playground.stories.tsx
  src/components/Avatar/__stories__/Size.stories.tsx
  src/components/Avatar/__stories__/Template.stories.tsx
  src/components/Avatar/__stories__/Text.stories.tsx
  src/components/Avatar/__stories__/TextColor.stories.tsx
  src/components/Avatar/__stories__/TextSize.stories.tsx
  src/components/Avatar/__stories__/index.stories.tsx
Labels: refactor

#1972 fix(modal): make sure close button is in front of content
  src/components/Modal/__tests__/__snapshots__/index.tsx.snap
  src/components/Modal/index.tsx
Labels: bug

#1967 fix(toggle): fix not toggling on storybook
  src/components/Toggle/__stories__/index.stories.tsx
Labels: bug

#1974 fix: add button type to styled buttons
  src/components/PaginationV2/__tests__/__snapshots__/index.test.tsx.snap
  src/components/PaginationV2/index.tsx
  src/components/SelectNumber/__tests__/__snapshots__/index.tsx.snap
  src/components/SelectNumber/index.tsx
Labels: bug

#1969 feat(CopyButton): new component
  .loki/reference/chrome_laptop_Components_Button_CopyButton_Custom_Texts.png
  .loki/reference/chrome_laptop_Components_Button_CopyButton_No_Border.png
  .loki/reference/chrome_laptop_Components_Button_CopyButton_Playground.png
  .loki/reference/chrome_laptop_Components_Button_CopyButton_Sizes.png
  .loki/reference/chrome_laptop_Components_Button_CopyButton_Variants.png
  src/components/CopyButton/__stories__/CustomTexts.stories.tsx
  src/components/CopyButton/__stories__/NoBorder.stories.tsx
  src/components/CopyButton/__stories__/Playground.stories.tsx
  src/components/CopyButton/__stories__/Sizes.stories.tsx
  src/components/CopyButton/__stories__/Template.stories.tsx
  src/components/CopyButton/__stories__/Variants.stories.tsx
  src/components/CopyButton/__stories__/index.stories.tsx
  src/components/CopyButton/__tests__/__snapshots__/index.tsx.snap
  src/components/CopyButton/__tests__/index.tsx
  src/components/CopyButton/index.tsx
  src/components/Tooltip/index.tsx
  src/components/index.ts
  website/src/components/CopyBoxCommand.tsx
  website/src/components/CopyButton.tsx
Labels: enhancement

#1973 docs(Table): fixed table crashing story and updated to new way
  src/components/Table/__stories__/Hoverable.stories.tsx
  src/components/Table/__stories__/Loader.stories.tsx
  src/components/Table/__stories__/Playground.stories.tsx
  src/components/Table/__stories__/Template.stories.tsx
  src/components/Table/__stories__/index.stories.tsx
  src/components/Table/__tests__/__snapshots__/index.tsx.snap
  src/components/Table/index.tsx
Labels: bug, documentation
