Repository scaleway/ultraviolet, pull requests merged in 2022-05, with the labels that each got.

#1436 fix(tags): remove inheritance background
  src/components/Tags/__tests__/__snapshots__/index.tsx.snap
  src/components/Tags/index.tsx
Labels: bug, design system

#1442 fix: modal types
  src/components/Modal/index.tsx
Labels: bug

#1464 feat(list): selected and disabled row
  .loki/reference/chrome_laptop_Components_List_Disabled.png
  src/components/List/__stories__/index.stories.tsx
  src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  src/components/List/__tests__/index.test.tsx
  src/components/List/index.tsx
  src/components/List/types.ts
  src/components/List/variantProduct.tsx
Labels: enhancement

#1467 ci(node): upgrade to node 18
  .github/workflows/ci.yml
  .github/workflows/pull_request_title.yml
  .github/workflows/sync-design-tokens.yml
  .github/workflows/visual-testing.yml
  package.json
Labels: ci

#1452 fix: stepper behaviour with rounding
  .loki/reference/chrome_laptop_Components_Data_Display_Stepper_Default.png
  .loki/reference/chrome_laptop_Components_Data_Display_Stepper_Disabled.png
  .loki/reference/chrome_laptop_Components_Data_Display_Stepper_Events.png
  .loki/reference/chrome_laptop_Components_Data_Display_Stepper_Steps.png
  .loki/reference/chrome_laptop_Components_Data_Display_Stepper_Text.png
  pnpm-lock.yaml
  src/components/PhoneInput/__tests__/__snapshots__/index.tsx.snap
  src/components/Stepper/__tests__/__snapshots__/index.tsx.snap
  src/components/Stepper/__tests__/index.tsx
  src/components/Stepper/index.tsx
Labels: bug

#1399 feat: bullet list becomes step title
  .loki/reference/chrome_laptop_Components_Data_Display_BulletList_Default.png
  .loki/reference/chrome_laptop_Components_Data_Display_BulletList_Showcase.png
  .loki/reference/chrome_laptop_Components_Data_Display_StepList_Bullet_Icon.png
  .loki/reference/chrome_laptop_Components_Data_Display_StepList_Default.png
  .loki/reference/chrome_laptop_Components_Data_Display_StepList_Disabled.png
  .loki/reference/chrome_laptop_Components_Data_Display_StepList_Sizes.png
  .loki/reference/chrome_laptop_Components_Data_Display_StepList_Variant.png
  .loki/reference/chrome_laptop_Components_Data_Display_StepTitle_Bullet_Icon.png
  .loki/reference/chrome_laptop_Components_Data_Display_StepTitle_Default.png
  .loki/reference/chrome_laptop_Components_Data_Display_StepTitle_Disabled.png
  .loki/reference/chrome_laptop_Components_Data_Display_StepTitle_List.png
  .loki/reference/chrome_laptop_Components_Data_Display_StepTitle_Sizes.png
  .loki/reference/chrome_laptop_Components_Data_Display_StepTitle_Variant.png
  src/__tests__/a11y.test.tsx
  src/components/BulletList/__stories__/index.stories.tsx
  src/components/BulletList/__tests__/__snapshots__/index.tsx.snap
  src/components/BulletList/__tests__/index.tsx
  src/components/BulletList/index.tsx
  src/components/StepList/__stories__/index.stories.tsx
  src/components/StepList/__tests__/__snapshots__/index.tsx.snap
  src/components/StepList/__tests__/index.tsx
  src/components/StepList/index.tsx
  src/components/index.ts
Labels: design system

#1483 fix: allow classname on steplist
  src/components/StepList/index.tsx
Labels: bug

#1480 fix(button): link variant
  .loki/reference/chrome_laptop_Components_Button_Button_Variants.png
  src/components/Button/__tests__/__snapshots__/index.tsx.snap
  src/components/Button/index.tsx
  src/components/ExtendedReminder/__tests__/__snapshots__/index.tsx.snap
  src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  src/components/Menu/__tests__/__snapshots__/index.tsx.snap
  src/components/Pagination/__tests__/__snapshots__/index.test.tsx.snap
Labels: bug

#1501 fix(list): bug with checkbox on list
  .loki/reference/chrome_laptop_Components_List_Table_Variant.png
  src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  src/components/List/variantExplorer.tsx
  src/components/List/variantProduct.tsx
  src/components/List/variantTable.tsx
Labels: bug

#1472 feat: explore loki interactions
  .loki/reference/chrome_laptop_Components_Feedback_TooltipIcon_Default.png
  .loki/reference/chrome_laptop_Components_Feedback_Tooltip_Default.png
  .loki/reference/chrome_laptop_Components_Navigation_Menu_Advanced_WIP.png
  .loki/reference/chrome_laptop_Components_Navigation_Menu_Borderless.png
  .loki/reference/chrome_laptop_Components_Navigation_Menu_Children_Props.png
  .loki/reference/chrome_laptop_Components_Navigation_Menu_Default.png
  .loki/reference/chrome_laptop_Components_Navigation_Menu_Modal.png
  .loki/reference/chrome_laptop_Components_Navigation_Menu_Variants.png
  .storybook/main.ts
  package.json
  pnpm-lock.yaml
  src/components/Menu/__stories__/index.stories.tsx
  src/components/Tooltip/__stories__/index.stories.tsx
  src/components/TooltipIcon/__stories__/index.stories.tsx
Labels: enhancement, design system
