Repository scaleway/ultraviolet, pull requests merged in 2022-03, with the labels that each got.

#1198 feat(colors): synchronise with figma
  .github/workflows/sync-design-tokens.yml
  .storybook/assets/scaleway-text-dark.png
  .storybook/assets/scaleway-text-light.png
  .storybook/components/DocsContainer.tsx
  .storybook/main.ts
  .storybook/manager.ts
  .storybook/preview.tsx
  .storybook/scaleway.ts
  CHANGELOG.md
  CONTRIBUTING.md
  package.json
  scripts/figma-synchronise-tokens.sh
  scripts/tokensExtension.json
  src/__stories__/Documentation.stories.mdx
  src/__stories__/Theme.stories.mdx
  src/__stories__/components/Colors.tsx
  src/__stories__/components/ThemeWrapper.tsx
  src/components/Dot/index.tsx
  src/components/Link/index.tsx
  src/components/Pentagon/index.tsx
  src/components/Sphere/index.tsx
  src/index.ts
  src/theme/__tests__/index.ts
  src/theme/deprecated/contrasts.ts
  src/theme/deprecated/helper.ts
  src/theme/index.ts
  src/theme/tokens/dark.ts
  src/theme/tokens/light.ts
  yarn.lock
Labels: enhancement, design system

#1254 fix: visual testing update
  .loki/reference/chrome_laptop_Components_Feedback_ActivityIndicator_Colors.png
  .loki/reference/chrome_laptop_Components_Feedback_ActivityIndicator_Trail_Color.png
Labels: bug, ci

#1259 fix: script and tokens
  .github/workflows/sync-design-tokens.yml
  CHANGELOG.md
  package.json
  scripts/figma-synchronise-tokens.sh
  src/theme/tokens/dark.ts
  src/theme/tokens/light.ts
Labels: enhancement

#1276 fix: missing yarn install
  .github/workflows/sync-design-tokens.yml
Labels: ci

#1280 fix: typescript errors and ci
  .github/workflows/sync-design-tokens.yml
  src/__stories__/components/Colors.tsx
Labels: bug

#1277 fix(menu): add className to menu component
  src/components/Menu/__tests__/__snapshots__/index.tsx.snap
  src/components/Menu/index.tsx
Labels: bug

#1264 feat(list): added some animation on list
  .loki/reference/chrome_laptop_Components_List_Animated.png
  src/components/List/__stories__/index.stories.tsx
  src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  src/components/List/__tests__/index.test.tsx
  src/components/List/index.tsx
  src/components/List/types.ts
  src/components/List/variantProduct.tsx
  src/components/List/variantTable.tsx
  src/utils/animations.ts
Labels: enhancement
