Repository scaleway/ultraviolet, pull requests merged in 2022-08, with the labels that each got.

#1719 fix(link): add on click for react router
  src/components/Link/index.tsx
Labels: bug

#1721 docs: fixed description to bodyStrong migration
  src/components/Typography/__stories__/migration.stories.mdx
Labels: documentation

#1704 fix(icons): removed product icons
  .loki/reference/chrome_laptop_Components_Button_Button_Action.png
  .loki/reference/chrome_laptop_Components_Token_Icon_Name.png
  src/components/Bullet/__tests__/__snapshots__/index.tsx.snap
  src/components/Bullet/__tests__/index.tsx
  src/components/Icon/__tests__/__snapshots__/index.test.tsx.snap
  src/components/Icon/index.tsx
Labels: enhancement

#1706 fix(colors): remove colors deprecated
  .loki/reference/chrome_laptop_Components_Data_Display_VolumeSize_Default.png
  .loki/reference/chrome_laptop_Components_Data_Display_VolumeSize_Min_Max_Size.png
  .loki/reference/chrome_laptop_Components_Data_Display_VolumeSize_Min_Size_Only.png
  .loki/reference/chrome_laptop_Components_Data_Display_VolumeSize_Min_Size_Only_And_Too_Small.png
  .loki/reference/chrome_laptop_Components_Data_Display_VolumeSize_Size_Too_Large.png
  .loki/reference/chrome_laptop_Components_Data_Display_VolumeSize_Size_Too_Small.png
  .loki/reference/chrome_laptop_Components_Data_Display_VolumeSize_Sizes.png
  .loki/reference/chrome_laptop_Components_Feedback_TooltipIcon_Colors.png
  .loki/reference/chrome_laptop_Components_Fondation_Typography_Colored_Command.png
  .loki/reference/chrome_laptop_Components_Token_Icon_Unknown_Or_Undefined.png
  src/components/Icon/__stories__/index.stories.tsx
  src/components/Icon/index.tsx
  src/components/Typography/index.tsx
  src/components/VolumeSize/__tests__/__snapshots__/index.tsx.snap
  src/components/VolumeSize/index.tsx
  src/theme/deprecated/colors.ts
  src/theme/index.ts
Labels: migration

#1730 fix(link): animation is broken when text follow
  src/components/Breadcrumbs/__tests__/__snapshots__/index.tsx.snap
  src/components/Button/__tests__/__snapshots__/index.tsx.snap
  src/components/Link/__stories__/index.stories.tsx
  src/components/Link/__tests__/__snapshots__/index.tsx.snap
  src/components/Link/index.tsx
  src/components/MarkDown/__tests__/__snapshots__/index.tsx.snap
Labels: bug

#1728 ci: max coverage on RadioBorderedBox, Tag and Text
  src/components/RadioBorderedBox/__tests__/__snapshots__/index.tsx.snap
  src/components/RadioBorderedBox/__tests__/index.tsx
  src/components/RadioBorderedBox/index.tsx
  src/components/Tag/__tests__/__snapshots__/index.tsx.snap
  src/components/Tag/__tests__/index.tsx
  src/components/Tag/index.tsx
  src/components/Text/__tests__/__snapshots__/index.test.tsx.snap
  src/components/Text/__tests__/index.test.tsx
  src/components/Text/index.tsx
Labels: ci

#1744 fix(PieChart): tooltip alignement
  src/components/PieChart/Tooltip.tsx
Labels: bug

#1727 feat: new selectablecard component
  .loki/reference/chrome_laptop_Components_Data_Entry_SelectableCard_Complex_Children.png
  .loki/reference/chrome_laptop_Components_Data_Entry_SelectableCard_Controlled.png
  .loki/reference/chrome_laptop_Components_Data_Entry_SelectableCard_Default.png
  .loki/reference/chrome_laptop_Components_Data_Entry_SelectableCard_Disabled.png
  .loki/reference/chrome_laptop_Components_Data_Entry_SelectableCard_Is_Error.png
  .loki/reference/chrome_laptop_Components_Data_Entry_SelectableCard_Show_Tick.png
  .loki/reference/chrome_laptop_Components_Data_Entry_SelectableCard_Type.png
  src/components/Radio/__tests__/__snapshots__/index.tsx.snap
  src/components/Radio/__tests__/index.tsx
  src/components/Radio/index.tsx
  src/components/SelectableCard/__stories__/index.stories.tsx
  src/components/SelectableCard/__tests__/__snapshots__/index.tsx.snap
  src/components/SelectableCard/__tests__/index.tsx
  src/components/SelectableCard/index.tsx
Labels: enhancement, design system

#1746 fix: labelDescription parm
  src/components/RadioBorderedBox/index.tsx
Labels: bug

#1748 feat(RadioBorderedBox): use SelectableCard
  .loki/reference/chrome_laptop_Components_Data_Entry_RadioBorderedBox_Badge.png
  .loki/reference/chrome_laptop_Components_Data_Entry_RadioBorderedBox_Controlled.png
  .loki/reference/chrome_laptop_Components_Data_Entry_RadioBorderedBox_Disabled.png
  .loki/reference/chrome_laptop_Components_Data_Entry_RadioBorderedBox_Error.png
  .loki/reference/chrome_laptop_Components_Data_Entry_RadioBorderedBox_Label.png
  src/components/RadioBorderedBox/__tests__/__snapshots__/index.tsx.snap
  src/components/RadioBorderedBox/index.tsx
  src/components/SelectableCard/index.tsx
Labels: enhancement, refactor

#1750 feat: make text support italic and underline
  .loki/reference/chrome_laptop_Components_Fondation_Text_Italic.png
  .loki/reference/chrome_laptop_Components_Fondation_Text_Underline.png
  src/components/LineChart/__tests__/__snapshots__/Tooltip.tsx.snap
  src/components/LineChart/__tests__/__snapshots__/index.tsx.snap
  src/components/RadioBorderedBox/__tests__/__snapshots__/index.tsx.snap
  src/components/StateBar/__tests__/__snapshots__/index.tsx.snap
  src/components/Stepper/__tests__/__snapshots__/index.test.tsx.snap
  src/components/Text/__stories__/index.stories.tsx
  src/components/Text/__tests__/__snapshots__/index.test.tsx.snap
  src/components/Text/__tests__/index.test.tsx
  src/components/Text/index.tsx
  src/components/VolumeSize/__tests__/__snapshots__/index.tsx.snap
Labels: enhancement

#1758 fix: radio and selectablecard
  src/components/Radio/__tests__/__snapshots__/index.tsx.snap
  src/components/Radio/index.tsx
  src/components/RadioBorderedBox/__tests__/__snapshots__/index.tsx.snap
  src/components/RadioBorderedBox/__tests__/index.tsx
  src/components/SelectableCard/__tests__/__snapshots__/index.tsx.snap
  src/components/SelectableCard/index.tsx
Labels: bug

#1752 refactor: remove flexbox usage
  .loki/reference/chrome_laptop_Components_Data_Display_Chart_LineChart_Multiple_Series_With_Custom_Legend.png
  .loki/reference/chrome_laptop_Components_Data_Entry_Range_Default.png
  .loki/reference/chrome_laptop_Components_Data_Entry_Range_Single_Value.png
  src/__stories__/Index.stories.mdx
  src/components/BarChart/Tooltip.tsx
  src/components/BarChart/__tests__/__snapshots__/Tooltip.tsx.snap
  src/components/Container/__tests__/__snapshots__/index.tsx.snap
  src/components/Container/index.tsx
  src/components/DotSteps/__tests__/__snapshots__/index.tsx.snap
  src/components/DotSteps/index.tsx
  src/components/LineChart/CustomLegend.tsx
  src/components/LineChart/Tooltip.tsx
  src/components/LineChart/__tests__/__snapshots__/Tooltip.tsx.snap
  src/components/LineChart/__tests__/__snapshots__/index.tsx.snap
  src/components/List/SelectBar.tsx
  src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  src/components/Pentagon/__stories__/index.stories.tsx
  src/components/Separator/__stories__/index.stories.tsx
  src/components/TagsPoplist/__tests__/__snapshots__/index.tsx.snap
  src/components/TagsPoplist/index.tsx
  src/components/TooltipIcon/__stories__/index.stories.tsx
Labels: refactor

#1753 feat(Notice): migrate from Box to div
  src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap
  src/components/Notice/__tests__/__snapshots__/index.tsx.snap
  src/components/Notice/index.tsx
  src/components/TextBox/__tests__/__snapshots__/index.test.tsx.snap
  src/components/TextBox/index.tsx
  src/components/UnitInput/__tests__/__snapshots__/index.tsx.snap
Labels: refactor

#1763 ci: mock random globally
  .jest/setupTests.ts
  src/components/Button/__tests__/index.tsx
  src/components/Checkbox/__tests__/index.tsx
  src/components/List/__tests__/index.test.tsx
  src/components/Loader/__tests__/index.test.tsx
  src/components/NavigationStepper/__tests__/index.test.tsx
  src/components/Pagination/__tests__/index.test.tsx
  src/components/PieChart/__tests__/index.tsx
  src/components/Placeholder/__tests__/index.tsx
  src/components/Radio/__tests__/index.tsx
  src/components/SelectNumber/__tests__/index.tsx
  src/components/SelectableCard/__tests__/index.tsx
  src/components/Table/__tests__/index.tsx
  src/components/Tags/__tests__/index.tsx
  src/components/Text/__tests__/index.test.tsx
  src/components/Toaster/__tests__/index.tsx
  src/components/Tooltip/__tests__/index.test.tsx
  src/components/UnitInput/__tests__/index.tsx
  src/utils/__tests__/index.tsx
Labels: ci

#1764 fix(pagination): double arrow icon too small
  .loki/reference/chrome_laptop_Components_Button_Button_Action.png
  .loki/reference/chrome_laptop_Components_List_Pagination_Data.png
  .loki/reference/chrome_laptop_Components_List_Pagination_Loading.png
  .loki/reference/chrome_laptop_Components_List_Pagination_Loading_Page_Count.png
  .loki/reference/chrome_laptop_Components_List_Pagination_Prefetched_Data.png
  .loki/reference/chrome_laptop_Components_Pagination_Basic.png
  .loki/reference/chrome_laptop_Components_Pagination_Default.png
  .loki/reference/chrome_laptop_Components_Pagination_Loadable_Next_Page.png
  .loki/reference/chrome_laptop_Components_Pagination_More_Page_Buttons.png
  .loki/reference/chrome_laptop_Components_Pagination_Page_Count.png
  .loki/reference/chrome_laptop_Components_Pagination_React_Component_Children.png
  .loki/reference/chrome_laptop_Components_Token_Icon_Name.png
  src/components/Icon/__tests__/__snapshots__/index.test.tsx.snap
  src/components/Icon/index.tsx
  src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  src/components/Pagination/__tests__/__snapshots__/index.test.tsx.snap
Labels: bug

#1771 fix(SelectableCard): support tooltip
  .loki/reference/chrome_laptop_Components_Data_Entry_SelectableCard_Tooltip.png
  src/components/SelectableCard/__stories__/index.stories.tsx
  src/components/SelectableCard/__tests__/__snapshots__/index.tsx.snap
  src/components/SelectableCard/__tests__/index.tsx
  src/components/SelectableCard/index.tsx
Labels: enhancement

#1773 fix(SelectableCard): avoid hidding all children svg
  src/components/Radio/__tests__/__snapshots__/index.tsx.snap
  src/components/Radio/index.tsx
  src/components/RadioBorderedBox/__tests__/__snapshots__/index.tsx.snap
  src/components/SelectableCard/__tests__/__snapshots__/index.tsx.snap
  src/components/SelectableCard/index.tsx
Labels: bug

#1751 feat: port Description from console
  src/components/Description/__stories__/index.stories.tsx
  src/components/Description/__tests__/__snapshots__/index.test.tsx.snap
  src/components/Description/__tests__/index.test.tsx
  src/components/Description/index.tsx
Labels: enhancement, refactor

#1801 ci(visual): fix tests
  .loki/reference/chrome_laptop_Components_Data_Display_Description_Default.png
  .loki/reference/chrome_laptop_Components_Data_Display_Description_Inline.png
  .loki/reference/chrome_laptop_Components_Data_Display_Description_Selectable.png
Labels: bug

#1762 refactor: remove typography usage
  .loki/reference/chrome_laptop_Components_Container_Container_Custom_Header.png
  .loki/reference/chrome_laptop_Components_Container_Container_Disabled.png
  .loki/reference/chrome_laptop_Components_Container_Container_Edition.png
  .loki/reference/chrome_laptop_Components_Container_Container_Right_Title.png
  .loki/reference/chrome_laptop_Components_Container_Container_Small.png
  .loki/reference/chrome_laptop_Components_Container_Container_Sub_Title.png
  .loki/reference/chrome_laptop_Components_Container_Container_Title.png
  .loki/reference/chrome_laptop_Components_Data_Display_Badge_Size.png
  .loki/reference/chrome_laptop_Components_Data_Entry_Checkbox_Errors.png
  .loki/reference/chrome_laptop_Components_Data_Entry_PasswordStrengthMeter_Default.png
  .loki/reference/chrome_laptop_Components_Data_Entry_PasswordStrengthMeter_User_Inputs.png
  .loki/reference/chrome_laptop_Components_Data_Entry_RadioBorderedBox_Badge.png
  .loki/reference/chrome_laptop_Components_Data_Entry_RadioBorderedBox_Controlled.png
  .loki/reference/chrome_laptop_Components_Data_Entry_RadioBorderedBox_Default.png
  .loki/reference/chrome_laptop_Components_Data_Entry_RadioBorderedBox_Disabled.png
  .loki/reference/chrome_laptop_Components_Data_Entry_RadioBorderedBox_Error.png
  .loki/reference/chrome_laptop_Components_Data_Entry_Range_Default.png
  .loki/reference/chrome_laptop_Components_Data_Entry_Range_Single_Value.png
  .loki/reference/chrome_laptop_Components_MarkDown_Default.png
  .loki/reference/chrome_laptop_Components_MarkDown_Link_Target.png
  src/__stories__/Index.stories.mdx
  src/__stories__/components/Colors.tsx
  src/components/Alert/__stories__/index.stories.tsx
  src/components/Alert/__tests__/__snapshots__/index.test.tsx.snap
  src/components/Alert/index.tsx
  src/components/Badge/__tests__/__snapshots__/index.tsx.snap
  src/components/Badge/index.tsx
  src/components/BarChart/Tooltip.tsx
  src/components/BarChart/__tests__/__snapshots__/Tooltip.tsx.snap
  src/components/Checkbox/__tests__/__snapshots__/index.tsx.snap
  src/components/Checkbox/index.tsx
  src/components/Container/__tests__/__snapshots__/index.tsx.snap
  src/components/Container/index.tsx
  src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap
  src/components/DateInput/index.tsx
  src/components/LineChart/__tests__/__snapshots__/index.tsx.snap
  src/components/List/SelectBar.tsx
  src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  src/components/List/index.tsx
  src/components/MarkDown/__tests__/__snapshots__/index.tsx.snap
  src/components/MarkDown/index.tsx
  src/components/PasswordStrengthMeter/__tests__/__snapshots__/index.test.tsx.snap
  src/components/PasswordStrengthMeter/index.tsx
  src/components/PieChart/__tests__/__snapshots__/index.tsx.snap
  src/components/PieChart/index.tsx
  src/components/Radio/__tests__/__snapshots__/index.tsx.snap
  src/components/Radio/index.tsx
  src/components/RadioBorderedBox/__tests__/__snapshots__/index.tsx.snap
  src/components/RichSelect/__tests__/__snapshots__/index.tsx.snap
  src/components/RichSelect/index.tsx
  src/components/SelectableCard/__tests__/__snapshots__/index.tsx.snap
  src/components/TextBox/__tests__/__snapshots__/index.test.tsx.snap
  src/components/TextBox/index.tsx
  src/components/TimeInput/__tests__/__snapshots__/index.tsx.snap
  src/components/Toaster/__tests__/__snapshots__/index.tsx.snap
  src/components/UnitInput/__tests__/__snapshots__/index.tsx.snap
Labels: refactor

#1803 ci(codecov): fix very low coverage changes on ci
  codecov.yml
Labels: ci

#1802 feat(SwitchButton): full refacto
  .loki/reference/chrome_laptop_Components_Data_Entry_SwitchButton_Default.png
  src/components/SwitchButton/__stories__/index.stories.tsx
  src/components/SwitchButton/__tests__/__snapshots__/index.tsx.snap
  src/components/SwitchButton/__tests__/index.tsx
  src/components/SwitchButton/index.tsx
Labels: enhancement, refactor

#1809 ci(codecov): correct fix
  codecov.yml
Labels: bug, ci

#1808 fix(SwitchButton): make background size dynamic using refs
  .loki/reference/chrome_laptop_Components_Data_Entry_SwitchButton_Default.png
  src/components/Checkbox/index.tsx
  src/components/Radio/index.tsx
  src/components/SelectableCard/index.tsx
  src/components/SwitchButton/__stories__/index.stories.tsx
  src/components/SwitchButton/__tests__/__snapshots__/index.tsx.snap
  src/components/SwitchButton/index.tsx
Labels: bug

#1810 fix(SwitchButton): drop animation
  .loki/reference/chrome_laptop_Components_Data_Entry_SwitchButton_Default.png
  src/components/Checkbox/__tests__/__snapshots__/index.tsx.snap
  src/components/Checkbox/index.tsx
  src/components/LineChart/__tests__/__snapshots__/index.tsx.snap
  src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  src/components/Radio/__tests__/__snapshots__/index.tsx.snap
  src/components/Radio/index.tsx
  src/components/RadioBorderedBox/__tests__/__snapshots__/index.tsx.snap
  src/components/SelectableCard/__tests__/__snapshots__/index.tsx.snap
  src/components/SwitchButton/__stories__/index.stories.tsx
  src/components/SwitchButton/__tests__/__snapshots__/index.tsx.snap
  src/components/SwitchButton/index.tsx
Labels: bug

#1815 fix(SwitchButton): disabled prop
  src/components/SwitchButton/index.tsx
Labels: bug

#1818 chore(react-count): remove unused dependency
  package.json
  pnpm-lock.yaml
Labels: dependencies

#1825 fix(toggle): uncontrolled and controlled behavior are wrong
  src/components/Toggle/__tests__/index.tsx
  src/components/Toggle/index.tsx
Labels: bug

#1823 fix(radio): nested radio container hover
  src/components/Radio/__tests__/__snapshots__/index.tsx.snap
  src/components/Radio/index.tsx
  src/components/RadioBorderedBox/__tests__/__snapshots__/index.tsx.snap
  src/components/SelectableCard/__tests__/__snapshots__/index.tsx.snap
  src/components/SwitchButton/__tests__/__snapshots__/index.tsx.snap
Labels: bug

#1827 fix(Toggle): add classname
  src/components/Toggle/index.tsx
Labels: bug

#1826 fix: use `useId` instead of `useUUID`
  src/components/Checkbox/__tests__/__snapshots__/index.tsx.snap
  src/components/Checkbox/index.tsx
  src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  src/components/Radio/__tests__/__snapshots__/index.tsx.snap
  src/components/Radio/index.tsx
  src/components/RichSelect/index.tsx
  src/components/SelectableCard/__tests__/__snapshots__/index.tsx.snap
  src/components/SwitchButton/__tests__/__snapshots__/index.tsx.snap
  src/components/Tooltip/__tests__/__snapshots__/index.test.tsx.snap
  src/components/Tooltip/index.tsx
  src/components/UnitInput/__tests__/__snapshots__/index.tsx.snap
  src/index.ts
  src/utils/__tests__/__snapshots__/index.tsx.snap
  src/utils/__tests__/index.tsx
  src/utils/ids.ts
Labels: refactor

#1824 feat(icons): add reboot icon
  .loki/reference/chrome_laptop_Components_Button_Button_Action.png
  .loki/reference/chrome_laptop_Components_Token_Icon_Name.png
  src/components/Icon/__tests__/__snapshots__/index.test.tsx.snap
  src/components/Icon/index.tsx
Labels: enhancement
