Repository scaleway/ultraviolet, pull requests merged in 2022-11, with the labels that each got.

#2005 fix(SelectNumber): max value undefined makes it unlimited value
  src/components/SelectNumber/__stories__/index.stories.tsx
  src/components/SelectNumber/__tests__/__snapshots__/index.tsx.snap
  src/components/SelectNumber/index.tsx
Labels: enhancement

#2001 docs: rewrite `Tag`, `Tags` and `TagsPoplist` stories
  src/components/Tag/__stories__/Disabled.stories.tsx
  src/components/Tag/__stories__/Icons.stories.tsx
  src/components/Tag/__stories__/Loading.stories.tsx
  src/components/Tag/__stories__/OnClose.stories.tsx
  src/components/Tag/__stories__/Playground.stories.tsx
  src/components/Tag/__stories__/Template.stories.tsx
  src/components/Tag/__stories__/Variants.stories.tsx
  src/components/Tag/__stories__/index.stories.tsx
  src/components/Tags/__stories__/Playground.stories.tsx
  src/components/Tags/__stories__/Template.stories.tsx
  src/components/Tags/__stories__/index.stories.tsx
  src/components/TagsPoplist/__stories__/Multiline.stories.tsx
  src/components/TagsPoplist/__stories__/Playground.stories.tsx
  src/components/TagsPoplist/__stories__/Template.stories.tsx
  src/components/TagsPoplist/__stories__/Threshold.stories.tsx
  src/components/TagsPoplist/__stories__/index.stories.tsx
Labels: documentation

#2010 refactor(grid): remove box props
  src/components/Grid/Col.tsx
  src/components/Grid/Grid.tsx
  src/components/Grid/Row.tsx
  src/components/Grid/__tests__/__snapshots__/index.tsx.snap
  src/components/PasswordCheck/__tests__/__snapshots__/index.test.tsx.snap
Labels: refactor

#2002 docs: rewrite `Stack`, `Stepper` and `Tooltip` stories
  src/components/Stack/__stories__/AlignItems.stories.tsx
  src/components/Stack/__stories__/AlignItems.tsx
  src/components/Stack/__stories__/Classname.tsx
  src/components/Stack/__stories__/Direction.stories.tsx
  src/components/Stack/__stories__/Direction.tsx
  src/components/Stack/__stories__/Gap.stories.tsx
  src/components/Stack/__stories__/Gap.tsx
  src/components/Stack/__stories__/JustifyContent.stories.tsx
  src/components/Stack/__stories__/JustifyContent.tsx
  src/components/Stack/__stories__/Playground.stories.tsx
  src/components/Stack/__stories__/Playground.tsx
  src/components/Stack/__stories__/Template.stories.tsx
  src/components/Stack/__stories__/helper.tsx
  src/components/Stack/__stories__/index.stories.tsx
  src/components/Stepper/__stories__/Playground.stories.tsx
  src/components/Stepper/__stories__/Template.stories.tsx
  src/components/Stepper/__stories__/WithAnimation.stories.tsx
  src/components/Stepper/__stories__/index.stories.tsx
  src/components/Tooltip/__stories__/MaxWidth.stories.tsx
  src/components/Tooltip/__stories__/Placement.stories.tsx
  src/components/Tooltip/__stories__/Playground.stories.tsx
  src/components/Tooltip/__stories__/Template.stories.tsx
  src/components/Tooltip/__stories__/index.stories.tsx
Labels: documentation

#2011 ci: fix teardown workflow
  .github/workflows/teardown_pull_request.yml
Labels: ci

#2007 refactor(RichSelect): remove Box
  src/components/RichSelect/__tests__/__snapshots__/index.tsx.snap
  src/components/RichSelect/index.tsx
  src/components/TimeInput/__tests__/__snapshots__/index.tsx.snap
  src/components/UnitInput/__tests__/__snapshots__/index.tsx.snap
  src/components/UnitInput/index.tsx
Labels: refactor

#2006 docs: rewrite `Loader` story and remove unused storybook helper
  src/__stories__/utils/decorators.tsx
  src/__stories__/utils/index.ts
  src/__stories__/utils/story.ts
  src/components/Loader/__stories__/Active.stories.tsx
  src/components/Loader/__stories__/Colors.stories.tsx
  src/components/Loader/__stories__/Percentages.stories.tsx
  src/components/Loader/__stories__/Playground.stories.tsx
  src/components/Loader/__stories__/Sizes.stories.tsx
  src/components/Loader/__stories__/StrokeWidth.stories.tsx
  src/components/Loader/__stories__/Template.tsx
  src/components/Loader/__stories__/Text.stories.tsx
  src/components/Loader/__stories__/TrailColor.stories.tsx
  src/components/Loader/__stories__/index.stories.tsx
Labels: documentation

#2012 fix(pagination): initial change page should never return 0
  src/components/Pagination/usePagination.ts
Labels: bug

#2013 fix(list): fix missing gap between list and pagination with table variant
  src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  src/components/List/index.tsx
  src/components/List/variants/variantProduct.tsx
Labels: bug

#1997 feat(Snippet): new component
  .storybook/preview.tsx
  src/__stories__/components/ThemeWrapper.tsx
  src/components/Snippet/__stories__/LongMultiline.stories.tsx
  src/components/Snippet/__stories__/LongSingleLine.stories.tsx
  src/components/Snippet/__stories__/Multiline.stories.tsx
  src/components/Snippet/__stories__/Playground.stories.tsx
  src/components/Snippet/__stories__/Prefixes.stories.tsx
  src/components/Snippet/__stories__/SingleLine.stories.tsx
  src/components/Snippet/__stories__/Template.stories.tsx
  src/components/Snippet/__stories__/index.stories.tsx
  src/components/Snippet/__tests__/__snapshots__/index.tsx.snap
  src/components/Snippet/__tests__/index.tsx
  src/components/Snippet/index.tsx
Labels: enhancement

#2014 fix(list): fix visual regression where gap is too large when list is loading
  src/components/List/LoadingPlaceholder.tsx
  src/components/List/__tests__/__snapshots__/index.test.tsx.snap
Labels: bug

#2015 refactor(list): reorganize List stories
  src/components/List/__stories__/Animated.stories.tsx
  src/components/List/__stories__/AutoClose.stories.tsx
  src/components/List/__stories__/Disabled.stories.tsx
  src/components/List/__stories__/EmptyText.stories.tsx
  src/components/List/__stories__/ExplorerVariant.stories.tsx
  src/components/List/__stories__/Loading.stories.tsx
  src/components/List/__stories__/Multiselect.stories.tsx
  src/components/List/__stories__/PaginationData.stories.tsx
  src/components/List/__stories__/PaginationLazyLoading.stories.tsx
  src/components/List/__stories__/PaginationPrefetchedData.stories.tsx
  src/components/List/__stories__/Playground.stories.tsx
  src/components/List/__stories__/Ref.stories.tsx
  src/components/List/__stories__/RowVariants.stories.tsx
  src/components/List/__stories__/Sorting.stories.tsx
  src/components/List/__stories__/TableVariant.stories.tsx
  src/components/List/__stories__/Template.stories.tsx
  src/components/List/__stories__/helper.ts
  src/components/List/__stories__/index.stories.tsx
  src/components/List/index.tsx
  src/mocks/list.ts
Labels: refactor

#2020 refactor: reorganize and improve `Image`, `Label`, `LineChart` stories
  src/components/Avatar/index.tsx
  src/components/Image/__stories__/Playground.stories.tsx
  src/components/Image/__stories__/Template.stories.tsx
  src/components/Image/__stories__/index.stories.tsx
  src/components/Image/index.tsx
  src/components/Label/__stories__/Playground.stories.tsx
  src/components/Label/__stories__/Template.stories.tsx
  src/components/Label/__stories__/index.stories.tsx
  src/components/Label/index.tsx
  src/components/LineChart/__stories__/FormattedAxisAndPoints.stories.tsx
  src/components/LineChart/__stories__/MultipleSeriesWithCustomLegend.stories.tsx
  src/components/LineChart/__stories__/Playground.stories.tsx
  src/components/LineChart/__stories__/Template.stories.tsx
  src/components/LineChart/__stories__/Time.stories.tsx
  src/components/LineChart/__stories__/index.stories.tsx
Labels: refactor

#2017 refactor: reorganize and improve DotSteps Expandable and Icon stories
  src/components/DotSteps/__stories__/Playground.stories.tsx
  src/components/DotSteps/__stories__/Template.stories.tsx
  src/components/DotSteps/__stories__/index.stories.tsx
  src/components/Expandable/__stories__/Controlled.stories.tsx
  src/components/Expandable/__stories__/Playground.stories.tsx
  src/components/Expandable/__stories__/Template.stories.tsx
  src/components/Expandable/__stories__/index.stories.tsx
  src/components/Icon/__stories__/Color.stories.tsx
  src/components/Icon/__stories__/Name.stories.tsx
  src/components/Icon/__stories__/Playground.stories.tsx
  src/components/Icon/__stories__/Size.stories.tsx
  src/components/Icon/__stories__/Template.stories.tsx
  src/components/Icon/__stories__/UnknownOrUndefined.stories.tsx
  src/components/Icon/__stories__/index.stories.tsx
Labels: refactor

#2021 fix(list): fix list header gap
  src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  src/components/List/index.tsx
  src/components/Pagination/index.tsx
Labels: bug

#2019 refactor: reorganize and improve PieChart, Placeholder and SelectNumber stories
  src/components/PieChart/Tooltip.tsx
  src/components/PieChart/__stories__/Content.stories.tsx
  src/components/PieChart/__stories__/EmptyLegend.stories.tsx
  src/components/PieChart/__stories__/Legends.stories.tsx
  src/components/PieChart/__stories__/Playground.stories.tsx
  src/components/PieChart/__stories__/PopperDetails.stories.tsx
  src/components/PieChart/__stories__/Strikethrough.stories.tsx
  src/components/PieChart/__stories__/Template.stories.tsx
  src/components/PieChart/__stories__/index.stories.tsx
  src/components/Placeholder/__stories__/Block.stories.tsx
  src/components/Placeholder/__stories__/Blocks.stories.tsx
  src/components/Placeholder/__stories__/Box.stories.tsx
  src/components/Placeholder/__stories__/Donut.stories.tsx
  src/components/Placeholder/__stories__/Line.stories.tsx
  src/components/Placeholder/__stories__/List.stories.tsx
  src/components/Placeholder/__stories__/Playground.stories.tsx
  src/components/Placeholder/__stories__/Slider.stories.tsx
  src/components/Placeholder/__stories__/Template.stories.tsx
  src/components/Placeholder/__stories__/index.stories.tsx
  src/components/SelectNumber/__stories__/Disabled.stories.tsx
  src/components/SelectNumber/__stories__/DisabledTooltip.stories.tsx
  src/components/SelectNumber/__stories__/Events.stories.tsx
  src/components/SelectNumber/__stories__/Playground.stories.tsx
  src/components/SelectNumber/__stories__/Sizes.stories.tsx
  src/components/SelectNumber/__stories__/Steps.stories.tsx
  src/components/SelectNumber/__stories__/Template.stories.tsx
  src/components/SelectNumber/__stories__/Text.stories.tsx
  src/components/SelectNumber/__stories__/index.stories.tsx
Labels: refactor

#2023 ci: fix script with new storiesfile format
  src/__tests__/a11y.test.tsx
Labels: enhancement, ci

#2018 fix: radio and checkbox properties and removed reakit usages
  src/components/Checkbox/__tests__/__snapshots__/index.tsx.snap
  src/components/Checkbox/__tests__/index.tsx
  src/components/Checkbox/index.tsx
  src/components/LineChart/__tests__/__snapshots__/index.tsx.snap
  src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  src/components/Radio/__tests__/__snapshots__/index.tsx.snap
  src/components/Radio/index.tsx
  src/components/SelectableCard/__tests__/__snapshots__/index.tsx.snap
  src/components/SwitchButton/__tests__/__snapshots__/index.tsx.snap
Labels: enhancement

#2035 feat(RichSelect): allow customization of empty state
  src/components/RichSelect/__stories__/index.stories.tsx
  src/components/RichSelect/__tests__/__snapshots__/index.tsx.snap
  src/components/RichSelect/__tests__/index.tsx
  src/components/RichSelect/index.tsx
Labels: enhancement

#2046 fix(Snippet): no prefix as default value
  src/components/Snippet/__stories__/LongMultiline.stories.tsx
  src/components/Snippet/__tests__/__snapshots__/index.tsx.snap
  src/components/Snippet/index.tsx
Labels: bug

#2055 feat(Icon): add book-open-outline and play-circle-outline
  src/components/Icon/__tests__/__snapshots__/index.test.tsx.snap
  src/components/Icon/index.tsx
Labels: design system

#2047 refactor: passwordStrengthMeter pentagon and progressBar stories
  src/components/PasswordStrengthMeter/__stories__/Playground.stories.tsx
  src/components/PasswordStrengthMeter/__stories__/Template.stories.tsx
  src/components/PasswordStrengthMeter/__stories__/UserInputs.stories.tsx
  src/components/PasswordStrengthMeter/__stories__/index.stories.tsx
  src/components/Pentagon/__stories__/Color.stories.tsx
  src/components/Pentagon/__stories__/Playground.stories.tsx
  src/components/Pentagon/__stories__/Size.stories.tsx
  src/components/Pentagon/__stories__/Template.stories.tsx
  src/components/Pentagon/__stories__/index.stories.tsx
  src/components/ProgressBar/__stories__/Cap.stories.tsx
  src/components/ProgressBar/__stories__/Playground.stories.tsx
  src/components/ProgressBar/__stories__/Progress.stories.tsx
  src/components/ProgressBar/__stories__/Template.stories.tsx
  src/components/ProgressBar/__stories__/Variants.stories.tsx
  src/components/ProgressBar/__stories__/index.stories.tsx
Labels: refactor

#2049 fix(menu): add forward ref to menu item
  src/components/Menu/Item.tsx
Labels: bug

#2057 fix(Button): as link
  src/components/Button/__stories__/index.stories.tsx
  src/components/Button/__tests__/__snapshots__/index.tsx.snap
  src/components/Button/index.tsx
  src/components/Menu/__tests__/__snapshots__/index.tsx.snap
Labels: bug

#2062 refactor: remove stealth copiable replace by copy button
  src/__tests__/a11y.test.tsx
  src/components/StealthCopiable/__stories__/index.stories.tsx
  src/components/StealthCopiable/__tests__/__snapshots__/index.tsx.snap
  src/components/StealthCopiable/__tests__/index.tsx
  src/components/StealthCopiable/index.tsx
  src/components/index.ts
  src/index.ts
Labels: refactor

#2063 docs: remove fonts load at each story to make it global
  .storybook/components/DocsContainer.tsx
  .storybook/preview.tsx
Labels: bug, documentation

#2064 refactor: remove volume size
  src/components/VolumeSize/__stories__/index.stories.tsx
  src/components/VolumeSize/__tests__/__snapshots__/index.tsx.snap
  src/components/VolumeSize/__tests__/index.tsx
  src/components/VolumeSize/index.tsx
  src/components/index.ts
  src/index.ts
Labels: refactor

#2067 fix: a11y parameters for text and link
  src/components/Link/index.tsx
  src/components/Text/index.tsx
Labels: enhancement

#2061 feat(toaster): add more options and update stories
  src/components/Toaster/__stories__/Playground.stories.tsx
  src/components/Toaster/__stories__/Template.stories.tsx
  src/components/Toaster/__stories__/Variants.stories.tsx
  src/components/Toaster/__stories__/index.stories.tsx
  src/components/Toaster/index.tsx
Labels: enhancement

#2053 docs: add readme changelog and component state
  .storybook/components/DocsContainer.tsx
  .storybook/preview.tsx
  README.md
  package.json
  pnpm-lock.yaml
  src/__stories__/Changelog.stories.mdx
  src/__stories__/ComponentState.tsx
  src/__stories__/ComponentsState.stories.mdx
  src/__stories__/Documentation.stories.mdx
  src/__stories__/HowToMakeBreakingChanges.stories.mdx
  src/__stories__/Index.stories.mdx
  src/__stories__/components/ThemeWrapper.tsx
  src/components/Grid/Col.tsx
Labels: documentation, enhancement
