Repository scaleway/ultraviolet, pull requests merged in 2022-07, with the labels that each got.

#1644 fix(Charts): correct color generation
  .loki/reference/chrome_laptop_Components_Data_Display_Chart_LineChart_Multiple_Series_With_Custom_Legend.png
  src/components/LineChart/__stories__/mockData.ts
  src/components/LineChart/__tests__/__snapshots__/index.tsx.snap
  src/helpers/legend.ts
Labels: bug

#1643 docs(migration): documentation for component migration
  .storybook/assets/logo-dark.svg
  .storybook/assets/logo-light.svg
  .storybook/assets/scaleway-text-dark.png
  .storybook/assets/scaleway-text-light.png
  .storybook/components/DocsContainer.tsx
  .storybook/components/Page.tsx
  .storybook/main.ts
  .storybook/storybookThemes.ts
  README.md
  pnpm-lock.yaml
  src/__stories__/Documentation.stories.mdx
  src/__stories__/HowToMakeBreakingChanges.stories.mdx
  src/__stories__/Migration.stories.mdx
  src/__stories__/MigrationTemplate.mdx.example
  src/components/Typography/__stories__/index.stories.tsx
  src/components/Typography/__stories__/migration.stories.mdx
Labels: documentation

#1649 fix: remove dep colors separator
  .loki/reference/chrome_laptop_Components_Data_Display_Separator_Color.png
  .loki/reference/chrome_laptop_Components_Data_Display_Separator_Icon.png
  src/__stories__/components/Colors.tsx
  src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap
  src/components/DateInput/index.tsx
  src/components/Separator/__stories__/index.stories.tsx
  src/components/Separator/__tests__/__snapshots__/index.tsx.snap
  src/components/Separator/__tests__/index.tsx
  src/components/Separator/index.tsx
  src/components/TextBox/__tests__/__snapshots__/index.test.tsx.snap
Labels: design system

#1647 feat: radioborderedbox complementary text and disabled
  .loki/reference/chrome_laptop_Components_Data_Entry_RadioBorderedBox_Badge.png
  .loki/reference/chrome_laptop_Components_Data_Entry_RadioBorderedBox_Controlled.png
  .loki/reference/chrome_laptop_Components_Data_Entry_RadioBorderedBox_Default.png
  .loki/reference/chrome_laptop_Components_Data_Entry_RadioBorderedBox_Disabled.png
  .loki/reference/chrome_laptop_Components_Data_Entry_RadioBorderedBox_Error.png
  .loki/reference/chrome_laptop_Components_Data_Entry_RadioBorderedBox_Label.png
  .loki/reference/chrome_laptop_Components_Fondation_Text_Disabled.png
  src/components/RadioBorderedBox/__stories__/index.stories.tsx
  src/components/RadioBorderedBox/__tests__/__snapshots__/index.tsx.snap
  src/components/RadioBorderedBox/index.tsx
  src/components/Text/__stories__/index.stories.tsx
  src/components/Text/index.tsx
Labels: enhancement

#1686 fix(button): progress with icon
  .loki/reference/chrome_laptop_Components_Button_Button_Progress_And_Icon.png
  src/components/Button/__stories__/index.stories.tsx
  src/components/Button/__tests__/__snapshots__/index.tsx.snap
  src/components/Button/__tests__/index.tsx
  src/components/Button/index.tsx
Labels: bug

#1690 feat: drop to prop on link component
  .loki/reference/chrome_laptop_Components_Button_Button_Link_Delegation.png
  src/components/Button/__tests__/__snapshots__/index.tsx.snap
  src/components/Button/__tests__/index.tsx
  src/components/Button/index.tsx
  src/components/Link/__tests__/__snapshots__/index.tsx.snap
  src/components/Link/__tests__/index.tsx
  src/components/Link/index.tsx
  src/components/Menu/__tests__/__snapshots__/index.tsx.snap
Labels: enhancement

#1653 fix(text): remove margin set by headers and paragraphs
  .loki/reference/chrome_laptop_Components_MarkDown_Default.png
  .loki/reference/chrome_laptop_Components_MarkDown_Link_Target.png
  src/utils/normalize.ts
Labels: enhancement

#1694 fix: errors and menu link not working
  .loki/reference/chrome_laptop_Components_Button_Button_Link_Delegation.png
  .loki/reference/chrome_laptop_Components_Container_Container_Right_Title.png
  .storybook/components/Page.tsx
  src/components/Avatar/__tests__/__snapshots__/index.tsx.snap
  src/components/Avatar/__tests__/index.tsx
  src/components/Button/__stories__/index.stories.tsx
  src/components/Container/__stories__/index.stories.tsx
  src/components/Link/__stories__/index.stories.tsx
  src/components/List/__stories__/index.stories.tsx
  src/components/Menu/Item.tsx
  src/components/Menu/__stories__/index.stories.tsx
  src/components/RichSelect/__stories__/index.stories.tsx
Labels: bug

#1698 fix: display link with inline flex
  .loki/reference/chrome_laptop_Components_Foundation_Link_Size.png
  .loki/reference/chrome_laptop_Components_MarkDown_Default.png
  .loki/reference/chrome_laptop_Components_MarkDown_Link_Target.png
  .loki/reference/chrome_laptop_Components_Navigation_Breadcrumbs_Default.png
  .loki/reference/chrome_laptop_Components_Navigation_Breadcrumbs_Selected.png
  .loki/reference/chrome_laptop_Components_Navigation_Breadcrumbs_To.png
  src/components/Breadcrumbs/__tests__/__snapshots__/index.tsx.snap
  src/components/Button/__tests__/__snapshots__/index.tsx.snap
  src/components/Link/__stories__/index.stories.tsx
  src/components/Link/__tests__/__snapshots__/index.tsx.snap
  src/components/Link/index.tsx
  src/components/MarkDown/__tests__/__snapshots__/index.tsx.snap
Labels: bug

#1697 fix: remove all errors and enable typecheck
  .github/workflows/ci.yml
  .loki/reference/chrome_laptop_Components_Data_Entry_RichSelect_Controlled.png
  src/__stories__/components/ControlValue.ts
  src/__stories__/utils/story.ts
  src/components/DateInput/__stories__/index.stories.tsx
  src/components/List/__stories__/index.stories.tsx
  src/components/Menu/__tests__/__snapshots__/index.tsx.snap
  src/components/Menu/__tests__/index.tsx
  src/components/RadioBorderedBox/__tests__/index.tsx
  src/components/RichSelect/__stories__/index.stories.tsx
  src/components/TimeInput/__stories__/index.stories.tsx
  src/helpers/recursivelyGetChildrenString.ts
Labels: enhancement

#1708 fix: button link alignement
  src/components/Button/__tests__/__snapshots__/index.tsx.snap
  src/components/Button/index.tsx
Labels: bug
