Repository scaleway/ultraviolet, pull requests merged in 2023-08, with the labels that each got.

#2768 refactor(Radio): update styling
  .changeset/warm-jars-serve.md
  packages/form/src/components/Form/__stories__/Playground.stories.tsx
  packages/form/src/components/RadioField/__stories__/Checked.stories.tsx
  packages/form/src/components/RadioField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/RadioField/__tests__/index.spec.tsx
  packages/form/src/components/RadioField/index.tsx
  packages/form/src/components/SelectableCardField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/ui/src/components/Radio/__stories__/Controlled.stories.tsx
  packages/ui/src/components/Radio/__stories__/Disabled.stories.tsx
  packages/ui/src/components/Radio/__stories__/Error.stories.tsx
  packages/ui/src/components/Radio/__stories__/Helper.stories.tsx
  packages/ui/src/components/Radio/__stories__/Template.stories.tsx
  packages/ui/src/components/Radio/__stories__/index.stories.tsx
  packages/ui/src/components/Radio/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Radio/__tests__/index.test.tsx
  packages/ui/src/components/Radio/index.tsx
  packages/ui/src/components/SelectableCard/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectableCard/index.tsx
  packages/ui/src/components/SwitchButton/__tests__/__snapshots__/index.test.tsx.snap
Labels: design system

#2783 feat(Text): add placement property
  .changeset/curvy-cobras-report.md
  packages/form/src/components/CheckboxField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/SubmitErrorAlert/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/TextInputField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/ui/src/components/Alert/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Badge/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Banner/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/BarChart/__tests__/__snapshots__/Tooltip.tsx.snap
  packages/ui/src/components/Card/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Checkbox/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/EmptyState/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/LineChart/__tests__/__snapshots__/Tooltip.test.tsx.snap
  packages/ui/src/components/LineChart/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Meter/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Notice/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/NumberInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/PasswordCheck/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/PasswordStrengthMeter/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/PieChart/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Radio/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectableCard/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Snippet/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Stepper/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Table/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Tabs/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Text/__stories__/Placement.stories.tsx
  packages/ui/src/components/Text/__stories__/index.stories.tsx
  packages/ui/src/components/Text/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Text/__tests__/index.test.tsx
  packages/ui/src/components/Text/index.tsx
  packages/ui/src/components/TextInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Toaster/__tests__/__snapshots__/index.test.tsx.snap
Labels: enhancement, UPDATE-MINOR

#2797 fix(submit): forward fullwidth into submit
  .changeset/odd-shrimps-speak.md
  packages/form/src/components/Submit/index.tsx
Labels: bug

#2796 feat(TagList): support icons
  .changeset/beige-cobras-train.md
  packages/ui/src/components/TagList/__stories__/Icons.stories.tsx
  packages/ui/src/components/TagList/__stories__/index.stories.tsx
  packages/ui/src/components/TagList/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TagList/__tests__/index.test.tsx
  packages/ui/src/components/TagList/index.tsx
Labels: enhancement

#2807 refactor(toggle): update toggle style
  .changeset/pretty-bats-juggle.md
  packages/form/src/components/ToggleField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/ui/src/components/Toggle/__stories__/Helper.stories.tsx
  packages/ui/src/components/Toggle/__stories__/index.stories.tsx
  packages/ui/src/components/Toggle/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Toggle/__tests__/index.test.tsx
  packages/ui/src/components/Toggle/index.tsx
Labels: enhancement

#2808 test(Modal): add story for Modal with Tooltip
  .changeset/twelve-masks-collect.md
  packages/ui/src/components/Modal/__stories__/WithTooltip.stories.tsx
  packages/ui/src/components/Modal/__stories__/index.stories.tsx
Labels: bug

#2782 refactor: update checkbox style
  .changeset/sour-ties-camp.md
  packages/form/src/components/CheckboxField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/CheckboxField/index.tsx
  packages/ui/src/components/Checkbox/__stories__/Checked.stories.tsx
  packages/ui/src/components/Checkbox/__stories__/Disabled.stories.tsx
  packages/ui/src/components/Checkbox/__stories__/Helper.stories.tsx
  packages/ui/src/components/Checkbox/__stories__/Progress.stories.tsx
  packages/ui/src/components/Checkbox/__stories__/Sizes.stories.tsx
  packages/ui/src/components/Checkbox/__stories__/index.stories.tsx
  packages/ui/src/components/Checkbox/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Checkbox/__tests__/index.tsx
  packages/ui/src/components/Checkbox/index.tsx
  packages/ui/src/components/LineChart/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectableCard/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Table/__tests__/__snapshots__/index.test.tsx.snap
Labels: enhancement

#2781 feat(ui,form): add `RadioGroup` & `RadioFormGroup` components
  .changeset/friendly-baboons-poke.md
  .changeset/sour-comics-float.md
  packages/form/src/components/RadioGroupField/__stories__/Direction.stories.tsx
  packages/form/src/components/RadioGroupField/__stories__/Error.stories.tsx
  packages/form/src/components/RadioGroupField/__stories__/Helper.stories.tsx
  packages/form/src/components/RadioGroupField/__stories__/Playground.stories.tsx
  packages/form/src/components/RadioGroupField/__stories__/Required.stories.tsx
  packages/form/src/components/RadioGroupField/__stories__/Template.stories.tsx
  packages/form/src/components/RadioGroupField/__stories__/index.stories.tsx
  packages/form/src/components/RadioGroupField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/RadioGroupField/__tests__/index.spec.tsx
  packages/form/src/components/RadioGroupField/index.tsx
  packages/form/src/components/index.ts
  packages/form/src/index.ts
  packages/ui/src/components/Radio/index.tsx
  packages/ui/src/components/RadioGroup/__stories__/Controlled.stories.tsx
  packages/ui/src/components/RadioGroup/__stories__/Direction.stories.tsx
  packages/ui/src/components/RadioGroup/__stories__/Error.stories.tsx
  packages/ui/src/components/RadioGroup/__stories__/Helper.stories.tsx
  packages/ui/src/components/RadioGroup/__stories__/Playground.stories.tsx
  packages/ui/src/components/RadioGroup/__stories__/Template.stories.tsx
  packages/ui/src/components/RadioGroup/__stories__/index.stories.tsx
  packages/ui/src/components/RadioGroup/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/RadioGroup/__tests__/index.test.tsx
  packages/ui/src/components/RadioGroup/index.tsx
  packages/ui/src/components/index.ts
Labels: enhancement

#2848 feat(Icons): add new social network icons
  .changeset/forty-parents-talk.md
  packages/icons/src/components/Icon/__tests__/__snapshots__/index.test.tsx.snap
  packages/icons/src/components/Icon/index.tsx
Labels: enhancement

#2851 feat(submit): adds onclick prop
  .changeset/silent-grapes-heal.md
  packages/form/src/components/Submit/index.tsx
Labels: enhancement
