Repository scaleway/ultraviolet, pull requests merged in 2023-09, with the labels that each got.

#2847 feat(ui): implement a new modal
  .changeset/big-hairs-serve.md
  packages/ui/src/components/Menu/__stories__/WithModal.stories.tsx
  packages/ui/src/components/Modal/Dialog.tsx
  packages/ui/src/components/Modal/Disclosure.tsx
  packages/ui/src/components/Modal/Modal.tsx
  packages/ui/src/components/Modal/__stories__/Animated.stories.tsx
  packages/ui/src/components/Modal/__stories__/CustomStyle.stories.tsx
  packages/ui/src/components/Modal/__stories__/FunctionChildren.stories.tsx
  packages/ui/src/components/Modal/__stories__/Height.stories.tsx
  packages/ui/src/components/Modal/__stories__/IsClosable.stories.tsx
  packages/ui/src/components/Modal/__stories__/ModalProp.stories.tsx
  packages/ui/src/components/Modal/__stories__/NotBordered.stories.tsx
  packages/ui/src/components/Modal/__stories__/Placement.stories.tsx
  packages/ui/src/components/Modal/__stories__/PreventBodyScroll.stories.tsx
  packages/ui/src/components/Modal/__stories__/Size.stories.tsx
  packages/ui/src/components/Modal/__stories__/WithDisclosureFunction.stories.tsx
  packages/ui/src/components/Modal/__stories__/WithLotsOfContent.stories.tsx
  packages/ui/src/components/Modal/__stories__/WithTooltip.stories.tsx
  packages/ui/src/components/Modal/__stories__/index.stories.tsx
  packages/ui/src/components/Modal/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Modal/__tests__/index.test.tsx
  packages/ui/src/components/Modal/constants.ts
  packages/ui/src/components/Modal/index.tsx
  packages/ui/src/components/Modal/types.ts
Labels: enhancement

#2855 ci: add github action to auto assign when pull request is created
  .github/auto_assign.yml
  .github/workflows/action.yml
Labels: ci

#2857 docs: fix show code on some stories and remove button migration doc
  packages/ui/src/__stories__/ButtonMigration/Sizes.tsx
  packages/ui/src/__stories__/ButtonMigration/Variants.tsx
  packages/ui/src/__stories__/ButtonMigration/index.stories.mdx
  packages/ui/src/components/Banner/__stories__/Directions.stories.tsx
  packages/ui/src/components/Banner/__stories__/Sizes.stories.tsx
  packages/ui/src/components/Banner/__stories__/Variants.stories.tsx
  packages/ui/src/components/Button/__stories__/AsLink.stories.tsx
  packages/ui/src/components/Button/__stories__/IconPosition.stories.tsx
  packages/ui/src/components/Button/__stories__/Showcase.stories.tsx
  packages/ui/src/components/Button/__stories__/Size.stories.tsx
  packages/ui/src/components/Card/__stories__/AdvancedHeader.stories.tsx
  packages/ui/src/components/Card/__stories__/Disabled.stories.tsx
  packages/ui/src/components/Card/__stories__/IsActive.stories.tsx
  packages/ui/src/components/Checkbox/__stories__/Checked.stories.tsx
  packages/ui/src/components/Checkbox/__stories__/Disabled.stories.tsx
  packages/ui/src/components/Checkbox/__stories__/Value.stories.tsx
  packages/ui/src/components/DateInput/__stories__/Controlled.stories.tsx
  packages/ui/src/components/DateInput/__stories__/I18n.stories.tsx
  packages/ui/src/components/Expandable/__stories__/Controlled.stories.tsx
  packages/ui/src/components/Expandable/__stories__/MinHeight.stories.tsx
  packages/ui/src/components/Expandable/__stories__/NestedExpandable.stories.tsx
  packages/ui/src/components/Link/__stories__/OneLine.stories.tsx
  packages/ui/src/components/List/__stories__/ColumnInfo.stories.tsx
  packages/ui/src/components/List/__stories__/Context.stories.tsx
  packages/ui/src/components/List/__stories__/Example.stories.tsx
  packages/ui/src/components/List/__stories__/Ordering.stories.tsx
  packages/ui/src/components/Loader/__stories__/Active.stories.tsx
  packages/ui/src/components/Meter/__stories__/Playground.stories.tsx
  packages/ui/src/components/NumberInput/__stories__/Controlled.stories.tsx
  packages/ui/src/components/ProgressBar/__stories__/Progress.stories.tsx
  packages/ui/src/components/Radio/__stories__/Controlled.stories.tsx
  packages/ui/src/components/Radio/__stories__/Disabled.stories.tsx
  packages/ui/src/components/Radio/__stories__/Error.stories.tsx
  packages/ui/src/components/Radio/__stories__/Helper.stories.tsx
  packages/ui/src/components/RadioGroup/__stories__/Controlled.stories.tsx
  packages/ui/src/components/RadioGroup/__stories__/Direction.stories.tsx
  packages/ui/src/components/Row/__stories__/AlignItems.stories.tsx
  packages/ui/src/components/Row/__stories__/Example.stories.tsx
  packages/ui/src/components/SelectableCard/__stories__/Children.stories.tsx
  packages/ui/src/components/SelectableCard/__stories__/Controlled.stories.tsx
  packages/ui/src/components/SelectableCard/__stories__/Disabled.stories.tsx
  packages/ui/src/components/SelectableCard/__stories__/Error.stories.tsx
  packages/ui/src/components/SelectableCard/__stories__/ShowTick.stories.tsx
  packages/ui/src/components/SelectableCard/__stories__/Tooltip.stories.tsx
  packages/ui/src/components/SelectableCard/__stories__/Type.stories.tsx
  packages/ui/src/components/Table/__stories__/Context.stories.tsx
  packages/ui/src/components/Table/__stories__/Ordering.stories.tsx
  packages/ui/src/components/Table/__stories__/Spanning.stories.tsx
  packages/ui/src/components/Table/__stories__/Style.stories.tsx
  packages/ui/src/components/Text/__stories__/Dir.stories.tsx
  packages/ui/src/components/Text/__stories__/OneLine.stories.tsx
  packages/ui/src/components/Text/__stories__/Placement.stories.tsx
  packages/ui/src/components/Text/__stories__/Sentiments.stories.tsx
  packages/ui/src/components/Toaster/__stories__/Variants.stories.tsx
  packages/ui/src/components/Toggle/__stories__/Helper.stories.tsx
  packages/ui/src/components/VerificationCode/__stories__/OnComplete.stories.tsx
Labels: documentation

#2852 fix(Tooltip): fixed tooltip too long with long words and button with full width
  .changeset/yellow-eggs-learn.md
  packages/ui/src/components/Button/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Button/index.tsx
  packages/ui/src/components/CopyButton/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/PieChart/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Popover/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectableCard/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Snippet/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SwitchButton/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Table/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Tag/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TagList/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Tooltip/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Tooltip/index.tsx
  packages/ui/src/internalComponents/Popup/__tests__/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/internalComponents/Popup/index.tsx
Labels: bug

#2850 feat(ToggleGroup): add new component toggle group and field
  .changeset/eight-guests-judge.md
  .changeset/warm-toes-perform.md
  packages/form/src/components/ToggleField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/ToggleGroupField/__stories__/Direction.stories.tsx
  packages/form/src/components/ToggleGroupField/__stories__/Error.stories.tsx
  packages/form/src/components/ToggleGroupField/__stories__/Helper.stories.tsx
  packages/form/src/components/ToggleGroupField/__stories__/Playground.stories.tsx
  packages/form/src/components/ToggleGroupField/__stories__/Required.stories.tsx
  packages/form/src/components/ToggleGroupField/__stories__/Template.stories.tsx
  packages/form/src/components/ToggleGroupField/__stories__/index.stories.tsx
  packages/form/src/components/ToggleGroupField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/ToggleGroupField/__tests__/index.spec.tsx
  packages/form/src/components/ToggleGroupField/index.tsx
  packages/ui/src/components/SelectableCard/__stories__/Template.stories.tsx
  packages/ui/src/components/Toggle/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Toggle/index.tsx
  packages/ui/src/components/ToggleGroup/__stories__/Controlled.stories.tsx
  packages/ui/src/components/ToggleGroup/__stories__/Direction.stories.tsx
  packages/ui/src/components/ToggleGroup/__stories__/Errors.stories.tsx
  packages/ui/src/components/ToggleGroup/__stories__/Helper.stories.tsx
  packages/ui/src/components/ToggleGroup/__stories__/Playground.stories.tsx
  packages/ui/src/components/ToggleGroup/__stories__/Required.stories.tsx
  packages/ui/src/components/ToggleGroup/__stories__/Template.stories.tsx
  packages/ui/src/components/ToggleGroup/__stories__/index.stories.tsx
  packages/ui/src/components/ToggleGroup/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/ToggleGroup/__tests__/index.test.tsx
  packages/ui/src/components/ToggleGroup/index.tsx
  packages/ui/src/components/index.ts
Labels: enhancement

#2873 fix: make modal controllable again
  .changeset/slow-baboons-listen.md
  packages/ui/src/components/Modal/Modal.tsx
Labels: bug

#2885 fix: dialog add attributes
  .changeset/loud-moose-remember.md
  packages/ui/src/components/ActionBar/index.tsx
  packages/ui/src/components/Modal/Dialog.tsx
  packages/ui/src/components/Modal/Disclosure.tsx
  packages/ui/src/components/Modal/__tests__/__snapshots__/index.test.tsx.snap
Labels: enhancement

#2884 refactor(ProductIcon): rename some product icons and added a new one
  .changeset/hip-sloths-jog.md
  packages/icons/src/components/ProductIcon/Icons.tsx
  packages/icons/src/components/ProductIcon/__tests__/__snapshots__/index.tsx.snap
  packages/icons/src/components/ProductIcon/index.tsx
Labels: refactor, breaking changes

#2888 ci: fix renovate to check examples folder
  .github/renovate.json
Labels: bug, ci

#2894 fix: modal restore focus
  .changeset/seven-kings-serve.md
  packages/ui/src/components/Modal/Dialog.tsx
  packages/ui/src/components/Modal/Disclosure.tsx
  packages/ui/src/components/Modal/__tests__/__snapshots__/index.test.tsx.snap
Labels: bug

#2887 fix(Checkbox): wrong tokens usages
  .changeset/shaggy-chairs-dress.md
  packages/form/src/components/CheckboxField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/CheckboxGroupField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/ui/src/components/Checkbox/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Checkbox/index.tsx
  packages/ui/src/components/CheckboxGroup/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/LineChart/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectableCard/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Table/__tests__/__snapshots__/index.test.tsx.snap
Labels: bug

#2905 ci(changeset): add examples project into ignore
  .changeset/config.json
Labels: ci

#2910 fix(modal): dialog should use overflow y
  .changeset/happy-squids-design.md
  packages/ui/src/components/Modal/Dialog.tsx
Labels: bug

#2913 docs(Icons): add documentation about product category and icons
  packages/icons/src/components/CategoryIcon/__stories__/Documentation.md
  packages/icons/src/components/CategoryIcon/__stories__/index.stories.tsx
  packages/icons/src/components/Icon/__stories__/Documentation.md
  packages/icons/src/components/Icon/__stories__/index.stories.tsx
  packages/icons/src/components/ProductIcon/__stories__/Documentation.md
  packages/icons/src/components/ProductIcon/__stories__/index.stories.tsx
  packages/ui/src/__stories__/Changelog/Changelog.stories.tsx
Labels: documentation

#2906 feat(Stack): add new parameters width and flex
  .changeset/spotty-cups-appear.md
  packages/form/src/components/CheckboxField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/CheckboxGroupField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/NumberInputField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/RadioField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/RadioGroupField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/SelectInputField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/SelectableCardField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/SubmitErrorAlert/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/TextInputField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/TimeField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/ToggleField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/ToggleGroupField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/ui/src/components/Alert/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Banner/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Card/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Checkbox/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/CheckboxGroup/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/EmptyState/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/LineChart/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Notice/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/NumberInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/PasswordCheck/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Radio/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/RadioGroup/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectInput/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/SelectableCard/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Snippet/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Stack/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Stack/__tests__/index.test.tsx
  packages/ui/src/components/Stack/index.tsx
  packages/ui/src/components/SwitchButton/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Table/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TextInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TimeInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Toaster/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Toggle/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/ToggleGroup/__tests__/__snapshots__/index.test.tsx.snap
Labels: enhancement

#2920 fix(Tooltip): implement esc key without focus
  .changeset/spotty-islands-unite.md
  packages/ui/src/components/Button/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Button/index.tsx
  packages/ui/src/components/Checkbox/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/CopyButton/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/PieChart/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Popover/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Radio/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectableCard/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Snippet/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SwitchButton/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Table/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Tag/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TagList/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Toggle/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Tooltip/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Tooltip/__tests__/index.test.tsx
  packages/ui/src/internalComponents/Popup/__tests__/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/internalComponents/Popup/__tests__/__tests__/index.test.tsx
  packages/ui/src/internalComponents/Popup/index.tsx
Labels: enhancement

#2915 fix(Tooltip): avoid breaking all words and break only when necessary
  .changeset/cool-buttons-pump.md
  packages/ui/src/internalComponents/Popup/index.tsx
Labels: bug

#2930 fix(Popover): improve accessibility of the component
  .changeset/green-sheep-grin.md
  packages/ui/src/components/Popover/__tests__/index.test.tsx
  packages/ui/src/components/Popover/index.tsx
  packages/ui/src/internalComponents/Popup/index.tsx
Labels: enhancement

#2936 fix(Modal): disclosure function
  .changeset/wicked-falcons-lick.md
  packages/ui/src/components/Modal/Disclosure.tsx
  packages/ui/src/components/Modal/__stories__/WithDisclosureFunction.stories.tsx
  packages/ui/src/components/Modal/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Modal/index.tsx
  packages/ui/src/components/Modal/types.ts
Labels: bug

#2935 fix(Badge): simplify and correct badge tags in the dom
  .changeset/sharp-rockets-search.md
  packages/ui/src/components/Badge/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Badge/index.tsx
  packages/ui/src/components/Tabs/__tests__/__snapshots__/index.test.tsx.snap
Labels: enhancement

#2938 refactor(Notice): changed to span and reduced icon size
  .changeset/pretty-cameras-push.md
  packages/form/src/components/TextInputField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/ui/src/components/Notice/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Notice/index.tsx
  packages/ui/src/components/TextInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TextInput/index.tsx
Labels: refactor

#2944 fix: changesets
  .changeset/renovate-7410c46.md
Labels: bug

#2918 feat(ui): add MenuV2
  .changeset/fuzzy-bees-shake.md
  packages/ui/src/__stories__/HowToMakeBreakingChanges.stories.mdx
  packages/ui/src/__stories__/MigrationMenuV2.stories.mdx
  packages/ui/src/components/Menu/__stories__/Sentiments.stories.tsx
  packages/ui/src/components/Menu/__stories__/index.stories.tsx
  packages/ui/src/components/Menu/index.tsx
  packages/ui/src/components/MenuV2/Item.tsx
  packages/ui/src/components/MenuV2/__stories__/Borderless.stories.tsx
  packages/ui/src/components/MenuV2/__stories__/FunctionDisclosure.stories.tsx
  packages/ui/src/components/MenuV2/__stories__/Playground.stories.tsx
  packages/ui/src/components/MenuV2/__stories__/Sentiments.stories.tsx
  packages/ui/src/components/MenuV2/__stories__/Template.stories.tsx
  packages/ui/src/components/MenuV2/__stories__/WithModal.stories.tsx
  packages/ui/src/components/MenuV2/__stories__/index.stories.tsx
  packages/ui/src/components/MenuV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/MenuV2/__tests__/index.test.tsx
  packages/ui/src/components/MenuV2/index.tsx
  packages/ui/src/components/index.ts
  packages/ui/src/internalComponents/Popup/index.tsx
Labels: enhancement

#2947 feat: theme generator
  .changeset/tidy-mirrors-build.md
  .storybook/preview.tsx
  package.json
  packages/ui/README.md
  packages/ui/src/__stories__/Tools/ThemeGenerator/FormContent/index.tsx
  packages/ui/src/__stories__/Tools/ThemeGenerator/ThemeResult/CodeIntegration.tsx
  packages/ui/src/__stories__/Tools/ThemeGenerator/ThemeResult/Demo.tsx
  packages/ui/src/__stories__/Tools/ThemeGenerator/ThemeResult/index.tsx
  packages/ui/src/__stories__/Tools/ThemeGenerator/contants.ts
  packages/ui/src/__stories__/Tools/ThemeGenerator/helpers.ts
  packages/ui/src/__stories__/Tools/ThemeGenerator/index.tsx
  packages/ui/src/__stories__/Tools/index.stories.mdx
  packages/ui/src/components/Button/index.tsx
  scripts/figma-synchronise-tokens.mjs
Labels: enhancement
