Repository scaleway/ultraviolet, pull requests merged in 2023-07, with the labels that each got.

#2682 fix(Button): add more aria props for better compatibility
  .changeset/violet-weeks-appear.md
  packages/ui/src/components/Button/index.tsx
Labels: enhancement

#2671 feat(Meter): refactor password strength meter to meter
  .changeset/dirty-swans-press.md
  packages/ui/src/components/Meter/Meter.tsx
  packages/ui/src/components/Meter/__stories__/Playground.stories.tsx
  packages/ui/src/components/Meter/__stories__/index.stories.tsx
  packages/ui/src/components/Meter/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Meter/__tests__/index.test.tsx
  packages/ui/src/components/Meter/index.ts
  packages/ui/src/components/PasswordStrengthMeter/__stories__/index.stories.tsx
  packages/ui/src/components/PasswordStrengthMeter/index.tsx
  packages/ui/src/components/index.ts
Labels: enhancement, refactor

#2691 fix(themes): export all themes
  .changeset/hungry-meals-trade.md
  packages/themes/src/index.ts
Labels: bug

#2694 fix: tabs and carousel colors and updates data charts
  .changeset/olive-crabs-eat.md
  packages/themes/src/themes/console/dark.ts
  packages/themes/src/themes/console/darker.ts
  packages/ui/src/components/Carousel/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Carousel/index.tsx
  packages/ui/src/components/Tabs/Tab.tsx
  packages/ui/src/components/Tabs/__tests__/__snapshots__/index.test.tsx.snap
Labels: bug

#2696 fix(theme): colors fixes for all components
  .changeset/fifty-kids-type.md
  .changeset/honest-llamas-hear.md
  packages/form/src/components/DateField/__tests__/__snapshots__/index.tsx.snap
  packages/form/src/components/NumberInputField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/SelectInputField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/SelectableCardField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/Submit/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/TagInputField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/TextInputField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/TimeField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/ToggleField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/themes/src/themes/console/dark.ts
  packages/themes/src/themes/console/darker.ts
  packages/themes/src/themes/console/light.ts
  packages/ui/src/components/Alert/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Avatar/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Badge/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Banner/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/BarChart/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/BarStack/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Bullet/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Button/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/CopyButton/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/LineChart/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/List/HeaderCell.tsx
  packages/ui/src/components/List/Row.tsx
  packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Loader/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Modal/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/NumberInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/NumberInput/index.tsx
  packages/ui/src/components/Pagination/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/ProgressBar/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectInput/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/SelectInput/index.tsx
  packages/ui/src/components/SelectableCard/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectableCard/index.tsx
  packages/ui/src/components/Snippet/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/StepList/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Stepper/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SwitchButton/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Table/Header.tsx
  packages/ui/src/components/Table/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Tag/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TagInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TagInput/index.tsx
  packages/ui/src/components/TextInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TextInput/index.tsx
  packages/ui/src/components/TimeInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Toggle/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/VerificationCode/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/VerificationCode/index.tsx
Labels: enhancement

#2700 fix(theme): update tokens
  .changeset/tough-cobras-hunt.md
  packages/form/src/components/CheckboxField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/DateField/__tests__/__snapshots__/index.tsx.snap
  packages/form/src/components/RadioField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/SelectableCardField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/SubmitErrorAlert/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/TagInputField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/TextInputField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/themes/src/themes/console/dark.ts
  packages/themes/src/themes/console/darker.ts
  packages/themes/src/themes/console/light.ts
  packages/ui/src/components/Alert/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Badge/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Banner/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Bullet/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Button/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Checkbox/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/CopyButton/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/LineChart/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Modal/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Pagination/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Radio/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectInput/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/SelectableCard/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Snippet/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/StepList/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Stepper/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SwitchButton/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Table/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Tabs/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Tag/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TagInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TagList/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TextInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Toaster/__tests__/__snapshots__/index.test.tsx.snap
Labels: enhancement

#2715 docs: add font import explanation
  packages/ui/README.md
Labels: documentation

#2736 fix(icons): missing exports
  .changeset/eighty-eagles-exist.md
  packages/icons/src/components/index.ts
Labels: bug

#2739 fix(icons): change product icon name for serverless db
  .changeset/tough-windows-drive.md
  packages/icons/src/components/ProductIcon/Icons.tsx
  packages/icons/src/components/ProductIcon/__tests__/__snapshots__/index.tsx.snap
Labels: bug

#2741 feat(tokens): colors update
  .changeset/unlucky-badgers-argue.md
  packages/form/src/components/DateField/__tests__/__snapshots__/index.tsx.snap
  packages/form/src/components/NumberInputField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/SelectInputField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/SelectableCardField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/Submit/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/SubmitErrorAlert/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/TagInputField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/TextInputField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/TimeField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/icons/src/components/Icon/__tests__/__snapshots__/index.test.tsx.snap
  packages/icons/src/components/ProductIcon/__tests__/__snapshots__/index.tsx.snap
  packages/themes/src/themes/console/dark.ts
  packages/themes/src/themes/console/darker.ts
  packages/themes/src/themes/console/light.ts
  packages/ui/src/components/Alert/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Avatar/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Badge/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Banner/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/BarChart/__tests__/__snapshots__/Tooltip.tsx.snap
  packages/ui/src/components/BarChart/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Breadcrumbs/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Bullet/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Button/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Card/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/CopyButton/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/EmptyState/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Icon/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/LineChart/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Link/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Menu/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Meter/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Modal/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Notice/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/NumberInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Pagination/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/PasswordCheck/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/PasswordStrengthMeter/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/PieChart/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/ProgressBar/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectInput/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/SelectableCard/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Separator/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Snippet/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Status/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/StepList/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Stepper/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SwitchButton/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Table/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Tabs/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Tag/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TagInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TagList/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Text/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TextInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TimeInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Toaster/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/VerificationCode/__tests__/__snapshots__/index.tsx.snap
Labels: enhancement

#2743 fix(form): update submit sentiment to default instead of success
  .changeset/great-schools-bathe.md
  packages/form/src/components/Submit/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/Submit/index.tsx
  packages/form/src/components/SubmitErrorAlert/__tests__/__snapshots__/index.spec.tsx.snap
Labels: enhancement

#2745 fix(DateInput): fix component
  .changeset/fluffy-queens-punch.md
  packages/ui/src/components/DateInput/index.tsx
Labels: bug

#2752 fix(tokens): update tokens for product icon warning sentiment
  .changeset/wet-shoes-sneeze.md
  packages/icons/src/components/ProductIcon/__tests__/__snapshots__/index.tsx.snap
  packages/themes/src/themes/console/light.ts
Labels: enhancement

#2761 feat(Banner): new banner design
  .changeset/rich-hairs-nail.md
  packages/ui/src/components/Banner/__stories__/Directions.stories.tsx
  packages/ui/src/components/Banner/__stories__/Image.png
  packages/ui/src/components/Banner/__stories__/Playground.stories.tsx
  packages/ui/src/components/Banner/__stories__/Sizes.stories.tsx
  packages/ui/src/components/Banner/__stories__/Variants.stories.tsx
  packages/ui/src/components/Banner/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Banner/assets/default-image-small.svg
  packages/ui/src/components/Banner/assets/default-image.svg
  packages/ui/src/components/Banner/assets/intro-compact-left-pattern.svg
  packages/ui/src/components/Banner/assets/intro-compact-right-pattern.svg
  packages/ui/src/components/Banner/assets/intro-pattern.svg
  packages/ui/src/components/Banner/assets/promotion-compact-left-pattern.svg
  packages/ui/src/components/Banner/assets/promotion-compact-right-pattern.svg
  packages/ui/src/components/Banner/assets/promotion-pattern.svg
  packages/ui/src/components/Banner/index.tsx
Labels: enhancement
