Repository scaleway/ultraviolet, pull requests merged in 2023-11, with the labels that each got.

#3113 fix: jest ts node version
  package.json
  pnpm-lock.yaml
Labels: bug

#3116 ci: make build and tests needs typecheck and lint
  .github/workflows/ci.yml
Labels: ci

#3121 fix(ContentCard): to have title and subtitle vertically centered
  .changeset/sweet-bees-joke.md
  packages/plus/src/components/ContentCard/__tests__/__snapshots__/index.test.tsx.snap
  packages/plus/src/components/ContentCard/index.tsx
Labels: bug

#3132 fix(illustrations): fix bundle and story
  .changeset/long-mirrors-jam.md
  packages/illustrations/package.json
  packages/illustrations/rollup.config.mjs
  packages/illustrations/src/__stories__/List.tsx
Labels: bug

#3120 feat: rebranding with new gradients and banner update
  .changeset/good-elephants-poke.md
  .storybook/assets/fonts/space-grotesk/SpaceGrotesk-Medium.woff2
  .storybook/assets/fonts/space-grotesk/SpaceGrotesk-Regular.woff2
  .storybook/preview.tsx
  packages/themes/src/themes/console/dark.ts
  packages/themes/src/themes/console/darker.ts
  packages/themes/src/themes/console/deprecated/dark.ts
  packages/themes/src/themes/console/deprecated/darker.ts
  packages/themes/src/themes/console/deprecated/light.ts
  packages/themes/src/themes/console/light.ts
  packages/ui/src/components/Banner/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Banner/assets/intro-compact-left-pattern.svg
  packages/ui/src/components/Banner/assets/intro-compact-right-pattern.svg
  packages/ui/src/components/Banner/assets/intro-pattern.svg
  packages/ui/src/components/Banner/assets/promotion-compact-left-pattern.svg
  packages/ui/src/components/Banner/assets/promotion-compact-right-pattern.svg
  packages/ui/src/components/Banner/assets/promotion-pattern.svg
  packages/ui/src/components/Banner/index.tsx
  packages/ui/src/components/Card/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/EmptyState/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Text/__tests__/__snapshots__/index.test.tsx.snap
Labels: enhancement

#3131 refactor: remove jsx element when not needed and imported others from react
  .changeset/six-toys-hammer.md
  packages/form/src/components/CheckboxField/index.tsx
  packages/form/src/components/Form/index.tsx
  packages/form/src/components/RadioField/index.tsx
  packages/form/src/components/RadioGroupField/index.tsx
  packages/form/src/components/SelectableCardField/index.tsx
  packages/form/src/components/Submit/index.tsx
  packages/form/src/components/TagInputField/index.tsx
  packages/form/src/components/TextInputField/index.tsx
  packages/form/src/providers/ErrorContext/index.tsx
  packages/ui/src/components/BarStack/index.tsx
  packages/ui/src/components/Carousel/index.tsx
  packages/ui/src/components/Meter/index.tsx
  packages/ui/src/components/Pagination/index.tsx
  packages/ui/src/components/PasswordStrengthMeter/index.tsx
  packages/ui/src/components/Separator/index.tsx
  packages/ui/src/components/Status/index.tsx
  packages/ui/src/components/TagInput/index.tsx
  packages/ui/src/components/TagList/index.tsx
  packages/ui/src/components/TextInput/index.tsx
  packages/ui/src/components/VerificationCode/index.tsx
Labels: refactor

#3142 feat(Snippet): new prop initially expanded on component
  .changeset/dirty-wolves-wait.md
  packages/ui/src/components/Snippet/__stories__/LongMultilineExpanded.stories.tsx
  packages/ui/src/components/Snippet/__stories__/index.stories.tsx
  packages/ui/src/components/Snippet/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Snippet/__tests__/index.test.tsx
  packages/ui/src/components/Snippet/index.tsx
Labels: enhancement

#3143 feat(Tabs): add subtitle props
  .changeset/rich-radios-call.md
  packages/ui/src/components/Tabs/Tab.tsx
  packages/ui/src/components/Tabs/TabMenu.tsx
  packages/ui/src/components/Tabs/__stories__/WithSubtitle.stories.tsx
  packages/ui/src/components/Tabs/__stories__/index.stories.tsx
  packages/ui/src/components/Tabs/__tests__/Tab.test.tsx
  packages/ui/src/components/Tabs/__tests__/__snapshots__/Tab.test.tsx.snap
  packages/ui/src/components/Tabs/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Tabs/__tests__/index.test.tsx
  packages/ui/src/components/Tabs/index.tsx
Labels: enhancement

#3141 fix(Popup): attach to children and new prop portal target
  .changeset/shaggy-waves-grab.md
  packages/ui/src/components/MenuV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/MenuV2/index.tsx
  packages/ui/src/components/Modal/Dialog.tsx
  packages/ui/src/components/Modal/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Popover/__stories__/AdvancedUsage.stories.tsx
  packages/ui/src/components/Popover/__stories__/Controlled.stories.tsx
  packages/ui/src/components/Popover/__stories__/Playground.stories.tsx
  packages/ui/src/components/Popover/__stories__/Sentiments.stories.tsx
  packages/ui/src/components/Popover/__stories__/Sizes.stories.tsx
  packages/ui/src/components/Popover/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Popover/__tests__/index.test.tsx
  packages/ui/src/components/Popover/index.tsx
  packages/ui/src/components/Popup/__tests__/__tests__/index.test.tsx
  packages/ui/src/components/Popup/animations.ts
  packages/ui/src/components/Popup/helpers.ts
  packages/ui/src/components/Popup/index.tsx
  packages/ui/src/components/TagList/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Tooltip/__stories__/Playground.stories.tsx
  packages/ui/src/components/Tooltip/index.tsx
Labels: enhancement

#3155 fix(illustrations): fix orientation of scaleway logo
  .changeset/many-mails-fail.md
  packages/illustrations/src/various/onboarding/scaleway.webp
Labels: enhancement

#3172 fix(popup): to handle table and sub table elements when choosing parent
  .changeset/eleven-paws-provide.md
  packages/ui/src/components/Popup/helpers.ts
  packages/ui/src/components/Table/__stories__/WithMenu.stories.tsx
  packages/ui/src/components/Table/__stories__/index.stories.tsx
Labels: bug

#3173 fix(ContentCardGroup): to fit inside a row
  .changeset/late-pens-visit.md
  packages/plus/src/components/ContentCardGroup/Card.tsx
  packages/plus/src/components/ContentCardGroup/__stories__/WithRow.stories.tsx
  packages/plus/src/components/ContentCardGroup/__stories__/index.stories.tsx
  packages/plus/src/components/ContentCardGroup/__tests__/__snapshots__/index.test.tsx.snap
  packages/plus/src/components/ContentCardGroup/index.tsx
Labels: bug

#3177 fix(DateInput): types broken
  packages/ui/src/components/DateInput/index.tsx
Labels: bug

#3182 docs(storybook): add more clarity into storybook about sub components
  packages/plus/src/components/ContentCardGroup/__stories__/index.stories.tsx
  packages/ui/src/components/Breadcrumbs/__stories__/index.stories.tsx
  packages/ui/src/components/Carousel/__stories__/index.stories.tsx
  packages/ui/src/components/Table/__stories__/index.stories.tsx
  packages/ui/src/components/Tabs/__stories__/index.stories.tsx
Labels: documentation

#3185 fix(Popup): to add parent scroll on popup positioning
  .changeset/late-crabs-exist.md
  packages/ui/src/components/Popup/helpers.ts
Labels: bug

#3183 fix(Tag): to display tooltip when tag content is too long
  .changeset/pink-dolphins-approve.md
  packages/form/src/components/TagInputField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/ui/src/components/Tag/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Tag/index.tsx
  packages/ui/src/components/TagInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TagList/__tests__/__snapshots__/index.test.tsx.snap
Labels: enhancement

#3187 fix(DateInput): to use tokens from theme for font
  .changeset/rotten-wolves-compete.md
  packages/form/src/components/DateField/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/DateInput/index.tsx
Labels: bug

#3189 feat(verificationcode): add size prop and fix disabled
  .changeset/spicy-windows-sin.md
  packages/ui/src/components/VerificationCode/__stories__/Disabled.stories.tsx
  packages/ui/src/components/VerificationCode/__stories__/Size.stories.tsx
  packages/ui/src/components/VerificationCode/__stories__/index.stories.tsx
  packages/ui/src/components/VerificationCode/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/VerificationCode/__tests__/index.tsx
  packages/ui/src/components/VerificationCode/index.tsx
Labels: enhancement
