Repository scaleway/ultraviolet, pull requests merged in 2023-01, with the labels that each got.

#2160 fix(List): fix sort type to allow numbers
  packages/ui/src/components/List/index.tsx
  packages/ui/src/components/List/types.ts
  packages/ui/src/components/List/variants/variantExplorer.tsx
  packages/ui/src/components/List/variants/variantProduct.tsx
  packages/ui/src/components/List/variants/variantTable.tsx
  packages/ui/src/utils/index.ts
  packages/ui/src/utils/orderBy.ts
Labels: bug

#2138 refactor: remove ErrorTransition and ControlValue from stories
  packages/ui/src/__stories__/components/ControlValue.ts
  packages/ui/src/__stories__/components/ErrorTransition.tsx
  packages/ui/src/components/ListV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/ListV2/__tests__/index.test.tsx
  packages/ui/src/components/NavigationStepper/__stories__/Condensed.stories.tsx
  packages/ui/src/components/NavigationStepper/__stories__/Controlled.stories.tsx
Labels: enhancement

#2155 fix(Button): manage flex display on tooltip
  packages/ui/src/components/Button/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/CopyButton/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/PieChart/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/SelectableCard/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Snippet/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/SwitchButton/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/TagsPoplist/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Tooltip/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Tooltip/index.tsx
  packages/ui/src/components/TooltipIcon/__tests__/__snapshots__/index.tsx.snap
Labels: bug

#2168 fix: add emoji in changelog
  lerna.json
Labels: enhancement

#2169 docs: add main README and updated documentation usages
  .storybook/preview.tsx
  README.md
  packages/form/README.md
  packages/form/src/__stories__/Introduction.stories.mdx
  packages/ui/README.md
  packages/ui/src/__stories__/GetStarted.stories.mdx
Labels: documentation

#2166 fix(TextBox): show required icon with right components
  packages/form/src/components/DateField/__tests__/__snapshots__/index.tsx.snap
  packages/form/src/components/Submit/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/TextBoxField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/TextBoxField/index.tsx
  packages/ui/src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TextBox/__stories__/MultipleRightComponents.stories.tsx
  packages/ui/src/components/TextBox/__stories__/RandomizeRequired.stories.tsx
  packages/ui/src/components/TextBox/__stories__/ToggleableRequired.stories.tsx
  packages/ui/src/components/TextBox/__stories__/UnitRequired.stories.tsx
  packages/ui/src/components/TextBox/__stories__/Valid.stories.tsx
  packages/ui/src/components/TextBox/__stories__/ValidRequired.stories.tsx
  packages/ui/src/components/TextBox/__stories__/index.stories.tsx
  packages/ui/src/components/TextBox/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TextBox/__tests__/index.test.tsx
  packages/ui/src/components/TextBox/index.tsx
  packages/ui/src/components/UnitInput/__tests__/__snapshots__/index.tsx.snap
Labels: bug

#2165 fix(actionBar): remove padding and center content from list action bar
  packages/ui/src/components/ActionBar/__stories__/Ranks.stories.tsx
  packages/ui/src/components/ActionBar/__stories__/Template.stories.tsx
  packages/ui/src/components/ActionBar/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/ActionBar/index.tsx
  packages/ui/src/components/List/SelectBar.tsx
  packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap
Labels: bug

#2174 fix(TimeInput): required icon correct position
  packages/form/src/components/RichSelectField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/TimeField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/ui/src/components/RichSelect/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/RichSelect/index.tsx
  packages/ui/src/components/TimeInput/__stories__/index.stories.tsx
  packages/ui/src/components/TimeInput/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/TimeInput/index.tsx
  packages/ui/src/components/UnitInput/__tests__/__snapshots__/index.tsx.snap
Labels: bug

#2167 docs: update toaster doc and add all component into categories
  packages/ui/src/__stories__/HowToMakeBreakingChanges.stories.mdx
  packages/ui/src/components/ActionBar/__stories__/index.stories.tsx
  packages/ui/src/components/Avatar/__stories__/index.stories.tsx
  packages/ui/src/components/Badge/__stories__/index.stories.tsx
  packages/ui/src/components/BorderedBox/__stories__/index.stories.tsx
  packages/ui/src/components/Bullet/__stories__/index.stories.tsx
  packages/ui/src/components/Button/__stories__/index.stories.tsx
  packages/ui/src/components/Container/__stories__/index.stories.tsx
  packages/ui/src/components/CopyButton/__stories__/index.stories.tsx
  packages/ui/src/components/Expandable/__stories__/index.stories.tsx
  packages/ui/src/components/Grid/__stories__/index.stories.tsx
  packages/ui/src/components/Icon/__stories__/index.stories.tsx
  packages/ui/src/components/Image/__stories__/index.stories.tsx
  packages/ui/src/components/Label/__stories__/index.stories.tsx
  packages/ui/src/components/Link/__stories__/index.stories.tsx
  packages/ui/src/components/List/__stories__/index.stories.tsx
  packages/ui/src/components/ListV2/__stories__/index.stories.tsx
  packages/ui/src/components/Markdown/__stories__/index.stories.tsx
  packages/ui/src/components/Menu/__stories__/index.stories.tsx
  packages/ui/src/components/Modal/__stories__/index.stories.tsx
  packages/ui/src/components/Notice/__stories__/index.stories.tsx
  packages/ui/src/components/Pagination/__stories__/index.stories.tsx
  packages/ui/src/components/PasswordCheck/__stories__/index.stories.tsx
  packages/ui/src/components/PasswordStrengthMeter/__stories__/index.stories.tsx
  packages/ui/src/components/Placeholder/__stories__/index.stories.tsx
  packages/ui/src/components/ProgressBar/__stories__/index.stories.tsx
  packages/ui/src/components/ProgressionButton/__stories__/index.stories.tsx
  packages/ui/src/components/ScrollView/__stories__/index.stories.tsx
  packages/ui/src/components/SelectNumber/__stories__/index.stories.tsx
  packages/ui/src/components/Separator/__stories__/index.stories.tsx
  packages/ui/src/components/Sphere/__stories__/index.stories.tsx
  packages/ui/src/components/Stack/__stories__/index.stories.tsx
  packages/ui/src/components/StateBar/__stories__/index.stories.tsx
  packages/ui/src/components/Status/__stories__/index.stories.tsx
  packages/ui/src/components/SwitchButton/__stories__/index.stories.tsx
  packages/ui/src/components/Tag/__stories__/index.stories.tsx
  packages/ui/src/components/Tags/__stories__/index.stories.tsx
  packages/ui/src/components/Text/__stories__/index.stories.tsx
  packages/ui/src/components/Toaster/__stories__/index.stories.tsx
  packages/ui/src/components/Tooltip/__stories__/index.stories.tsx
Labels: documentation

#2188 fix(TextBox): required icon wrongly positioned
  packages/form/src/components/TextBoxField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/ui/src/components/TextBox/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TextBox/index.tsx
Labels: bug

#2191 fix(Button): wrong overflow on extend
  packages/ui/src/components/Button/__stories__/Extend.stories.tsx
  packages/ui/src/components/Button/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Button/index.tsx
Labels: bug

#2179 refactor(ActionBar): remove z-index by using portal and add animation on display
  packages/ui/src/components/ActionBar/__stories__/Ranks.stories.tsx
  packages/ui/src/components/ActionBar/__stories__/Template.stories.tsx
  packages/ui/src/components/ActionBar/__stories__/index.stories.tsx
  packages/ui/src/components/ActionBar/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/ActionBar/index.tsx
  packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap
Labels: enhancement

#2187 docs(form): update git repository
  packages/form/package.json
  packages/ui/package.json
  website/package.json
Labels: documentation

#2193 docs: improve dark theme documentation
  packages/ui/src/__stories__/theme/darkMode.stories.mdx
Labels: documentation

#2196 test: improve code coverage on verification code and slider
  packages/ui/src/components/Slider/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Slider/__tests__/index.tsx
  packages/ui/src/components/Slider/index.tsx
  packages/ui/src/components/VerificationCode/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/VerificationCode/__tests__/index.tsx
Labels: enhancement

#2199 fix(Toggle): use gap instead of margin for `label` content
  packages/form/src/components/ToggleField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/ui/src/components/Toggle/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Toggle/index.tsx
Labels: bug

#2207 refactor(components): rename TextBox and TextBoxField to TextInput an…
  packages/form/README.md
  packages/form/src/components/DateField/__tests__/__snapshots__/index.tsx.snap
  packages/form/src/components/Form/__stories__/Playground.stories.tsx
  packages/form/src/components/Submit/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/Submit/__tests__/index.spec.tsx
  packages/form/src/components/TextBoxField/__stories__/Template.stories.tsx
  packages/form/src/components/TextInputField/__stories__/Disabled.stories.tsx
  packages/form/src/components/TextInputField/__stories__/DynamicRequired.stories.tsx
  packages/form/src/components/TextInputField/__stories__/MinMaxLength.stories.tsx
  packages/form/src/components/TextInputField/__stories__/Playground.stories.tsx
  packages/form/src/components/TextInputField/__stories__/Regex.stories.tsx
  packages/form/src/components/TextInputField/__stories__/Required.stories.tsx
  packages/form/src/components/TextInputField/__stories__/Template.stories.tsx
  packages/form/src/components/TextInputField/__stories__/index.stories.tsx
  packages/form/src/components/TextInputField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/TextInputField/__tests__/index.spec.tsx
  packages/form/src/components/TextInputField/index.tsx
  packages/form/src/components/index.ts
  packages/form/src/hooks/__stories__/useOnFieldChange.stories.tsx
  packages/form/src/hooks/__tests__/useOnFieldChange.spec.tsx
  packages/form/src/index.ts
  packages/ui/src/__tests__/a11y.test.tsx
  packages/ui/src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/DateInput/index.tsx
  packages/ui/src/components/PasswordStrengthMeter/__stories__/UncontrolledPasswordStrengthMeter.tsx
  packages/ui/src/components/TextInput/__stories__/DisableResize.stories.tsx
  packages/ui/src/components/TextInput/__stories__/Disabled.stories.tsx
  packages/ui/src/components/TextInput/__stories__/Error.stories.tsx
  packages/ui/src/components/TextInput/__stories__/ForceEdit.stories.tsx
  packages/ui/src/components/TextInput/__stories__/Multiline.stories.tsx
  packages/ui/src/components/TextInput/__stories__/MultipleRightComponents.stories.tsx
  packages/ui/src/components/TextInput/__stories__/NoLabel.stories.tsx
  packages/ui/src/components/TextInput/__stories__/Notice.stories.tsx
  packages/ui/src/components/TextInput/__stories__/Placeholder.stories.tsx
  packages/ui/src/components/TextInput/__stories__/Playground.stories.tsx
  packages/ui/src/components/TextInput/__stories__/Randomize.stories.tsx
  packages/ui/src/components/TextInput/__stories__/RandomizeRequired.stories.tsx
  packages/ui/src/components/TextInput/__stories__/ReadOnly.stories.tsx
  packages/ui/src/components/TextInput/__stories__/Required.stories.tsx
  packages/ui/src/components/TextInput/__stories__/Sizes.stories.tsx
  packages/ui/src/components/TextInput/__stories__/TabIndex.stories.tsx
  packages/ui/src/components/TextInput/__stories__/Template.stories.tsx
  packages/ui/src/components/TextInput/__stories__/ToggleablePassword.stories.tsx
  packages/ui/src/components/TextInput/__stories__/ToggleableRequired.stories.tsx
  packages/ui/src/components/TextInput/__stories__/Unit.stories.tsx
  packages/ui/src/components/TextInput/__stories__/UnitRequired.stories.tsx
  packages/ui/src/components/TextInput/__stories__/Valid.stories.tsx
  packages/ui/src/components/TextInput/__stories__/ValidRequired.stories.tsx
  packages/ui/src/components/TextInput/__stories__/index.stories.tsx
  packages/ui/src/components/TextInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TextInput/__tests__/index.test.tsx
  packages/ui/src/components/TextInput/index.tsx
  packages/ui/src/components/UnitInput/__stories__/index.stories.tsx
  packages/ui/src/components/UnitInput/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/UnitInput/__tests__/index.tsx
  packages/ui/src/components/UnitInput/index.tsx
  packages/ui/src/components/index.ts
  packages/ui/src/index.ts
Labels: design system

#2192 fix(Text): show tooltip on ellipsis only when needed
  packages/ui/src/components/Text/index.tsx
Labels: bug

#2206 fix(TextBoxField): forward `size` prop to TextBox
  packages/form/src/components/TextInputField/index.tsx
  packages/ui/src/components/TextInput/index.tsx
Labels: bug

#2213 fix(Slider): rename Slider component to Carousel
  packages/ui/src/__tests__/a11y.test.tsx
  packages/ui/src/components/Carousel/__stories__/Playground.stories.tsx
  packages/ui/src/components/Carousel/__stories__/Template.stories.tsx
  packages/ui/src/components/Carousel/__stories__/index.stories.tsx
  packages/ui/src/components/Carousel/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Carousel/__tests__/index.tsx
  packages/ui/src/components/Carousel/index.tsx
  packages/ui/src/components/Slider/__stories__/Template.stories.tsx
  packages/ui/src/components/index.ts
  packages/ui/src/index.ts
Labels: design system

#2214 fix(Separator): background color in dark theme
  packages/ui/src/components/Separator/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Separator/index.tsx
Labels: bug

#2215 fix(TooltipIcon): remove component
  packages/ui/src/__tests__/a11y.test.tsx
  packages/ui/src/components/TooltipIcon/__stories__/Colors.stories.tsx
  packages/ui/src/components/TooltipIcon/__stories__/Playground.stories.tsx
  packages/ui/src/components/TooltipIcon/__stories__/Sizes.stories.tsx
  packages/ui/src/components/TooltipIcon/__stories__/Template.stories.tsx
  packages/ui/src/components/TooltipIcon/__stories__/index.stories.tsx
  packages/ui/src/components/TooltipIcon/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/TooltipIcon/__tests__/index.tsx
  packages/ui/src/components/TooltipIcon/index.tsx
  packages/ui/src/components/index.ts
  packages/ui/src/index.ts
Labels: refactor

#2218 refactor(Tags+TagsField): rename Tags and TagsField to TagInput and TagInputField
  packages/form/src/components/Form/__stories__/Playground.stories.tsx
  packages/form/src/components/TagInputField/__stories__/DefaultTagInput.stories.tsx
  packages/form/src/components/TagInputField/__stories__/Disabled.stories.tsx
  packages/form/src/components/TagInputField/__stories__/Placeholder.stories.tsx
  packages/form/src/components/TagInputField/__stories__/Playground.stories.tsx
  packages/form/src/components/TagInputField/__stories__/Required.stories.tsx
  packages/form/src/components/TagInputField/__stories__/Template.stories.tsx
  packages/form/src/components/TagInputField/__stories__/index.stories.tsx
  packages/form/src/components/TagInputField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/TagInputField/__tests__/index.spec.tsx
  packages/form/src/components/TagInputField/index.tsx
  packages/form/src/components/TagsField/__stories__/DefaultTags.stories.tsx
  packages/form/src/components/TagsField/__stories__/Template.stories.tsx
  packages/form/src/components/index.ts
  packages/form/src/index.ts
  packages/ui/src/__tests__/a11y.test.tsx
  packages/ui/src/components/TagInput/__stories__/Playground.stories.tsx
  packages/ui/src/components/TagInput/__stories__/Template.stories.tsx
  packages/ui/src/components/TagInput/__stories__/index.stories.tsx
  packages/ui/src/components/TagInput/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/TagInput/__tests__/index.tsx
  packages/ui/src/components/TagInput/index.tsx
  packages/ui/src/components/Tags/__stories__/Template.stories.tsx
  packages/ui/src/components/index.ts
  packages/ui/src/index.ts
Labels: design system

#2219 feat(Text): add `dir` prop
  packages/ui/src/components/Text/__stories__/Dir.stories.tsx
  packages/ui/src/components/Text/__stories__/index.stories.tsx
  packages/ui/src/components/Text/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Text/__tests__/index.test.tsx
  packages/ui/src/components/Text/index.tsx
Labels: enhancement

#2209 feat(tooltip): improve tooltip behavior and fix some issues
  packages/ui/src/components/Tooltip/index.tsx
Labels: bug, enhancement

#2225 fix(Button): stack has direction column by default
  packages/form/src/components/Submit/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/SubmitErrorAlert/__tests__/__snapshots__/index.spec.tsx.snap
  packages/ui/src/components/Button/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Button/index.tsx
  packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Menu/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Pagination/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/PaginationV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Tabs/__tests__/__snapshots__/index.test.tsx.snap
Labels: bug

#2224 refactor(components): rename TagsPoplist to TagList
  packages/ui/src/components/TagList/__stories__/Multiline.stories.tsx
  packages/ui/src/components/TagList/__stories__/Playground.stories.tsx
  packages/ui/src/components/TagList/__stories__/Template.stories.tsx
  packages/ui/src/components/TagList/__stories__/Threshold.stories.tsx
  packages/ui/src/components/TagList/__stories__/index.stories.tsx
  packages/ui/src/components/TagList/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/TagList/__tests__/index.tsx
  packages/ui/src/components/TagList/index.tsx
  packages/ui/src/components/TagsPoplist/__stories__/Template.stories.tsx
  packages/ui/src/components/index.ts
  packages/ui/src/index.ts
Labels: design system

#2222 feat(table): add `striped` property update loading state and remove hover style
  packages/ui/src/__stories__/ComponentState/ComponentState.tsx
  packages/ui/src/__stories__/Properties/Properties.tsx
  packages/ui/src/components/Table/__stories__/Striped.stories.tsx
  packages/ui/src/components/Table/__stories__/index.stories.tsx
  packages/ui/src/components/Table/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Table/__tests__/index.tsx
  packages/ui/src/components/Table/index.tsx
Labels: enhancement

#2227 docs(Markdown): fix deprecated parmeters in storybook
  packages/ui/src/components/Markdown/__stories__/index.stories.tsx
Labels: documentation
