Repository scaleway/ultraviolet, pull requests merged in 2023-05, with the labels that each got.

#2487 fix(Charts): update barchart and linechart to have new data colors
  .changeset/angry-crabs-relate.md
  packages/ui/src/components/BarChart/__stories__/PositiveNegative.stories.tsx
  packages/ui/src/components/BarChart/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/BarChart/index.tsx
  packages/ui/src/components/LineChart/CustomLegend.tsx
  packages/ui/src/components/LineChart/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/LineChart/index.tsx
  packages/ui/src/components/PieChart/index.tsx
  packages/ui/src/helpers/legend.ts
Labels: enhancement

#2496 fix: expandable row registering
  .changeset/weak-donuts-tickle.md
  packages/ui/src/components/ListV2/Row.tsx
Labels: bug

#2499 fix(Separator): icon color
  packages/ui/src/components/Separator/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Separator/__tests__/index.test.tsx
  packages/ui/src/components/Separator/index.tsx
Labels: bug

#2517 feat: remove ProgressionButton
  .changeset/angry-kings-add.md
  packages/ui/src/components/ProgressionButton/__stories__/Example.stories.tsx
  packages/ui/src/components/ProgressionButton/__stories__/Playground.stories.tsx
  packages/ui/src/components/ProgressionButton/__stories__/Template.stories.tsx
  packages/ui/src/components/ProgressionButton/__stories__/index.stories.tsx
  packages/ui/src/components/ProgressionButton/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/ProgressionButton/__tests__/index.test.tsx
  packages/ui/src/components/ProgressionButton/index.tsx
  packages/ui/src/components/index.ts
  packages/ui/src/index.ts
Labels: enhancement

#2485 fix: improve accessibility on components and enable more a11y testing
  .changeset/six-snails-hope.md
  packages/form/src/components/NumberInputField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/NumberInputField/__tests__/index.spec.tsx
  packages/form/src/components/ToggleField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/ui/src/__tests__/a11y.test.tsx
  packages/ui/src/components/CopyButton/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/CopyButton/index.tsx
  packages/ui/src/components/EmptyState/__stories__/index.stories.tsx
  packages/ui/src/components/NumberInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/NumberInput/__tests__/index.test.tsx
  packages/ui/src/components/NumberInput/index.tsx
  packages/ui/src/components/Snippet/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Snippet/index.tsx
  packages/ui/src/components/Toggle/__stories__/Template.stories.tsx
  packages/ui/src/components/Toggle/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Toggle/index.tsx
  packages/ui/src/components/VerificationCode/__stories__/Template.stories.tsx
  packages/ui/src/components/VerificationCode/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/VerificationCode/index.tsx
Labels: enhancement, accessibility

#2525 docs(Banner): move banner into other category in storybook
  packages/ui/src/components/Banner/__stories__/index.stories.tsx
Labels: documentation

#2536 refactor(NumberInput): new parameters and behavior
  .changeset/giant-planets-stare.md
  packages/form/src/components/NumberInputField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/ui/src/components/NumberInput/__stories__/Controlled.stories.tsx
  packages/ui/src/components/NumberInput/__stories__/Error.stories.tsx
  packages/ui/src/components/NumberInput/__stories__/Placeholder.stories.tsx
  packages/ui/src/components/NumberInput/__stories__/Text.stories.tsx
  packages/ui/src/components/NumberInput/__stories__/index.stories.tsx
  packages/ui/src/components/NumberInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/NumberInput/__tests__/index.test.tsx
  packages/ui/src/components/NumberInput/helpers.ts
  packages/ui/src/components/NumberInput/index.tsx
Labels: enhancement

#2554 feat(design): new space and radii from theme
  .changeset/grumpy-dots-notice.md
  packages/form/src/components/CheckboxField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/themes/src/themes/console/dark.ts
  packages/themes/src/themes/console/index.ts
  packages/themes/src/themes/console/light.ts
  packages/ui/src/components/Banner/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Banner/index.tsx
  packages/ui/src/components/BarChart/__tests__/__snapshots__/Tooltip.tsx.snap
  packages/ui/src/components/Checkbox/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/LineChart/__tests__/__snapshots__/Tooltip.test.tsx.snap
  packages/ui/src/components/LineChart/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/ListV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Row/index.tsx
  packages/ui/src/components/SelectableCard/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Stack/index.tsx
  packages/ui/src/components/TableV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/theme/index.ts
  scripts/figma-synchronise-tokens.sh
Labels: enhancement

#2566 feat(Tag,TagList): add copiable props
  .changeset/nice-worms-wonder.md
  packages/form/src/components/TagInputField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/ui/src/components/Tag/__stories__/Copiable.stories.tsx
  packages/ui/src/components/Tag/__stories__/index.stories.tsx
  packages/ui/src/components/Tag/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Tag/__tests__/index.test.tsx
  packages/ui/src/components/Tag/index.tsx
  packages/ui/src/components/TagInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TagList/__stories__/Copiable.stories.tsx
  packages/ui/src/components/TagList/__stories__/index.stories.tsx
  packages/ui/src/components/TagList/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TagList/__tests__/index.test.tsx
  packages/ui/src/components/TagList/index.tsx
Labels: enhancement

#2578 fix: verification code focus on paste
  .changeset/nice-singers-shout.md
  packages/ui/src/components/VerificationCode/index.tsx
Labels: bug

#2538 docs: update readme of scaleway ui for emotion type declaration
  packages/ui/README.md
Labels: documentation

#2581 docs: update text and link documentation
  packages/ui/src/components/Link/__stories__/OneLine.stories.tsx
  packages/ui/src/components/Link/__stories__/index.stories.tsx
  packages/ui/src/components/Text/__stories__/Dir.stories.tsx
  packages/ui/src/components/Text/__stories__/OneLine.stories.tsx
Labels: documentation
