Repository scaleway/ultraviolet, pull requests merged in 2023-10, with the labels that each got.

#2967 fix(theme): deprecated theme name and replaced by new one
  .changeset/violet-flowers-move.md
  examples/next-simple/emotion.d.ts
  packages/icons/src/emotion.d.ts
  packages/ui/README.md
  packages/ui/src/components/Row/index.tsx
  packages/ui/src/components/Stack/index.tsx
  packages/ui/src/emotion.d.ts
  packages/ui/src/index.ts
  packages/ui/src/theme/index.ts
Labels: enhancement

#2968 refactor: removed deprecated usages
  packages/ui/src/__stories__/theme/colors.stories.mdx
  packages/ui/src/components/Alert/index.tsx
  packages/ui/src/components/Banner/index.tsx
  packages/ui/src/components/BarChart/Tooltip.tsx
  packages/ui/src/components/Card/__stories__/IsActive.stories.tsx
  packages/ui/src/components/Checkbox/index.tsx
  packages/ui/src/components/LineChart/CustomLegend.tsx
  packages/ui/src/components/LineChart/Tooltip.tsx
  packages/ui/src/components/List/__stories__/Selectable.stories.tsx
  packages/ui/src/components/Modal/__stories__/HideOnClickOutside.stories.tsx
  packages/ui/src/components/Modal/__stories__/HideOnEsc.stories.tsx
  packages/ui/src/components/NumberInput/index.tsx
  packages/ui/src/components/Table/HeaderRow.tsx
  packages/ui/src/components/Table/Row.tsx
  packages/ui/src/components/Table/__stories__/Selectable.stories.tsx
  packages/ui/src/components/Toaster/__stories__/Sentiments.stories.tsx
  packages/ui/src/components/Toaster/__stories__/index.stories.tsx
  packages/ui/src/components/Toaster/index.tsx
Labels: refactor

#2989 fix(checkbox): decrease the size of the svg
  .changeset/thick-penguins-explain.md
  packages/form/src/components/CheckboxField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/CheckboxGroupField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/ui/src/components/Checkbox/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Checkbox/index.tsx
  packages/ui/src/components/CheckboxGroup/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/LineChart/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectableCard/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Table/__tests__/__snapshots__/index.test.tsx.snap
Labels: bug

#2988 fix: event workflow not consistent
  .changeset/hungry-spoons-hear.md
  packages/ui/src/components/MenuV2/__stories__/WithModal.stories.tsx
  packages/ui/src/components/MenuV2/index.tsx
  packages/ui/src/components/Modal/Dialog.tsx
  packages/ui/src/components/Popover/__tests__/index.test.tsx
  packages/ui/src/components/Popover/index.tsx
  packages/ui/src/internalComponents/Popup/index.tsx
Labels: bug

#2982 feat: new library for advanced components
  .changeset/cyan-squids-decide.md
  .changeset/hip-rocks-no.md
  .changeset/hip-rocks-smell.md
  .storybook/components/DocsContainer.tsx
  .storybook/preview.tsx
  README.md
  packages/icons/src/components/ProductIcon/__tests__/__snapshots__/index.tsx.snap
  packages/icons/src/components/ProductIcon/index.tsx
  packages/plus/.eslintrc.cjs
  packages/plus/.jest/helpers.tsx
  packages/plus/.npmignore
  packages/plus/CHANGELOG.md
  packages/plus/README.md
  packages/plus/package.json
  packages/plus/src/__stories__/Introduction.stories.mdx
  packages/plus/src/components/ContentCard/Skeleton.tsx
  packages/plus/src/components/ContentCard/__stories__/Click.stories.tsx
  packages/plus/src/components/ContentCard/__stories__/Directions.stories.tsx
  packages/plus/src/components/ContentCard/__stories__/Examples.stories.tsx
  packages/plus/src/components/ContentCard/__stories__/Link.stories.tsx
  packages/plus/src/components/ContentCard/__stories__/Loading.stories.tsx
  packages/plus/src/components/ContentCard/__stories__/Playground.stories.tsx
  packages/plus/src/components/ContentCard/__stories__/Template.stories.tsx
  packages/plus/src/components/ContentCard/__stories__/index.stories.tsx
  packages/plus/src/components/ContentCard/__tests__/__snapshots__/index.test.tsx.snap
  packages/plus/src/components/ContentCard/__tests__/index.test.tsx
  packages/plus/src/components/ContentCard/assets/illustration.png
  packages/plus/src/components/ContentCard/assets/illustration2.svg
  packages/plus/src/components/ContentCard/index.tsx
  packages/plus/src/components/index.tsx
  packages/plus/src/emotion.d.ts
  packages/plus/src/index.ts
  packages/plus/tsconfig.json
  packages/themes/package.json
  packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Skeleton/Square.tsx
  packages/ui/src/components/Skeleton/__stories__/Square.stories.tsx
  packages/ui/src/components/Skeleton/__stories__/index.stories.tsx
  packages/ui/src/components/Skeleton/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Skeleton/index.tsx
  packages/ui/src/components/Table/__tests__/__snapshots__/index.test.tsx.snap
  pnpm-lock.yaml
Labels: enhancement

#3006 feat(ProductIcon): new ipfs naming
  .changeset/silly-points-teach.md
  packages/icons/src/components/ProductIcon/Icons.tsx
  packages/icons/src/components/ProductIcon/__tests__/__snapshots__/index.tsx.snap
Labels: enhancement

#3015 fix(ContentCard): main stack to get all height
  .changeset/fluffy-poems-bathe.md
  packages/plus/src/components/ContentCard/__tests__/__snapshots__/index.test.tsx.snap
  packages/plus/src/components/ContentCard/index.tsx
Labels: enhancement

#3013 feat(ProductIcon): new file and folder
  .changeset/three-brooms-kiss.md
  packages/icons/src/components/ProductIcon/Icons.tsx
  packages/icons/src/components/ProductIcon/__tests__/__snapshots__/index.tsx.snap
Labels: enhancement

#3018 feat(experimental-popup): move popup as an experimental component
  .changeset/shiny-pots-relax.md
  packages/ui/src/components/Button/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Checkbox/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/CopyButton/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/MenuV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/MenuV2/index.tsx
  packages/ui/src/components/PieChart/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Popover/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Popover/index.tsx
  packages/ui/src/components/Popup/__tests__/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Popup/__tests__/__tests__/index.test.tsx
  packages/ui/src/components/Popup/helpers.ts
  packages/ui/src/components/Popup/index.tsx
  packages/ui/src/components/Radio/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectableCard/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Snippet/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SwitchButton/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Table/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Tag/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TagList/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Toggle/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Tooltip/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Tooltip/index.tsx
  packages/ui/src/components/index.ts
  packages/ui/src/internalComponents/index.ts
Labels: design system

#3023 fix(ProductIcon): color not correctly applied on some icons
  .changeset/green-toes-reflect.md
  packages/icons/src/components/ProductIcon/__tests__/__snapshots__/index.tsx.snap
  packages/icons/src/components/ProductIcon/index.tsx
Labels: bug

#3020 fix(ContentCard): replace title variant from body strong to body stronger
  .changeset/plenty-teachers-wonder.md
  packages/plus/src/components/ContentCard/__tests__/__snapshots__/index.test.tsx.snap
  packages/plus/src/components/ContentCard/index.tsx
Labels: enhancement

#3008 feat(modal): replace function names by good ones
  .changeset/modern-years-applaud.md
  packages/ui/src/components/Modal/Disclosure.tsx
  packages/ui/src/components/Modal/__tests__/index.test.tsx
  packages/ui/src/components/Modal/index.tsx
  packages/ui/src/components/Modal/types.ts
Labels: enhancement

#2990 fix(Text): remove default color neutral
  .changeset/old-wolves-fail.md
  packages/form/src/components/CheckboxGroupField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/RadioGroupField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/SubmitErrorAlert/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/ToggleGroupField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/ui/src/components/Alert/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Badge/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/BarChart/__tests__/__snapshots__/Tooltip.tsx.snap
  packages/ui/src/components/Card/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/CheckboxGroup/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/EmptyState/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Meter/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/PasswordCheck/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/PasswordStrengthMeter/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/PieChart/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Radio/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/RadioGroup/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Snippet/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Stepper/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Tabs/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Text/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Text/index.tsx
  packages/ui/src/components/TextInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Toggle/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/ToggleGroup/__tests__/__snapshots__/index.test.tsx.snap
Labels: enhancement

#3037 feat(code-editor): add code editor to ultraviolet/plus package
  .changeset/famous-beds-develop.md
  .github/renovate.json
  codecov.yml
  packages/plus/package.json
  packages/plus/src/components/CodeEditor/CodeEditor.tsx
  packages/plus/src/components/CodeEditor/__stories__/Playground.stories.tsx
  packages/plus/src/components/CodeEditor/__stories__/Template.stories.tsx
  packages/plus/src/components/CodeEditor/__stories__/index.stories.tsx
  packages/plus/src/components/CodeEditor/__tests__/__snapshots__/index.tsx.snap
  packages/plus/src/components/CodeEditor/__tests__/index.tsx
  packages/plus/src/components/CodeEditor/index.ts
  packages/plus/src/components/index.ts
  pnpm-lock.yaml
Labels: migration

#3040 fix(Banner): alignement issue when description is too little
  .changeset/popular-years-own.md
  packages/ui/src/components/Banner/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Banner/index.tsx
Labels: bug

#3044 fix(Popup): popup component to change event on mousedown and add ref into popover component
  .changeset/brave-crabs-press.md
  packages/ui/src/components/Popover/index.tsx
  packages/ui/src/components/Popup/index.tsx
  pnpm-lock.yaml
Labels: bug

#3011 feat(dateinput): update design and add range date
  .changeset/fair-boxes-carry.md
  packages/form/src/components/DateField/__stories__/Playground.stories.tsx
  packages/form/src/components/DateField/__tests__/__snapshots__/index.tsx.snap
  packages/form/src/components/DateField/index.tsx
  packages/ui/src/components/DateInput/__stories__/Controlled.stories.tsx
  packages/ui/src/components/DateInput/__stories__/Exclude.stories.tsx
  packages/ui/src/components/DateInput/__stories__/Range.stories.tsx
  packages/ui/src/components/DateInput/__stories__/index.stories.tsx
  packages/ui/src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/DateInput/__tests__/index.test.tsx
  packages/ui/src/components/DateInput/index.tsx
Labels: enhancement

#3043 fix(Popover): text to be correct color
  .changeset/moody-items-lie.md
  packages/ui/src/components/Popover/index.tsx
Labels: bug

#3047 fix(Popup): popup to re-compute position when screen resize or when width changes
  .changeset/moody-lies-call.md
  packages/ui/src/components/Popup/index.tsx
Labels: bug

#3052 fix(ui): textinput should pass min and max prop
  .changeset/tasty-dolphins-peel.md
  packages/ui/src/components/TextInput/index.tsx
Labels: bug

#3075 fix(MenuV2): focus when opening error
  .changeset/sixty-gorillas-approve.md
  packages/ui/src/components/MenuV2/index.tsx
Labels: bug

#3076 fix(Popup): hotfix on click event handler causing modal to close when nested in popover
  .changeset/slimy-kiwis-yawn.md
  packages/ui/src/components/Popover/__stories__/AdvancedUsage.stories.tsx
  packages/ui/src/components/Popover/__stories__/index.stories.tsx
  packages/ui/src/components/Popup/index.tsx
Labels: bug, hotfix

#3072 fix(ContentCard): color on title and description
  .changeset/olive-humans-call.md
  .storybook/preview.tsx
  packages/plus/src/components/ContentCard/__tests__/__snapshots__/index.test.tsx.snap
  packages/plus/src/components/ContentCard/index.tsx
Labels: bug

#3079 feat(Icons): new database Icon
  .changeset/thirty-carpets-wave.md
  packages/icons/src/components/Icon/__tests__/__snapshots__/index.test.tsx.snap
  packages/icons/src/components/Icon/index.tsx
Labels: design system

#3081 fix(Popover): set a default color in content to avoid inherit from parent
  .changeset/strong-pumpkins-buy.md
  packages/ui/src/components/Popover/index.tsx
Labels: bug

#3080 feat(menuV2): add children function props with toggle to handle toggl…
  .changeset/six-parents-whisper.md
  packages/ui/src/components/MenuV2/__stories__/FunctionChildrenToggle.stories.tsx
  packages/ui/src/components/MenuV2/__stories__/index.stories.tsx
  packages/ui/src/components/MenuV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/MenuV2/__tests__/index.test.tsx
  packages/ui/src/components/MenuV2/index.tsx
Labels: enhancement

#3083 feat: add new illustrations
  .changeset/strange-steaks-begin.md
  packages/illustrations/src/products/blockStorage/block-storage-original.webp
  packages/illustrations/src/products/blockStorage/index.ts
  packages/illustrations/src/products/documentDB/documentDB.webp
  packages/illustrations/src/products/documentDB/index.ts
  packages/illustrations/src/products/iam/iam-original.webp
  packages/illustrations/src/products/iam/index.ts
  packages/illustrations/src/products/index.ts
  packages/illustrations/src/products/ipfsNaming/index.ts
  packages/illustrations/src/products/ipfsNaming/ipfs-naming-original.webp
  packages/illustrations/src/products/serverlessDB/index.ts
  packages/illustrations/src/products/serverlessDB/serverlessDB.webp
  packages/illustrations/src/products/serverlessJob/index.ts
  packages/illustrations/src/products/serverlessJob/serverlessJob.webp
Labels: enhancement

#3087 ci(Popover): add advanced unit testing with modal within popover
  package.json
  packages/ui/src/components/Popover/__tests__/index.test.tsx
Labels: ci

#3097 fix(Popup): new props and remove animation when max height is set
  .changeset/lovely-socks-yawn.md
  packages/ui/src/components/MenuV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/MenuV2/index.tsx
  packages/ui/src/components/Popover/index.tsx
  packages/ui/src/components/Popup/__tests__/__tests__/index.test.tsx
  packages/ui/src/components/Popup/index.tsx
Labels: bug, enhancement

#3086 feat(node): update node version ci
  .github/workflows/ci.yml
  .github/workflows/pull_request_title.yml
  .github/workflows/release.yml
  .github/workflows/sync-design-tokens.yml
Labels: enhancement
