Repository scaleway/ultraviolet, pull requests merged in 2023-12, with the labels that each got.

#3204 fix(EstimateCost): fix style and export default locales
  .changeset/hungry-sheep-dance.md
  packages/plus/src/components/EstimateCost/Components/Item.tsx
  packages/plus/src/components/EstimateCost/EstimateCostContent.tsx
  packages/plus/src/components/EstimateCost/OverlayComponent.tsx
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Item.spec.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Region.spec.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Regular.spec.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Stepper.spec.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Strong.spec.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Unit.spec.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Zone.spec.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/index.spec.tsx.snap
  packages/plus/src/components/EstimateCost/componentStyle.ts
  packages/plus/src/components/EstimateCost/constants.ts
  packages/plus/src/components/EstimateCost/index.ts
  packages/plus/src/components/index.ts
Labels: enhancement

#3200 fix(Text): one line prop to be working on modals
  .changeset/green-guests-yell.md
  packages/ui/.jest/helpers.tsx
  packages/ui/src/components/Modal/__stories__/WithTooltip.stories.tsx
  packages/ui/src/components/Text/index.tsx
  packages/ui/src/hooks/__tests__/useIsOverflowing.test.tsx
  packages/ui/src/hooks/useIsOverflowing.ts
  pnpm-lock.yaml
Labels: bug

#3207 fix(EstimateCost): add missing props
  .changeset/nine-jokes-bow.md
  packages/plus/src/components/EstimateCost/Components/Region.tsx
  packages/plus/src/components/EstimateCost/Components/Zone.tsx
  packages/plus/src/components/EstimateCost/EstimateCostContent.tsx
  packages/plus/src/components/EstimateCost/types.ts
Labels: bug

#3205 ci: fix size limit to ignore ultraviolet plus
  package.json
Labels: bug, ci

#3221 fix(Checkbox): trigger a on change on space bar pressed
  .changeset/wet-terms-again.md
  .changeset/wet-terms-repeat.md
  packages/form/src/components/CheckboxField/__stories__/index.stories.tsx
  packages/ui/src/components/Checkbox/__tests__/index.tsx
  packages/ui/src/components/Checkbox/index.tsx
Labels: bug

#3220 fix(SelectableCard): label to take full space
  .changeset/gentle-avocados-compete.md
  packages/form/src/components/CheckboxField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/CheckboxGroupField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/RadioField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/RadioGroupField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/SelectableCardField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/ui/src/components/Checkbox/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Checkbox/index.tsx
  packages/ui/src/components/CheckboxGroup/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/LineChart/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Radio/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Radio/index.tsx
  packages/ui/src/components/RadioGroup/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectableCard/__stories__/Examples.stories.tsx
  packages/ui/src/components/SelectableCard/__stories__/index.stories.tsx
  packages/ui/src/components/SelectableCard/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectableCard/index.tsx
  packages/ui/src/components/Stack/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Stack/index.tsx
  packages/ui/src/components/SwitchButton/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Table/__tests__/__snapshots__/index.test.tsx.snap
Labels: bug, enhancement, refactor

#3229 fix(EstimateCost): when discount is set to 0 display correct values
  .changeset/shiny-flowers-invent.md
  packages/plus/src/components/EstimateCost/EstimateCostContent.tsx
  packages/plus/src/components/EstimateCost/__stories__/GlobalDiscount.stories.tsx
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Regular.spec.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/index.spec.tsx.snap
Labels: bug

#3218 refactor(Tabs): use menu v2
  .changeset/lemon-lamps-bake.md
  packages/ui/src/components/Tabs/TabMenu.tsx
  packages/ui/src/components/Tabs/__tests__/__snapshots__/index.test.tsx.snap
Labels: refactor

#3234 feat(Icon): new icon address
  .changeset/beige-pants-accept.md
  packages/icons/src/components/Icon/__tests__/__snapshots__/index.test.tsx.snap
  packages/icons/src/components/Icon/index.tsx
Labels: enhancement

#3228 fix(Popup): fix right position on popup
  .changeset/shaggy-bulldogs-notice.md
  packages/ui/src/components/MenuV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Popover/__stories__/Controlled.stories.tsx
  packages/ui/src/components/Popover/__stories__/Playground.stories.tsx
  packages/ui/src/components/Popover/__stories__/index.stories.tsx
  packages/ui/src/components/Popover/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Popup/helpers.ts
  packages/ui/src/components/Popup/index.tsx
Labels: bug

#3233 feat(CopyButton): add more sizes to follow button specifications
  .changeset/slow-bugs-call.md
  packages/ui/src/components/CopyButton/__stories__/Sizes.stories.tsx
  packages/ui/src/components/CopyButton/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/CopyButton/__tests__/index.tsx
  packages/ui/src/components/CopyButton/index.tsx
Labels: enhancement

#3249 fix(SelectableCard): type checkbox to work properly when clicking on both card and checkbox
  .changeset/moody-goats-remain.md
  packages/form/src/components/SelectableCardField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/ui/src/components/SelectableCard/__stories__/Examples.stories.tsx
  packages/ui/src/components/SelectableCard/__stories__/ShowTick.stories.tsx
  packages/ui/src/components/SelectableCard/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectableCard/index.tsx
  packages/ui/src/components/SwitchButton/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SwitchButton/__tests__/index.test.tsx
  packages/ui/src/components/SwitchButton/index.tsx
Labels: bug

#3199 feat: new component TextArea
  .changeset/hot-gorillas-behave.md
  packages/form/src/components/TextAreaField/__stories__/Playground.stories.tsx
  packages/form/src/components/TextAreaField/__stories__/Required.stories.tsx
  packages/form/src/components/TextAreaField/__stories__/Template.stories.tsx
  packages/form/src/components/TextAreaField/__stories__/index.stories.tsx
  packages/form/src/components/TextAreaField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/TextAreaField/__tests__/index.spec.tsx
  packages/form/src/components/TextAreaField/index.tsx
  packages/form/src/components/index.ts
  packages/ui/src/components/TextArea/__stories__/Disabled.stories.tsx
  packages/ui/src/components/TextArea/__stories__/Error.stories.tsx
  packages/ui/src/components/TextArea/__stories__/Examples.stories.tsx
  packages/ui/src/components/TextArea/__stories__/Helper.stories.tsx
  packages/ui/src/components/TextArea/__stories__/MaxLength.stories.tsx
  packages/ui/src/components/TextArea/__stories__/Placeholder.stories.tsx
  packages/ui/src/components/TextArea/__stories__/Playground.stories.tsx
  packages/ui/src/components/TextArea/__stories__/ReadOnly.stories.tsx
  packages/ui/src/components/TextArea/__stories__/Success.stories.tsx
  packages/ui/src/components/TextArea/__stories__/Template.stories.tsx
  packages/ui/src/components/TextArea/__stories__/index.stories.tsx
  packages/ui/src/components/TextArea/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TextArea/__tests__/index.test.tsx
  packages/ui/src/components/TextArea/index.tsx
  packages/ui/src/components/index.ts
Labels: design system

#3260 fix(SelectableCard): fix type radio
  .changeset/polite-nails-build.md
  packages/form/src/components/SelectableCardField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/ui/src/components/SelectableCard/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectableCard/index.tsx
  packages/ui/src/components/SwitchButton/__tests__/__snapshots__/index.test.tsx.snap
Labels: bug

#3262 fix(TextInput): input padding to follow unit length
  .changeset/chilly-cobras-bathe.md
  .changeset/curvy-kiwis-turn.md
  .changeset/purple-ads-jam.md
  packages/form/src/components/TextInputField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/plus/src/components/EstimateCost/Components/Unit.tsx
  packages/plus/src/components/EstimateCost/__stories__/Unit.stories.tsx
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Unit.spec.tsx.snap
  packages/ui/src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TextInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TextInput/index.tsx
Labels: bug

#3237 fix(EstimateCost): unit input to be clearable in time amount
  .changeset/silent-ladybugs-provide.md
  packages/plus/src/components/EstimateCost/Components/UnitInput.tsx
  packages/plus/src/components/EstimateCost/__tests__/CustomUnitInput.spec.tsx
  packages/plus/src/components/EstimateCost/__tests__/helper.spec.ts
  packages/plus/src/components/EstimateCost/helper.ts
Labels: bug
