Repository scaleway/ultraviolet, pull requests merged in 2023-06, with the labels that each got.

#2583 feat(Button): add xsmall size
  .changeset/curvy-brooms-shop.md
  packages/ui/src/__stories__/ButtonMigration/Sizes.tsx
  packages/ui/src/components/Button/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Button/index.tsx
Labels: enhancement

#2593 fix(textinput): style issue on padding
  packages/form/src/components/TextInputField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/ui/src/components/TextInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TextInput/index.tsx
Labels: bug

#2599 fix(NumberInputField): min max validation
  .changeset/wise-mayflies-try.md
  packages/form/src/components/NumberInputField/index.tsx
Labels: bug

#2600 fix(Tooltip): alignment
  .changeset/modern-mangos-fry.md
  packages/ui/src/components/Button/__stories__/Tooltip.stories.tsx
  packages/ui/src/components/Button/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/CopyButton/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/PieChart/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Popover/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectableCard/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Snippet/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SwitchButton/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Tag/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TagList/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Tooltip/__stories__/MaxWidth.stories.tsx
  packages/ui/src/components/Tooltip/__stories__/Playground.stories.tsx
  packages/ui/src/components/Tooltip/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Tooltip/index.tsx
Labels: bug

#2618 feat(passwordstrengthmeter): add async estimate method
  .changeset/many-cooks-dress.md
  packages/ui/src/components/PasswordStrengthMeter/__stories__/Estimate.stories.tsx
  packages/ui/src/components/PasswordStrengthMeter/__stories__/index.stories.tsx
  packages/ui/src/components/PasswordStrengthMeter/index.tsx
  pnpm-lock.yaml
Labels: enhancement

#2608 refactor(TagList): use Popover component instead of Tooltip
  .changeset/perfect-items-smash.md
  .changeset/smart-buckets-shave.md
  packages/ui/src/components/Popover/index.tsx
  packages/ui/src/components/TagList/__stories__/Copiable.stories.tsx
  packages/ui/src/components/TagList/__stories__/Template.stories.tsx
  packages/ui/src/components/TagList/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TagList/__tests__/index.test.tsx
  packages/ui/src/components/TagList/index.tsx
Labels: enhancement

#2622 fix(Button): remove `iconOnly` from dom
  .changeset/ten-socks-repeat.md
  packages/ui/src/components/Button/index.tsx
Labels: bug

#2626 fix(Tooltip): rollback alignement
  .changeset/chatty-countries-draw.md
  packages/ui/src/components/Button/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/CopyButton/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/PieChart/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Popover/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectableCard/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Snippet/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SwitchButton/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Table/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Tag/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TagList/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Tooltip/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Tooltip/index.tsx
Labels: bug

#2629 fix: make old package deprecated for one last release
  .changeset/renaming-deprecated-ultraviolet.md
Labels: enhancement

#2635 docs: update button migration page
  packages/ui/src/__stories__/ButtonMigration/Variants.tsx
  packages/ui/src/__stories__/ButtonMigration/index.stories.mdx
  packages/ui/src/__stories__/assets/button-action-migration.png
  packages/ui/src/__stories__/assets/button-migration.png
Labels: documentation

#2641 docs(themes): fix auto closing global in readme
  packages/themes/README.md
Labels: documentation

#2644 fix(PieChart): remove strikethrough style
  .changeset/wise-paws-end.md
  packages/ui/src/components/PieChart/Legends.tsx
  packages/ui/src/components/PieChart/__stories__/Strikethrough.stories.tsx
  packages/ui/src/components/PieChart/__stories__/index.stories.tsx
  packages/ui/src/components/PieChart/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/PieChart/index.tsx
  packages/ui/src/components/PieChart/patterns.tsx
Labels: refactor

#2642 docs(ui): fix auto closing global in readme
  packages/ui/README.md
Labels: documentation

#2650 docs: fix variant link new matching sentiments
  packages/ui/src/__stories__/ButtonMigration/Variants.tsx
Labels: documentation

#2647 ci: remove teardown pull request job
  .github/workflows/teardown_pull_request.yml
Labels: ci

#2651 ci: revert teardown
  .github/workflows/teardown_pull_request.yml
Labels: ci

#2661 fix(pnpm): remove useless field pnpm peerDeps
  packages/ui/package.json
Labels: bug, dependencies

#2648 docs: update readme versioning and link to documentation
  README.md
Labels: documentation

#2664 feat(modal): forward onClick events based on disclosure component
  .changeset/gold-parents-itch.md
  packages/ui/src/components/Modal/__tests__/index.test.tsx
  packages/ui/src/components/Modal/index.tsx
Labels: enhancement

#2663 fix(Loader): active animation
  .changeset/modern-tools-think.md
  packages/form/src/components/Submit/__tests__/__snapshots__/index.spec.tsx.snap
  packages/ui/src/components/Button/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Checkbox/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Loader/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Loader/index.tsx
  packages/ui/src/components/Tag/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TagInput/__tests__/__snapshots__/index.test.tsx.snap
Labels: bug

#2662 fix(TagInput): not to block focus while pressing key tab
  .changeset/wise-berries-poke.md
  packages/ui/src/components/TagInput/index.tsx
Labels: bug

#2670 fix(Button): add `tabIndex` prop
  .changeset/two-cats-raise.md
  packages/form/src/components/NumberInputField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/Submit/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/SubmitErrorAlert/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/TagInputField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/TextInputField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/ui/src/components/Alert/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Banner/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Button/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Button/index.tsx
  packages/ui/src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Modal/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/NumberInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Pagination/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Tag/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TagInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TextInput/__tests__/__snapshots__/index.test.tsx.snap
Labels: bug
