Repository scaleway/ultraviolet, pull requests merged in 2023-03, with the labels that each got.

#2284 docs: new experimentals components in storybook
  .storybook/components/DocsContainer.tsx
  .storybook/components/Page.tsx
  packages/ui/src/__stories__/ComponentState/ComponentState.tsx
  packages/ui/src/components/BarChart/__stories__/index.stories.tsx
  packages/ui/src/components/BarChart/index.tsx
  packages/ui/src/components/LineChart/__stories__/index.stories.tsx
  packages/ui/src/components/LineChart/index.tsx
  packages/ui/src/components/PieChart/__stories__/index.stories.tsx
  packages/ui/src/components/PieChart/index.tsx
  packages/ui/src/components/StepList/__stories__/index.stories.tsx
  packages/ui/src/components/StepList/index.tsx
  packages/ui/src/components/TagInput/__stories__/index.stories.tsx
  packages/ui/src/components/TagInput/index.tsx
  packages/ui/src/components/TimeInput/__stories__/index.stories.tsx
  packages/ui/src/components/TimeInput/index.tsx
Labels: documentation, enhancement

#2294 fix: menu and modal small issues
  packages/ui/src/components/Menu/__stories__/index.stories.tsx
  packages/ui/src/components/Menu/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Menu/__tests__/index.tsx
  packages/ui/src/components/Menu/index.tsx
  packages/ui/src/components/Modal/__stories__/Switch.stories.tsx
  packages/ui/src/components/Modal/__stories__/Toggle.stories.tsx
  packages/ui/src/components/Modal/__stories__/index.stories.tsx
  packages/ui/src/components/Modal/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Modal/__tests__/index.tsx
  packages/ui/src/components/Modal/index.tsx
  packages/ui/src/components/Tabs/TabMenu.tsx
  packages/ui/src/components/Tabs/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Tabs/__tests__/index.test.tsx
  pnpm-lock.yaml
Labels: design system

#2291 fix(toaster): improve placement and fix stories snippet
  packages/ui/src/components/Toaster/__stories__/Variants.stories.tsx
  packages/ui/src/components/Toaster/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Toaster/index.tsx
Labels: enhancement

#2292 refactor(ScrollView): remove component
  packages/ui/src/components/ScrollView/__stories__/Playground.stories.tsx
  packages/ui/src/components/ScrollView/__stories__/index.stories.tsx
  packages/ui/src/components/ScrollView/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/ScrollView/__tests__/index.tsx
  packages/ui/src/components/ScrollView/index.tsx
  packages/ui/src/components/index.ts
  packages/ui/src/index.ts
Labels: refactor

#2296 fix: text to accept hmtlFor
  packages/ui/src/components/Text/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Text/__tests__/index.test.tsx
  packages/ui/src/components/Text/index.tsx
Labels: enhancement

#2297 refactor(Sphere): remove component
  packages/ui/src/__tests__/a11y.test.tsx
  packages/ui/src/components/Sphere/__stories__/Halved.stories.tsx
  packages/ui/src/components/Sphere/__stories__/Playground.stories.tsx
  packages/ui/src/components/Sphere/__stories__/Template.stories.tsx
  packages/ui/src/components/Sphere/__stories__/Text.stories.tsx
  packages/ui/src/components/Sphere/__stories__/index.stories.tsx
  packages/ui/src/components/Sphere/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Sphere/__tests__/index.tsx
  packages/ui/src/components/Sphere/index.tsx
  packages/ui/src/components/index.ts
  packages/ui/src/index.ts
Labels: refactor

#2298 refactor(Label): remove component
  packages/form/src/hooks/__stories__/useOnFieldChange.stories.tsx
  packages/ui/src/components/Label/__stories__/Playground.stories.tsx
  packages/ui/src/components/Label/__stories__/Template.stories.tsx
  packages/ui/src/components/Label/__stories__/index.stories.tsx
  packages/ui/src/components/Label/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Label/__tests__/index.tsx
  packages/ui/src/components/Label/index.tsx
  packages/ui/src/components/index.ts
  packages/ui/src/index.ts
Labels: refactor

#2303 fix: update snapshots with last node version
  packages/ui/src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap
Labels: bug

#2302 feat(Icon): new icon email-remove-outline
  packages/ui/src/components/Icon/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Icon/index.tsx
Labels: enhancement

#2305 feat(description): remove Description component from scw/ui
  packages/ui/src/components/Description/__stories__/Inline.stories.tsx
  packages/ui/src/components/Description/__stories__/Playground.stories.tsx
  packages/ui/src/components/Description/__stories__/Selectable.stories.tsx
  packages/ui/src/components/Description/__stories__/index.stories.tsx
  packages/ui/src/components/Description/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Description/__tests__/index.test.tsx
  packages/ui/src/components/Description/index.tsx
  packages/ui/src/components/index.ts
  packages/ui/src/index.ts
Labels: enhancement, design system

#2306 feat(StateBar): remove StateBar component
  packages/ui/src/components/StateBar/__stories__/LabelValue.stories.tsx
  packages/ui/src/components/StateBar/__stories__/Playground.stories.tsx
  packages/ui/src/components/StateBar/__stories__/Progress.stories.tsx
  packages/ui/src/components/StateBar/__stories__/Unlimited.stories.tsx
  packages/ui/src/components/StateBar/__stories__/index.stories.tsx
  packages/ui/src/components/StateBar/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/StateBar/__tests__/index.tsx
  packages/ui/src/components/StateBar/index.tsx
  packages/ui/src/components/index.ts
  packages/ui/src/index.ts
Labels: enhancement, design system

#2316 feat(EmptyState): add EmptyState component
  global.d.ts
  packages/ui/src/components/EmptyState/__stories__/index.stories.tsx
  packages/ui/src/components/EmptyState/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/EmptyState/__tests__/index.tsx
  packages/ui/src/components/EmptyState/illustrations/kapsule.webp
  packages/ui/src/components/EmptyState/illustrations/product-error.svg
  packages/ui/src/components/EmptyState/index.tsx
  packages/ui/src/components/index.ts
Labels: enhancement, design system

#2334 fix: broken lockfile
  pnpm-lock.yaml
Labels: bug

#2345 refactor(Breadcrumbs): remove variants
  packages/ui/src/components/Breadcrumbs/__stories__/OnClick.stories.tsx
  packages/ui/src/components/Breadcrumbs/__stories__/To.stories.tsx
  packages/ui/src/components/Breadcrumbs/__stories__/Variants.stories.tsx
  packages/ui/src/components/Breadcrumbs/__stories__/index.stories.tsx
  packages/ui/src/components/Breadcrumbs/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Breadcrumbs/__tests__/index.tsx
  packages/ui/src/components/Breadcrumbs/index.tsx
Labels: refactor

#2337 fix(NumberInput): enable controlled NumberInput
  packages/form/src/components/NumberInputField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/NumberInputField/__tests__/index.spec.tsx
  packages/form/src/components/NumberInputField/index.tsx
  packages/ui/src/components/NumberInput/__stories__/Controlled.stories.tsx
  packages/ui/src/components/NumberInput/__stories__/DefaultValue.stories.tsx
  packages/ui/src/components/NumberInput/__stories__/Disabled.stories.tsx
  packages/ui/src/components/NumberInput/__stories__/Events.stories.tsx
  packages/ui/src/components/NumberInput/__stories__/Steps.stories.tsx
  packages/ui/src/components/NumberInput/__stories__/index.stories.tsx
  packages/ui/src/components/NumberInput/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/NumberInput/__tests__/index.tsx
  packages/ui/src/components/NumberInput/index.tsx
Labels: bug

#2359 fix(tooltip): improve tooltip by hidding when generating positions
  packages/ui/src/components/Tooltip/helpers.ts
Labels: enhancement

#2360 feat: nuke unused Col/Row
  packages/ui/src/components/Grid/Col.tsx
  packages/ui/src/components/Grid/Row.tsx
  packages/ui/src/components/Grid/__stories__/ColWithBackground.ts
  packages/ui/src/components/Grid/__stories__/index.stories.tsx
  packages/ui/src/components/Grid/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Grid/__tests__/index.test.tsx
  packages/ui/src/components/Grid/index.ts
  packages/ui/src/components/index.ts
  packages/ui/src/index.ts
Labels: refactor

#2361 feat: rename RowV2 to Row
  packages/ui/src/components/Row/__stories__/AlignItems.stories.tsx
  packages/ui/src/components/Row/__stories__/Example.stories.tsx
  packages/ui/src/components/Row/__stories__/Gap.stories.tsx
  packages/ui/src/components/Row/__stories__/Playground.stories.tsx
  packages/ui/src/components/Row/__stories__/Template.stories.tsx
  packages/ui/src/components/Row/__stories__/index.stories.tsx
  packages/ui/src/components/Row/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Row/__tests__/index.test.tsx
  packages/ui/src/components/Row/index.tsx
  packages/ui/src/components/index.ts
  packages/ui/src/index.ts
Labels: refactor

#2349 refactor(Expandable): smart expandable
  packages/form/src/components/DateField/__tests__/__snapshots__/index.tsx.snap
  packages/form/src/components/SelectInputField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/Submit/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/TextInputField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/TimeField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/ui/src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Expandable/__stories__/MinHeight.stories.tsx
  packages/ui/src/components/Expandable/__stories__/NestedExpandable.stories.tsx
  packages/ui/src/components/Expandable/__stories__/index.stories.tsx
  packages/ui/src/components/Expandable/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Expandable/__tests__/index.test.tsx
  packages/ui/src/components/Expandable/index.tsx
  packages/ui/src/components/SelectInput/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/SelectInput/index.tsx
  packages/ui/src/components/Snippet/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Snippet/index.tsx
  packages/ui/src/components/TextInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TextInput/index.tsx
  packages/ui/src/components/TimeInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/UnitInput/__tests__/__snapshots__/index.test.tsx.snap
Labels: enhancement, refactor

#2363 feat(components): add className and data-testid - Part 1
  packages/ui/src/components/ActionBar/index.tsx
  packages/ui/src/components/Alert/index.tsx
  packages/ui/src/components/Avatar/index.tsx
  packages/ui/src/components/Badge/index.tsx
  packages/ui/src/components/BarChart/Tooltip.tsx
  packages/ui/src/components/BarChart/index.tsx
  packages/ui/src/components/BarStack/index.tsx
  packages/ui/src/components/Breadcrumbs/index.tsx
  packages/ui/src/components/Bullet/index.tsx
  packages/ui/src/components/Button/index.tsx
  packages/ui/src/components/Carousel/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Carousel/index.tsx
  packages/ui/src/components/Checkbox/index.tsx
  packages/ui/src/components/Container/index.tsx
  packages/ui/src/components/CopyButton/index.tsx
  packages/ui/src/components/DateInput/index.tsx
  packages/ui/src/components/EmptyState/index.tsx
  packages/ui/src/components/LineChart/CustomLegend.tsx
  packages/ui/src/components/LineChart/index.tsx
  packages/ui/src/components/Link/index.tsx
  packages/ui/src/components/Menu/index.tsx
  packages/ui/src/components/Modal/index.tsx
  packages/ui/src/components/Notice/index.tsx
  packages/ui/src/components/NumberInput/index.tsx
  packages/ui/src/components/PaginationV2/index.tsx
  packages/ui/src/components/PasswordCheck/index.tsx
  packages/ui/src/components/PasswordStrengthMeter/index.tsx
  packages/ui/src/components/ProgressBar/index.tsx
  packages/ui/src/components/ProgressionButton/index.tsx
  packages/ui/src/components/Radio/index.tsx
  packages/ui/src/components/SelectInput/index.tsx
  packages/ui/src/components/SelectableCard/index.tsx
  packages/ui/src/components/Separator/index.tsx
  packages/ui/src/components/Snippet/index.tsx
  packages/ui/src/components/Stack/index.tsx
  packages/ui/src/components/Status/index.tsx
  packages/ui/src/components/StepList/index.tsx
  packages/ui/src/components/Stepper/index.tsx
  packages/ui/src/components/SwitchButton/index.tsx
  packages/ui/src/components/Table/index.tsx
  packages/ui/src/components/Tabs/index.tsx
  packages/ui/src/components/Tag/index.tsx
  packages/ui/src/components/TagInput/index.tsx
  packages/ui/src/components/TagList/index.tsx
  packages/ui/src/components/Text/index.tsx
  packages/ui/src/components/Toaster/index.tsx
  packages/ui/src/components/Toggle/index.tsx
  packages/ui/src/components/Tooltip/index.tsx
  packages/ui/src/components/UnitInput/index.tsx
  packages/ui/src/components/VerificationCode/index.tsx
Labels: enhancement
