Repository scaleway/ultraviolet, pull requests merged in 2023-04, with the labels that each got.

#2377 fix(tooltip): flickering effect due to animation going backwards
  .changeset/rare-hotels-try.md
  packages/ui/src/components/Tooltip/helpers.ts
  packages/ui/src/components/Tooltip/index.tsx
Labels: bug

#2371 feat(ButtonV2): new component
  .changeset/stupid-knives-impress.md
  .storybook/preview.tsx
  packages/themes/src/themes/console/index.ts
  packages/ui/src/__stories__/ButtonMigration/Sizes.tsx
  packages/ui/src/__stories__/ButtonMigration/Variants.tsx
  packages/ui/src/__stories__/ButtonMigration/index.stories.mdx
  packages/ui/src/components/Button/__stories__/index.stories.tsx
  packages/ui/src/components/Button/index.tsx
  packages/ui/src/components/ButtonV2/__stories__/Disabled.stories.tsx
  packages/ui/src/components/ButtonV2/__stories__/FullWidth.stories.tsx
  packages/ui/src/components/ButtonV2/__stories__/IconOnly.stories.tsx
  packages/ui/src/components/ButtonV2/__stories__/IconPosition.stories.tsx
  packages/ui/src/components/ButtonV2/__stories__/IsLoading.stories.tsx
  packages/ui/src/components/ButtonV2/__stories__/Playground.stories.tsx
  packages/ui/src/components/ButtonV2/__stories__/Showcase.stories.tsx
  packages/ui/src/components/ButtonV2/__stories__/Size.stories.tsx
  packages/ui/src/components/ButtonV2/__stories__/Template.stories.tsx
  packages/ui/src/components/ButtonV2/__stories__/index.stories.tsx
  packages/ui/src/components/ButtonV2/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/ButtonV2/__tests__/index.tsx
  packages/ui/src/components/ButtonV2/index.tsx
  packages/ui/src/components/index.ts
  packages/ui/src/index.ts
Labels: design system

#2403 feat(Link): add new `prominence` props
  .changeset/witty-eyes-rest.md
  packages/ui/src/components/Breadcrumbs/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Button/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/EmptyState/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Link/__stories__/Prominence.stories.tsx
  packages/ui/src/components/Link/__stories__/index.stories.tsx
  packages/ui/src/components/Link/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Link/__tests__/index.test.tsx
  packages/ui/src/components/Link/index.tsx
  packages/ui/src/components/Menu/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Tabs/__tests__/__snapshots__/index.test.tsx.snap
Labels: enhancement

#2406 feat: new gradient colors
  .changeset/wet-waves-marry.md
  packages/themes/src/themes/console/dark.ts
  packages/themes/src/themes/console/light.ts
  scripts/figma-synchronise-tokens.sh
Labels: enhancement

#2407 fix(ButtonV2): add `aria-label` and `name` properties
  .changeset/shy-boxes-refuse.md
  packages/ui/src/components/ButtonV2/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/ButtonV2/index.tsx
Labels: enhancement

#2411 fix(form): meta type error function
  .changeset/quick-dodos-tan.md
  packages/form/src/components/NumberInputField/index.tsx
  packages/form/src/providers/ErrorContext/__tests__/index.spec.tsx
  packages/form/src/types.ts
Labels: bug

#2402 feat(ButtonV2): support href
  .changeset/calm-pillows-fry.md
  packages/ui/src/__stories__/ButtonMigration/index.stories.mdx
  packages/ui/src/components/ButtonV2/__stories__/AsLink.stories.tsx
  packages/ui/src/components/ButtonV2/__stories__/index.stories.tsx
  packages/ui/src/components/ButtonV2/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/ButtonV2/__tests__/index.tsx
  packages/ui/src/components/ButtonV2/index.tsx
Labels: enhancement

#2416 fix(Card): add missing export
  .changeset/sharp-lies-search.md
  packages/ui/src/components/index.ts
  packages/ui/src/index.ts
Labels: bug

#2418 fix(ListV2): click of expanded content do not collapse the row
  .changeset/tasty-fireants-smell.md
  packages/ui/src/components/ListV2/Row.tsx
  packages/ui/src/components/ListV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/ListV2/__tests__/index.test.tsx
Labels: bug

#2422 chore(pnpm): update version in package
  .changeset/cool-lobsters-fold.md
  package.json
  packages/form/package.json
  packages/ui/package.json
Labels: bug

#2424 refactor(VerificationCode): change state management
  .changeset/calm-moons-judge.md
  packages/ui/src/components/VerificationCode/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/VerificationCode/index.tsx
Labels: refactor

#2443 docs: update readme to scaleway theme information
  README.md
  packages/themes/README.md
  pnpm-lock.yaml
Labels: documentation

#2444 refactor(TagsInput): hover state and pointer cursor
  .changeset/dull-mugs-serve.md
  packages/form/src/components/TagInputField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/ui/src/components/TagInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TagInput/index.tsx
Labels: refactor

#2445 docs: fix component state page
  packages/ui/src/__stories__/ComponentState/ComponentState.tsx
Labels: bug

#2448 fix(Alert): useless stack and wrong typing for buttontext prop
  .changeset/pretty-points-report.md
  packages/form/src/components/SubmitErrorAlert/__tests__/__snapshots__/index.spec.tsx.snap
  packages/ui/src/components/Alert/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Alert/index.tsx
  packages/ui/src/components/Toaster/__tests__/__snapshots__/index.test.tsx.snap
Labels: bug

#2405 feat(Banner): add new component
  .changeset/fresh-donkeys-rhyme.md
  packages/ui/src/components/Banner/__stories__/Directions.stories.tsx
  packages/ui/src/components/Banner/__stories__/Image.png
  packages/ui/src/components/Banner/__stories__/Playground.stories.tsx
  packages/ui/src/components/Banner/__stories__/Sizes.stories.tsx
  packages/ui/src/components/Banner/__stories__/Template.tsx
  packages/ui/src/components/Banner/__stories__/Types.stories.tsx
  packages/ui/src/components/Banner/__stories__/index.stories.tsx
  packages/ui/src/components/Banner/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Banner/__tests__/index.tsx
  packages/ui/src/components/Banner/index.tsx
  packages/ui/src/components/index.ts
Labels: enhancement

#2447 refactor: remove container and borderedbox
  .changeset/wild-paws-mate.md
  packages/ui/src/__stories__/components/Colors.tsx
  packages/ui/src/components/BorderedBox/__stories__/Playground.stories.tsx
  packages/ui/src/components/BorderedBox/__stories__/Template.tsx
  packages/ui/src/components/BorderedBox/__stories__/index.stories.tsx
  packages/ui/src/components/BorderedBox/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/BorderedBox/__tests__/index.tsx
  packages/ui/src/components/BorderedBox/index.tsx
  packages/ui/src/components/Container/__stories__/Disabled.stories.tsx
  packages/ui/src/components/Container/__stories__/Edition.stories.tsx
  packages/ui/src/components/Container/__stories__/Header.stories.tsx
  packages/ui/src/components/Container/__stories__/Playground.stories.tsx
  packages/ui/src/components/Container/__stories__/RightTitle.stories.tsx
  packages/ui/src/components/Container/__stories__/Small.stories.tsx
  packages/ui/src/components/Container/__stories__/Subtitle.stories.tsx
  packages/ui/src/components/Container/__stories__/Template.stories.tsx
  packages/ui/src/components/Container/__stories__/Title.stories.tsx
  packages/ui/src/components/Container/__stories__/index.stories.tsx
  packages/ui/src/components/Container/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Container/__tests__/index.tsx
  packages/ui/src/components/Container/index.tsx
  packages/ui/src/components/Row/__stories__/Example.stories.tsx
  packages/ui/src/components/SwitchButton/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SwitchButton/index.tsx
  packages/ui/src/components/index.ts
  packages/ui/src/index.ts
  website/src/components/Card.tsx
  website/src/pages/home/AdvancedUseCases.tsx
Labels: refactor

#2464 feat(PieChart): using new data color
  .changeset/eighty-owls-pretend.md
  packages/ui/src/components/PieChart/Legends.tsx
  packages/ui/src/components/PieChart/__stories__/mockData.ts
  packages/ui/src/components/PieChart/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/PieChart/index.tsx
  packages/ui/src/components/PieChart/types.tsx
Labels: enhancement

#2467 docs: make changelog page global for all packages
  global.d.ts
  packages/form/src/__stories__/Changelog.stories.mdx
  packages/ui/src/__stories__/Changelog.stories.mdx
  packages/ui/src/__stories__/Changelog/Changelog.stories.tsx
  packages/ui/src/__stories__/Changelog/index.stories.mdx
  packages/ui/src/__stories__/Properties/Properties.tsx
Labels: documentation, enhancement

#2469 fix(Tooltip): improve accessibility the wrapper can now be focused for voiceover
  .changeset/four-queens-buy.md
  packages/ui/src/components/Button/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/CopyButton/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/PieChart/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Popover/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectableCard/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Snippet/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SwitchButton/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TagList/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Tooltip/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Tooltip/__tests__/index.test.tsx
  packages/ui/src/components/Tooltip/index.tsx
Labels: enhancement

#2471 ci: add pnpm provenance parameter
  .github/workflows/release.yml
Labels: ci

#2473 fix: component props names
  .changeset/odd-queens-pump.md
  packages/ui/src/components/Alert/__stories__/Button.stories.tsx
  packages/ui/src/components/Alert/__stories__/Closable.stories.tsx
  packages/ui/src/components/Alert/__stories__/LongChildren.stories.tsx
  packages/ui/src/components/Alert/__stories__/Variants.stories.tsx
  packages/ui/src/components/Alert/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Alert/__tests__/index.test.tsx
  packages/ui/src/components/Alert/index.tsx
  packages/ui/src/components/Banner/__stories__/Variants.stories.tsx
  packages/ui/src/components/Banner/__stories__/index.stories.tsx
  packages/ui/src/components/Banner/__tests__/index.tsx
  packages/ui/src/components/Banner/index.tsx
Labels: refactor

#2477 fix(alert): add disabled prop
  .changeset/fair-seals-serve.md
  packages/ui/src/components/Alert/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Alert/__tests__/index.test.tsx
  packages/ui/src/components/Alert/index.tsx
Labels: enhancement

#2486 fix(Alert): show close button when on close is given
  .changeset/nasty-seas-bake.md
  packages/ui/src/components/Alert/index.tsx
Labels: enhancement
