Repository scaleway/ultraviolet, pull requests merged in 2023-02, with the labels that each got.

#2253 fix(SelectInput): required icon to be 10px
  packages/ui/src/components/SelectInput/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/SelectInput/index.tsx
  pnpm-lock.yaml
Labels: bug

#2254 fix(Link): default color to be info and new prop one line
  packages/ui/src/components/Breadcrumbs/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Button/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Link/__stories__/OneLine.stories.tsx
  packages/ui/src/components/Link/__stories__/index.stories.tsx
  packages/ui/src/components/Link/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Link/__tests__/index.tsx
  packages/ui/src/components/Link/index.tsx
  packages/ui/src/components/Markdown/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Menu/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Tabs/__tests__/__snapshots__/index.test.tsx.snap
Labels: enhancement

#2257 fix(toggle): add forward ref
  packages/ui/src/components/Toggle/index.tsx
Labels: enhancement

#2259 docs(ComponentState): add link to each component main story
  packages/ui/src/__stories__/ComponentState/ComponentState.tsx
Labels: documentation

#2258 docs: fix documentation
  packages/ui/src/__stories__/Changelog.stories.mdx
  packages/ui/src/__stories__/HowToMakeBreakingChanges.stories.mdx
  packages/ui/src/__stories__/Testing.stories.mdx
  packages/ui/src/__stories__/assets/screen-shot-example.png
  packages/ui/src/components/Tooltip/index.tsx
Labels: documentation

#2263 fix(Checkbox): to use radii from theme
  packages/form/src/components/CheckboxField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/themes/src/themes/console/index.ts
  packages/ui/src/components/Checkbox/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Checkbox/index.tsx
  packages/ui/src/components/LineChart/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/ListV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectableCard/__tests__/__snapshots__/index.tsx.snap
Labels: enhancement

#2262 fix(unitInput): add border to disabled state and disable when there is only one option
  packages/form/src/components/SelectInputField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/TimeField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/ui/src/components/SelectInput/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/SelectInput/index.tsx
  packages/ui/src/components/UnitInput/__stories__/index.stories.tsx
  packages/ui/src/components/UnitInput/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/UnitInput/index.tsx
Labels: enhancement

#2271 fix: use radii from theme
  packages/form/src/components/DateField/__tests__/__snapshots__/index.tsx.snap
  packages/form/src/components/ToggleField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/themes/src/themes/console/index.ts
  packages/ui/src/components/Avatar/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Avatar/index.tsx
  packages/ui/src/components/Badge/index.tsx
  packages/ui/src/components/BarChart/Tooltip.tsx
  packages/ui/src/components/BarChart/__tests__/__snapshots__/Tooltip.tsx.snap
  packages/ui/src/components/Breadcrumbs/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Breadcrumbs/index.tsx
  packages/ui/src/components/Bullet/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Bullet/index.tsx
  packages/ui/src/components/Button/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Button/index.tsx
  packages/ui/src/components/Carousel/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Carousel/index.tsx
  packages/ui/src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/DateInput/index.tsx
  packages/ui/src/components/DotSteps/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/DotSteps/index.tsx
  packages/ui/src/components/LineChart/Tooltip.tsx
  packages/ui/src/components/LineChart/__tests__/__snapshots__/Tooltip.tsx.snap
  packages/ui/src/components/List/SelectBar.tsx
  packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/List/variants/variantProduct.tsx
  packages/ui/src/components/ListV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Menu/Item.tsx
  packages/ui/src/components/Modal/index.tsx
  packages/ui/src/components/PasswordStrengthMeter/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/PasswordStrengthMeter/index.tsx
  packages/ui/src/components/PieChart/Legends.tsx
  packages/ui/src/components/PieChart/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/ProgressBar/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/ProgressBar/index.tsx
  packages/ui/src/components/ProgressionButton/index.tsx
  packages/ui/src/components/Skeleton/Block.tsx
  packages/ui/src/components/Skeleton/Blocks.tsx
  packages/ui/src/components/Skeleton/BoxWithIcon.tsx
  packages/ui/src/components/Skeleton/IconSkeleton.tsx
  packages/ui/src/components/Skeleton/Line.tsx
  packages/ui/src/components/Skeleton/Slider.tsx
  packages/ui/src/components/Skeleton/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Sphere/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Sphere/index.tsx
  packages/ui/src/components/Stack/__stories__/helper.tsx
  packages/ui/src/components/StateBar/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/StepList/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Stepper/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Stepper/index.tsx
  packages/ui/src/components/Table/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Tag/index.tsx
  packages/ui/src/components/TagInput/index.tsx
  packages/ui/src/components/Toaster/index.tsx
  packages/ui/src/components/Toggle/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Toggle/index.tsx
  packages/ui/src/components/UnitInput/index.tsx
  packages/ui/src/components/VerificationCode/index.tsx
Labels: enhancement

#2272 ci: fix tokens script by changing others to other
  scripts/figma-synchronise-tokens.sh
Labels: ci

#2274 feat(Icon): new icon colors from theme
  packages/form/src/components/NumberInputField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/Submit/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/SubmitErrorAlert/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/TagInputField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/TextInputField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/ui/src/components/Alert/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Avatar/index.tsx
  packages/ui/src/components/Badge/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Bullet/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Button/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/CopyButton/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/DateInput/index.tsx
  packages/ui/src/components/Icon/__stories__/Color.stories.tsx
  packages/ui/src/components/Icon/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Icon/__tests__/index.test.tsx
  packages/ui/src/components/Icon/index.tsx
  packages/ui/src/components/Link/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/List/SortIcon.tsx
  packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/ListV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Loader/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Modal/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Notice/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/NumberInput/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Pagination/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/PaginationV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectInput/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/SelectInput/index.tsx
  packages/ui/src/components/Snippet/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/StepList/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Stepper/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Tabs/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Tag/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/TagInput/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/TextInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Toaster/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/theme/index.ts
Labels: enhancement

#2280 fix(Icon): default value to currentColor
  packages/form/src/components/NumberInputField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/SelectInputField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/Submit/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/SubmitErrorAlert/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/TagInputField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/TextInputField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/TimeField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/ui/src/components/Alert/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Badge/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Bullet/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Button/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/CopyButton/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Icon/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Icon/index.tsx
  packages/ui/src/components/Link/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/ListV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Modal/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Notice/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/NumberInput/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Pagination/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/PaginationV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectInput/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Snippet/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/StepList/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Stepper/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Tabs/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Tag/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/TagInput/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/TextInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TimeInput/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Toaster/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/UnitInput/__tests__/__snapshots__/index.tsx.snap
Labels: bug

#2279 fix(NumberInput): colors of icons and hover were wrong
  packages/form/src/components/NumberInputField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/ui/src/components/NumberInput/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/NumberInput/index.tsx
Labels: bug

#2278 feat: new product and category colors
  packages/themes/src/themes/console/dark.ts
  packages/themes/src/themes/console/light.ts
  scripts/figma-synchronise-tokens.sh
Labels: enhancement
