Repository scaleway/ultraviolet, pull requests merged in 2024-10, with the labels that each got.

#4280 fix(themes): wrong package json export
  .changeset/sweet-mugs-thank.md
  packages/themes/package.json
Labels: bug

#4297 fix(CheckboxGroupField): missing required prop and make form required while not
  .changeset/weak-buckets-appear.md
  packages/form/src/components/CheckboxGroupField/__stories__/NotRequired.stories.tsx
  packages/form/src/components/CheckboxGroupField/__stories__/index.stories.tsx
  packages/form/src/components/CheckboxGroupField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/CheckboxGroupField/index.tsx
Labels: bug

#4293 docs(ProductIcon): display all sizes on storybook
  packages/icons/src/components/ProductIcon/Icon.tsx
  packages/icons/src/components/ProductIcon/Icons.tsx
  packages/icons/src/components/ProductIcon/__stories__/Sizes.stories.tsx
Labels: documentation

#4273 refactor(Table): implement all new behaviors
  .changeset/strong-pants-invite.md
  .changeset/twelve-chairs-film.md
  packages/icons/src/components/Icon/__generatedIcons__/SortIcon.tsx
  packages/icons/src/components/Icon/assets/default/sort.svg
  packages/icons/src/components/Icon/assets/small/sort.svg
  packages/ui/src/components/List/HeaderCell.tsx
  packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Table/Cell.tsx
  packages/ui/src/components/Table/HeaderCell.tsx
  packages/ui/src/components/Table/HeaderRow.tsx
  packages/ui/src/components/Table/Row.tsx
  packages/ui/src/components/Table/TableContext.tsx
  packages/ui/src/components/Table/__stories__/Align.stories.tsx
  packages/ui/src/components/Table/__stories__/ColumnInfo.stories.tsx
  packages/ui/src/components/Table/__stories__/Expandable.stories.tsx
  packages/ui/src/components/Table/__stories__/Spanning.stories.tsx
  packages/ui/src/components/Table/__stories__/Style.stories.tsx
  packages/ui/src/components/Table/__stories__/WithMenu.stories.tsx
  packages/ui/src/components/Table/__stories__/index.stories.tsx
  packages/ui/src/components/Table/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Table/constants.ts
  packages/ui/src/components/Table/index.tsx
Labels: refactor

#4312 fix(TextArea): make label or aria label required
  .changeset/nasty-stingrays-retire.md
  packages/form/src/components/TextAreaField/index.tsx
  packages/ui/src/components/TextArea/index.tsx
Labels: bug

#4313 fix(SelectInputV2): to allow button on disabled option
  packages/form/src/components/SelectInputFieldV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectInputV2/Dropdown.tsx
  packages/ui/src/components/SelectInputV2/__stories__/OptionalInfo.stories.tsx
  packages/ui/src/components/SelectInputV2/__stories__/resources.tsx
  packages/ui/src/components/UnitInput/__tests__/__snapshots__/index.test.tsx.snap
Labels: enhancement

#4252 fix(Modal): minor changes
  .changeset/kind-shrimps-cry.md
  packages/ui/src/components/Modal/ModalProvider.tsx
  packages/ui/src/components/Modal/__stories__/NestedModal.stories.tsx
  packages/ui/src/components/Modal/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Modal/components/Dialog.tsx
Labels: bug

#4327 ci: automerge non marjor updates
  .github/renovate.json
Labels: enhancement, ci

#4328 fix(SelectableCard): illustration not aligned on the right when small content
  .changeset/sixty-ladybugs-know.md
  packages/ui/src/components/SelectableCard/__stories__/Illustration.stories.tsx
  packages/ui/src/components/SelectableCard/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectableCard/index.tsx
Labels: bug

#4325 feat: add interlink product icon
  .changeset/silver-carrots-push.md
  packages/icons/src/components/ProductIcon/__generatedIcons__/InterlinkProductIcon.tsx
  packages/icons/src/components/ProductIcon/__generatedIcons__/index.ts
  packages/icons/src/components/ProductIcon/assets/interlink.svg
Labels: enhancement

#4340 feat(icons): new system icon doc
  .changeset/spicy-terms-lick.md
  packages/icons/src/components/Icon/__generatedIcons__/DocIcon.tsx
  packages/icons/src/components/Icon/__generatedIcons__/DocOutlineIcon.tsx
  packages/icons/src/components/Icon/__generatedIcons__/index.ts
  packages/icons/src/components/Icon/assets/default-outline/doc.svg
  packages/icons/src/components/Icon/assets/default-solid/doc.svg
Labels: enhancement

#4330 fix(SelectInputV2): group shown when empty
  .changeset/wet-hairs-search.md
  packages/ui/src/components/SelectInputV2/Dropdown.tsx
  packages/ui/src/components/SelectInputV2/__stories__/Multiselect.stories.tsx
  packages/ui/src/components/SelectInputV2/__stories__/resources.tsx
Labels: bug

#4351 fix(Dialog): bug with scroll
  .changeset/fifty-ears-clean.md
  packages/ui/src/components/Modal/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Modal/components/Dialog.tsx
Labels: bug, hotfix

#4348 refactor: add aria label in error states and enforce one or another
  .changeset/dirty-monkeys-report.md
  packages/form/src/components/CheckboxField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/CheckboxField/__tests__/index.test.tsx
  packages/form/src/components/CheckboxField/index.tsx
  packages/form/src/components/Form/__stories__/Playground.stories.tsx
  packages/form/src/components/NumberInputFieldV2/index.tsx
  packages/form/src/components/RadioField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/RadioField/__tests__/index.test.tsx
  packages/form/src/components/RadioField/index.tsx
  packages/form/src/components/SelectInputFieldV2/index.tsx
  packages/form/src/components/SelectableCardField/__stories__/Checkbox.stories.tsx
  packages/form/src/components/SelectableCardField/__stories__/Checked.stories.tsx
  packages/form/src/components/SelectableCardField/__stories__/Playground.stories.tsx
  packages/form/src/components/SelectableCardField/__stories__/Required.stories.tsx
  packages/form/src/components/SelectableCardField/__stories__/Template.stories.tsx
  packages/form/src/components/SelectableCardField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/SelectableCardField/__tests__/index.test.tsx
  packages/form/src/components/SelectableCardField/index.tsx
  packages/form/src/components/SliderField/index.tsx
  packages/form/src/components/Submit/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/Submit/__tests__/index.test.tsx
  packages/form/src/components/TagInputField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/TagInputField/index.tsx
  packages/form/src/components/TextAreaField/index.tsx
  packages/form/src/components/TextInputFieldV2/index.tsx
  packages/form/src/components/ToggleField/index.tsx
  packages/form/src/types.ts
  packages/ui/src/components/Checkbox/index.tsx
  packages/ui/src/components/Radio/index.tsx
  packages/ui/src/components/SelectableCard/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectableCard/__tests__/index.test.tsx
  packages/ui/src/components/SelectableCard/index.tsx
  packages/ui/src/components/TagInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TagInput/index.tsx
  packages/ui/src/components/Toggle/index.tsx
  packages/ui/src/types.ts
Labels: refactor

#4354 docs: fix conversation avatar and implement real talks
  packages/plus/src/components/Conversation/__stories__/Message.stories.tsx
  packages/plus/src/components/Conversation/__stories__/Playground.stories.tsx
Labels: documentation

#4355 feat(assets): new product and system icons
  .changeset/clever-jokes-remember.md
  packages/icons/src/components/Icon/__generatedIcons__/ThumbsDownIcon.tsx
  packages/icons/src/components/Icon/__generatedIcons__/ThumbsDownOutlineIcon.tsx
  packages/icons/src/components/Icon/__generatedIcons__/ThumbsUpIcon.tsx
  packages/icons/src/components/Icon/__generatedIcons__/ThumbsUpOutlineIcon.tsx
  packages/icons/src/components/Icon/__generatedIcons__/index.ts
  packages/icons/src/components/Icon/assets/default-outline/thumbs-down.svg
  packages/icons/src/components/Icon/assets/default-outline/thumbs-up.svg
  packages/icons/src/components/Icon/assets/default-solid/thumbs-down.svg
  packages/icons/src/components/Icon/assets/default-solid/thumbs-up.svg
  packages/icons/src/components/ProductIcon/__generatedIcons__/AuditTrailProductIcon.tsx
  packages/icons/src/components/ProductIcon/__generatedIcons__/index.ts
  packages/icons/src/components/ProductIcon/assets/audit-trail.svg
Labels: enhancement

#4372 fix: add on copy prop on snippet and copy button
  .changeset/kind-eyes-grow.md
  packages/ui/src/components/CopyButton/__tests__/index.test.tsx
  packages/ui/src/components/CopyButton/index.tsx
  packages/ui/src/components/Snippet/index.tsx
Labels: enhancement

#4384 fix(CheckboxField): no working properly with children
  .changeset/forty-eyes-argue.md
  packages/form/src/components/CheckboxField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/CheckboxField/index.tsx
Labels: bug

#4373 fix(SelectInputV2): dropdown to be at least 320px
  .changeset/nice-pigs-hang.md
  packages/form/src/components/SelectInputFieldV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectInputV2/Dropdown.tsx
  packages/ui/src/components/SelectInputV2/__stories__/Playground.stories.tsx
  packages/ui/src/components/UnitInput/__tests__/__snapshots__/index.test.tsx.snap
Labels: enhancement

#4307 feat(Chip): new component
  .changeset/sharp-shoes-report.md
  packages/ui/src/components/Chip/ChipContext.tsx
  packages/ui/src/components/Chip/ChipIcon.tsx
  packages/ui/src/components/Chip/__stories__/Disabled.stories.tsx
  packages/ui/src/components/Chip/__stories__/Groups.stories.tsx.tsx
  packages/ui/src/components/Chip/__stories__/Icons.stories.tsx
  packages/ui/src/components/Chip/__stories__/Playground.stories.tsx
  packages/ui/src/components/Chip/__stories__/Size.stories.tsx
  packages/ui/src/components/Chip/__stories__/Template.stories.tsx
  packages/ui/src/components/Chip/__stories__/index.stories.tsx
  packages/ui/src/components/Chip/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Chip/__tests__/index.test.tsx
  packages/ui/src/components/Chip/index.tsx
  packages/ui/src/components/index.ts
Labels: enhancement
