Repository scaleway/ultraviolet, pull requests merged in 2024-04, with the labels that each got.

#3537 feat: new navigation
  .changeset/clean-yaks-prove.md
  packages/plus/src/components/Navigation/Navigation.tsx
  packages/plus/src/components/Navigation/NavigationContent.tsx
  packages/plus/src/components/Navigation/NavigationProvider.tsx
  packages/plus/src/components/Navigation/__stories__/Playground.stories.tsx
  packages/plus/src/components/Navigation/__stories__/assets/logo-small.svg
  packages/plus/src/components/Navigation/__stories__/assets/logo.svg
  packages/plus/src/components/Navigation/__stories__/index.stories.tsx
  packages/plus/src/components/Navigation/components/Group.tsx
  packages/plus/src/components/Navigation/components/Item.tsx
  packages/plus/src/components/Navigation/components/PinnedItems.tsx
  packages/plus/src/components/Navigation/components/Separator.tsx
  packages/plus/src/components/Navigation/constants.ts
  packages/plus/src/components/Navigation/index.ts
  packages/plus/src/components/Navigation/locales/en.ts
  packages/plus/src/components/index.ts
Labels: enhancement

#3612 feat: new product icons costManager and ManagedSearchDatabase
  .changeset/seven-donkeys-divide.md
  packages/icons/src/components/ProductIcon/Icons.tsx
  packages/icons/src/components/ProductIcon/assets/cost-manager.svg
  packages/icons/src/components/ProductIcon/assets/managed-search-database.svg
Labels: enhancement

#3619 feat(illustrations): new inference cost manager and distributed data lab
  .changeset/mighty-seas-scream.md
  packages/illustrations/src/__stories__/List.tsx
  packages/illustrations/src/products/costManager/cost-manager-content.webp
  packages/illustrations/src/products/costManager/cost-manager-keyvisual.webp
  packages/illustrations/src/products/costManager/cost-manager-original.webp
  packages/illustrations/src/products/costManager/cost-manager-wire.svg
  packages/illustrations/src/products/costManager/index.ts
  packages/illustrations/src/products/distributedDataLab/distributed-data-lab-content.webp
  packages/illustrations/src/products/distributedDataLab/distributed-data-lab-keyvisual.webp
  packages/illustrations/src/products/distributedDataLab/distributed-data-lab-original.webp
  packages/illustrations/src/products/distributedDataLab/distributed-data-lab-wire.svg
  packages/illustrations/src/products/distributedDataLab/index.ts
  packages/illustrations/src/products/index.ts
  packages/illustrations/src/products/inference/index.ts
  packages/illustrations/src/products/inference/inference-content.webp
  packages/illustrations/src/products/inference/inference-keyvisual.webp
  packages/illustrations/src/products/inference/inference-original.webp
  packages/illustrations/src/products/inference/inference-wire.svg
Labels: enhancement

#3618 refactor(KeyValueField): new spacing and text input v2 usage
  .changeset/tiny-cows-smile.md
  packages/form/src/components/KeyValueField/__stories__/Environnement.stories.tsx
  packages/form/src/components/KeyValueField/__stories__/Playground.stories.tsx
  packages/form/src/components/KeyValueField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/KeyValueField/index.tsx
Labels: refactor

#3626 fix(Navigation): some minor fixes
  .changeset/bright-clocks-compete.md
  .changeset/good-crabs-marry.md
  packages/plus/src/components/Navigation/components/Item.tsx
  packages/ui/src/components/Expandable/index.tsx
Labels: bug

#3627 feat(CategoryIcon): new state disabled and variant primary
  .changeset/five-rats-unite.md
  .changeset/late-books-shop.md
  packages/icons/src/components/CategoryIcon/__stories__/List.stories.tsx
  packages/icons/src/components/CategoryIcon/index.tsx
  packages/plus/src/components/Navigation/__stories__/Playground.stories.tsx
  packages/plus/src/components/Navigation/components/Item.tsx
  packages/themes/src/themes/console/dark.ts
  packages/themes/src/themes/console/darker.ts
  packages/themes/src/themes/console/light.ts
Labels: enhancement

#3642 fix(Navigation): correct color on hover for weak text
  .changeset/short-toes-relax.md
  packages/plus/src/components/Navigation/components/Item.tsx
Labels: bug

#3643 fix(Stepper): clean null or undefined children before render
  .changeset/honest-moles-notice.md
  packages/ui/src/components/Stepper/index.tsx
Labels: bug

#3645 fix(icons): adds application integration category icon
  .changeset/sweet-clocks-play.md
  packages/icons/src/components/CategoryIcon/Icons.tsx
  packages/icons/src/components/CategoryIcon/assets/application-integration.svg
Labels: enhancement

#3648 feat(ProgressBar): new sentiment danger
  .changeset/sweet-donuts-promise.md
  packages/ui/src/components/ProgressBar/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/ProgressBar/index.tsx
Labels: enhancement

#3556 feat(List): onSelectedChange
  .changeset/giant-eyes-hide.md
  packages/ui/src/components/List/ListContext.tsx
  packages/ui/src/components/List/__stories__/OnSelectedChange.stories.tsx
  packages/ui/src/components/List/__stories__/index.stories.tsx
  packages/ui/src/components/List/index.tsx
Labels: enhancement

#3649 fix(Navigation): category icon variant on collasped version
  .changeset/tricky-beans-compare.md
  packages/plus/src/components/Navigation/components/Item.tsx
Labels: bug

#3653 fix(Navigation): category icon on active and id prop
  .changeset/eight-ants-kneel.md
  packages/plus/src/components/Navigation/Navigation.tsx
  packages/plus/src/components/Navigation/NavigationContent.tsx
  packages/plus/src/components/Navigation/components/Item.tsx
Labels: enhancement

#3656 fix(Popup): to correctly set portal taget prop
  .changeset/lazy-squids-press.md
  packages/ui/src/components/Popup/index.tsx
Labels: bug

#3631 refactor(Menu): new style and behavior
  .changeset/tame-lizards-deliver.md
  .changeset/warm-mails-check.md
  packages/plus/src/components/Navigation/NavigationContent.tsx
  packages/plus/src/components/Navigation/components/Item.tsx
  packages/ui/src/components/MenuV2/Group.tsx
  packages/ui/src/components/MenuV2/Item.tsx
  packages/ui/src/components/MenuV2/__stories__/Active.stories.tsx
  packages/ui/src/components/MenuV2/__stories__/Group.stories.tsx
  packages/ui/src/components/MenuV2/__stories__/Playground.stories.tsx
  packages/ui/src/components/MenuV2/__stories__/Sentiments.stories.tsx
  packages/ui/src/components/MenuV2/__stories__/TriggerMethod.stories.tsx
  packages/ui/src/components/MenuV2/__stories__/index.stories.tsx
  packages/ui/src/components/MenuV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/MenuV2/__tests__/index.test.tsx
  packages/ui/src/components/MenuV2/index.tsx
  packages/ui/src/components/Popover/index.tsx
  packages/ui/src/components/Popup/__tests__/__tests__/index.test.tsx
  packages/ui/src/components/Popup/index.tsx
  packages/ui/src/components/SelectInput/__stories__/Playground.stories.tsx
  packages/ui/src/components/Tabs/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Tooltip/__tests__/index.test.tsx
  packages/ui/src/components/Tooltip/index.tsx
Labels: enhancement

#3673 fix(MenuV2): to have correct height set
  .changeset/new-fireants-exercise.md
  packages/ui/src/components/MenuV2/__stories__/LongMenu.stories.tsx
  packages/ui/src/components/MenuV2/__stories__/index.stories.tsx
  packages/ui/src/components/MenuV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/MenuV2/index.tsx
  packages/ui/src/components/Tabs/__tests__/__snapshots__/index.test.tsx.snap
Labels: bug

#3680 fix: various illustration bug
  .changeset/neat-buses-heal.md
  packages/illustrations/src/various/documentation/account-billing.svg
  packages/illustrations/src/various/documentation/generic.svg
Labels: bug

#3672 fix: workaround for autofocus problem
  packages/ui/src/components/Modal/__stories__/AutoFocus.stories.tsx
  packages/ui/src/components/Modal/__stories__/FunctionChildren.stories.tsx
  packages/ui/src/components/Modal/__stories__/index.stories.tsx
Labels: bug

#3678 chore: unify eslint config in one
  .eslintrc
  packages/form/.eslintrc.cjs
  packages/icons/.eslintrc.cjs
  packages/illustrations/.eslintrc.cjs
  packages/illustrations/package.json
  packages/plus/.eslintrc.cjs
  packages/themes/.eslintrc.cjs
  packages/ui/.eslintrc.cjs
  pnpm-lock.yaml
Labels: enhancement

#3688 feat(Icon): new product icons and new icon
  .changeset/wicked-ligers-smash.md
  packages/icons/src/components/Icon/Icons.tsx
  packages/icons/src/components/Icon/SmallIcons.tsx
  packages/icons/src/components/Icon/assets/default-outline/pen.svg
  packages/icons/src/components/Icon/assets/default-solid/pen.svg
  packages/icons/src/components/Icon/assets/small-outline/pen.svg
  packages/icons/src/components/Icon/assets/small-solid/pen.svg
  packages/icons/src/components/ProductIcon/Icons.tsx
  packages/icons/src/components/ProductIcon/assets/account-experience.svg
  packages/icons/src/components/ProductIcon/assets/saving-plan.svg
Labels: enhancement

#3651 feat(SelectInputV2): new select input
  .changeset/strong-fishes-press.md
  packages/ui/src/__stories__/migrations/MigrationSelectInputV2.stories.mdx
  packages/ui/src/components/Checkbox/index.tsx
  packages/ui/src/components/SelectInput/__stories__/index.stories.tsx
  packages/ui/src/components/SelectInput/index.tsx
  packages/ui/src/components/SelectInputV2/Dropdown.tsx
  packages/ui/src/components/SelectInputV2/DropdownOption.tsx
  packages/ui/src/components/SelectInputV2/SearchBarDropdown.tsx
  packages/ui/src/components/SelectInputV2/SelectBar.tsx
  packages/ui/src/components/SelectInputV2/SelectInputProvider.tsx
  packages/ui/src/components/SelectInputV2/__stories__/EmptyState.stories.tsx
  packages/ui/src/components/SelectInputV2/__stories__/Footer.stories.tsx
  packages/ui/src/components/SelectInputV2/__stories__/Grouped.stories.tsx
  packages/ui/src/components/SelectInputV2/__stories__/IsLoading.stories.tsx
  packages/ui/src/components/SelectInputV2/__stories__/LoadMore.stories.tsx
  packages/ui/src/components/SelectInputV2/__stories__/Multiselect.stories.tsx
  packages/ui/src/components/SelectInputV2/__stories__/OnChange.stories.tsx
  packages/ui/src/components/SelectInputV2/__stories__/OptionalInfo.stories.tsx
  packages/ui/src/components/SelectInputV2/__stories__/Playground.stories.tsx
  packages/ui/src/components/SelectInputV2/__stories__/SelectAll.stories.tsx
  packages/ui/src/components/SelectInputV2/__stories__/Template.stories.tsx
  packages/ui/src/components/SelectInputV2/__stories__/index.stories.tsx
  packages/ui/src/components/SelectInputV2/__stories__/resources.tsx
  packages/ui/src/components/SelectInputV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectInputV2/__tests__/index.test.tsx
  packages/ui/src/components/SelectInputV2/index.tsx
  packages/ui/src/components/SelectInputV2/resourceExamples.tsx
  packages/ui/src/components/SelectInputV2/types.ts
  packages/ui/src/components/TextInputV2/index.tsx
  packages/ui/src/components/index.ts
Labels: enhancement

#3696 ci(renovate): group testing library update together
  .github/renovate.json
Labels: ci

#3693 fix: change navitem text color
  .changeset/tall-seahorses-grow.md
  packages/plus/src/components/Navigation/components/Item.tsx
Labels: enhancement

#3704 fix(Menu): to have smaller debounce delay
  .changeset/dry-icons-punch.md
  packages/ui/src/components/MenuV2/index.tsx
Labels: enhancement

#3707 fix(Navigation): export missing navigation provider
  .changeset/stale-sloths-smile.md
  packages/plus/src/components/index.ts
Labels: bug

#3702 feat: selectInputFieldV2 and fixes selectInputV2
  .changeset/mean-planets-doubt.md
  packages/form/src/components/Form/__stories__/Playground.stories.tsx
  packages/form/src/components/SelectInputField/index.tsx
  packages/form/src/components/SelectInputFieldV2/__stories__/Multiple.stories.tsx
  packages/form/src/components/SelectInputFieldV2/__stories__/Playground.stories.tsx
  packages/form/src/components/SelectInputFieldV2/__stories__/Template.stories.tsx
  packages/form/src/components/SelectInputFieldV2/__stories__/index.stories.tsx
  packages/form/src/components/SelectInputFieldV2/__stories__/resources.tsx
  packages/form/src/components/SelectInputFieldV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/SelectInputFieldV2/__tests__/index.test.tsx
  packages/form/src/components/SelectInputFieldV2/__tests__/resources.tsx
  packages/form/src/components/SelectInputFieldV2/index.tsx
  packages/form/src/components/index.ts
  packages/ui/src/components/SelectInputV2/Dropdown.tsx
  packages/ui/src/components/SelectInputV2/DropdownOption.tsx
  packages/ui/src/components/SelectInputV2/SelectBar.tsx
  packages/ui/src/components/SelectInputV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectInputV2/__tests__/index.test.tsx
  packages/ui/src/components/SelectInputV2/__tests__/resources.tsx
  packages/ui/src/components/SelectInputV2/index.tsx
Labels: enhancement

#3723 ci: fix codecov to only check ultraviolet ui
  codecov.yml
Labels: ci

#3722 fix(SelectInputV2): use string or string[] as value prop instead of w…
  .changeset/fluffy-windows-dance.md
  .changeset/real-turtles-shop.md
  packages/form/src/components/SelectInputFieldV2/__stories__/Multiple.stories.tsx
  packages/form/src/components/SelectInputFieldV2/index.tsx
  packages/ui/src/components/SelectInputV2/Dropdown.tsx
  packages/ui/src/components/SelectInputV2/SearchBarDropdown.tsx
  packages/ui/src/components/SelectInputV2/SelectBar.tsx
  packages/ui/src/components/SelectInputV2/SelectInputProvider.tsx
  packages/ui/src/components/SelectInputV2/__stories__/Multiselect.stories.tsx
  packages/ui/src/components/SelectInputV2/__tests__/index.test.tsx
  packages/ui/src/components/SelectInputV2/findOptionInOptions.ts
  packages/ui/src/components/SelectInputV2/index.tsx
  packages/ui/src/components/SelectInputV2/types.ts
Labels: enhancement

#3725 feat(SelectInputV2): support typing on value and onChange based on mu…
  .changeset/clean-laws-dance.md
  .changeset/clever-turtles-lick.md
  packages/form/src/components/SelectInputFieldV2/index.tsx
  packages/ui/src/components/SelectInputV2/Dropdown.tsx
  packages/ui/src/components/SelectInputV2/SearchBarDropdown.tsx
  packages/ui/src/components/SelectInputV2/SelectBar.tsx
  packages/ui/src/components/SelectInputV2/SelectInputProvider.tsx
  packages/ui/src/components/SelectInputV2/__stories__/OnChange.stories.tsx
  packages/ui/src/components/SelectInputV2/index.tsx
Labels: enhancement

#3730 fix(Popup): new prop and improve initial positioning of the popup
  .changeset/strange-years-fly.md
  packages/form/src/components/SelectInputFieldV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/MenuV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/MenuV2/index.tsx
  packages/ui/src/components/Popover/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Popover/index.tsx
  packages/ui/src/components/Popup/helpers.ts
  packages/ui/src/components/Popup/index.tsx
  packages/ui/src/components/SelectInputV2/SearchBarDropdown.tsx
  packages/ui/src/components/SelectInputV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Tabs/__tests__/__snapshots__/index.test.tsx.snap
Labels: enhancement
