Repository scaleway/ultraviolet, pull requests merged in 2024-06, with the labels that each got.

#3858 fix(SelectInputV2): description in row should be baseline aligned
  .changeset/late-phones-smoke.md
  packages/ui/src/components/SelectInputV2/DropdownOption.tsx
  packages/ui/src/components/SelectInputV2/__tests__/__snapshots__/index.test.tsx.snap
Labels: bug

#3862 feat: new product illustration
  .changeset/purple-spoons-jog.md
  packages/illustrations/src/products/accountExperience/account-experience-content.webp
  packages/illustrations/src/products/accountExperience/account-experience-keyvisual.webp
  packages/illustrations/src/products/accountExperience/account-experience-original.webp
  packages/illustrations/src/products/accountExperience/account-experience-wire.svg
  packages/illustrations/src/products/accountExperience/index.ts
  packages/illustrations/src/products/index.ts
Labels: enhancement

#3859 fix: duplicated semicolon in css tokens
  scripts/create-css-variables.mjs
Labels: bug

#3873 ci: fix ci not running on release pr
  .github/workflows/release.yml
Labels: ci

#3874 refactor(ts): better typing on avatar, tag input, verification code
  .changeset/yellow-panthers-sort.md
  packages/ui/src/components/Avatar/index.tsx
  packages/ui/src/components/List/__tests__/index.test.tsx
  packages/ui/src/components/Table/__tests__/index.test.tsx
  packages/ui/src/components/TagInput/index.tsx
  packages/ui/src/components/VerificationCode/index.tsx
Labels: refactor

#3884 ci: ignore utils packages changeset
  .changeset/config.json
Labels: ci

#3872 feat(NumberInputV2): controls prop
  .changeset/olive-plants-impress.md
  packages/form/src/components/NumberInputFieldV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/NumberInputFieldV2/index.tsx
  packages/plus/src/components/EstimateCost/Components/NumberInput.tsx
  packages/plus/src/components/EstimateCost/__stories__/Design.stories.tsx
  packages/plus/src/components/EstimateCost/__stories__/GlobalDiscount.stories.tsx
  packages/plus/src/components/EstimateCost/__stories__/Item.stories.tsx
  packages/plus/src/components/EstimateCost/__stories__/LocalDiscount.stories.tsx
  packages/plus/src/components/EstimateCost/__stories__/NumberInput.stories.tsx
  packages/plus/src/components/EstimateCost/__stories__/Region.stories.tsx
  packages/plus/src/components/EstimateCost/__stories__/Unit.stories.tsx
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Stepper.test.tsx.snap
  packages/ui/package.json
  packages/ui/src/components/NumberInputV2/__stories__/Controls.stories.tsx
  packages/ui/src/components/NumberInputV2/__stories__/index.stories.tsx
  packages/ui/src/components/NumberInputV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/NumberInputV2/__tests__/index.test.tsx
  packages/ui/src/components/NumberInputV2/index.tsx
Labels: enhancement

#3885 feat: new component search input
  .changeset/thirty-crews-yell.md
  packages/ui/src/components/SearchInput/__stories__/Playground.stories.tsx
  packages/ui/src/components/SearchInput/__stories__/Template.stories.tsx
  packages/ui/src/components/SearchInput/__stories__/index.stories.tsx
  packages/ui/src/components/SearchInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SearchInput/__tests__/index.test.tsx
  packages/ui/src/components/SearchInput/index.tsx
  packages/ui/src/components/SearchInput/types.ts
  packages/ui/src/components/index.ts
Labels: enhancement

#3876 fix(SelectInputV2): change data-testid place for easier unit tests
  .changeset/cyan-fireants-do.md
  packages/form/src/components/SelectInputFieldV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/SelectInputFieldV2/__tests__/index.test.tsx
  packages/form/src/components/UnitInputField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/UnitInputField/__tests__/index.test.tsx
  packages/ui/src/components/SelectInputV2/SelectBar.tsx
  packages/ui/src/components/SelectInputV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectInputV2/__tests__/index.test.tsx
  packages/ui/src/components/SelectInputV2/index.tsx
  packages/ui/src/components/UnitInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/UnitInput/__tests__/index.test.tsx
Labels: enhancement

#3893 ci: add new action checking format using biome ci
  .github/workflows/ci.yml
  .storybook/components/DocsContainer.tsx
  biome.json
  package.json
  tsconfig.json
Labels: ci

#3892 fix(SelectInputV2): label to have correct color
  .changeset/funny-sloths-divide.md
  packages/ui/src/components/SelectInputV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectInputV2/index.tsx
Labels: bug

#3909 fix(Icon): locker icon solid
  .changeset/friendly-tigers-compare.md
  packages/icons/src/components/Icon/assets/default-solid/lock.svg
  packages/ui/src/components/Avatar/__tests__/__snapshots__/index.test.tsx.snap
Labels: bug

#3900 fix(NumberInputV2): handles float and fix onBlur
  .changeset/stale-jars-compare.md
  packages/form/src/components/NumberInputFieldV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Stepper.test.tsx.snap
  packages/ui/src/components/NumberInputV2/__stories__/Step.stories.tsx
  packages/ui/src/components/NumberInputV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/NumberInputV2/__tests__/index.test.tsx
  packages/ui/src/components/NumberInputV2/index.tsx
Labels: bug

#3864 fix: navigation loses focus
  .changeset/sweet-ties-wink.md
  packages/plus/src/components/Navigation/components/Item.tsx
Labels: bug

#3896 feat(tokens): new elevation tokens
  packages/themes/public/style/dark.css
  packages/themes/public/style/darker.css
  packages/themes/public/style/light.css
  packages/themes/src/themes/console/dark.ts
  packages/themes/src/themes/console/darker.ts
  packages/themes/src/themes/console/light.ts
  scripts/figma-synchronise-tokens.mjs
Labels: enhancement

#3913 fix(Stepper): animation
  .changeset/beige-planes-build.md
  packages/ui/src/components/Stepper/Step.tsx
  packages/ui/src/components/Stepper/__stories__/Example.stories.tsx
  packages/ui/src/components/Stepper/__stories__/WithAnimation.stories.tsx
  packages/ui/src/components/Stepper/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Stepper/__tests__/index.test.tsx
  packages/ui/src/components/Stepper/index.tsx
Labels: bug

#3908 fix(TextInputV2): width with error prop
  .changeset/lemon-pots-try.md
  packages/form/src/components/DateField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/TextInputFieldV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SearchInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectInputV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TextInputV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TextInputV2/index.tsx
Labels: bug

#3919 fix(List): expand button to have correct sizing
  .changeset/twelve-geckos-cross.md
  packages/ui/src/components/List/Cell.tsx
  packages/ui/src/components/List/Row.tsx
  packages/ui/src/components/List/__stories__/Example.stories.tsx
  packages/ui/src/components/List/__stories__/PreventClick.stories.tsx
  packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/List/__tests__/index.test.tsx
  packages/ui/src/components/List/constants.tsx
Labels: bug
