Repository scaleway/ultraviolet, pull requests merged in 2024-09, with the labels that each got.

#4167 feat: update design of documentation pages
  .storybook/assets/brand-background.png
  .storybook/components/DocsContainer.tsx
  .storybook/components/Page.tsx
  .storybook/components/globalStyle.ts
  .storybook/preview.tsx
  packages/ui/src/__stories__/components/ThemeWrapper.tsx
  packages/ui/src/components/Button/__stories__/Template.stories.tsx
Labels: documentation, enhancement

#4172 refactor: improve accessibility focus on selectable card
  .changeset/large-cycles-visit.md
  packages/form/src/components/SelectableCardField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/SelectableCardField/__tests__/index.test.tsx
  packages/form/src/components/SelectableCardGroupField/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Radio/index.tsx
  packages/ui/src/components/SelectableCard/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectableCard/__tests__/index.test.tsx
  packages/ui/src/components/SelectableCard/index.tsx
  packages/ui/src/components/SelectableCardGroup/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SwitchButton/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SwitchButton/index.tsx
Labels: accessibility

#4202 fix(NumberInputFieldV2): to validate or not depending if step is integer
  .changeset/many-bottles-exercise.md
  examples/next-login/src/constants.tsx
  packages/form/src/components/NumberInputFieldV2/__stories__/Required.stories.tsx
  packages/form/src/components/NumberInputFieldV2/index.tsx
  packages/form/src/mocks/mockErrors.ts
  packages/form/src/types.ts
  packages/form/src/validators/isInteger.ts
  packages/ui/src/__stories__/Tools/ThemeGenerator/index.tsx
  utils/test/src/vitest/helpers/index.tsx
Labels: enhancement

#4213 docs(Icons): improve storybook documentation
  packages/icons/src/components/CategoryIcon/__stories__/List.stories.tsx
  packages/icons/src/components/Icon/__stories__/Name.stories.tsx
  packages/icons/src/components/ProductIcon/__stories__/List.stories.tsx
Labels: documentation

#4218 fix(Alert): take full with for link case
  .changeset/many-grapes-rule.md
  packages/form/src/components/SubmitErrorAlert/__tests__/__snapshots__/index.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Regular.test.tsx.snap
  packages/ui/src/components/Alert/__stories__/Link.stories.tsx
  packages/ui/src/components/Alert/__stories__/index.stories.tsx
  packages/ui/src/components/Alert/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Alert/index.tsx
Labels: enhancement

#4219 fix(FAQ): product icon not working properly
  .changeset/shiny-crabs-visit.md
  packages/plus/src/components/FAQ/__tests__/__snapshots__/index.test.tsx.snap
  packages/plus/src/components/FAQ/index.tsx
Labels: bug

#4223 fix(Snippet): to respect carriage return
  .changeset/fuzzy-jokes-press.md
  packages/ui/src/components/Snippet/__stories__/LongMultiline.stories.tsx
  packages/ui/src/components/Snippet/__stories__/LongMultilineExpanded.stories.tsx
  packages/ui/src/components/Snippet/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Snippet/index.tsx
Labels: bug

#4226 feat(ContentCard): content card custom heading tag
  .changeset/honest-mayflies-lay.md
  packages/plus/src/components/ContentCard/__tests__/__snapshots__/index.test.tsx.snap
  packages/plus/src/components/ContentCard/__tests__/index.test.tsx
  packages/plus/src/components/ContentCard/index.tsx
Labels: accessibility

#4205 feat(ProgressBar): new props
  .changeset/light-ears-shop.md
  packages/ui/src/components/ProgressBar/__stories__/Direction.stories.tsx
  packages/ui/src/components/ProgressBar/__stories__/Label.stories.tsx
  packages/ui/src/components/ProgressBar/__stories__/ShowProgress.stories.tsx
  packages/ui/src/components/ProgressBar/__stories__/index.stories.tsx
  packages/ui/src/components/ProgressBar/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/ProgressBar/__tests__/index.test.tsx
  packages/ui/src/components/ProgressBar/index.tsx
Labels: enhancement

#4231 feat(Icon): leaf icon
  .changeset/soft-maps-perform.md
  packages/icons/src/components/Icon/__generatedIcons__/LeafIcon.tsx
  packages/icons/src/components/Icon/__generatedIcons__/LeafOutlineIcon.tsx
  packages/icons/src/components/Icon/__generatedIcons__/index.ts
  packages/icons/src/components/Icon/assets/default-outline/leaf.svg
  packages/icons/src/components/Icon/assets/default-solid/leaf.svg
  packages/icons/src/components/Icon/assets/small-outline/leaf.svg
  packages/icons/src/components/Icon/assets/small-solid/leaf.svg
Labels: enhancement

#4221 feat(Card): new prop subHeader
  .changeset/real-walls-own.md
  packages/ui/src/components/Card/__stories__/Active.stories.tsx
  packages/ui/src/components/Card/__stories__/AdvancedHeader.stories.tsx
  packages/ui/src/components/Card/__stories__/Disabled.stories.tsx
  packages/ui/src/components/Card/__stories__/SubHeader.stories.tsx
  packages/ui/src/components/Card/__stories__/index.stories.tsx
  packages/ui/src/components/Card/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Card/__tests__/index.test.tsx
  packages/ui/src/components/Card/index.tsx
Labels: enhancement

#4227 docs: fix storybook headers
  .storybook/components/DocsContainer.tsx
  .storybook/components/globalStyle.ts
Labels: bug, documentation

#4236 feat(Icons): logo icons
  .changeset/proud-hounds-walk.md
  packages/icons/package.json
  packages/icons/src/components/Logo/Icon.tsx
  packages/icons/src/components/Logo/__generatedIcons__/GmailLogo.tsx
  packages/icons/src/components/Logo/__generatedIcons__/GoogleLogo.tsx
  packages/icons/src/components/Logo/__generatedIcons__/MicrosoftLogo.tsx
  packages/icons/src/components/Logo/__generatedIcons__/OutlookLogo.tsx
  packages/icons/src/components/Logo/__generatedIcons__/index.ts
  packages/icons/src/components/Logo/__stories__/Documentation.md
  packages/icons/src/components/Logo/__stories__/List.stories.tsx
  packages/icons/src/components/Logo/__stories__/Playground.stories.tsx
  packages/icons/src/components/Logo/__stories__/Sizes.stories.tsx
  packages/icons/src/components/Logo/__stories__/Template.stories.tsx
  packages/icons/src/components/Logo/__stories__/index.stories.tsx
  packages/icons/src/components/Logo/assets/gmail.svg
  packages/icons/src/components/Logo/assets/google.svg
  packages/icons/src/components/Logo/assets/microsoft.svg
  packages/icons/src/components/Logo/assets/outlook.svg
  packages/icons/src/components/Logo/index.ts
  packages/icons/vite.config.ts
  scripts/generate-icons-file.ts
Labels: enhancement

#4248 fix: bug fixes on selectinputV2
  .changeset/stupid-bats-brake.md
  packages/form/src/components/SelectInputFieldV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/UnitInputField/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectInputV2/Dropdown.tsx
  packages/ui/src/components/SelectInputV2/DropdownOption.tsx
  packages/ui/src/components/SelectInputV2/SelectBar.tsx
  packages/ui/src/components/SelectInputV2/__stories__/EmptyState.stories.tsx
  packages/ui/src/components/SelectInputV2/__stories__/Grouped.stories.tsx
  packages/ui/src/components/SelectInputV2/__stories__/resources.tsx
  packages/ui/src/components/UnitInput/__tests__/__snapshots__/index.test.tsx.snap
Labels: bug

#4214 feat(selectableCard): illustrations and icons
  .changeset/neat-emus-try.md
  packages/form/src/components/SelectableCardField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/SelectableCardGroupField/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectableCard/__stories__/Illustration.stories.tsx
  packages/ui/src/components/SelectableCard/__stories__/index.stories.tsx
  packages/ui/src/components/SelectableCard/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectableCard/__tests__/illustrationTest.svg
  packages/ui/src/components/SelectableCard/__tests__/index.test.tsx
  packages/ui/src/components/SelectableCard/index.tsx
  packages/ui/src/components/SelectableCardGroup/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SwitchButton/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/types.ts
Labels: enhancement

#4249 feat(Snippet): rows and scroll
  .changeset/light-ligers-jog.md
  packages/ui/src/components/CopyButton/__stories__/Bordered.stories.tsx
  packages/ui/src/components/CopyButton/__stories__/NoBorder.stories.tsx
  packages/ui/src/components/CopyButton/__stories__/index.stories.tsx
  packages/ui/src/components/Snippet/__stories__/NoExpandable.stories.tsx
  packages/ui/src/components/Snippet/__stories__/Rows.stories.tsx
  packages/ui/src/components/Snippet/__stories__/index.stories.tsx
  packages/ui/src/components/Snippet/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Snippet/__tests__/index.test.tsx
  packages/ui/src/components/Snippet/index.tsx
Labels: enhancement

#4230 feat(themes): optimization of bundle size barrel file
  .changeset/fuzzy-singers-own.md
  packages/themes/README.md
  packages/themes/package.json
  packages/themes/src/index.ts
  packages/themes/src/themes/console/dark/__generated__/index.ts
  packages/themes/src/themes/console/dark/index.ts
  packages/themes/src/themes/console/darker/__generated__/index.ts
  packages/themes/src/themes/console/darker/index.ts
  packages/themes/src/themes/console/deprecated/dark.ts
  packages/themes/src/themes/console/deprecated/darker.ts
  packages/themes/src/themes/console/deprecated/light.ts
  packages/themes/src/themes/console/index.ts
  packages/themes/src/themes/console/light/__generated__/index.ts
  packages/themes/src/themes/console/light/index.ts
  packages/themes/src/themes/index.ts
  scripts/figma-synchronise-tokens.mjs
Labels: enhancement

#4274 fix(Link): remove flexbox allowing text to break
  .changeset/itchy-planes-sip.md
  packages/ui/src/components/Alert/__stories__/Link.stories.tsx
  packages/ui/src/components/Banner/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Breadcrumbs/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/EmptyState/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/GlobalAlert/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Link/__stories__/Examples.stories.tsx
  packages/ui/src/components/Link/__stories__/index.stories.tsx
  packages/ui/src/components/Link/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Link/index.tsx
  packages/ui/src/components/Tabs/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Toaster/__tests__/__snapshots__/index.test.tsx.snap
Labels: bug

#4285 fix(TextArea): add new props for allowing submit on enter pressed
  .changeset/perfect-balloons-tell.md
  .changeset/quiet-files-camp.md
  packages/form/src/components/TextAreaField/__stories__/SubmitOnEnter.stories.tsx
  packages/form/src/components/TextAreaField/__stories__/index.stories.tsx
  packages/form/src/components/TextAreaField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/TextAreaField/__tests__/index.test.tsx
  packages/form/src/components/TextAreaField/index.tsx
  packages/ui/src/components/TextArea/index.tsx
Labels: enhancement

#4291 fix(SelectInputV2): resize issue in a modal
  .changeset/dirty-planes-breathe.md
  packages/ui/src/components/SelectInputV2/Dropdown.tsx
Labels: bug, hotfix
