Repository scaleway/ultraviolet, pull requests merged in 2024-03, with the labels that each got.

#3514 fix(TextInputV2): add auto complete and missing props
  .changeset/seven-mangos-end.md
  .changeset/tiny-geckos-happen.md
  packages/form/src/components/TextInputFieldV2/index.tsx
  packages/ui/src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TextInputV2/index.tsx
Labels: bug, enhancement

#3524 feat: new component selectablecardgroup for ui and form
  .changeset/empty-islands-itch.md
  .changeset/great-elephants-attack.md
  packages/form/src/components/SelectableCardGroupField/__stories__/Checkbox.tsx
  packages/form/src/components/SelectableCardGroupField/__stories__/Error.stories.tsx
  packages/form/src/components/SelectableCardGroupField/__stories__/Playground.stories.tsx
  packages/form/src/components/SelectableCardGroupField/__stories__/Required.stories.tsx
  packages/form/src/components/SelectableCardGroupField/__stories__/Template.stories.tsx
  packages/form/src/components/SelectableCardGroupField/__stories__/index.stories.tsx
  packages/form/src/components/SelectableCardGroupField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/SelectableCardGroupField/__tests__/index.spec.tsx
  packages/form/src/components/SelectableCardGroupField/index.tsx
  packages/form/src/components/index.ts
  packages/ui/src/components/SelectableCardGroup/__stories__/Checkbox.tsx
  packages/ui/src/components/SelectableCardGroup/__stories__/Columns.stories.tsx
  packages/ui/src/components/SelectableCardGroup/__stories__/Error.stories.tsx
  packages/ui/src/components/SelectableCardGroup/__stories__/Examples.stories.tsx
  packages/ui/src/components/SelectableCardGroup/__stories__/Helper.stories.tsx
  packages/ui/src/components/SelectableCardGroup/__stories__/Playground.stories.tsx
  packages/ui/src/components/SelectableCardGroup/__stories__/Template.stories.tsx
  packages/ui/src/components/SelectableCardGroup/__stories__/index.stories.tsx
  packages/ui/src/components/SelectableCardGroup/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectableCardGroup/__tests__/index.test.tsx
  packages/ui/src/components/SelectableCardGroup/index.tsx
  packages/ui/src/components/index.ts
Labels: enhancement

#3535 feat: new various illustrations
  .changeset/lazy-pears-attend.md
  packages/illustrations/src/__stories__/List.tsx
  packages/illustrations/src/various/documentation/account-billing.svg
  packages/illustrations/src/various/documentation/generic.svg
  packages/illustrations/src/various/documentation/index.ts
  packages/illustrations/src/various/documentation/learning.svg
  packages/illustrations/src/various/documentation/write-community.svg
  packages/illustrations/src/various/index.ts
Labels: enhancement

#3533 fix(MenuV2.Item): item full width
  .changeset/olive-readers-chew.md
  packages/ui/src/components/MenuV2/Item.tsx
  packages/ui/src/components/MenuV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Tabs/__tests__/__snapshots__/index.test.tsx.snap
Labels: bug

#3542 fix: add container id to toaster and notification
  .changeset/tender-cats-mix.md
  packages/ui/src/components/Notification/__stories__/ContainerId.tsx
  packages/ui/src/components/Notification/__stories__/index.stories.tsx
  packages/ui/src/components/Notification/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Notification/__tests__/index.test.tsx
  packages/ui/src/components/Notification/index.tsx
  packages/ui/src/components/Toaster/__stories__/ContainerId.tsx
  packages/ui/src/components/Toaster/__stories__/index.stories.tsx
  packages/ui/src/components/Toaster/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Toaster/__tests__/index.test.tsx
  packages/ui/src/components/Toaster/index.tsx
Labels: enhancement

#3546 fix(illustrations): missing export in package json
  .changeset/strange-peaches-do.md
  packages/illustrations/package.json
Labels: hotfix

#3549 fix(EstimateCost): forward hideFromOverlay in Region
  .changeset/clean-guests-stare.md
  packages/plus/src/components/EstimateCost/Components/Region.tsx
Labels: enhancement

#3557 feat: new product icon "inference"
  .changeset/calm-pens-dance.md
  packages/icons/src/components/ProductIcon/Icons.tsx
  packages/icons/src/components/ProductIcon/assets/inference.svg
Labels: enhancement

#3558 fix(TagList): add popover placement on tag list
  .changeset/eight-books-build.md
  packages/ui/src/components/TagList/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TagList/__tests__/index.test.tsx
  packages/ui/src/components/TagList/index.tsx
Labels: enhancement

#3565 fix(TextInputV2): lower case readonly data attribute
  .changeset/eighty-rocks-pull.md
  packages/form/src/components/DateField/__tests__/__snapshots__/index.tsx.snap
  packages/form/src/components/TextInputFieldV2/__tests__/__snapshots__/index.spec.tsx.snap
  packages/ui/src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TextInputV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TextInputV2/index.tsx
Labels: bug

#3580 feat(icons): new system icon pin
  .changeset/tiny-foxes-attack.md
  packages/icons/src/components/CategoryIcon/Icons.tsx
  packages/icons/src/components/CategoryIcon/assets/pin.svg
  packages/icons/src/components/Icon/Icons.tsx
  packages/icons/src/components/Icon/SmallIcons.tsx
  packages/icons/src/components/Icon/assets/default-outline/pin.svg
  packages/icons/src/components/Icon/assets/default-solid/pin.svg
  packages/icons/src/components/Icon/assets/small-outline/pin.svg
  packages/icons/src/components/Icon/assets/small-solid/pin.svg
Labels: enhancement

#3581 feat(Expandable): add animation duration
  .changeset/poor-coats-develop.md
  packages/ui/src/components/Expandable/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Expandable/__tests__/index.test.tsx
  packages/ui/src/components/Expandable/index.tsx
Labels: enhancement

#3584 feat(Separator): change border color to weak
  .changeset/violet-oranges-warn.md
  packages/ui/src/components/Separator/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Separator/index.tsx
Labels: enhancement

#3586 feat(Icon): new icon unpin
  .changeset/six-zoos-nail.md
  packages/icons/src/components/Icon/Icons.tsx
  packages/icons/src/components/Icon/SmallIcons.tsx
  packages/icons/src/components/Icon/assets/default-outline/unpin.svg
  packages/icons/src/components/Icon/assets/default-solid/unpin.svg
  packages/icons/src/components/Icon/assets/small-outline/unpin.svg
  packages/icons/src/components/Icon/assets/small-solid/unpin.svg
Labels: enhancement

#3588 fix(Avatar): fix multiple space and trim for initials
  .changeset/lemon-lizards-explode.md
  packages/ui/src/components/Avatar/index.tsx
Labels: enhancement

#3598 fix(Separator): change color from border to border weak
  .changeset/brown-feet-impress.md
  packages/form/src/components/TimeField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Unit.spec.tsx.snap
  packages/ui/src/components/SelectInput/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Separator/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Separator/index.tsx
  packages/ui/src/components/TextInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TimeInput/__tests__/__snapshots__/index.test.tsx.snap
Labels: enhancement

#3607 fix(SelectableCardGroup): to hide required icon when there is no legend
  .changeset/strange-cars-retire.md
  packages/ui/src/components/SelectableCardGroup/index.tsx
Labels: bug

#3610 fix(Skeleton): add aria label and data test id
  .changeset/cuddly-ants-bathe.md
  packages/ui/src/components/Skeleton/index.tsx
Labels: enhancement

#3585 chore: remove react flatten children and nivo tooltip
  .changeset/lemon-suns-confess.md
  packages/plus/package.json
  packages/plus/src/components/EstimateCost/Components/Item.tsx
  packages/plus/src/components/EstimateCost/EstimateCostContent.tsx
  packages/plus/src/components/EstimateCost/OverlayComponent.tsx
  packages/ui/package.json
  packages/ui/src/components/SelectInput/index.tsx
  packages/ui/src/components/Stepper/index.tsx
  pnpm-lock.yaml
  tsconfig.json
Labels: enhancement
