Repository scaleway/ultraviolet, pull requests merged in 2024-12, with the labels that each got.

#4502 fix: groups inputs to display danger when on error
  .changeset/early-geese-exist.md
  packages/form/src/components/RadioGroupField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/SelectableCardGroupField/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Checkbox/index.tsx
  packages/ui/src/components/CheckboxGroup/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/CheckboxGroup/index.tsx
  packages/ui/src/components/RadioGroup/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/RadioGroup/index.tsx
  packages/ui/src/components/SelectableCard/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectableCardGroup/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectableCardGroup/index.tsx
  packages/ui/src/components/ToggleGroup/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/ToggleGroup/index.tsx
Labels: enhancement

#4533 fix(DateField): not showing any value in range mode
  .changeset/purple-mice-design.md
  packages/form/src/components/DateField/__stories__/index.stories.tsx
  packages/form/src/components/DateField/index.tsx
Labels: bug

#4492 feat: drawer
  .changeset/poor-flies-behave.md
  packages/ui/src/components/Drawer/__stories__/Footer.stories.tsx
  packages/ui/src/components/Drawer/__stories__/FunctionProps.stories.tsx
  packages/ui/src/components/Drawer/__stories__/Playground.stories.tsx
  packages/ui/src/components/Drawer/__stories__/Size.stories.tsx
  packages/ui/src/components/Drawer/__stories__/Template.stories.tsx
  packages/ui/src/components/Drawer/__stories__/index.stories.tsx
  packages/ui/src/components/Drawer/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Drawer/__tests__/index.test.tsx
  packages/ui/src/components/Drawer/index.tsx
  packages/ui/src/components/Drawer/style.css
Labels: enhancement

#4539 ci: fix deploy
  Dockerfile
  turbo.json
Labels: ci

#4542 docs(SelectableCard): add more examples in doc
  packages/ui/src/components/SelectableCard/__stories__/Examples.stories.tsx
  packages/ui/src/components/SelectableCard/__stories__/assets/fr.svg
  packages/ui/src/components/SelectableCard/__stories__/assets/nl.svg
  packages/ui/src/components/SelectableCard/__stories__/assets/pl.svg
  packages/ui/src/components/SelectableCardGroup/__stories__/Examples.stories.tsx
  packages/ui/src/components/SelectableCardGroup/__stories__/assets/fr.svg
  packages/ui/src/components/SelectableCardGroup/__stories__/assets/nl.svg
  packages/ui/src/components/SelectableCardGroup/__stories__/assets/pl.svg
Labels: documentation

#4504 refactor(Banner): add image in a img tag when is a string
  .changeset/five-radios-tie.md
  packages/ui/src/components/Banner/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Banner/index.tsx
Labels: enhancement

#4535 refactor: list and table to be an actual table in dom
  .changeset/poor-carpets-accept.md
  packages/ui/src/components/List/Body.tsx
  packages/ui/src/components/List/Cell.tsx
  packages/ui/src/components/List/HeaderCell.tsx
  packages/ui/src/components/List/HeaderRow.tsx
  packages/ui/src/components/List/Row.tsx
  packages/ui/src/components/List/SkeletonRows.tsx
  packages/ui/src/components/List/__stories__/Context.stories.tsx
  packages/ui/src/components/List/__stories__/Overflow.stories.tsx
  packages/ui/src/components/List/__stories__/index.stories.tsx
  packages/ui/src/components/List/__stories__/resources.ts
  packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/List/__tests__/index.test.tsx
  packages/ui/src/components/List/index.tsx
  packages/ui/src/components/Table/Cell.tsx
  packages/ui/src/components/Table/HeaderCell.tsx
  packages/ui/src/components/Table/HeaderRow.tsx
  packages/ui/src/components/Table/Row.tsx
  packages/ui/src/components/Table/__stories__/Overflow.stories.tsx
  packages/ui/src/components/Table/__stories__/index.stories.tsx
  packages/ui/src/components/Table/__stories__/resources.ts
  packages/ui/src/components/Table/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Table/constants.ts
  packages/ui/src/components/Table/index.tsx
Labels: refactor

#4571 fix: table and list with a container around for overflow
  .changeset/short-balloons-fetch.md
  examples/next-advanced/next-env.d.ts
  examples/next-login/next-env.d.ts
  examples/next-simple/next-env.d.ts
  packages/ui/package.json
  packages/ui/src/components/List/ListContext.tsx
  packages/ui/src/components/List/Row.tsx
  packages/ui/src/components/List/SkeletonRows.tsx
  packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/List/index.tsx
  packages/ui/src/components/List/types.ts
  packages/ui/src/components/Table/Row.tsx
  packages/ui/src/components/Table/TableContext.tsx
  packages/ui/src/components/Table/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Table/index.tsx
  packages/ui/src/components/Table/types.ts
Labels: bug

#4577 fix(Slider): bug when options are changing
  .changeset/nice-dots-pull.md
  packages/ui/src/components/Slider/__stories__/Options.stories.tsx
  packages/ui/src/components/Slider/components/DoubleSlider.tsx
  packages/ui/src/components/Slider/components/SingleSlider.tsx
Labels: bug, hotfix

#4585 refactor(MenuV2): default portal to be document body
  .changeset/flat-days-yawn.md
  packages/ui/src/components/MenuV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/MenuV2/index.tsx
Labels: refactor

#4587 fix: table and list to hide scroll bar is no overflow
  .changeset/dry-cats-hope.md
  packages/ui/src/components/List/HeaderRow.tsx
  packages/ui/src/components/List/Row.tsx
  packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/List/constants.tsx
  packages/ui/src/components/List/index.tsx
  packages/ui/src/components/Table/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Table/index.tsx
Labels: bug

#4594 fix: table and list to take 100% of container
  .changeset/mean-ways-drum.md
  packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/List/index.tsx
  packages/ui/src/components/Table/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Table/index.tsx
Labels: bug

#4584 fix: all groups input to accept react node as legend
  .changeset/strong-trains-rule.md
  packages/ui/src/components/CheckboxGroup/index.tsx
  packages/ui/src/components/RadioGroup/index.tsx
  packages/ui/src/components/SelectableCardGroup/index.tsx
  packages/ui/src/components/ToggleGroup/index.tsx
Labels: enhancement

#4615 fix(List): disabld state not properly working
  .changeset/gentle-cars-clean.md
  packages/ui/src/components/List/Row.tsx
  packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap
Labels: bug
