Repository scaleway/ultraviolet, pull requests merged in 2024-02, with the labels that each got.

#3383 feat(themes): update gradient structure and new radial gradients
  .changeset/long-parents-bathe.md
  packages/themes/src/themes/console/dark.ts
  packages/themes/src/themes/console/darker.ts
  packages/themes/src/themes/console/deprecated/dark.ts
  packages/themes/src/themes/console/deprecated/darker.ts
  packages/themes/src/themes/console/deprecated/light.ts
  packages/themes/src/themes/console/light.ts
  packages/ui/src/components/Banner/index.tsx
  packages/ui/src/components/GlobalAlert/index.tsx
Labels: enhancement

#3365 fix(EstimateCost): time unit spacing to be auto for fixing firefox
  .changeset/khaki-cows-flash.md
  packages/plus/src/components/EstimateCost/Components/CustomUnitInput.tsx
  packages/plus/src/components/EstimateCost/Components/UnitInput.tsx
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/CustomUnitInput.spec.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Item.spec.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Region.spec.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Regular.spec.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Stepper.spec.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Strong.spec.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Unit.spec.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Zone.spec.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/index.spec.tsx.snap
Labels: bug

#3393 refactor(Tabs): remvoe fully menu from tabs
  .changeset/honest-teachers-do.md
  packages/ui/src/components/Tabs/TabMenuItem.tsx
  packages/ui/src/components/Tabs/__tests__/__snapshots__/index.test.tsx.snap
Labels: refactor

#3396 fix: time field and select input
  .changeset/rotten-terms-repeat.md
  packages/form/src/components/SelectInputField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/TimeField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/TimeField/index.tsx
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/CustomUnitInput.spec.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Item.spec.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Region.spec.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Regular.spec.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Stepper.spec.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Strong.spec.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Unit.spec.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Zone.spec.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/index.spec.tsx.snap
  packages/ui/src/components/SelectInput/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/SelectInput/index.tsx
  packages/ui/src/components/TimeInput/__tests__/__snapshots__/index.test.tsx.snap
Labels: bug, enhancement

#3417 fix(Breadcrumbs): to be vertically center aligned
  .changeset/large-trains-speak.md
  packages/ui/src/components/Breadcrumbs/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Breadcrumbs/index.tsx
Labels: bug

#3419 fix(TextInput): to spread required prop to the dom
  .changeset/wild-carrots-deliver.md
  packages/form/src/components/TextInputField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/ui/src/components/TextInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TextInput/index.tsx
Labels: bug

#3413 fix: radio and checkbox to have correct sentiment and variant
  .changeset/loud-spies-brake.md
  .storybook/preview.tsx
  packages/form/src/components/CheckboxField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/ui/src/components/Checkbox/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Checkbox/index.tsx
  packages/ui/src/components/Radio/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Radio/index.tsx
  packages/ui/src/components/SelectableCard/__tests__/__snapshots__/index.test.tsx.snap
Labels: bug

#3398 fix(MenuV2): fix tooltip on menu item
  .changeset/stupid-shoes-report.md
  packages/ui/src/components/MenuV2/Item.tsx
  packages/ui/src/components/MenuV2/__stories__/Sentiments.stories.tsx
  packages/ui/src/components/MenuV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Tabs/__tests__/__snapshots__/index.test.tsx.snap
Labels: bug

#3415 fix(TextInputV2): remove some props and add some others
  .changeset/eighty-rockets-explode.md
  packages/ui/src/__stories__/migrations/MigrationTextInputV2.stories.mdx
  packages/ui/src/components/DateInput/index.tsx
  packages/ui/src/components/NumberInputV2/index.tsx
  packages/ui/src/components/TextInputV2/__stories__/Template.stories.tsx
  packages/ui/src/components/TextInputV2/index.tsx
Labels: documentation, enhancement

#3440 fix(form): export all components
  .changeset/odd-dancers-study.md
  packages/form/src/index.ts
Labels: bug

#3444 fix(SelectInput): to have prop empty state
  .changeset/popular-chairs-laugh.md
  packages/form/src/components/SelectInputField/index.tsx
Labels: bug

#3446 fix(estimatecost): missing discount value
  .changeset/friendly-clouds-approve.md
  packages/plus/src/components/EstimateCost/OverlayComponent.tsx
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/index.spec.tsx.snap
Labels: bug

#3459 fix(TextInputFieldV2): fix type prop
  .changeset/real-spoons-cough.md
  packages/form/src/components/TextInputFieldV2/index.tsx
Labels: bug

#3467 fix(Toaster): width and new props
  .changeset/pretty-buses-count.md
  packages/ui/src/components/Toaster/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Toaster/index.tsx
Labels: bug, enhancement

#3455 feat(Table): add highlightAnimation on table row
  .changeset/popular-cobras-buy.md
  packages/ui/src/components/Table/Row.tsx
  packages/ui/src/components/Table/__stories__/HighlightAnimation.stories.tsx
  packages/ui/src/components/Table/__stories__/index.stories.tsx
  packages/ui/src/components/Table/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Table/__tests__/index.test.tsx
Labels: enhancement

#3451 fix: add flex-wrap to breadcrumb list
  .changeset/purple-ducks-impress.md
  packages/ui/src/components/Breadcrumbs/__stories__/Template.tsx
  packages/ui/src/components/Breadcrumbs/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Breadcrumbs/index.tsx
Labels: bug

#3466 refactor: new component FAQ
  .changeset/rich-socks-develop.md
  packages/plus/src/components/FAQ/__stories__/Playground.stories.tsx
  packages/plus/src/components/FAQ/__stories__/Template.stories.tsx
  packages/plus/src/components/FAQ/__stories__/index.stories.tsx
  packages/plus/src/components/FAQ/__tests__/__snapshots__/index.test.tsx.snap
  packages/plus/src/components/FAQ/__tests__/index.test.tsx
  packages/plus/src/components/FAQ/index.tsx
  packages/plus/src/components/index.ts
Labels: refactor

#3483 refactor(SelectableCard): to take full width and have better spacings
  .changeset/strange-apes-care.md
  packages/form/src/components/SelectableCardField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/ui/src/components/SelectableCard/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectableCard/index.tsx
  packages/ui/src/components/SwitchButton/__tests__/__snapshots__/index.test.tsx.snap
Labels: refactor

#3482 fix(RadioGroup): children radio name optional as parent spread it
  .changeset/cyan-rocks-hug.md
  packages/form/src/components/NumberInputField/__stories__/index.stories.tsx
  packages/form/src/components/NumberInputField/index.tsx
  packages/form/src/components/RadioField/__stories__/index.stories.tsx
  packages/form/src/components/RadioField/index.tsx
  packages/form/src/components/RadioGroupField/__stories__/Required.stories.tsx
  packages/form/src/components/RadioGroupField/__stories__/Template.stories.tsx
  packages/form/src/components/RadioGroupField/__stories__/index.stories.tsx
  packages/form/src/components/RadioGroupField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/TextInputField/__stories__/index.stories.tsx
  packages/form/src/components/TextInputField/index.tsx
  packages/ui/src/components/NumberInput/__stories__/index.stories.tsx
  packages/ui/src/components/NumberInput/index.tsx
  packages/ui/src/components/RadioGroup/__stories__/Controlled.stories.tsx
  packages/ui/src/components/RadioGroup/__stories__/Template.stories.tsx
  packages/ui/src/components/RadioGroup/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/RadioGroup/index.tsx
  packages/ui/src/components/TextInput/__stories__/index.stories.tsx
Labels: documentation, enhancement

#3480 feat(ProductIcon): new product icon variant original
  .changeset/dull-cougars-appear.md
  .changeset/dull-cougars-disappear.md
  packages/icons/src/components/ProductIcon/__stories__/Disabled.stories.tsx
  packages/icons/src/components/ProductIcon/__stories__/Playground.stories.tsx
  packages/icons/src/components/ProductIcon/__stories__/Variants.stories.tsx
  packages/icons/src/components/ProductIcon/__stories__/index.stories.tsx
  packages/icons/src/components/ProductIcon/index.tsx
  packages/themes/src/themes/console/dark.ts
  packages/themes/src/themes/console/darker.ts
  packages/themes/src/themes/console/light.ts
Labels: enhancement

#3453 docs: add more colors tokens
  .storybook/components/DocsContainer.tsx
  packages/ui/src/__stories__/components/Colors.tsx
Labels: documentation

#3409 fix(CheckboxField): remove array value
  .changeset/ninety-ghosts-carry.md
  packages/form/src/components/CheckboxField/__stories__/Checked.stories.tsx
  packages/form/src/components/CheckboxField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/CheckboxField/__tests__/index.spec.tsx
  packages/form/src/components/CheckboxField/index.tsx
Labels: bug

#3487 fix(inputs): multiple inputs issue with required icon and no label
  .changeset/strange-doors-study.md
  packages/form/src/components/DateField/__tests__/__snapshots__/index.tsx.snap
  packages/form/src/components/NumberInputFieldV2/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/TagInputField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Stepper.spec.tsx.snap
  packages/ui/src/components/NumberInputV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/NumberInputV2/index.tsx
  packages/ui/src/components/TagInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TagInput/index.tsx
  packages/ui/src/components/TextArea/index.tsx
  packages/ui/src/components/TextInputV2/__stories__/Template.stories.tsx
  packages/ui/src/components/TextInputV2/__stories__/index.stories.tsx
  packages/ui/src/components/TextInputV2/index.tsx
Labels: bug

#3490 fix(SelectableCard): to remove gap when no label is set
  .changeset/quiet-elephants-explain.md
  packages/form/src/components/SelectableCardField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/ui/src/components/SelectableCard/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectableCard/index.tsx
  packages/ui/src/components/SwitchButton/__tests__/__snapshots__/index.test.tsx.snap
Labels: bug

#3493 fix(Skeleton): add aria-busy property
  .changeset/lucky-yaks-fry.md
  packages/plus/src/components/ContentCard/__tests__/__snapshots__/index.test.tsx.snap
  packages/plus/src/components/ContentCardGroup/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Skeleton/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Skeleton/index.tsx
  packages/ui/src/components/Table/__tests__/__snapshots__/index.test.tsx.snap
Labels: enhancement

#3486 feat: new component Notification
  .changeset/famous-stingrays-exist.md
  packages/ui/src/components/Notification/__stories__/Children.tsx
  packages/ui/src/components/Notification/__stories__/Playground.stories.tsx
  packages/ui/src/components/Notification/__stories__/Template.stories.tsx
  packages/ui/src/components/Notification/__stories__/index.stories.tsx
  packages/ui/src/components/Notification/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Notification/__tests__/index.test.tsx
  packages/ui/src/components/Notification/index.tsx
  packages/ui/src/components/index.ts
Labels: enhancement

#3488 feat(ProductIcon): 37 new product icons
  .changeset/wild-seas-admire.md
  packages/icons/src/components/ProductIcon/Icons.tsx
  packages/icons/src/components/ProductIcon/assets/additional-disk.svg
  packages/icons/src/components/ProductIcon/assets/ansible.svg
  packages/icons/src/components/ProductIcon/assets/api.svg
  packages/icons/src/components/ProductIcon/assets/bandwidth.svg
  packages/icons/src/components/ProductIcon/assets/cloud-hosting.svg
  packages/icons/src/components/ProductIcon/assets/cold-storage.svg
  packages/icons/src/components/ProductIcon/assets/data-warehouse.svg
  packages/icons/src/components/ProductIcon/assets/ddos.svg
  packages/icons/src/components/ProductIcon/assets/ddx-core-servers.svg
  packages/icons/src/components/ProductIcon/assets/ddx-pro-servers.svg
  packages/icons/src/components/ProductIcon/assets/ddx-start-servers.svg
  packages/icons/src/components/ProductIcon/assets/dedibackup.svg
  packages/icons/src/components/ProductIcon/assets/edge-services.svg
  packages/icons/src/components/ProductIcon/assets/elastic-metal-aluminium.svg
  packages/icons/src/components/ProductIcon/assets/elastic-metal-beryllium.svg
  packages/icons/src/components/ProductIcon/assets/elastic-metal-iridium.svg
  packages/icons/src/components/ProductIcon/assets/elastic-metal-lithium.svg
  packages/icons/src/components/ProductIcon/assets/elastic-metal-titanium.svg
  packages/icons/src/components/ProductIcon/assets/icon-elastic-metal.svg
  packages/icons/src/components/ProductIcon/assets/icon-sdk-js.svg
  packages/icons/src/components/ProductIcon/assets/icon-sdk.svg
  packages/icons/src/components/ProductIcon/assets/instance-cost-optimized.svg
  packages/icons/src/components/ProductIcon/assets/instance-learn.svg
  packages/icons/src/components/ProductIcon/assets/instance-pop.svg
  packages/icons/src/components/ProductIcon/assets/instance-wop.svg
  packages/icons/src/components/ProductIcon/assets/mac-mini.svg
  packages/icons/src/components/ProductIcon/assets/monitoring.svg
  packages/icons/src/components/ProductIcon/assets/os.svg
  packages/icons/src/components/ProductIcon/assets/rpn-san.svg
  packages/icons/src/components/ProductIcon/assets/rpn-v1.svg
  packages/icons/src/components/ProductIcon/assets/rpn-v2.svg
  packages/icons/src/components/ProductIcon/assets/rpn.svg
  packages/icons/src/components/ProductIcon/assets/sdk-go.svg
  packages/icons/src/components/ProductIcon/assets/sdk-python.svg
  packages/icons/src/components/ProductIcon/assets/service-level.svg
  packages/icons/src/components/ProductIcon/assets/store-servers.svg
  packages/icons/src/components/ProductIcon/assets/web-platform.svg
Labels: enhancement

#3491 feat: new DynamicIllustration component
  .changeset/popular-spies-dream.md
  packages/illustrations/.jest/helpers.tsx
  packages/illustrations/src/components/DynamicIllustration/Illustrations.tsx
  packages/illustrations/src/components/DynamicIllustration/__stories__/List.stories.tsx
  packages/illustrations/src/components/DynamicIllustration/__stories__/Playground.stories.tsx
  packages/illustrations/src/components/DynamicIllustration/__stories__/Template.stories.tsx
  packages/illustrations/src/components/DynamicIllustration/__stories__/index.stories.tsx
  packages/illustrations/src/components/DynamicIllustration/__tests__/__snapshots__/index.test.tsx.snap
  packages/illustrations/src/components/DynamicIllustration/__tests__/index.test.tsx
  packages/illustrations/src/components/DynamicIllustration/index.tsx
  packages/illustrations/src/components/index.ts
  packages/illustrations/src/index.ts
  packages/illustrations/src/various/empty/empty-dark.webp
  packages/illustrations/src/various/empty/empty-light.webp
  packages/illustrations/src/various/empty/failed-dark.webp
  packages/illustrations/src/various/empty/failed-light.webp
  packages/illustrations/src/various/empty/generic-dark.webp
  packages/illustrations/src/various/empty/generic-light.webp
  packages/illustrations/src/various/empty/index.ts
  packages/illustrations/src/various/empty/loading-dark.webp
  packages/illustrations/src/various/empty/loading-light.webp
  packages/illustrations/src/various/empty/lock-dark.webp
  packages/illustrations/src/various/empty/lock-light.webp
  packages/illustrations/src/various/empty/plus-dark.webp
  packages/illustrations/src/various/empty/plus-light.webp
  packages/illustrations/src/various/empty/resources-dark.webp
  packages/illustrations/src/various/empty/resources-light.webp
  packages/illustrations/src/various/empty/search-dark.webp
  packages/illustrations/src/various/empty/search-light.webp
  packages/illustrations/src/various/feedback/danger-dark.webp
  packages/illustrations/src/various/feedback/danger-light.webp
  packages/illustrations/src/various/feedback/index.ts
  packages/illustrations/src/various/feedback/success-dark.webp
  packages/illustrations/src/various/feedback/success-light.webp
  packages/illustrations/src/various/feedback/warning-dark.webp
  packages/illustrations/src/various/feedback/warning-light.webp
  packages/illustrations/src/various/index.ts
Labels: enhancement

#3503 feat(SelectableCard): native indentation for children and spacing with label
  .changeset/gorgeous-insects-build.md
  packages/form/src/components/SelectableCardField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/ui/src/components/SelectableCard/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectableCard/index.tsx
  packages/ui/src/components/SwitchButton/__tests__/__snapshots__/index.test.tsx.snap
Labels: enhancement
