Repository scaleway/ultraviolet, pull requests merged in 2024-07, with the labels that each got.

#3929 docs: update contributing guidelines
  CONTRIBUTING.md
Labels: documentation

#3931 fix(Illustrations): add doc and update generated files
  packages/illustrations/README.md
  packages/illustrations/src/assets/products/index.ts
  utils/illustrations/uploadIllustrations.js
Labels: bug, documentation

#3916 fix(TextArea): to have correct error icon variant
  .changeset/angry-penguins-clean.md
  packages/ui/src/components/TextArea/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TextArea/index.tsx
Labels: bug

#3927 feat(SearchInput): redesign and new shortcut feature
  .changeset/silly-penguins-heal.md
  packages/ui/src/components/SearchInput/Key.tsx
  packages/ui/src/components/SearchInput/KeyGroup.tsx
  packages/ui/src/components/SearchInput/__stories__/Disabled.stories.tsx
  packages/ui/src/components/SearchInput/__stories__/Error.stories.tsx
  packages/ui/src/components/SearchInput/__stories__/Shortcut.stories.tsx
  packages/ui/src/components/SearchInput/__stories__/index.stories.tsx
  packages/ui/src/components/SearchInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SearchInput/__tests__/index.test.tsx
  packages/ui/src/components/SearchInput/index.tsx
  packages/ui/src/components/SearchInput/types.ts
  packages/ui/src/components/TextInputV2/index.tsx
Labels: enhancement

#3938 feat(Icons): new icon and category icon
  .changeset/dry-pumas-add.md
  packages/icons/src/components/CategoryIcon/Icons.tsx
  packages/icons/src/components/CategoryIcon/assets/partners.svg
  packages/icons/src/components/Icon/Icons.tsx
  packages/icons/src/components/Icon/SmallIcons.tsx
  packages/icons/src/components/Icon/assets/default-outline/send.svg
  packages/icons/src/components/Icon/assets/default-solid/send.svg
  packages/icons/src/components/Icon/assets/small-outline/send.svg
  packages/icons/src/components/Icon/assets/small-solid/send.svg
Labels: enhancement

#3928 fix(Dialog): title to have correct sentiment
  .changeset/clever-schools-design.md
  .storybook/assets/fonts/space-grotesk/SpaceGrotesk.woff2
  .storybook/preview.tsx
  packages/ui/README.md
  packages/ui/src/components/Dialog/index.tsx
  packages/ui/src/components/Dialog/subComponents/Text.tsx
Labels: bug

#3960 ci: fix min scale and cpu usage for deployement
  .github/workflows/deploy-storybook.yml
Labels: ci

#3959 refactor(EstimateCost): add negative values on items
  .changeset/tall-pigs-roll.md
  packages/plus/src/components/EstimateCost/Components/Item.tsx
  packages/plus/src/components/EstimateCost/EstimateCostContent.tsx
  packages/plus/src/components/EstimateCost/__stories__/NegativeValues.stories.tsx
  packages/plus/src/components/EstimateCost/__stories__/Playground.stories.tsx
  packages/plus/src/components/EstimateCost/__stories__/index.stories.tsx
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/index.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/helper.test.ts
  packages/plus/src/components/EstimateCost/helper.ts
Labels: refactor

#3965 fix(SelectInputFieldV2): add tooltip
  .changeset/tough-pianos-agree.md
  packages/form/src/components/SelectInputFieldV2/index.tsx
Labels: bug

#3967 fix(Modal): focus on close
  .changeset/seven-laws-pump.md
  packages/ui/src/components/Modal/Disclosure.tsx
  packages/ui/src/components/Modal/index.tsx
  packages/ui/src/components/Modal/types.ts
Labels: bug

#3963 fix(List): add expanded on list row
  .changeset/clever-hotels-behave.md
  packages/ui/src/components/List/Row.tsx
  packages/ui/src/components/List/__stories__/Expandable.stories.tsx
  packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/List/__tests__/index.test.tsx
Labels: enhancement

#3969 fix(Radio): disabled checked radio color
  .changeset/angry-meals-wave.md
  packages/form/src/components/RadioField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/RadioGroupField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/SelectableCardField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/SelectableCardGroupField/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Radio/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Radio/index.tsx
  packages/ui/src/components/RadioGroup/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectableCard/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectableCardGroup/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SwitchButton/__tests__/__snapshots__/index.test.tsx.snap
Labels: bug

#3918 feat(Slider): new component
  .changeset/sixty-fishes-vanish.md
  packages/ui/src/components/Slider/DoubleSlider.tsx
  packages/ui/src/components/Slider/Label.tsx
  packages/ui/src/components/Slider/Options.tsx
  packages/ui/src/components/Slider/SingleSlider.tsx
  packages/ui/src/components/Slider/__stories__/CustomScale.stories.tsx
  packages/ui/src/components/Slider/__stories__/Disabled.stories.tsx
  packages/ui/src/components/Slider/__stories__/Double.stories.tsx
  packages/ui/src/components/Slider/__stories__/Error.stories.tsx
  packages/ui/src/components/Slider/__stories__/Input.stories.tsx
  packages/ui/src/components/Slider/__stories__/Options.stories.tsx
  packages/ui/src/components/Slider/__stories__/Playground.stories.tsx
  packages/ui/src/components/Slider/__stories__/PrefixSuffix.stories.tsx
  packages/ui/src/components/Slider/__stories__/Template.stories.tsx
  packages/ui/src/components/Slider/__stories__/Tooltip.stories.tsx
  packages/ui/src/components/Slider/__stories__/index.stories.tsx
  packages/ui/src/components/Slider/__tests__/__snapshots__/doubleSlider.test.tsx.snap
  packages/ui/src/components/Slider/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Slider/__tests__/__snapshots__/onchange.test.tsx.snap
  packages/ui/src/components/Slider/__tests__/__snapshots__/singleSlider.test.tsx.snap
  packages/ui/src/components/Slider/__tests__/doubleSlider.test.tsx
  packages/ui/src/components/Slider/__tests__/singleSlider.test.tsx
  packages/ui/src/components/Slider/constant.ts
  packages/ui/src/components/Slider/index.tsx
  packages/ui/src/components/Slider/styles.ts
  packages/ui/src/components/Slider/types.ts
  packages/ui/src/components/index.ts
Labels: enhancement

#3970 fix(SelectableCard): label to take full width in radio and checkbox
  .changeset/tough-items-exist.md
  packages/form/src/components/RadioGroupField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/SelectableCardField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/SelectableCardGroupField/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Checkbox/index.tsx
  packages/ui/src/components/Radio/index.tsx
  packages/ui/src/components/RadioGroup/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectableCard/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectableCard/index.tsx
  packages/ui/src/components/SelectableCardGroup/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SwitchButton/__tests__/__snapshots__/index.test.tsx.snap
Labels: enhancement

#3972 fix(Dialog): wrong width
  .changeset/nice-pumpkins-repeat.md
  packages/ui/src/components/Dialog/index.tsx
  packages/ui/src/components/Modal/Dialog.tsx
Labels: bug

#3981 ci: fix teardown error
  .github/workflows/teardown_pull_request.yml
Labels: bug, ci

#3984 fix(List): prop expanded not working properly
  .changeset/lazy-squids-train.md
  packages/ui/src/components/List/ListContext.tsx
  packages/ui/src/components/List/Row.tsx
  packages/ui/src/components/List/__stories__/Expandable.stories.tsx
Labels: bug

#3987 revert(modal): revert focus on close modal
  .changeset/beige-ladybugs-kiss.md
  packages/ui/src/components/Modal/Disclosure.tsx
  packages/ui/src/components/Modal/index.tsx
  packages/ui/src/components/Modal/types.ts
Labels: hotfix

#3920 refactor: update elevation tokens usages on many components
  .changeset/sweet-apricots-beam.md
  packages/form/src/components/DateField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/SelectInputFieldV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/ActionBar/index.tsx
  packages/ui/src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/DateInput/index.tsx
  packages/ui/src/components/MenuV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/MenuV2/index.tsx
  packages/ui/src/components/Modal/Dialog.tsx
  packages/ui/src/components/Modal/__stories__/Template.stories.tsx
  packages/ui/src/components/Modal/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Notification/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Notification/index.tsx
  packages/ui/src/components/SelectInputV2/Dropdown.tsx
  packages/ui/src/components/SelectInputV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Tabs/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/UnitInput/__tests__/__snapshots__/index.test.tsx.snap
Labels: refactor

#3990 fix(SearchInput): add missing props
  .changeset/funny-ghosts-argue.md
  packages/ui/src/components/SearchInput/index.tsx
  packages/ui/src/components/SearchInput/types.ts
Labels: enhancement

#3995 fix(SearchInput): only handle keyboard event
  .changeset/sharp-suits-knock.md
  packages/ui/src/components/SearchInput/index.tsx
Labels: bug

#3994 feat(Icon): new icon sparkles
  .changeset/gentle-icons-roll.md
  packages/icons/src/components/Icon/Icons.tsx
  packages/icons/src/components/Icon/SmallIcons.tsx
  packages/icons/src/components/Icon/assets/default-outline/sparkles.svg
  packages/icons/src/components/Icon/assets/default-solid/sparkles.svg
  packages/icons/src/components/Icon/assets/small-outline/sparkles.svg
  packages/icons/src/components/Icon/assets/small-solid/sparkles.svg
  packages/icons/src/components/Icon/index.tsx
Labels: enhancement

#3983 fix(Navigation): add a prop to disable animation if needed
  .changeset/fifty-chicken-float.md
  .changeset/twenty-olives-hunt.md
  packages/form/src/components/SelectInputField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/Submit/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/TextInputField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/TimeField/__tests__/__snapshots__/index.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/CustomUnitInput.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Item.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Region.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Regular.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Stepper.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Strong.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Unit.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Zone.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/index.test.tsx.snap
  packages/plus/src/components/Navigation/NavigationContent.tsx
  packages/plus/src/components/Navigation/NavigationProvider.tsx
  packages/plus/src/components/Navigation/__stories__/Playground.stories.tsx
  packages/plus/src/components/Navigation/__stories__/index.stories.tsx
  packages/plus/src/components/Navigation/components/Item.tsx
  packages/ui/src/components/Expandable/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Expandable/__tests__/index.test.tsx
  packages/ui/src/components/Expandable/index.tsx
  packages/ui/src/components/SelectInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Snippet/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TextInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TimeInput/__tests__/__snapshots__/index.test.tsx.snap
Labels: enhancement

#4000 ci: remove dns deployement on preprod env
  .github/workflows/deploy-storybook.yml
  .github/workflows/teardown_pull_request.yml
Labels: enhancement

#4001 ci: fix remove storybook deployement
  .github/workflows/teardown_pull_request.yml
Labels: ci

#4002 fix(TagInputField): add regex prop
  .changeset/fresh-bags-burn.md
  packages/form/src/components/TagInputField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/TagInputField/__tests__/index.test.tsx
  packages/form/src/components/TagInputField/index.tsx
Labels: enhancement

#3944 fix: text input and date input to be fixed
  .changeset/hot-llamas-fry.md
  .changeset/shy-parrots-matter.md
  packages/form/src/components/TextInputFieldV2/index.tsx
  packages/ui/src/components/DateInput/__stories__/Localized.stories.tsx
  packages/ui/src/components/DateInput/__stories__/Size.stories.tsx
  packages/ui/src/components/DateInput/index.tsx
  packages/ui/src/components/SearchInput/index.tsx
  packages/ui/src/components/SelectInputV2/SearchBarDropdown.tsx
  packages/ui/src/components/TextInputV2/__stories__/ControlledVSUncontrolled.stories.tsx
  packages/ui/src/components/TextInputV2/__stories__/Examples.stories.tsx
  packages/ui/src/components/TextInputV2/__stories__/OnRandomize.stories.tsx
  packages/ui/src/components/TextInputV2/__stories__/Size.stories.tsx
  packages/ui/src/components/TextInputV2/__stories__/Template.stories.tsx
  packages/ui/src/components/TextInputV2/__stories__/index.stories.tsx
  packages/ui/src/components/TextInputV2/__tests__/index.test.tsx
  packages/ui/src/components/TextInputV2/index.tsx
Labels: bug

#4014 ci: fix dns deployement
  .github/workflows/deploy-storybook.yml
Labels: ci

#3997 feat(SliderField): new slider into forms
  .changeset/khaki-fishes-hear.md
  .changeset/poor-turkeys-deny.md
  packages/form/src/components/SliderField/__stories__/Double.stories.tsx
  packages/form/src/components/SliderField/__stories__/Playground.stories.tsx
  packages/form/src/components/SliderField/__stories__/Required.stories.tsx
  packages/form/src/components/SliderField/__stories__/Template.stories.tsx
  packages/form/src/components/SliderField/__stories__/index.stories.tsx
  packages/form/src/components/SliderField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/SliderField/__tests__/index.test.tsx
  packages/form/src/components/SliderField/index.tsx
  packages/form/src/components/index.ts
  packages/ui/src/components/Slider/__stories__/Template.stories.tsx
  packages/ui/src/components/Slider/__tests__/__snapshots__/doubleSlider.test.tsx.snap
  packages/ui/src/components/Slider/__tests__/doubleSlider.test.tsx
  packages/ui/src/components/Slider/components/DoubleSlider.tsx
  packages/ui/src/components/Slider/components/Label.tsx
  packages/ui/src/components/Slider/components/Options.tsx
  packages/ui/src/components/Slider/components/SingleSlider.tsx
  packages/ui/src/components/Slider/index.tsx
  packages/ui/src/components/Slider/styles.ts
Labels: bug, enhancement

#4013 ci: fix unit testing
  packages/ui/src/components/SelectInputV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectInputV2/__tests__/index.test.tsx
Labels: ci

#4022 ci: increase vcpu for deployement
  .github/workflows/deploy-storybook.yml
Labels: ci

#4023 ci: do not deploy if build and typecheck is not green
  .github/workflows/ci.yml
  .github/workflows/deploy-storybook.yml
Labels: ci

#3926 ci: add unit testing on navigation
  packages/plus/src/components/Navigation/NavigationContent.tsx
  packages/plus/src/components/Navigation/__tests__/__snapshots__/index.test.tsx.snap
  packages/plus/src/components/Navigation/__tests__/index.test.tsx
  packages/plus/src/components/Navigation/components/Item.tsx
  packages/plus/src/components/Navigation/components/PinnedItems.tsx
Labels: ci

#4007 feat(Modal): introducing nested modals
  .changeset/famous-clouds-report.md
  packages/ui/src/components/Modal/ModalContent.tsx
  packages/ui/src/components/Modal/ModalProvider.tsx
  packages/ui/src/components/Modal/__stories__/NestedModal.stories.tsx
  packages/ui/src/components/Modal/__stories__/index.stories.tsx
  packages/ui/src/components/Modal/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Modal/__tests__/index.test.tsx
  packages/ui/src/components/Modal/components/Dialog.tsx
  packages/ui/src/components/Modal/components/Disclosure.tsx
  packages/ui/src/components/Modal/index.tsx
Labels: enhancement

#4016 fix(Slider): option positioning
  .changeset/smooth-camels-press.md
  packages/form/src/components/SliderField/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Slider/__stories__/CustomScale.stories.tsx
  packages/ui/src/components/Slider/__tests__/__snapshots__/doubleSlider.test.tsx.snap
  packages/ui/src/components/Slider/__tests__/__snapshots__/singleSlider.test.tsx.snap
  packages/ui/src/components/Slider/components/DoubleSlider.tsx
  packages/ui/src/components/Slider/components/Options.tsx
  packages/ui/src/components/Slider/components/SingleSlider.tsx
  packages/ui/src/components/Slider/styles.ts
Labels: bug

#4030 feat(assets): new icon illustrations and product icon size
  .changeset/selfish-forks-peel.md
  .changeset/slimy-jars-sneeze.md
  packages/icons/src/components/Icon/Icons.tsx
  packages/icons/src/components/Icon/SmallIcons.tsx
  packages/icons/src/components/Icon/assets/default-outline/light-bulb.svg
  packages/icons/src/components/Icon/assets/default-solid/light-bulb.svg
  packages/icons/src/components/Icon/assets/small-outline/light-bulb.svg
  packages/icons/src/components/Icon/assets/small-solid/light-bulb.svg
  packages/icons/src/components/ProductIcon/index.tsx
  packages/illustrations/src/assets/products/edgeServices/edge-services-content.webp
  packages/illustrations/src/assets/products/edgeServices/edge-services-keyvisual.webp
  packages/illustrations/src/assets/products/edgeServices/edge-services-original.webp
  packages/illustrations/src/assets/products/edgeServices/edge-services-wire.svg
  packages/illustrations/src/assets/products/edgeServices/index.ts
  packages/illustrations/src/assets/products/index.ts
  packages/illustrations/src/assets/products/managedSearchDatabase/index.ts
  packages/illustrations/src/assets/products/managedSearchDatabase/managed-search-database-content.webp
  packages/illustrations/src/assets/products/managedSearchDatabase/managed-search-database-keyvisual.webp
  packages/illustrations/src/assets/products/managedSearchDatabase/managed-search-database-original.webp
  packages/illustrations/src/assets/products/managedSearchDatabase/managed-search-database-wire.svg
  packages/illustrations/src/assets/products/quantumApplication/index.ts
  packages/illustrations/src/assets/products/quantumApplication/quantum-application-content.webp
  packages/illustrations/src/assets/products/quantumApplication/quantum-application-keyvisual.webp
  packages/illustrations/src/assets/products/quantumApplication/quantum-application-original.webp
  packages/illustrations/src/assets/products/quantumApplication/quantum-application-wire.svg
Labels: enhancement

#4032 refactor(SliderField): match possible values with slider value
  .changeset/brave-rings-wink.md
  .changeset/dirty-kangaroos-tickle.md
  packages/form/src/components/SliderField/__stories__/Options.stories.tsx
  packages/form/src/components/SliderField/__stories__/index.stories.tsx
  packages/form/src/components/SliderField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/SliderField/__tests__/index.test.tsx
  packages/form/src/components/SliderField/index.tsx
  packages/ui/src/components/Slider/__stories__/CustomScale.stories.tsx
  packages/ui/src/components/Slider/__stories__/Options.stories.tsx
  packages/ui/src/components/Slider/__stories__/index.stories.tsx
  packages/ui/src/components/Slider/__tests__/__snapshots__/doubleSlider.test.tsx.snap
  packages/ui/src/components/Slider/__tests__/__snapshots__/singleSlider.test.tsx.snap
  packages/ui/src/components/Slider/__tests__/doubleSlider.test.tsx
  packages/ui/src/components/Slider/__tests__/singleSlider.test.tsx
  packages/ui/src/components/Slider/components/DoubleSlider.tsx
  packages/ui/src/components/Slider/components/Options.tsx
  packages/ui/src/components/Slider/components/SingleSlider.tsx
  packages/ui/src/components/Slider/index.tsx
  packages/ui/src/components/Slider/styles.ts
  packages/ui/src/components/Slider/types.ts
Labels: enhancement, refactor

#4038 fix(badge): font weight and sizes
  .changeset/curvy-rocks-film.md
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Regular.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Badge/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Badge/index.tsx
  packages/ui/src/components/Tabs/__tests__/__snapshots__/Tab.test.tsx.snap
  packages/ui/src/components/Tabs/__tests__/__snapshots__/index.test.tsx.snap
Labels: bug

#4041 ci: fix dns setting not working properly with github action
  .github/workflows/ci.yml
Labels: bug, ci

#4018 refactor(form): spread props on checkbox and radio
  .changeset/silent-jobs-lay.md
  eslint.config.mjs
  packages/form/src/components/CheckboxField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/CheckboxField/index.tsx
  packages/form/src/components/CheckboxGroupField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/CheckboxGroupField/index.tsx
  packages/form/src/components/RadioField/index.tsx
  packages/form/src/components/RadioGroupField/index.tsx
Labels: refactor

#4047 fix(Navigation): enable back animaiton by default
  .changeset/good-horses-vanish.md
  packages/plus/src/components/Navigation/NavigationProvider.tsx
  packages/plus/src/components/Navigation/__stories__/Playground.stories.tsx
  packages/plus/src/components/Navigation/__tests__/__snapshots__/index.test.tsx.snap
Labels: bug

#4039 feat(Toaster): new sub component for button and link with examples
  .changeset/loud-points-warn.md
  packages/ui/src/components/Toaster/__stories__/ComplexChildren.stories.tsx
  packages/ui/src/components/Toaster/__stories__/ContainerId.stories.tsx
  packages/ui/src/components/Toaster/__stories__/index.stories.tsx
  packages/ui/src/components/Toaster/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Toaster/__tests__/index.test.tsx
  packages/ui/src/components/Toaster/components/Button.tsx
  packages/ui/src/components/Toaster/components/Link.tsx
  packages/ui/src/components/Toaster/index.tsx
Labels: enhancement

#4040 feat(DateInput): new prop show month year picker
  .changeset/polite-pets-refuse.md
  packages/form/src/components/DateField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/DateField/index.tsx
  packages/ui/src/components/DateInput/__stories__/Months.stories.tsx
  packages/ui/src/components/DateInput/__stories__/index.stories.tsx
  packages/ui/src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/DateInput/__tests__/index.test.tsx
  packages/ui/src/components/DateInput/index.tsx
Labels: enhancement

#4051 fix(Icon): update docs and restore default name to alert
  .changeset/weak-buckets-build.md
  packages/icons/src/components/Icon/__stories__/Size.stories.tsx
  packages/icons/src/components/Icon/index.tsx
Labels: bug, documentation

#4043 feat(Alert): new sentiment neutral
  .changeset/polite-crabs-obey.md
  packages/form/src/components/SubmitErrorAlert/__tests__/__snapshots__/index.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Regular.test.tsx.snap
  packages/ui/src/components/Alert/__stories__/Link.stories.tsx
  packages/ui/src/components/Alert/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Alert/__tests__/index.test.tsx
  packages/ui/src/components/Alert/index.tsx
Labels: enhancement

#4052 feat(AvatarV2): new component
  .changeset/green-eels-trade.md
  .changeset/unlucky-turtles-invent.md
  packages/icons/src/components/Icon/__stories__/Size.stories.tsx
  packages/icons/src/components/Icon/index.tsx
  packages/icons/src/components/ProductIcon/index.tsx
  packages/ui/src/__stories__/migrations/MigrationAvatarV2.mdx
  packages/ui/src/components/Avatar/__stories__/index.stories.tsx
  packages/ui/src/components/Avatar/index.tsx
  packages/ui/src/components/AvatarV2/__stories__/Examples.stories.tsx
  packages/ui/src/components/AvatarV2/__stories__/Playground.stories.tsx
  packages/ui/src/components/AvatarV2/__stories__/Sentiment.stories.tsx
  packages/ui/src/components/AvatarV2/__stories__/Shape.stories.tsx
  packages/ui/src/components/AvatarV2/__stories__/Size.stories.tsx
  packages/ui/src/components/AvatarV2/__stories__/Template.stories.tsx
  packages/ui/src/components/AvatarV2/__stories__/Upload.stories.tsx
  packages/ui/src/components/AvatarV2/__stories__/Variant.stories.tsx
  packages/ui/src/components/AvatarV2/__stories__/assets/avatar.svg
  packages/ui/src/components/AvatarV2/__stories__/index.stories.tsx
  packages/ui/src/components/AvatarV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/AvatarV2/__tests__/index.test.tsx
  packages/ui/src/components/AvatarV2/constants.ts
  packages/ui/src/components/AvatarV2/index.tsx
  packages/ui/src/components/AvatarV2/types.ts
Labels: enhancement

#4061 fix: radio and checkbox field to spread data testid
  .changeset/red-buckets-bow.md
  packages/form/src/components/CheckboxField/index.tsx
  packages/form/src/components/RadioField/index.tsx
Labels: bug

#4071 fix(DateInput): wrong type
  .changeset/breezy-boats-complain.md
  packages/ui/src/components/DateInput/index.tsx
Labels: bug

#4063 feat(CopyButton): add children prop
  .changeset/lovely-terms-roll.md
  packages/ui/src/components/CopyButton/__stories__/Children.stories.tsx
  packages/ui/src/components/CopyButton/__stories__/index.stories.tsx
  packages/ui/src/components/CopyButton/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/CopyButton/__tests__/index.test.tsx
  packages/ui/src/components/CopyButton/index.tsx
Labels: enhancement

#4062 fix(Alert): change title gap
  .changeset/nasty-ads-tap.md
  packages/form/src/components/SubmitErrorAlert/__tests__/__snapshots__/index.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Regular.test.tsx.snap
  packages/ui/src/components/Alert/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Alert/index.tsx
Labels: refactor

#4083 fix(TagInputField): regex to work with array of string value
  .changeset/bright-bottles-pay.md
  packages/form/src/components/TagInputField/index.tsx
Labels: bug

#4074 refactor(inputs): to have 8px padding instead of 16px in small sizes
  .changeset/young-toes-rescue.md
  packages/form/src/components/DateField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/SelectInputFieldV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/TextInputFieldV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/UnitInputField/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SearchInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectInputV2/SelectBar.tsx
  packages/ui/src/components/TagInput/index.tsx
  packages/ui/src/components/TextInputV2/__stories__/Template.stories.tsx
  packages/ui/src/components/TextInputV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TextInputV2/index.tsx
  packages/ui/src/components/UnitInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/UnitInput/index.tsx
Labels: refactor

#4080 fix: slider and select input helper and option no wrap
  .changeset/chilly-emus-sleep.md
  packages/form/src/components/SliderField/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectInputV2/index.tsx
  packages/ui/src/components/Slider/__stories__/Options.stories.tsx
  packages/ui/src/components/Slider/__tests__/__snapshots__/doubleSlider.test.tsx.snap
  packages/ui/src/components/Slider/__tests__/__snapshots__/singleSlider.test.tsx.snap
  packages/ui/src/components/Slider/components/Options.tsx
  packages/ui/src/components/Slider/index.tsx
Labels: bug

#4081 fix(DateInput): to have correct color when month only and range
  .changeset/itchy-buckets-enjoy.md
  packages/form/src/components/DateField/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/DateInput/__stories__/Months.stories.tsx
  packages/ui/src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/DateInput/index.tsx
Labels: bug

#4087 fix(Icon): send icon wrong sizing
  .changeset/perfect-ways-matter.md
  packages/icons/src/components/Icon/assets/default-outline/send.svg
  packages/icons/src/components/Icon/assets/default/send.svg
  packages/icons/src/components/Icon/assets/small-outline/send.svg
  packages/icons/src/components/Icon/assets/small/send.svg
  packages/icons/src/components/Icon/index.tsx
Labels: bug
