Repository scaleway/ultraviolet, pull requests merged in 2024-08, with the labels that each got.

#4108 fix(textinputv2): reset minLength in errors
  .changeset/mean-trainers-mate.md
  packages/form/src/components/TextInputFieldV2/index.tsx
Labels: bug

#4107 chore(serve): switch from serve to http-server
  Dockerfile
  package.json
  pnpm-lock.yaml
Labels: documentation, enhancement

#4117 fix(navigation): animation time is way tooooooooo long
  .changeset/shy-clouds-serve.md
  packages/plus/src/components/Navigation/NavigationContent.tsx
  packages/plus/src/components/Navigation/NavigationProvider.tsx
  packages/plus/src/components/Navigation/__stories__/Playground.stories.tsx
  packages/plus/src/components/Navigation/__tests__/__snapshots__/index.test.tsx.snap
  packages/plus/src/components/Navigation/components/Group.tsx
  packages/plus/src/components/Navigation/components/Item.tsx
  packages/plus/src/components/Navigation/components/PinnedItems.tsx
  packages/plus/src/components/Navigation/constants.ts
Labels: enhancement

#4161 refactor(tokens): update gradient color
  .changeset/modern-queens-sneeze.md
  packages/themes/public/style/dark.css
  packages/themes/public/style/darker.css
  packages/themes/public/style/light.css
  packages/themes/src/themes/console/dark.ts
  packages/themes/src/themes/console/darker.ts
  packages/themes/src/themes/console/light.ts
Labels: refactor

#4160 feat(Icon): new system icon stop
  .changeset/beige-spies-complain.md
  packages/icons/src/components/Icon/Icons.tsx
  packages/icons/src/components/Icon/SmallIcons.tsx
  packages/icons/src/components/Icon/assets/default-outline/stop.svg
  packages/icons/src/components/Icon/assets/default-solid/stop.svg
  packages/icons/src/components/Icon/assets/small-outline/stop.svg
  packages/icons/src/components/Icon/assets/small-solid/stop.svg
Labels: enhancement

#4162 feat(ProductIcon): new generative api icon
  .changeset/odd-apricots-kiss.md
  packages/icons/src/components/ProductIcon/Icons.tsx
  packages/icons/src/components/ProductIcon/assets/generative-api.svg
Labels: enhancement
