Repository scaleway/ultraviolet, pull requests merged in 2024-05, with the labels that each got.

#3735 ci: fix check title github action
  .github/workflows/pull_request_title.yml
Labels: enhancement

#3717 feat(Navigation): new pinned feature and reorder
  .changeset/neat-badgers-juggle.md
  packages/plus/src/components/Navigation/NavigationProvider.tsx
  packages/plus/src/components/Navigation/__stories__/Playground.stories.tsx
  packages/plus/src/components/Navigation/components/Group.tsx
  packages/plus/src/components/Navigation/components/Item.tsx
  packages/plus/src/components/Navigation/components/PinnedItems.tsx
  packages/plus/src/components/Navigation/constants.ts
  packages/plus/src/components/Navigation/locales/en.ts
Labels: enhancement

#3740 fix(Navigation): some fixes
  .changeset/tough-moons-listen.md
  packages/plus/src/components/Navigation/components/Item.tsx
Labels: bug

#3744 feat(build): add cjs export and build
  .changeset/thin-gorillas-jump.md
  package.json
  packages/form/package.json
  packages/form/src/components/CheckboxField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/CheckboxGroupField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/DateField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/NumberInputField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/SelectInputField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/SubmitErrorAlert/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/TextInputField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/TimeField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/ToggleGroupField/__tests__/__snapshots__/index.test.tsx.snap
  packages/icons/package.json
  packages/illustrations/package.json
  packages/plus/package.json
  packages/plus/src/components/ContentCard/__tests__/__snapshots__/index.test.tsx.snap
  packages/plus/src/components/ContentCardGroup/__tests__/__snapshots__/index.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/CustomUnitInput.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Item.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Region.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Regular.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Stepper.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Strong.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Unit.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Zone.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/index.test.tsx.snap
  packages/themes/package.json
  packages/ui/package.json
  packages/ui/src/components/Alert/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Avatar/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Banner/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Checkbox/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/CheckboxGroup/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Link/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/NumberInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/PasswordCheck/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectInputV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectableCardGroup/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Separator/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Snippet/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Table/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Tabs/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TextArea/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TextInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TimeInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Toggle/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/ToggleGroup/__tests__/__snapshots__/index.test.tsx.snap
  vite.config.ts
Labels: enhancement

#3747 fix(Navigation): some last fixes on click pin unpin
  .changeset/thin-buckets-burn.md
  packages/plus/src/components/Navigation/NavigationProvider.tsx
  packages/plus/src/components/Navigation/__stories__/Playground.stories.tsx
  packages/plus/src/components/Navigation/components/Item.tsx
  packages/plus/src/components/Navigation/components/PinnedItems.tsx
  packages/plus/src/components/Navigation/constants.ts
  packages/plus/src/components/Navigation/index.ts
  packages/plus/src/components/index.ts
Labels: bug

#3755 ci: fix size limit by testing each packages individually
  .github/workflows/size-limit.yml
  packages/illustrations/package.json
  packages/plus/package.json
Labels: bug

#3729 feat: new icons and product icons
  .changeset/pink-games-check.md
  packages/icons/src/components/Icon/Icons.tsx
  packages/icons/src/components/Icon/SmallIcons.tsx
  packages/icons/src/components/Icon/assets/default/east-short.svg
  packages/icons/src/components/Icon/assets/default/north-short.svg
  packages/icons/src/components/Icon/assets/default/south-short.svg
  packages/icons/src/components/Icon/assets/default/west-short.svg
  packages/icons/src/components/Icon/assets/small/east-short.svg
  packages/icons/src/components/Icon/assets/small/north-short.svg
  packages/icons/src/components/Icon/assets/small/south-short.svg
  packages/icons/src/components/Icon/assets/small/west-short.svg
  packages/icons/src/components/ProductIcon/Icons.tsx
  packages/icons/src/components/ProductIcon/assets/kms.svg
  packages/icons/src/components/ProductIcon/assets/private-ip.svg
  packages/icons/src/components/ProductIcon/assets/quantum-application.svg
Labels: enhancement

#3749 fix(Navigation): to hide unknown pinned items
  .changeset/quick-forks-dream.md
  packages/plus/src/components/Navigation/__stories__/Playground.stories.tsx
  packages/plus/src/components/Navigation/components/PinnedItems.tsx
  packages/plus/src/components/Navigation/index.ts
  packages/plus/src/components/index.ts
Labels: bug

#3736 fix(Popup): reduce margin between trigger button and popup
  .changeset/tasty-colts-fold.md
  packages/form/src/components/SelectInputFieldV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/MenuV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Popup/helpers.ts
  packages/ui/src/components/Popup/index.tsx
  packages/ui/src/components/SelectInputV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Tabs/__tests__/__snapshots__/index.test.tsx.snap
Labels: enhancement

#3745 fix(EmptyState): reduce text sizes on small size
  .changeset/nasty-dolls-visit.md
  packages/ui/src/components/EmptyState/__stories__/InATinySpace.stories.tsx
  packages/ui/src/components/EmptyState/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/EmptyState/index.tsx
Labels: enhancement

#3762 chore: migration to storybook v8 and to vite
  .storybook/components/DocsContainer.tsx
  .storybook/components/Page.tsx
  .storybook/main.ts
  .storybook/manager.ts
  .storybook/preview.tsx
  .storybook/vite.config.ts
  package.json
  packages/form/src/__stories__/Introduction.mdx
  packages/form/src/hooks/__stories__/useOnFieldChange.stories.tsx
  packages/icons/src/__stories__/Introduction.mdx
  packages/icons/src/components/CategoryIcon/__stories__/index.stories.tsx
  packages/icons/src/components/Icon/__stories__/index.stories.tsx
  packages/icons/src/components/ProductIcon/__stories__/List.stories.tsx
  packages/icons/src/components/ProductIcon/__stories__/index.stories.tsx
  packages/illustrations/src/__stories__/Introduction.mdx
  packages/illustrations/src/__stories__/components/ThemeWrapper.tsx
  packages/illustrations/src/__stories__/index.mdx
  packages/plus/src/__stories__/Introduction.mdx
  packages/plus/src/components/EstimateCost/__stories__/Template.tsx
  packages/plus/src/components/EstimateCost/__stories__/index.stories.tsx
  packages/ui/src/__stories__/Changelog/Changelog.stories.tsx
  packages/ui/src/__stories__/Changelog/index.mdx
  packages/ui/src/__stories__/ComponentState/index.mdx
  packages/ui/src/__stories__/Documentation.mdx
  packages/ui/src/__stories__/GetStarted.mdx
  packages/ui/src/__stories__/HowToMakeBreakingChanges.mdx
  packages/ui/src/__stories__/Properties/index.mdx
  packages/ui/src/__stories__/Testing.mdx
  packages/ui/src/__stories__/Tools/index.mdx
  packages/ui/src/__stories__/components/ThemeWrapper.tsx
  packages/ui/src/__stories__/migrations/MigrationMenuV2.mdx
  packages/ui/src/__stories__/migrations/MigrationNumberInputV2.mdx
  packages/ui/src/__stories__/migrations/MigrationNumberInputV2.stories.mdx
  packages/ui/src/__stories__/migrations/MigrationSelectInputV2.mdx
  packages/ui/src/__stories__/migrations/MigrationSelectInputV2.stories.mdx
  packages/ui/src/__stories__/migrations/MigrationTextInputV2.mdx
  packages/ui/src/__stories__/migrations/MigrationTextInputV2.stories.mdx
  packages/ui/src/__stories__/theme/colors.mdx
  packages/ui/src/__stories__/theme/darkMode.mdx
  packages/ui/src/__stories__/theme/shadows.mdx
  packages/ui/src/__stories__/theme/spacesAndRadii.mdx
  packages/ui/src/__stories__/theme/typography.mdx
  packages/ui/src/__stories__/theme/understandTokens.mdx
  pnpm-lock.yaml
Labels: enhancement, refactor

#3772 docs: add some more info
  packages/icons/README.md
  packages/ui/README.md
Labels: documentation

#3774 feat(EstimateCost): add on total price change providing total and total max
  .changeset/silly-chairs-do.md
  packages/plus/src/components/EstimateCost/EstimateCost.tsx
  packages/plus/src/components/EstimateCost/EstimateCostContent.tsx
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Regular.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Stepper.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/index.test.tsx.snap
  packages/plus/src/components/EstimateCost/types.ts
Labels: enhancement

#3775 feat(Toggle): error state
  .changeset/fuzzy-carrots-juggle.md
  packages/form/src/components/ToggleField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/ToggleField/index.tsx
  packages/form/src/components/ToggleGroupField/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Toggle/__stories__/Error.stories.tsx
  packages/ui/src/components/Toggle/__stories__/index.stories.tsx
  packages/ui/src/components/Toggle/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Toggle/__tests__/index.test.tsx
  packages/ui/src/components/Toggle/index.tsx
  packages/ui/src/components/ToggleGroup/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/ToggleGroup/index.tsx
Labels: enhancement

#3779 fix(Navigation): more fixes on how we handle toggle change
  .changeset/twenty-shrimps-talk.md
  packages/plus/src/components/Navigation/Navigation.tsx
  packages/plus/src/components/Navigation/NavigationContent.tsx
  packages/plus/src/components/Navigation/NavigationProvider.tsx
  packages/plus/src/components/Navigation/__stories__/Playground.stories.tsx
  packages/plus/src/components/Navigation/components/Item.tsx
  packages/plus/src/components/Navigation/components/PinnedItems.tsx
  packages/plus/src/components/Navigation/constants.ts
  packages/plus/src/components/Navigation/types.ts
Labels: enhancement

#3776 fix(Navigation): add functionality to disable expand
  .changeset/healthy-squids-sin.md
  packages/plus/src/components/Navigation/NavigationContent.tsx
  packages/plus/src/components/Navigation/NavigationProvider.tsx
  packages/plus/src/components/Navigation/components/PinnedItems.tsx
Labels: enhancement

#3782 fix(Expandable): slight performance improvement on expandable
  .changeset/flat-bats-bow.md
  packages/form/src/components/SelectInputField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/Submit/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/TextInputField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/TimeField/__tests__/__snapshots__/index.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/CustomUnitInput.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Item.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Region.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Regular.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Stepper.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Strong.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Unit.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Zone.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Expandable/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Expandable/__tests__/index.test.tsx
  packages/ui/src/components/Expandable/index.tsx
  packages/ui/src/components/SelectInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Snippet/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TextInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TimeInput/__tests__/__snapshots__/index.test.tsx.snap
Labels: enhancement

#3797 docs(storybook): fix broken stories on form
  .storybook/preview.tsx
  packages/form/src/components/CheckboxField/__stories__/index.stories.tsx
  packages/form/src/components/CheckboxGroupField/__stories__/index.stories.tsx
  packages/form/src/components/DateField/__stories__/index.stories.tsx
  packages/form/src/components/KeyValueField/__stories__/index.stories.tsx
  packages/form/src/components/NumberInputField/__stories__/index.stories.tsx
  packages/form/src/components/NumberInputFieldV2/__stories__/index.stories.tsx
  packages/form/src/components/RadioField/__stories__/index.stories.tsx
  packages/form/src/components/RadioGroupField/__stories__/index.stories.tsx
  packages/form/src/components/SelectInputField/__stories__/index.stories.tsx
  packages/form/src/components/SelectableCardField/__stories__/index.stories.tsx
  packages/form/src/components/SelectableCardGroupField/__stories__/index.stories.tsx
  packages/form/src/components/TagInputField/__stories__/index.stories.tsx
  packages/form/src/components/TextAreaField/__stories__/index.stories.tsx
  packages/form/src/components/TextInputField/__stories__/index.stories.tsx
  packages/form/src/components/TextInputFieldV2/__stories__/index.stories.tsx
  packages/form/src/components/TimeField/__stories__/index.stories.tsx
  packages/form/src/components/ToggleField/__stories__/index.stories.tsx
  packages/form/src/components/ToggleGroupField/__stories__/index.stories.tsx
  packages/ui/src/components/PieChart/__stories__/index.stories.tsx
  packages/ui/src/components/Popover/__stories__/index.stories.tsx
  packages/ui/src/components/Skeleton/__stories__/index.stories.tsx
Labels: bug, documentation

#3798 fix(SelectInputV2): handle change value
  .changeset/flat-lobsters-reply.md
  packages/ui/src/components/SelectInputV2/SelectInputProvider.tsx
  packages/ui/src/components/SelectInputV2/__stories__/Controlled.stories.tsx
  packages/ui/src/components/SelectInputV2/__stories__/index.stories.tsx
  packages/ui/src/components/SelectInputV2/types.ts
Labels: bug

#3804 fix(SelectInput): description and inline description spacing
  .changeset/tender-walls-relate.md
  packages/ui/src/components/SelectInput/index.tsx
Labels: bug

#3805 fix(SelectInputV2): auto focus on search bar
  .changeset/thin-maps-drum.md
  packages/ui/src/components/SelectInputV2/SearchBarDropdown.tsx
  packages/ui/src/components/SelectInputV2/__tests__/__snapshots__/index.test.tsx.snap
Labels: bug

#3806 fix(Navigation): bad typing on locales
  .changeset/forty-pumpkins-wink.md
  packages/plus/src/components/EstimateCost/EstimateCostContent.tsx
  packages/plus/src/components/EstimateCost/EstimateCostProvider.tsx
  packages/plus/src/components/EstimateCost/types.ts
  packages/plus/src/components/Navigation/NavigationProvider.tsx
Labels: bug

#3810 feat(SelectInputV2): allow description as ReactNode and tooltip
  .changeset/pretty-bats-beam.md
  .changeset/twenty-badgers-boil.md
  packages/form/src/components/SelectInputFieldV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectInputV2/DropdownOption.tsx
  packages/ui/src/components/SelectInputV2/__stories__/resources.tsx
  packages/ui/src/components/SelectInputV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectInputV2/__tests__/resources.tsx
  packages/ui/src/components/SelectInputV2/types.ts
  packages/ui/src/components/UnitInput/__tests__/__snapshots__/index.test.tsx.snap
Labels: enhancement

#3801 feat(UnitInputField): new component
  .changeset/modern-suits-burn.md
  packages/form/src/components/UnitInputField/__stories__/Playground.stories.tsx
  packages/form/src/components/UnitInputField/__stories__/Required.stories.tsx
  packages/form/src/components/UnitInputField/__stories__/Template.stories.tsx
  packages/form/src/components/UnitInputField/__stories__/index.stories.tsx
  packages/form/src/components/UnitInputField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/UnitInputField/__tests__/index.test.tsx
  packages/form/src/components/UnitInputField/index.tsx
  packages/form/src/components/index.ts
Labels: enhancement

#3781 feat(Stepper): various enhancements and refactor
  .changeset/gorgeous-weeks-fail.md
  packages/form/src/components/TimeField/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Stepper/Step.tsx
  packages/ui/src/components/Stepper/StepperProvider.tsx
  packages/ui/src/components/Stepper/__stories__/Children.stories.tsx
  packages/ui/src/components/Stepper/__stories__/Disabled.stories.tsx
  packages/ui/src/components/Stepper/__stories__/Example.stories.tsx
  packages/ui/src/components/Stepper/__stories__/Interactive.stories.tsx
  packages/ui/src/components/Stepper/__stories__/LongName.stories.tsx
  packages/ui/src/components/Stepper/__stories__/Playground.stories.tsx
  packages/ui/src/components/Stepper/__stories__/Separator.stories.tsx
  packages/ui/src/components/Stepper/__stories__/Template.stories.tsx
  packages/ui/src/components/Stepper/__stories__/WithAnimation.stories.tsx
  packages/ui/src/components/Stepper/__stories__/index.stories.tsx
  packages/ui/src/components/Stepper/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Stepper/__tests__/index.test.tsx
  packages/ui/src/components/Stepper/index.tsx
Labels: enhancement

#3813 feat: new illustrations and icons
  .changeset/funny-cheetahs-suffer.md
  packages/icons/src/components/ProductIcon/Icons.tsx
  packages/icons/src/components/ProductIcon/assets/delete-marker.svg
  packages/icons/src/components/ProductIcon/assets/iot.svg
  packages/icons/src/components/ProductIcon/assets/ipam.svg
  packages/illustrations/src/products/dediboxVPS/dedibox-vps-content.webp
  packages/illustrations/src/products/dediboxVPS/dedibox-vps-keyvisual.webp
  packages/illustrations/src/products/dediboxVPS/dedibox-vps-original.webp
  packages/illustrations/src/products/dediboxVPS/dedibox-vps-pro-content.webp
  packages/illustrations/src/products/dediboxVPS/dedibox-vps-pro-keyvisual.webp
  packages/illustrations/src/products/dediboxVPS/dedibox-vps-pro-original.webp
  packages/illustrations/src/products/dediboxVPS/dedibox-vps-pro-wire.svg
  packages/illustrations/src/products/dediboxVPS/dedibox-vps-start-content.webp
  packages/illustrations/src/products/dediboxVPS/dedibox-vps-start-keyvisual.webp
  packages/illustrations/src/products/dediboxVPS/dedibox-vps-start-original.webp
  packages/illustrations/src/products/dediboxVPS/dedibox-vps-start-wire.svg
  packages/illustrations/src/products/dediboxVPS/dedibox-vps-wire.svg
  packages/illustrations/src/products/dediboxVPS/index.ts
  packages/illustrations/src/products/index.ts
  packages/illustrations/src/products/kms/index.ts
  packages/illustrations/src/products/kms/kms-content.webp
  packages/illustrations/src/products/kms/kms-keyvisual.webp
  packages/illustrations/src/products/kms/kms-original.webp
  packages/illustrations/src/products/kms/kms-wire.svg
  svgo.config.cjs
Labels: enhancement

#3820 fix: locales vitest
  packages/form/package.json
  packages/form/src/components/TimeField/__tests__/__snapshots__/index.test.tsx.snap
  packages/illustrations/package.json
  packages/plus/package.json
  packages/ui/package.json
Labels: ci

#3828 fix(Illustrations): broken illustrations
  .changeset/wet-drinks-protect.md
  packages/illustrations/src/products/quantum/quantum-wire.svg
  packages/illustrations/src/various/documentation/learning.svg
  packages/illustrations/src/various/documentation/write-community.svg
Labels: bug
