Repository scaleway/ultraviolet, pull requests merged in 2024-11, with the labels that each got.

#4377 fix: slider and popup to work better
  .changeset/dull-buses-boil.md
  packages/form/src/components/SliderField/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Popup/helpers.ts
  packages/ui/src/components/Slider/__tests__/__snapshots__/doubleSlider.test.tsx.snap
  packages/ui/src/components/Slider/__tests__/__snapshots__/singleSlider.test.tsx.snap
  packages/ui/src/components/Slider/components/DoubleSlider.tsx
  packages/ui/src/components/Slider/components/SingleSlider.tsx
  packages/ui/src/components/Slider/constant.ts
  packages/ui/src/components/Slider/styles.ts
Labels: bug

#4392 fix(Card): auto expand height in a row context
  .changeset/thick-queens-brush.md
  packages/plus/src/components/FAQ/__tests__/__snapshots__/index.test.tsx.snap
  packages/plus/src/components/SteppedListCard/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Card/__stories__/Layout.stories.tsx
  packages/ui/src/components/Card/__stories__/index.stories.tsx
  packages/ui/src/components/Card/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Card/index.tsx
Labels: enhancement

#4423 fix(SelectInputV2): fix dropdown align on left
  .changeset/soft-swans-cry.md
  packages/ui/src/components/MenuV2/index.tsx
  packages/ui/src/components/Popover/index.tsx
  packages/ui/src/components/Popup/helpers.ts
  packages/ui/src/components/Popup/index.tsx
  packages/ui/src/components/SelectInputV2/Dropdown.tsx
  packages/ui/src/components/SelectInputV2/__stories__/Playground.stories.tsx
Labels: bug, enhancement

#4429 fix(Meter): remove extra margin bottom
  .changeset/gorgeous-monkeys-remember.md
  packages/ui/src/components/Meter/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Meter/index.tsx
Labels: bug

#4339 feat(SelectInputV2): various improvements
  .changeset/ten-pans-sleep.md
  packages/form/src/components/SelectInputFieldV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectInputV2/Dropdown.tsx
  packages/ui/src/components/SelectInputV2/__stories__/EmptyState.stories.tsx
  packages/ui/src/components/SelectInputV2/__stories__/Footer.stories.tsx
  packages/ui/src/components/SelectInputV2/__stories__/Modal.stories.tsx
  packages/ui/src/components/SelectInputV2/__stories__/Searchable.stories.tsx
  packages/ui/src/components/SelectInputV2/__stories__/index.stories.tsx
  packages/ui/src/components/SelectInputV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectInputV2/__tests__/index.test.tsx
  packages/ui/src/components/SelectInputV2/index.tsx
Labels: enhancement

#4383 ci: add publint to check on package json and avoid mistakes
  .github/workflows/ci.yml
  package.json
  packages/form/package.json
  packages/icons/package.json
  packages/illustrations/package.json
  packages/plus/package.json
  packages/themes/package.json
  packages/ui/package.json
  pnpm-lock.yaml
  turbo.json
Labels: enhancement, ci

#4451 docs(storybook): fix margins set by docs container
  .storybook/components/globalStyle.ts
  packages/ui/src/components/SelectInputV2/__stories__/resources.tsx
Labels: documentation, enhancement

#4452 fix(ContentCard): space between body and button
  .changeset/lemon-lizards-sell.md
  packages/plus/src/components/ContentCard/__stories__/Examples.stories.tsx
  packages/plus/src/components/ContentCard/__tests__/__snapshots__/index.test.tsx.snap
  packages/plus/src/components/ContentCard/index.tsx
Labels: enhancement

#4461 fix: added new description prop to group inputs
  .changeset/great-grapes-pretend.md
  packages/form/src/components/CheckboxGroupField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/RadioGroupField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/SelectableCardField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/ToggleGroupField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/ToggleGroupField/index.tsx
  packages/ui/src/components/CheckboxGroup/__stories__/Description.stories.tsx
  packages/ui/src/components/CheckboxGroup/__stories__/index.stories.tsx
  packages/ui/src/components/CheckboxGroup/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/CheckboxGroup/index.tsx
  packages/ui/src/components/RadioGroup/__stories__/Description.stories.tsx
  packages/ui/src/components/RadioGroup/__stories__/index.stories.tsx
  packages/ui/src/components/RadioGroup/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/RadioGroup/index.tsx
  packages/ui/src/components/SelectableCard/__stories__/Children.stories.tsx
  packages/ui/src/components/SelectableCard/__stories__/Illustration.stories.tsx
  packages/ui/src/components/SelectableCard/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectableCard/index.tsx
  packages/ui/src/components/ToggleGroup/__stories__/Description.stories.tsx
  packages/ui/src/components/ToggleGroup/__stories__/index.stories.tsx
  packages/ui/src/components/ToggleGroup/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/ToggleGroup/index.tsx
Labels: enhancement

#4468 fix(SliderField): check if value exists
  .changeset/calm-icons-dance.md
  packages/form/src/components/SliderField/index.tsx
Labels: bug

#4471 fix(Navigation): pin button disabled still working
  .changeset/weak-kings-taste.md
  packages/plus/src/components/Navigation/__stories__/Playground.stories.tsx
  packages/plus/src/components/Navigation/components/Item.tsx
Labels: bug

#4472 fix(Skeleton): due to px to rem migration skeleton is broken
  .changeset/orange-pots-explain.md
  packages/plus/src/components/ContentCard/__tests__/__snapshots__/index.test.tsx.snap
  packages/plus/src/components/ContentCardGroup/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Skeleton/Donut.tsx
  packages/ui/src/components/Skeleton/Line.tsx
  packages/ui/src/components/Skeleton/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Table/__tests__/__snapshots__/index.test.tsx.snap
Labels: bug

#4487 feat(icons): add new adjustments horizontal
  .changeset/perfect-onions-tie.md
  packages/icons/src/components/Icon/__generatedIcons__/AdjustmentsHorizontalIcon.tsx
  packages/icons/src/components/Icon/__generatedIcons__/AdjustmentsHorizontalOutlineIcon.tsx
  packages/icons/src/components/Icon/__generatedIcons__/index.ts
  packages/icons/src/components/Icon/assets/default-outline/adjustments-horizontal.svg
  packages/icons/src/components/Icon/assets/default-solid/adjustments-horizontal.svg
  packages/icons/src/components/Icon/assets/small-outline/adjustments-horizontal.svg
  packages/icons/src/components/Icon/assets/small-solid/adjustments-horizontal.svg
Labels: enhancement

#4489 refactor(EstimateCost): improve re-render performances
  .changeset/spicy-months-sniff.md
  packages/plus/src/components/EstimateCost/Components/CustomUnitInput.tsx
  packages/plus/src/components/EstimateCost/Components/Item.tsx
  packages/plus/src/components/EstimateCost/Components/Region.tsx
  packages/plus/src/components/EstimateCost/Components/Regular.tsx
  packages/plus/src/components/EstimateCost/Components/Strong.tsx
  packages/plus/src/components/EstimateCost/Components/Zone.tsx
  packages/plus/src/components/EstimateCost/EstimateCostContent.tsx
  packages/plus/src/components/EstimateCost/__stories__/Unit.stories.tsx
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Item.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Regular.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Stepper.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Strong.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Unit.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Zone.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/index.test.tsx.snap
Labels: enhancement

#4488 fix(SelectableCard): content not to have weak color
  .changeset/eighty-lizards-search.md
  packages/form/src/components/SelectableCardField/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectableCard/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectableCard/index.tsx
Labels: bug

#4499 fix(Snippet): snippet height
  .changeset/hot-rockets-watch.md
  packages/ui/src/components/Snippet/__stories__/Multiline.stories.tsx
  packages/ui/src/components/Snippet/__stories__/Prefixes.stories.tsx
  packages/ui/src/components/Snippet/__stories__/Rows.stories.tsx
  packages/ui/src/components/Snippet/index.tsx
Labels: bug

#4476 docs(storybook): add tags and fix component state
  .storybook/main.ts
  .storybook/manager.ts
  package.json
  packages/form/src/components/NumberInputField/__stories__/index.stories.tsx
  packages/form/src/components/SelectInputField/__stories__/index.stories.tsx
  packages/form/src/components/TextInputField/__stories__/index.stories.tsx
  packages/ui/src/__stories__/ComponentState/ComponentState.tsx
  packages/ui/src/components/Avatar/__stories__/index.stories.tsx
  packages/ui/src/components/Dialog/__stories__/index.stories.tsx
  packages/ui/src/components/LineChart/__stories__/index.stories.tsx
  packages/ui/src/components/Menu/__stories__/index.stories.tsx
  packages/ui/src/components/NumberInput/__stories__/index.stories.tsx
  packages/ui/src/components/NumberInputV2/__stories__/index.stories.tsx
  packages/ui/src/components/PasswordStrengthMeter/__stories__/index.stories.tsx
  packages/ui/src/components/PieChart/__stories__/index.stories.tsx
  packages/ui/src/components/Row/__stories__/index.stories.tsx
  packages/ui/src/components/Row/index.tsx
  packages/ui/src/components/SelectInput/__stories__/index.stories.tsx
  packages/ui/src/components/SelectInputV2/__stories__/index.stories.tsx
  packages/ui/src/components/Slider/__stories__/index.stories.tsx
  packages/ui/src/components/StepList/__stories__/index.stories.tsx
  packages/ui/src/components/TextInput/__stories__/index.stories.tsx
  packages/ui/src/components/TextInputV2/__stories__/index.stories.tsx
  packages/ui/src/components/TimeInput/__stories__/index.stories.tsx
  pnpm-lock.yaml
Labels: documentation

#4491 fix(Navigation): segment components in sub components
  packages/plus/src/components/Navigation/Footer.tsx
  packages/plus/src/components/Navigation/Header.tsx
  packages/plus/src/components/Navigation/NavigationContent.tsx
  packages/plus/src/components/Navigation/__tests__/__snapshots__/index.test.tsx.snap
  packages/plus/src/components/Navigation/components/Item.tsx
Labels: enhancement

#4506 docs: remove deprecated usages from documentation
  packages/ui/src/__stories__/Tools/ThemeGenerator/ThemeResult/Demo.tsx
  packages/ui/src/components/List/__stories__/Example.stories.tsx
  packages/ui/src/components/MenuV2/__stories__/WithModal.stories.tsx
  packages/ui/src/components/Meter/__stories__/Playground.stories.tsx
  packages/ui/src/components/Notification/__stories__/Children.tsx
  packages/ui/src/components/PasswordStrengthMeter/__stories__/Estimate.stories.tsx
  packages/ui/src/components/PasswordStrengthMeter/__stories__/ForbiddenInputs.stories.tsx
  packages/ui/src/components/PasswordStrengthMeter/__stories__/Playground.stories.tsx
  packages/ui/src/components/Popover/__stories__/AdvancedUsage.stories.tsx
  packages/ui/src/components/Popover/__tests__/index.test.tsx
  packages/ui/src/components/SelectableCard/__stories__/Children.stories.tsx
Labels: documentation, enhancement

#4516 fix(fonts): wrongly written semi bold
  .changeset/smooth-cougars-bake.md
  packages/fonts/src/fonts.css
Labels: bug
