Repository scaleway/ultraviolet, pull requests merged in 2024-01, with the labels that each got.

#3267 fix: groups radio and checkbox to have better spacing in row
  .changeset/warm-parents-crash.md
  packages/form/src/components/CheckboxField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/CheckboxGroupField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/RadioField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/RadioGroupField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/SelectableCardField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/ui/src/components/Checkbox/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Checkbox/index.tsx
  packages/ui/src/components/CheckboxGroup/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/LineChart/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Radio/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Radio/index.tsx
  packages/ui/src/components/RadioGroup/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectableCard/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SwitchButton/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Table/__tests__/__snapshots__/index.test.tsx.snap
Labels: enhancement

#3292 docs: fix storybook and add more readme
  .storybook/components/Page.tsx
  .storybook/preview.tsx
  README.md
  packages/icons/CHANGELOG.md
  packages/ui/src/__stories__/Properties/Properties.tsx
Labels: documentation

#3297 fix(ProductIcon): color bug with theme on some icons
  .changeset/dirty-ducks-yawn.md
  packages/icons/src/components/ProductIcon/assets/file.svg
  packages/icons/src/components/ProductIcon/assets/ipfs-naming.svg
  packages/icons/src/components/ProductIcon/assets/sepa.svg
  packages/icons/src/components/ProductIcon/assets/silver-support.svg
Labels: bug

#3310 fix(Banner): default illustration to be correctly imported
  .changeset/brown-otters-repair.md
  packages/ui/src/components/Banner/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Banner/index.tsx
Labels: bug

#3270 feat(plus): add customer satisfaction components
  .changeset/funny-eyes-repair.md
  packages/plus/global.d.ts
  packages/plus/src/components/CustomerSatisfaction/__stories__/Playground.stories.tsx
  packages/plus/src/components/CustomerSatisfaction/__stories__/Template.stories.tsx
  packages/plus/src/components/CustomerSatisfaction/__stories__/index.stories.tsx
  packages/plus/src/components/CustomerSatisfaction/__tests__/__snapshots__/index.tsx.snap
  packages/plus/src/components/CustomerSatisfaction/__tests__/index.tsx
  packages/plus/src/components/CustomerSatisfaction/assets/1-5.svg
  packages/plus/src/components/CustomerSatisfaction/assets/1-5NB.svg
  packages/plus/src/components/CustomerSatisfaction/assets/2-5.svg
  packages/plus/src/components/CustomerSatisfaction/assets/2-5NB.svg
  packages/plus/src/components/CustomerSatisfaction/assets/3-5.svg
  packages/plus/src/components/CustomerSatisfaction/assets/3-5NB.svg
  packages/plus/src/components/CustomerSatisfaction/assets/4-5.svg
  packages/plus/src/components/CustomerSatisfaction/assets/4-5NB.svg
  packages/plus/src/components/CustomerSatisfaction/assets/5-5.svg
  packages/plus/src/components/CustomerSatisfaction/assets/5-5NB.svg
  packages/plus/src/components/CustomerSatisfaction/index.tsx
  packages/plus/src/components/index.ts
  packages/plus/tsconfig.json
Labels: enhancement, design system

#3315 refactor: fix svgs in all repo with svgr webpack for storybook and rollup for bundle
  .changeset/brave-donkeys-bake.md
  .jest/svg.ts
  .jest/unit.config.ts
  .storybook/main.ts
  global.d.ts
  package.json
  packages/icons/global.d.ts
  packages/icons/src/components/CategoryIcon/Icons.tsx
  packages/icons/src/components/CategoryIcon/__tests__/__snapshots__/index.tsx.snap
  packages/icons/src/components/CategoryIcon/__tests__/index.tsx
  packages/icons/src/components/CategoryIcon/index.tsx
  packages/icons/src/components/ProductIcon/Icons.tsx
  packages/icons/src/components/ProductIcon/__tests__/__snapshots__/index.tsx.snap
  packages/icons/src/components/ProductIcon/__tests__/index.tsx
  packages/icons/src/components/ProductIcon/index.tsx
  packages/icons/tsconfig.json
  packages/ui/src/components/Banner/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/Banner/index.tsx
  pnpm-lock.yaml
  rollup.config.mjs
Labels: bug, refactor

#3317 fix: remove useless props spread to dom on some components and fix tests
  .changeset/pink-bees-sing.md
  .changeset/pink-bees-song.md
  .jest/setupTests.ts
  packages/form/src/components/CheckboxField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/CheckboxGroupField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/plus/src/components/ContentCard/__tests__/__snapshots__/index.test.tsx.snap
  packages/plus/src/components/EstimateCost/Components/Item.tsx
  packages/plus/src/components/EstimateCost/__tests__/Item.spec.tsx
  packages/plus/src/components/EstimateCost/__tests__/LineThrough.spec.tsx
  packages/plus/src/components/EstimateCost/__tests__/Region.spec.tsx
  packages/plus/src/components/EstimateCost/__tests__/Regular.spec.tsx
  packages/plus/src/components/EstimateCost/__tests__/Stepper.spec.tsx
  packages/plus/src/components/EstimateCost/__tests__/Strong.spec.tsx
  packages/plus/src/components/EstimateCost/__tests__/Unit.spec.tsx
  packages/plus/src/components/EstimateCost/__tests__/Zone.spec.tsx
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Item.spec.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Region.spec.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Regular.spec.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Stepper.spec.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Strong.spec.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Unit.spec.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Zone.spec.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/index.spec.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/index.spec.tsx
  packages/plus/src/components/EstimateCost/componentStyle.ts
  packages/ui/src/components/Checkbox/__tests__/__snapshots__/index.tsx.snap
  packages/ui/src/components/CheckboxGroup/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/GlobalAlert/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/GlobalAlert/__tests__/index.test.tsx
  packages/ui/src/components/LineChart/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/NumberInput/__tests__/index.test.tsx
  packages/ui/src/components/SelectableCard/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Stack/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Stack/index.tsx
  packages/ui/src/components/Table/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TextInput/__tests__/index.test.tsx
Labels: enhancement

#3244 feat(NumberInputV2): new component
  .changeset/itchy-comics-teach.md
  packages/form/src/components/NumberInputFieldV2/__stories__/Playground.stories.tsx
  packages/form/src/components/NumberInputFieldV2/__stories__/Required.stories.tsx
  packages/form/src/components/NumberInputFieldV2/__stories__/Template.stories.tsx
  packages/form/src/components/NumberInputFieldV2/__stories__/index.stories.tsx
  packages/form/src/components/NumberInputFieldV2/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/NumberInputFieldV2/__tests__/index.spec.tsx
  packages/form/src/components/NumberInputFieldV2/index.tsx
  packages/form/src/components/index.ts
  packages/ui/src/__stories__/migrations/MigrationMenuV2.stories.mdx
  packages/ui/src/__stories__/migrations/MigrationNumberInputV2.stories.mdx
  packages/ui/src/components/NumberInputV2/__stories__/Disabled.stories.tsx
  packages/ui/src/components/NumberInputV2/__stories__/Error.stories.tsx
  packages/ui/src/components/NumberInputV2/__stories__/Helper.stories.tsx
  packages/ui/src/components/NumberInputV2/__stories__/LabelDescription.stories.tsx
  packages/ui/src/components/NumberInputV2/__stories__/MinMax.stories.tsx
  packages/ui/src/components/NumberInputV2/__stories__/Placeholder.stories.tsx
  packages/ui/src/components/NumberInputV2/__stories__/Playground.stories.tsx
  packages/ui/src/components/NumberInputV2/__stories__/ReadOnly.stories.tsx
  packages/ui/src/components/NumberInputV2/__stories__/Sizes.stories.tsx
  packages/ui/src/components/NumberInputV2/__stories__/Step.stories.tsx
  packages/ui/src/components/NumberInputV2/__stories__/Success.stories.tsx
  packages/ui/src/components/NumberInputV2/__stories__/Template.stories.tsx
  packages/ui/src/components/NumberInputV2/__stories__/Unit.stories.tsx
  packages/ui/src/components/NumberInputV2/__stories__/index.stories.tsx
  packages/ui/src/components/NumberInputV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/NumberInputV2/__tests__/index.test.tsx
  packages/ui/src/components/NumberInputV2/index.tsx
  packages/ui/src/components/index.ts
Labels: enhancement

#3332 fix: export KeyValueField component
  .changeset/wet-boxes-complain.md
  packages/form/src/index.ts
Labels: design system

#3328 fix(CustomerSatisfaction): error on display images on storybook
  .changeset/polite-dryers-wonder.md
  packages/plus/global.d.ts
  packages/plus/src/components/CustomerSatisfaction/__stories__/Template.stories.tsx
  packages/plus/src/components/CustomerSatisfaction/__tests__/__snapshots__/index.tsx.snap
  packages/plus/src/components/CustomerSatisfaction/index.tsx
  packages/plus/tsconfig.json
Labels: bug

#3331 docs: fix readme to include space grotesk fonts
  packages/ui/README.md
Labels: documentation

#3311 docs(storybook): fix logo using png file
  .storybook/assets/logo-dark.png
  .storybook/assets/logo-dark.svg
  .storybook/assets/logo-light.png
  .storybook/assets/logo-light.svg
  .storybook/storybookThemes.ts
Labels: bug, documentation

#3333 refactor: remove create ref usaged that can be replace by use ref
  .changeset/friendly-camels-care.md
  packages/plus/src/components/ContentCard/index.tsx
  packages/ui/src/components/Modal/Disclosure.tsx
Labels: enhancement

#3330 docs: fix number and text input fields v2 to have better documentation
  packages/form/src/components/NumberInputFieldV2/__stories__/index.stories.tsx
  packages/form/src/components/TextInputFieldV2/__stories__/index.stories.tsx
  packages/ui/src/components/Breadcrumbs/__stories__/To.stories.tsx
Labels: documentation

#3349 feat(ProductIcon): new product icon names
  .changeset/friendly-zebras-jump.md
  packages/icons/src/components/ProductIcon/Icons.tsx
  packages/icons/src/components/ProductIcon/assets/dedicated-control-plane.svg
  packages/icons/src/components/ProductIcon/assets/distributed-data-lab.svg
  packages/icons/src/components/ProductIcon/assets/jero.svg
  packages/icons/src/components/ProductIcon/assets/nabu.svg
  packages/icons/src/components/ProductIcon/assets/qaas.svg
  packages/icons/src/components/ProductIcon/assets/router.svg
  packages/illustrations/src/products/quantum/quantum-wire.svg
  packages/plus/src/components/ContentCard/assets/illustration2.svg
  packages/plus/src/components/EstimateCost/__stories__/assets/fr.svg
  packages/plus/src/components/EstimateCost/__stories__/assets/nl.svg
  packages/plus/src/components/EstimateCost/__tests__/assets/fr.svg
  packages/ui/src/components/Banner/assets/default-image-small.svg
  packages/ui/src/components/Banner/assets/default-image.svg
Labels: enhancement

#3364 feat(illustrations): add new 404 illustration
  .changeset/itchy-shirts-jump.md
  packages/illustrations/src/various/feedback/404.svg
  packages/illustrations/src/various/feedback/index.ts
  packages/illustrations/src/various/index.ts
Labels: enhancement

#3350 fix: v2 inputs to have body strong variant
  .changeset/quick-panthers-punch.md
  packages/form/src/components/NumberInputFieldV2/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/TextAreaField/__tests__/__snapshots__/index.spec.tsx.snap
  packages/form/src/components/TextInputFieldV2/__tests__/__snapshots__/index.spec.tsx.snap
  packages/ui/src/components/NumberInputV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/NumberInputV2/index.tsx
  packages/ui/src/components/TextArea/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TextArea/index.tsx
  packages/ui/src/components/TextInputV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TextInputV2/index.tsx
Labels: enhancement

#3368 fix: export number input and text input v2
  .changeset/fluffy-rules-talk.md
  packages/form/src/index.ts
Labels: refactor

#3367 fix: radio group and checkbox group to have the correct style
  .changeset/grumpy-phones-own.md
  packages/ui/src/components/CheckboxGroup/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/CheckboxGroup/index.tsx
  packages/ui/src/components/RadioGroup/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/RadioGroup/index.tsx
Labels: bug

#3382 fix(MenuV2): to spread onclick of the disclosure
  .changeset/chatty-snakes-vanish.md
  packages/ui/src/components/MenuV2/index.tsx
Labels: bug
