Repository scaleway/ultraviolet, pull requests merged in 2025-10, with the labels that each got.

#5598 refactor(Skeleton): vanilla extract
  .changeset/silver-tools-add.md
  packages/plus/src/components/ContentCard/__tests__/__snapshots__/index.test.tsx.snap
  packages/plus/src/components/ContentCardGroup/__tests__/__snapshots__/index.test.tsx.snap
  packages/plus/src/components/OfferList/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/BarStack/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/BarStack/index.tsx
  packages/ui/src/components/BarStack/styles.css.ts
  packages/ui/src/components/BarStack/variables.css.ts
  packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Skeleton/Block.tsx
  packages/ui/src/components/Skeleton/Blocks.tsx
  packages/ui/src/components/Skeleton/BoxWithIcon.tsx
  packages/ui/src/components/Skeleton/Donut.tsx
  packages/ui/src/components/Skeleton/IconSkeleton.tsx
  packages/ui/src/components/Skeleton/Line.tsx
  packages/ui/src/components/Skeleton/List.tsx
  packages/ui/src/components/Skeleton/Slider.tsx
  packages/ui/src/components/Skeleton/Square.tsx
  packages/ui/src/components/Skeleton/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Skeleton/index.tsx
  packages/ui/src/components/Skeleton/styles.css.ts
  packages/ui/src/components/Skeleton/stylesVariants.css.ts
  packages/ui/src/components/Table/__tests__/__snapshots__/index.test.tsx.snap
Labels: refactor

#5629 ci: update codeowner to avoid spam
  .github/CODEOWNERS
Labels: ci

#5617 feat(ProductIcon): mailbox icon
  .changeset/deep-waves-count.md
  packages/icons/src/components/ProductIcon/__generated__/MailboxProductIcon.tsx
  packages/icons/src/components/ProductIcon/__generated__/index.ts
  packages/icons/src/components/ProductIcon/assets/mailbox.svg
Labels: enhancement

#5614 refactor: tagInput and tagList vanilla extract
  .changeset/lazy-lights-invent.md
  packages/form/src/components/TagInputField/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TagInput/__stories__/Size.stories.tsx
  packages/ui/src/components/TagInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TagInput/index.tsx
  packages/ui/src/components/TagInput/styles.css.ts
  packages/ui/src/components/TagList/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TagList/__tests__/index.test.tsx
  packages/ui/src/components/TagList/constant.ts
  packages/ui/src/components/TagList/index.tsx
  packages/ui/src/components/TagList/styles.css.ts
Labels: refactor

#5624 refactor(DateInput): vanilla extract
  .changeset/whole-actors-prove.md
  packages/form/src/components/DateInputField/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/DateInput/components/CalendarContent.tsx
  packages/ui/src/components/DateInput/components/CalendarDaily.tsx
  packages/ui/src/components/DateInput/components/CalendarMonthly.tsx
  packages/ui/src/components/DateInput/components/Popup.tsx
  packages/ui/src/components/DateInput/components/styles.css.ts
  packages/ui/src/components/DateInput/helpers.ts
  packages/ui/src/components/DateInput/index.tsx
  packages/ui/src/components/DateInput/styles.css.ts
Labels: refactor

#5608 refactor(TextInput): migrate to vanilla extract
  .changeset/public-fans-dance.md
  packages/form/src/components/DateInputField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/Submit/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/TextInputField/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SearchInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SearchInput/index.tsx
  packages/ui/src/components/SelectInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TextInput/__stories__/Size.stories.tsx
  packages/ui/src/components/TextInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TextInput/constants.ts
  packages/ui/src/components/TextInput/index.tsx
  packages/ui/src/components/TextInput/styles.css.ts
Labels: refactor

#5634 refactor(SwitchButton): vanilla extract
  .changeset/ten-wolves-battle.md
  packages/form/src/components/SwitchButtonField/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SwitchButton/FocusOverlay.tsx
  packages/ui/src/components/SwitchButton/Option.tsx
  packages/ui/src/components/SwitchButton/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SwitchButton/index.tsx
  packages/ui/src/components/SwitchButton/styles.css.ts
Labels: refactor
