Repository scaleway/ultraviolet, pull requests merged in 2025-03, with the labels that each got.

#4839 fix(SelectInput): wrong arrow size
  .changeset/sixty-nights-grab.md
  packages/form/src/components/SelectInputField/__tests__/__snapshots__/index.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/CustomUnitInput.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Item.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Region.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Regular.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Stepper.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Strong.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Unit.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Zone.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectInput/index.tsx
Labels: bug

#4826 feat(illustrations): new illustration instance scaling group
  .changeset/two-zoos-cry.md
  packages/illustrations/src/assets/products/instance/index.ts
  packages/illustrations/src/assets/products/instance/instance-scaling-groups-content.webp
  packages/illustrations/src/assets/products/instance/instance-scaling-groups-keyvisual.webp
  packages/illustrations/src/assets/products/instance/instance-scaling-groups-original.webp
  packages/illustrations/src/assets/products/instance/instance-scaling-groups-wire.svg
Labels: enhancement

#4828 fix(Dialog): add disabled prop on button cancel
  .changeset/six-meals-knock.md
  packages/ui/src/components/Dialog/components/Button.tsx
  packages/ui/src/components/Dialog/components/Buttons.tsx
  packages/ui/src/components/Dialog/components/CancelButton.tsx
  packages/ui/src/components/Dialog/components/Stack.tsx
  packages/ui/src/components/Dialog/components/Text.tsx
  packages/ui/src/components/Dialog/index.tsx
Labels: refactor

#4842 fix(Banner): component not to have correct image size
  .changeset/four-spoons-laugh.md
  packages/ui/src/components/Banner/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Banner/index.tsx
Labels: bug

#4841 fix(Slider): inputs sizes and labels
  .changeset/weak-queens-wave.md
  packages/form/src/components/SliderField/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Slider/__tests__/__snapshots__/doubleSlider.test.tsx.snap
  packages/ui/src/components/Slider/__tests__/__snapshots__/singleSlider.test.tsx.snap
  packages/ui/src/components/Slider/components/DoubleSlider.tsx
  packages/ui/src/components/Slider/components/Label.tsx
  packages/ui/src/components/Slider/components/SingleSlider.tsx
  packages/ui/src/components/Text/index.tsx
Labels: bug

#4636 fix: shift select
  .changeset/strange-socks-beam.md
  packages/form/src/components/SliderField/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/List/ListContext.tsx
  packages/ui/src/components/List/Row.tsx
  packages/ui/src/components/List/__stories__/Selectable.stories.tsx
  packages/ui/src/components/List/index.tsx
  packages/ui/src/components/Slider/__tests__/__snapshots__/doubleSlider.test.tsx.snap
  packages/ui/src/components/Slider/__tests__/__snapshots__/singleSlider.test.tsx.snap
  packages/ui/src/components/Table/Row.tsx
  packages/ui/src/components/Table/__stories__/Selectable.stories.tsx
  packages/ui/src/components/Table/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Table/__tests__/index.test.tsx
  packages/ui/src/components/Table/index.tsx
Labels: enhancement

#4824 chore: remove unused react-datepicker
  package.json
  packages/ui/package.json
  pnpm-lock.yaml
Labels: refactor

#4870 fix(SelectableCard): make label clickable by removing pointer events to none
  .changeset/brown-months-repeat.md
  packages/form/src/components/SelectableCardField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/SelectableCardGroupField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/SelectableCardOptionGroupField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/SwitchButtonField/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Checkbox/index.tsx
  packages/ui/src/components/Radio/index.tsx
  packages/ui/src/components/SelectableCard/__stories__/Examples.stories.tsx
  packages/ui/src/components/SelectableCard/__stories__/Illustration.stories.tsx
  packages/ui/src/components/SelectableCard/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectableCard/__tests__/index.test.tsx
  packages/ui/src/components/SelectableCard/index.tsx
  packages/ui/src/components/SelectableCardGroup/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectableCardOptionGroup/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectableCardOptionGroup/__tests__/index.test.tsx
  packages/ui/src/components/SelectableCardOptionGroup/components/Option.tsx
  packages/ui/src/components/SwitchButton/__tests__/__snapshots__/index.test.tsx.snap
Labels: bug

#4855 fix(ProgressBar): allow value to be above maximum
  .changeset/tasty-olives-flash.md
  packages/ui/src/components/ProgressBar/__stories__/Overflow.stories.tsx
  packages/ui/src/components/ProgressBar/__stories__/index.stories.tsx
  packages/ui/src/components/ProgressBar/index.tsx
Labels: bug

#4872 fix(Radio): to have correct id when the label is complexe
  .changeset/bright-pens-take.md
  packages/ui/src/components/Radio/index.tsx
Labels: bug

#4846 feat(InfiniteScroll): new component
  .changeset/early-cameras-work.md
  packages/ui/src/components/InfiniteScroll/__stories__/Playground.stories.tsx
  packages/ui/src/components/InfiniteScroll/__stories__/SelectInput.stories.tsx
  packages/ui/src/components/InfiniteScroll/__stories__/Table.stories.tsx
  packages/ui/src/components/InfiniteScroll/__stories__/Template.stories.tsx
  packages/ui/src/components/InfiniteScroll/__stories__/data.ts
  packages/ui/src/components/InfiniteScroll/__stories__/index.stories.tsx
  packages/ui/src/components/InfiniteScroll/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/InfiniteScroll/__tests__/index.test.tsx
  packages/ui/src/components/InfiniteScroll/index.tsx
  packages/ui/src/components/Loader/index.tsx
  packages/ui/src/components/Stack/index.tsx
  packages/ui/src/components/index.ts
Labels: enhancement

#4888 fix(SelectableCard): wrong layout
  .changeset/social-buses-post.md
  packages/form/src/components/SelectableCardOptionGroupField/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectableCard/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectableCard/index.tsx
  packages/ui/src/components/SelectableCardOptionGroup/__tests__/__snapshots__/index.test.tsx.snap
Labels: bug

#4886 fix(SelectInputV2): change dropdown scroll to auto
  .changeset/soft-taxis-wink.md
  packages/form/src/components/SelectInputFieldV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectInputV2/Dropdown.tsx
  packages/ui/src/components/UnitInput/__tests__/__snapshots__/index.test.tsx.snap
Labels: bug

#4890 fix(SelectableCardOptionGroup): add missing tooltip
  .changeset/tender-parts-sin.md
  packages/form/src/components/SelectableCardOptionGroupField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/SelectableCardOptionGroupField/index.tsx
  packages/ui/src/components/SelectableCardOptionGroup/__stories__/Disabled.stories.tsx
  packages/ui/src/components/SelectableCardOptionGroup/components/Option.tsx
Labels: enhancement

#4847 fix(SteppedListCard): rename component and add prop completed
  .changeset/brown-pillows-enjoy.md
  packages/plus/src/components/SteppedListCard/Step.tsx
  packages/plus/src/components/SteppedListCard/SteppedListCard.tsx
  packages/plus/src/components/SteppedListCard/SteppedListContent.tsx
  packages/plus/src/components/SteppedListCard/__stories__/OnClickHide.stories.tsx
  packages/plus/src/components/SteppedListCard/__stories__/Template.stories.tsx
  packages/plus/src/components/SteppedListCard/__stories__/WithoutToggleButton.stories.tsx
  packages/plus/src/components/SteppedListCard/__stories__/index.stories.tsx
  packages/plus/src/components/SteppedListCard/__tests__/__snapshots__/index.test.tsx.snap
  packages/plus/src/components/SteppedListCard/__tests__/index.test.tsx
  packages/plus/src/components/SteppedListCard/index.ts
  packages/plus/src/components/index.ts
Labels: breaking changes

#4910 feat(illustrations): new illustration local storage
  .changeset/flat-clubs-punch.md
  packages/illustrations/src/assets/products/index.ts
  packages/illustrations/src/assets/products/localStorage/index.ts
  packages/illustrations/src/assets/products/localStorage/local-storage-content.webp
  packages/illustrations/src/assets/products/localStorage/local-storage-keyvisual.webp
  packages/illustrations/src/assets/products/localStorage/local-storage-original.webp
  packages/illustrations/src/assets/products/localStorage/local-storage-wire.svg
Labels: enhancement

#4913 fix(TagList): better popover
  .changeset/thick-insects-mate.md
  packages/ui/src/components/Popover/index.tsx
Labels: enhancement

#4893 fix(Navigation): implement item provider to detect parents
  .changeset/solid-socks-hunt.md
  packages/plus/src/components/Navigation/components/Item.tsx
  packages/plus/src/components/Navigation/components/ItemProvider.tsx
  packages/plus/src/components/Navigation/components/PinnedItems.tsx
Labels: enhancement

#4871 ci(SelectableCard): add test to get by role checkbox or radio
  packages/ui/src/components/SelectableCard/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectableCard/__tests__/index.test.tsx
Labels: ci

#4895 feat(MenuV2): add empty state on groups
  .changeset/every-pianos-hide.md
  packages/ui/src/components/MenuV2/__stories__/Searchable.stories.tsx
  packages/ui/src/components/MenuV2/components/Group.tsx
Labels: enhancement

#4909 fix(InfiniteScroll): improve accessibility
  .changeset/smooth-bottles-agree.md
  packages/ui/src/components/InfiniteScroll/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/InfiniteScroll/index.tsx
Labels: enhancement

#4894 fix(SelectInputFieldV2): call on change after field value change
  .changeset/ripe-webs-shine.md
  packages/form/src/components/SelectInputFieldV2/index.tsx
Labels: bug

#4947 feat(TextInputV2): add examples password
  packages/ui/src/components/TextInputV2/__stories__/Password.stories.tsx
Labels: documentation

#4957 fix(SelectableCardOptionGroupField): add new prop option name
  .changeset/afraid-yaks-happen.md
  packages/form/src/components/SelectableCardOptionGroupField/__stories__/OptionName.stories.tsx
  packages/form/src/components/SelectableCardOptionGroupField/__stories__/index.stories.tsx
  packages/form/src/components/SelectableCardOptionGroupField/__tests__/index.test.tsx
  packages/form/src/components/SelectableCardOptionGroupField/index.tsx
  packages/form/src/components/UnitInputField/__stories__/OptionName.stories.tsx
  packages/form/src/components/UnitInputField/__stories__/index.stories.tsx
  packages/form/src/components/UnitInputField/__tests__/index.test.tsx
  packages/form/src/components/UnitInputField/index.tsx
Labels: enhancement
