Repository scaleway/ultraviolet, pull requests merged in 2025-04, with the labels that each got.

#4960 fix(Navigation): wrong alignemenet on pin unpin buttons
  .changeset/stupid-cooks-study.md
  packages/plus/src/components/Navigation/__tests__/__snapshots__/index.test.tsx.snap
  packages/plus/src/components/Navigation/components/Item.tsx
Labels: bug

#4975 fix(SelectableCard): make parent container relative
  .changeset/eager-times-watch.md
  packages/form/src/components/SelectableCardField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/SelectableCardGroupField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/SelectableCardOptionGroupField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/SwitchButtonField/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectableCard/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectableCard/index.tsx
  packages/ui/src/components/SelectableCardGroup/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectableCardOptionGroup/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SwitchButton/__tests__/__snapshots__/index.test.tsx.snap
Labels: bug

#4986 fix(ui): toaster remove blocking auto closing options
  .changeset/dark-kings-travel.md
  packages/ui/src/components/Toaster/index.tsx
Labels: enhancement

#4989 fix(Breadcrumbs): handle responsive by providing min and max width
  .changeset/social-aliens-begin.md
  packages/ui/src/components/Breadcrumbs/__stories__/Responsive.stories.tsx
  packages/ui/src/components/Breadcrumbs/__stories__/Template copy.tsx
  packages/ui/src/components/Breadcrumbs/__stories__/index.stories.tsx
  packages/ui/src/components/Breadcrumbs/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Breadcrumbs/__tests__/index.test.tsx
  packages/ui/src/components/Breadcrumbs/components/Item.tsx
Labels: enhancement

#4992 fix(List): error div in tr
  .changeset/moody-books-care.md
  packages/ui/src/components/List/HeaderRow.tsx
  packages/ui/src/components/List/SkeletonRows.tsx
  packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap
Labels: bug

#5005 fix(SwitchButton): relative card is breaking the display
  .changeset/late-coins-love.md
  packages/form/src/components/SwitchButtonField/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SwitchButton/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SwitchButton/index.tsx
Labels: hotfix

#4965 fix(UnitInput): not to be disabled when only one option
  .changeset/thin-pugs-drive.md
  packages/ui/src/components/UnitInput/index.tsx
Labels: bug

#5023 fix(SelectInputV2): new prop portal target for dropdown
  .changeset/neat-ends-battle.md
  packages/ui/src/components/SelectInputV2/Dropdown.tsx
  packages/ui/src/components/SelectInputV2/__stories__/DropdownPortalTarget.stories.tsx
  packages/ui/src/components/SelectInputV2/__stories__/index.stories.tsx
  packages/ui/src/components/SelectInputV2/index.tsx
Labels: enhancement

#5022 fix(UnitInput): value to change in controlled
  .changeset/warm-wombats-kiss.md
  packages/ui/src/components/UnitInput/index.tsx
Labels: bug

#4988 fix: navigation and expandable better performances
  .changeset/small-paths-bake.md
  .changeset/tangy-times-take.md
  packages/plus/src/components/Navigation/Footer.tsx
  packages/plus/src/components/Navigation/__stories__/Playground.stories.tsx
  packages/plus/src/components/Navigation/__tests__/__snapshots__/index.test.tsx.snap
  packages/plus/src/components/Navigation/components/Group.tsx
  packages/plus/src/components/Navigation/components/Item.tsx
  packages/plus/src/components/Navigation/components/PinnedItems.tsx
  packages/ui/src/components/Expandable/__stories__/NoAnimations.stories.tsx
  packages/ui/src/components/Expandable/__stories__/index.stories.tsx
  packages/ui/src/components/Expandable/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Expandable/index.tsx
Labels: enhancement

#5032 feat(Stack): new prop min and max width
  .changeset/lucky-jars-dress.md
  packages/ui/src/components/Stack/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Stack/__tests__/index.test.tsx
  packages/ui/src/components/Stack/index.tsx
Labels: enhancement

#5036 feat(Bullet): add new sizes xsmall and xxsmall
  .changeset/modern-chicken-train.md
  packages/plus/src/components/FAQ/__tests__/__snapshots__/index.test.tsx.snap
  packages/plus/src/components/SteppedListCard/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Bullet/__stories__/Sizes.stories.tsx
  packages/ui/src/components/Bullet/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Bullet/__tests__/index.test.tsx
  packages/ui/src/components/Bullet/index.tsx
  packages/ui/src/components/StepList/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Stepper/__tests__/__snapshots__/index.test.tsx.snap
Labels: enhancement

#5050 fix(SelectInputV2): sanitize SearchBarDropdown
  .changeset/big-candies-dream.md
  packages/ui/src/components/SelectInputV2/SearchBarDropdown.tsx
Labels: bug

#5054 ci: fix unit test on main
  packages/form/src/components/TimeInputFieldV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/TimeInputFieldV2/__tests__/index.test.tsx
Labels: ci

#5055 fix: type utility simplified usage
  .changeset/ninety-coats-camp.md
  packages/plus/src/types.ts
Labels: bug

#5039 feat(icons): export type names in icons
  .changeset/tender-loops-change.md
  packages/icons/src/components/CategoryIcon/__generatedIcons__/index.ts
  packages/icons/src/components/Icon/__generatedIcons__/index.ts
  packages/icons/src/components/Logo/__generatedIcons__/index.ts
  packages/icons/src/components/ProductIcon/__generatedIcons__/index.ts
  utils/scripts/generate-icons-file.tsx
Labels: enhancement

#5009 feat(icons): new icon partner space
  .changeset/clean-moles-cheat.md
  packages/icons/src/components/Icon/__generatedIcons__/PartnerSpaceIcon.tsx
  packages/icons/src/components/Icon/__generatedIcons__/index.ts
  packages/icons/src/components/Icon/assets/default/partner-space.svg
  packages/icons/src/components/Icon/assets/small/partner-space.svg
Labels: enhancement

#5057 fix(SelectInputFieldV2): spread props to avoid missing some of them
  .changeset/wicked-nights-slide.md
  packages/form/src/components/SelectInputFieldV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/SelectInputFieldV2/index.tsx
Labels: bug

#5051 fix(SelectableCard): bubble event on checkbox type
  .changeset/curvy-shirts-carry.md
  e2e/App.tsx
  e2e/package.json
  e2e/tests/selectableCardComplexChildren/render.tsx
  e2e/tests/selectableCardComplexChildren/test.spec.ts
  e2e/tests/template/test.spec.ts
  packages/form/src/components/SelectableCardField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/SelectableCardGroupField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/SelectableCardOptionGroupField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/SwitchButtonField/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectableCard/__stories__/Examples.stories.tsx
  packages/ui/src/components/SelectableCard/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectableCard/index.tsx
  packages/ui/src/components/SelectableCardGroup/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectableCardOptionGroup/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SwitchButton/__tests__/__snapshots__/index.test.tsx.snap
  pnpm-lock.yaml
Labels: bug
