Repository scaleway/ultraviolet, pull requests merged in 2025-02, with the labels that each got.

#4728 ci: fix corepack issue
  Dockerfile
Labels: bug

#4717 feat(illustrations): new illustration file storage
  .changeset/wise-wasps-do.md
  packages/illustrations/src/assets/products/fileStorage/file-storage-content.webp
  packages/illustrations/src/assets/products/fileStorage/file-storage-keyvisual.webp
  packages/illustrations/src/assets/products/fileStorage/file-storage-original.webp
  packages/illustrations/src/assets/products/fileStorage/file-storage-wire.svg
  packages/illustrations/src/assets/products/fileStorage/index.ts
  packages/illustrations/src/assets/products/index.ts
Labels: enhancement

#4733 feat(illustrations): new illustration onboarding background
  .changeset/early-clocks-care.md
  packages/illustrations/src/assets/various/onboarding/auth-background.webp
  packages/illustrations/src/assets/various/onboarding/index.ts
Labels: UPDATE-MINOR

#4731 fix(charts): issues with dark and darker mode
  .changeset/witty-pumas-cheat.md
  packages/ui/src/components/BarChart/index.tsx
  packages/ui/src/components/LineChart/Tooltip.tsx
  packages/ui/src/components/LineChart/__tests__/__snapshots__/Tooltip.test.tsx.snap
  packages/ui/src/components/LineChart/index.tsx
Labels: bug

#4729 fix(Dialog): to have correct icon with sentiment danger and warning
  .changeset/seven-insects-look.md
  packages/ui/src/components/Dialog/index.tsx
Labels: bug

#4742 refactor(icons): remove some legacy icons usages in the lib and improve button
  .changeset/shiny-cups-smoke.md
  packages/form/src/components/DateField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/SubmitErrorAlert/__tests__/__snapshots__/index.test.tsx.snap
  packages/icons/src/components/Icon/Icon.tsx
  packages/plus/src/components/ContentCard/__tests__/__snapshots__/index.test.tsx.snap
  packages/plus/src/components/ContentCard/index.tsx
  packages/plus/src/components/ContentCardGroup/Card.tsx
  packages/plus/src/components/ContentCardGroup/__tests__/__snapshots__/index.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Regular.test.tsx.snap
  packages/plus/src/components/Navigation/__tests__/__snapshots__/index.test.tsx.snap
  packages/plus/src/components/Navigation/components/Item.tsx
  packages/ui/src/__stories__/migrations/MigrationIconUsages.mdx
  packages/ui/src/components/Alert/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Alert/index.tsx
  packages/ui/src/components/Avatar/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Avatar/index.tsx
  packages/ui/src/components/AvatarV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/AvatarV2/index.tsx
  packages/ui/src/components/Button/__stories__/AsLink.stories.tsx
  packages/ui/src/components/Button/__stories__/IconOnly.stories.tsx
  packages/ui/src/components/Button/__stories__/IconPosition.stories.tsx
  packages/ui/src/components/Button/__stories__/index.stories.tsx
  packages/ui/src/components/Button/constants.ts
  packages/ui/src/components/Button/index.tsx
  packages/ui/src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/GlobalAlert/index.tsx
  packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/PasswordCheck/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Table/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TextArea/index.tsx
Labels: refactor

#4755 feat(icons): new category icon environmental footprint
  .changeset/healthy-kiwis-attack.md
  packages/icons/src/components/CategoryIcon/__generatedIcons__/EnvironmentalFootprintCategoryIcon.tsx
  packages/icons/src/components/CategoryIcon/__generatedIcons__/index.ts
  packages/icons/src/components/CategoryIcon/assets/environmental-footprint.svg
Labels: enhancement

#4737 feat(DateInput): new prop input
  .changeset/cold-bananas-poke.md
  .changeset/spicy-files-fold.md
  packages/form/src/components/DateField/__stories__/Input.stories.tsx
  packages/form/src/components/DateField/__stories__/index.stories.tsx
  packages/form/src/components/DateField/index.tsx
  packages/ui/src/components/DateInput/Context.tsx
  packages/ui/src/components/DateInput/__stories__/Calendar.stories.tsx
  packages/ui/src/components/DateInput/__stories__/Template.tsx
  packages/ui/src/components/DateInput/__stories__/index.stories.tsx
  packages/ui/src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/DateInput/__tests__/index.test.tsx
  packages/ui/src/components/DateInput/components/CalendarContent.tsx
  packages/ui/src/components/DateInput/components/CalendarDaily.tsx
  packages/ui/src/components/DateInput/components/CalendarMonthly.tsx
  packages/ui/src/components/DateInput/components/Popup.tsx
  packages/ui/src/components/DateInput/constants.ts
  packages/ui/src/components/DateInput/helpers.ts
  packages/ui/src/components/DateInput/index.tsx
Labels: enhancement

#4760 fix(Navigation): wrong icons and wrong size
  .changeset/nervous-rings-add.md
  packages/plus/src/components/Navigation/__tests__/__snapshots__/index.test.tsx.snap
  packages/plus/src/components/Navigation/components/Item.tsx
Labels: bug

#4761 fix(icons): broken icons
  .changeset/grumpy-ladybugs-fail.md
  package.json
  packages/form/src/components/SubmitErrorAlert/__tests__/__snapshots__/index.test.tsx.snap
  packages/icons/src/components/CategoryIcon/__generatedIcons__/EnvironmentalFootprintCategoryIcon.tsx
  packages/icons/src/components/Icon/__generatedIcons__/AlertCircleIcon.tsx
  packages/icons/src/components/Icon/__generatedIcons__/BookOpenOutlineIcon.tsx
  packages/icons/src/components/Icon/__generatedIcons__/BookOpenOutlineOutlineIcon.tsx
  packages/icons/src/components/Icon/__generatedIcons__/CalculatorIcon.tsx
  packages/icons/src/components/Icon/__generatedIcons__/CheckCircleIcon.tsx
  packages/icons/src/components/Icon/__generatedIcons__/ClockOutlineIcon.tsx
  packages/icons/src/components/Icon/__generatedIcons__/ClockOutlineOutlineIcon.tsx
  packages/icons/src/components/Icon/__generatedIcons__/DeleteIcon.tsx
  packages/icons/src/components/Icon/__generatedIcons__/DeleteOutlineIcon.tsx
  packages/icons/src/components/Icon/__generatedIcons__/DocIcon.tsx
  packages/icons/src/components/Icon/__generatedIcons__/EyeIcon.tsx
  packages/icons/src/components/Icon/__generatedIcons__/EyeOffIcon.tsx
  packages/icons/src/components/Icon/__generatedIcons__/HelpCircleIcon.tsx
  packages/icons/src/components/Icon/__generatedIcons__/IdIcon.tsx
  packages/icons/src/components/Icon/__generatedIcons__/InformationIcon.tsx
  packages/icons/src/components/Icon/__generatedIcons__/LockIcon.tsx
  packages/icons/src/components/Icon/__generatedIcons__/LockOutlineIcon.tsx
  packages/icons/src/components/Icon/__generatedIcons__/PlayIcon.tsx
  packages/icons/src/components/Icon/__generatedIcons__/PrivacyOutlineIcon.tsx
  packages/icons/src/components/Icon/__generatedIcons__/RocketIcon.tsx
  packages/icons/src/components/Icon/__generatedIcons__/StopIcon.tsx
  packages/icons/src/components/Icon/assets/default-outline/book-open-outline.svg
  packages/icons/src/components/Icon/assets/default-outline/clock-outline.svg
  packages/icons/src/components/Icon/assets/default-outline/delete.svg
  packages/icons/src/components/Icon/assets/default-outline/lock.svg
  packages/icons/src/components/Icon/assets/default-outline/privacy.svg
  packages/icons/src/components/Icon/assets/default-solid/alert-circle.svg
  packages/icons/src/components/Icon/assets/default-solid/book-open-outline.svg
  packages/icons/src/components/Icon/assets/default-solid/calculator.svg
  packages/icons/src/components/Icon/assets/default-solid/check-circle.svg
  packages/icons/src/components/Icon/assets/default-solid/clock-outline.svg
  packages/icons/src/components/Icon/assets/default-solid/delete.svg
  packages/icons/src/components/Icon/assets/default-solid/doc.svg
  packages/icons/src/components/Icon/assets/default-solid/eye-off.svg
  packages/icons/src/components/Icon/assets/default-solid/eye.svg
  packages/icons/src/components/Icon/assets/default-solid/help-circle.svg
  packages/icons/src/components/Icon/assets/default-solid/id.svg
  packages/icons/src/components/Icon/assets/default-solid/information.svg
  packages/icons/src/components/Icon/assets/default-solid/lock.svg
  packages/icons/src/components/Icon/assets/default-solid/play.svg
  packages/icons/src/components/Icon/assets/default-solid/rocket.svg
  packages/icons/src/components/Icon/assets/default-solid/stop.svg
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Regular.test.tsx.snap
  packages/ui/src/components/Alert/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Avatar/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SearchInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Table/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TagInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TextArea/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TextInputV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TimeInputV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/UnitInput/__tests__/__snapshots__/index.test.tsx.snap
  pnpm-lock.yaml
  scripts/generate-icons-file.ts
Labels: bug, hotfix

#4759 fix(Table): cell to have all available sentiment as type
  .changeset/fifty-cycles-smell.md
  packages/ui/src/components/Table/Cell.tsx
Labels: bug

#4741 fix(DateInput): range fixes
  .changeset/breezy-camels-join.md
  packages/ui/src/components/DateInput/Context.tsx
  packages/ui/src/components/DateInput/__stories__/Range.stories.tsx
  packages/ui/src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/DateInput/__tests__/index.test.tsx
  packages/ui/src/components/DateInput/components/CalendarDaily.tsx
  packages/ui/src/components/DateInput/components/CalendarMonthly.tsx
  packages/ui/src/components/DateInput/index.tsx
Labels: bug

#4752 feat(List): new prop highlightAnimation
  .changeset/dirty-dragons-know.md
  packages/ui/src/components/List/Row.tsx
  packages/ui/src/components/List/__stories__/HighlightAnimation.stories.tsx
  packages/ui/src/components/List/__stories__/index.stories.tsx
  packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap
Labels: enhancement

#4758 refactor: remove some more legacy icons and deprecated others
  .changeset/curvy-beers-roll.md
  packages/ui/src/__stories__/migrations/MigrationIconUsages.mdx
  packages/ui/src/components/Badge/__stories__/Icon.stories.tsx
  packages/ui/src/components/Badge/index.tsx
  packages/ui/src/components/Banner/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Breadcrumbs/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/EmptyState/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/GlobalAlert/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Link/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Link/index.tsx
  packages/ui/src/components/Separator/__stories__/Icon.stories.tsx
  packages/ui/src/components/Separator/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Separator/__tests__/index.test.tsx
  packages/ui/src/components/Separator/index.tsx
  packages/ui/src/components/Tabs/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Toaster/__tests__/__snapshots__/index.test.tsx.snap
Labels: refactor

#4764 docs(Slider): add partial option example
  packages/ui/src/components/Slider/__stories__/Options.stories.tsx
Labels: documentation

#4768 fix(Navigation): allow better links on navigation items
  .changeset/cyan-pants-search.md
  .changeset/slimy-laws-grab.md
  packages/plus/src/components/Navigation/__stories__/Playground.stories.tsx
  packages/plus/src/components/Navigation/components/Item.tsx
  packages/ui/src/components/MenuV2/components/Item.tsx
Labels: enhancement

#4765 fix(Popup): better compute placement
  .changeset/beige-suits-shake.md
  packages/ui/src/components/Popup/helpers.ts
Labels: bug

#4780 fix(Labe): required
  .changeset/chilled-lobsters-poke.md
  packages/form/src/components/TextAreaField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/TextInputFieldV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/UnitInputField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/VerificationCodeField/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Label/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Label/index.tsx
  packages/ui/src/components/ProgressBar/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TextArea/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TimeInputV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/UnitInput/__tests__/__snapshots__/index.test.tsx.snap
Labels: bug

#4763 fix(Modal): select input not closing inside modal when clicking outside
  .changeset/brave-guests-thank.md
  e2e/tests/componentsWithinModal/test.spec.ts
  packages/ui/src/components/Modal/components/Dialog.tsx
Labels: bug

#4796 fix(ProgressBar): label not correctly set in row mode
  .changeset/little-lions-report.md
  packages/ui/src/components/ProgressBar/__stories__/Label.stories.tsx
  packages/ui/src/components/ProgressBar/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/ProgressBar/index.tsx
Labels: bug

#4797 fix: all group inputs
  .changeset/thick-pandas-hunt.md
  packages/ui/src/components/CheckboxGroup/index.tsx
  packages/ui/src/components/RadioGroup/index.tsx
  packages/ui/src/components/ToggleGroup/index.tsx
Labels: bug

#4793 refactor(icons): remove deprecated icons used internally and add more documentation
  .changeset/tiny-jars-pump.md
  packages/form/src/components/SelectInputField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/TagInputField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/TextInputField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/TimeField/__tests__/__snapshots__/index.test.tsx.snap
  packages/plus/src/components/Conversation/__tests__/__snapshots__/index.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/CustomUnitInput.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Item.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Region.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Regular.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Stepper.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Strong.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Unit.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Zone.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/__stories__/migrations/MigrationIconUsages.mdx
  packages/ui/src/__stories__/migrations/styles.css
  packages/ui/src/components/AvatarV2/__stories__/Variant.stories.tsx
  packages/ui/src/components/AvatarV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/AvatarV2/index.tsx
  packages/ui/src/components/AvatarV2/types.ts
  packages/ui/src/components/Bullet/__stories__/Icon.stories.tsx
  packages/ui/src/components/Bullet/index.tsx
  packages/ui/src/components/SelectInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectInput/index.tsx
  packages/ui/src/components/Stepper/__stories__/Children.stories.tsx
  packages/ui/src/components/Stepper/__stories__/Example.stories.tsx
  packages/ui/src/components/Tabs/TabMenu.tsx
  packages/ui/src/components/Tabs/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Tag/__stories__/Icons.stories.tsx
  packages/ui/src/components/Tag/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Tag/index.tsx
  packages/ui/src/components/TagInput/__stories__/LabelDescription.stories.tsx
  packages/ui/src/components/TagInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TagList/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TextArea/__stories__/Examples.stories.tsx
  packages/ui/src/components/TextInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TextInput/index.tsx
  packages/ui/src/components/TimeInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Toggle/__stories__/ComplexLabel.stories.tsx
  packages/ui/src/components/UnitInput/__stories__/LabelInformation.stories.tsx
Labels: refactor

#4810 refactor(Icon): remove fixed size by using normal one
  .changeset/big-trees-sip.md
  packages/icons/src/components/Icon/Icon.tsx
  packages/plus/src/components/ContentCard/__tests__/__snapshots__/index.test.tsx.snap
  packages/plus/src/components/ContentCardGroup/__tests__/__snapshots__/index.test.tsx.snap
  packages/plus/src/components/Navigation/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Avatar/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/ExpandableCard/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SearchInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Snippet/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Table/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Tabs/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TextArea/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TimeInputV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/UnitInput/__tests__/__snapshots__/index.test.tsx.snap
Labels: refactor
