Repository scaleway/ultraviolet, pull requests merged in 2025-05, with the labels that each got.

#5085 fix(SelectInputFieldV2): re-add the label
  .changeset/true-mirrors-carry.md
  packages/form/src/components/SelectInputFieldV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/SelectInputFieldV2/index.tsx
Labels: bug

#5074 fix(EstimateCost): fix unit state
  .changeset/wicked-yaks-clap.md
  packages/plus/src/components/EstimateCost/Components/Unit.tsx
  packages/plus/src/components/EstimateCost/__stories__/Unit.stories.tsx
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Unit.test.tsx.snap
Labels: bug

#4946 fix: selectableCard height
  .changeset/shaky-yaks-carry.md
  packages/form/src/components/DateField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/KeyValueField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/SelectInputFieldV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/SelectableCardOptionGroupField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/UnitInputField/__tests__/__snapshots__/index.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Item.test.tsx.snap
  packages/plus/src/components/Navigation/__tests__/__snapshots__/index.test.tsx.snap
  packages/plus/src/components/SteppedListCard/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Button/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Checkbox/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/CopyButton/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/MenuV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Pagination/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/PieChart/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Popover/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Popup/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Popup/index.tsx
  packages/ui/src/components/Radio/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SearchInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectableCard/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectableCard/index.tsx
  packages/ui/src/components/SelectableCardOptionGroup/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Slider/__tests__/__snapshots__/doubleSlider.test.tsx.snap
  packages/ui/src/components/Slider/__tests__/__snapshots__/singleSlider.test.tsx.snap
  packages/ui/src/components/Snippet/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SwitchButton/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Table/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Tabs/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Tag/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TagList/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Toggle/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Tooltip/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Tooltip/index.tsx
  packages/ui/src/components/UnitInput/__tests__/__snapshots__/index.test.tsx.snap
Labels: bug

#4945 feat(Link): visited state and deprecate sentiments
  .changeset/moody-clocks-crash.md
  packages/ui/src/components/Banner/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Banner/__tests__/index.test.tsx
  packages/ui/src/components/Banner/index.tsx
  packages/ui/src/components/Breadcrumbs/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Breadcrumbs/components/Item.tsx
  packages/ui/src/components/EmptyState/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/EmptyState/index.tsx
  packages/ui/src/components/GlobalAlert/GlobalAlertLink.tsx
  packages/ui/src/components/GlobalAlert/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Link/__stories__/Primary.stories.tsx
  packages/ui/src/components/Link/__stories__/Sentiments.stories.tsx
  packages/ui/src/components/Link/__stories__/index.stories.tsx
  packages/ui/src/components/Link/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Link/__tests__/index.test.tsx
  packages/ui/src/components/Link/index.tsx
  packages/ui/src/components/Tabs/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Toaster/__tests__/__snapshots__/index.test.tsx.snap
Labels: enhancement

#5073 fix(Status): to have notification prop
  .changeset/lovely-moons-dance.md
  packages/form/src/components/DateField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/KeyValueField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/NumberInputField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/NumberInputFieldV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/Submit/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/SubmitErrorAlert/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/SwitchButtonField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/TagInputField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/TextAreaField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/TextInputField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/TextInputFieldV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/UnitInputField/__tests__/__snapshots__/index.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Stepper.test.tsx.snap
  packages/plus/src/components/Navigation/__tests__/__snapshots__/index.test.tsx.snap
  packages/plus/src/components/SteppedListCard/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Alert/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Banner/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Breadcrumbs/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Button/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Button/index.tsx
  packages/ui/src/components/CopyButton/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Drawer/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/GlobalAlert/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Modal/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Notification/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/NumberInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/NumberInputV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Pagination/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Snippet/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Status/__stories__/Notification.stories.tsx
  packages/ui/src/components/Status/__stories__/Sentiments.stories.tsx
  packages/ui/src/components/Status/__stories__/index.stories.tsx
  packages/ui/src/components/Status/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Status/index.tsx
  packages/ui/src/components/Tag/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TagInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TextInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TimeInputV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Toaster/__tests__/__snapshots__/index.test.tsx.snap
Labels: enhancement

#5084 fix(Navigation): do not register item if pinned items feature is off
  .changeset/five-bars-yawn.md
  packages/plus/src/components/Navigation/__stories__/Playground.stories.tsx
  packages/plus/src/components/Navigation/components/Item.tsx
Labels: enhancement

#5102 ci: beta sync with main and releases
  .github/workflows/release.yml
  .github/workflows/sync-main-to-beta.yml
Labels: ci

#5100 refactor(Navigation): deprecated and change some types category icon items
  .changeset/nine-teeth-wave.md
  packages/plus/src/components/Navigation/__stories__/Playground.stories.tsx
  packages/plus/src/components/Navigation/__tests__/__snapshots__/index.test.tsx.snap
  packages/plus/src/components/Navigation/__tests__/index.test.tsx
  packages/plus/src/components/Navigation/components/Item.tsx
  packages/plus/src/components/Navigation/components/PinnedItems.tsx
Labels: refactor

#5120 revert(react-hook-form): useless re-render
  .changeset/polite-keys-crash.md
  packages/form/package.json
  pnpm-lock.yaml
Labels: bug

#5119 fix(Notice): icon size
  .changeset/flat-kids-like.md
  packages/form/src/components/TextInputField/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Notice/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Notice/index.tsx
  packages/ui/src/components/TextInput/__tests__/__snapshots__/index.test.tsx.snap
Labels: bug

#5113 refactor(CategoryIcon): renaming some category icons
  .changeset/spicy-sites-march.md
  packages/icons/src/components/CategoryIcon/__generated__/CostAndImpactManagementCategoryIcon.tsx
  packages/icons/src/components/CategoryIcon/__generated__/DataAndAnalyticsCategoryIcon.tsx
  packages/icons/src/components/CategoryIcon/__generated__/DomainsAndWebHostingCategoryIcon.tsx
  packages/icons/src/components/CategoryIcon/__generated__/IntegrationServicesCategoryIcon.tsx
  packages/icons/src/components/CategoryIcon/__generated__/ManagementAndGovernanceCategoryIcon.tsx
  packages/icons/src/components/CategoryIcon/__generated__/MonitoringCategoryIcon.tsx
  packages/icons/src/components/CategoryIcon/__generated__/OrganizationDashboardCategoryIcon.tsx
  packages/icons/src/components/CategoryIcon/__generated__/ServerlessComputeCategoryIcon.tsx
  packages/icons/src/components/CategoryIcon/__generated__/index.ts
  packages/icons/src/components/CategoryIcon/assets/cost-and-impact-management.svg
  packages/icons/src/components/CategoryIcon/assets/data-and-analytics.svg
  packages/icons/src/components/CategoryIcon/assets/domains-and-web-hosting.svg
  packages/icons/src/components/CategoryIcon/assets/integration-services.svg
  packages/icons/src/components/CategoryIcon/assets/management-and-governance.svg
  packages/icons/src/components/CategoryIcon/assets/monitoring.svg
  packages/icons/src/components/CategoryIcon/assets/organization-dashboard.svg
  packages/icons/src/components/CategoryIcon/assets/serverless-compute.svg
  packages/plus/src/components/Navigation/__stories__/Playground.stories.tsx
  packages/plus/src/components/Navigation/components/Item.tsx
Labels: refactor

#5126 fix: plus and form to have ui ad peer deps
  .changeset/modern-poems-lose.md
  packages/form/README.md
  packages/form/package.json
  packages/plus/README.md
  packages/plus/package.json
  pnpm-lock.yaml
Labels: enhancement

#5133 docs: update contributing documentation to include beta and releases
  CONTRIBUTING.md
  README.md
Labels: documentation

#5147 fix(Notification): improve display notification
  .changeset/crazy-colts-accept.md
  packages/ui/src/components/Notification/index.tsx
Labels: bug

#5101 docs(Modal): carousel example
  packages/ui/src/components/Modal/__stories__/Carousel.stories.tsx
  packages/ui/src/components/Modal/__stories__/Image.stories.tsx
  packages/ui/src/components/Modal/__stories__/assets/apple-silicon-m4-content.webp
  packages/ui/src/components/Modal/__stories__/assets/cost-manager-content.webp
  packages/ui/src/components/Modal/__stories__/assets/illustration.webp
  packages/ui/src/components/Modal/__stories__/assets/illustrationCorrectFormat.webp
  packages/ui/src/components/Modal/__stories__/index.stories.tsx
  packages/ui/src/components/Modal/__tests__/index.test.tsx
  packages/ui/src/components/Tag/__stories__/LongTag.stories.tsx
Labels: documentation

#5151 ci: fix timeout vitests
  vite.config.ts
Labels: ci
