Repository scaleway/ultraviolet, pull requests merged in 2025-06, with the labels that each got.

#5196 docs(SelectableCard): text weak
  packages/ui/src/components/SelectableCard/__stories__/Children.stories.tsx
  packages/ui/src/components/SelectableCard/__stories__/Examples.stories.tsx
  packages/ui/src/components/SelectableCard/__stories__/Illustration.stories.tsx
  packages/ui/src/components/SelectableCard/__stories__/Template.stories.tsx
  packages/ui/src/components/SelectableCardGroup/__stories__/Examples.stories.tsx
Labels: documentation

#5194 fix(Link): visited state prominence
  .changeset/nine-eyes-rescue.md
  packages/ui/src/components/Banner/__stories__/Variants.stories.tsx
  packages/ui/src/components/Banner/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Banner/index.tsx
  packages/ui/src/components/Breadcrumbs/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/EmptyState/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/GlobalAlert/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Link/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Link/index.tsx
  packages/ui/src/components/Tabs/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Toaster/__tests__/__snapshots__/index.test.tsx.snap
Labels: bug

#5177 refactor(Form): spread props
  .changeset/fast-dingos-rest.md
  .changeset/rotten-walls-argue.md
  packages/form/src/components/DateField/__stories__/MinMaxDate.stories.tsx
  packages/form/src/components/DateField/index.tsx
  packages/form/src/components/NumberInputFieldV2/index.tsx
  packages/form/src/components/SelectableCardField/index.tsx
  packages/form/src/components/SelectableCardGroupField/__tests__/index.test.tsx
  packages/form/src/components/SelectableCardGroupField/index.tsx
  packages/form/src/components/TagInputField/index.tsx
  packages/form/src/components/TextAreaField/index.tsx
  packages/form/src/components/TextInputFieldV2/index.tsx
  packages/form/src/components/TimeInputFieldV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/TimeInputFieldV2/index.tsx
  packages/form/src/components/ToggleField/index.tsx
  packages/form/src/components/ToggleGroupField/index.tsx
  packages/form/src/components/UnitInputField/index.tsx
  packages/form/src/components/VerificationCodeField/index.tsx
  packages/ui/src/components/DateInput/index.tsx
  packages/ui/src/components/TimeInputV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TimeInputV2/index.tsx
Labels: refactor

#5224 fix(TextInputV2): allow clearable for uncontrolled
  .changeset/plenty-peas-smoke.md
  packages/ui/src/components/TextInputV2/index.tsx
Labels: bug

#5247 fix: form values
  packages/form/src/components/DateField/index.tsx
  packages/form/src/components/NumberInputFieldV2/index.tsx
  packages/form/src/components/SelectableCardField/index.tsx
  packages/form/src/components/SelectableCardGroupField/index.tsx
  packages/form/src/components/TagInputField/index.tsx
Labels: bug

#5249 fix(stepper): wrong alignement on small and label right
  .changeset/long-mangos-remain.md
  packages/ui/src/components/Stepper/Step.tsx
  packages/ui/src/components/Stepper/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Stepper/index.tsx
Labels: bug

#5213 fix(menuV2): search text prop
  .changeset/cold-icons-stick.md
  packages/ui/src/components/MenuV2/__stories__/Searchable.stories.tsx
  packages/ui/src/components/MenuV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/MenuV2/__tests__/index.test.tsx
  packages/ui/src/components/MenuV2/components/Item.tsx
  packages/ui/src/components/MenuV2/helpers.ts
Labels: enhancement

#5260 fix(Modal): focus on disclosure
  .changeset/fancy-mice-start.md
  packages/ui/src/components/Modal/components/Disclosure.tsx
  packages/ui/src/components/Modal/index.tsx
  packages/ui/src/components/Modal/types.ts
Labels: accessibility

#5266 fix(list): border issues on safari
  .changeset/dirty-breads-joke.md
  packages/ui/src/components/List/HeaderRow.tsx
  packages/ui/src/components/List/Row.tsx
  packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/List/index.tsx
Labels: bug

#5270 fix(Navigation): active state
  .changeset/rude-paths-stick.md
  packages/plus/src/components/Navigation/components/Item.tsx
Labels: bug

#5291 feat(CategoryIcon): seven new icons
  .changeset/orange-radios-rule.md
  packages/icons/src/components/CategoryIcon/__generated__/BusinessDetailsCategoryIcon.tsx
  packages/icons/src/components/CategoryIcon/__generated__/InteractiveDemosCategoryIcon.tsx
  packages/icons/src/components/CategoryIcon/__generated__/KeyManagerCategoryIcon.tsx
  packages/icons/src/components/CategoryIcon/__generated__/OrganizationCategoryIcon.tsx
  packages/icons/src/components/CategoryIcon/__generated__/OrganizationNotificationsCategoryIcon.tsx
  packages/icons/src/components/CategoryIcon/__generated__/PrivacyCategoryIcon.tsx
  packages/icons/src/components/CategoryIcon/__generated__/ProfileCategoryIcon.tsx
  packages/icons/src/components/CategoryIcon/__generated__/ProfileNotificationsCategoryIcon.tsx
  packages/icons/src/components/CategoryIcon/__generated__/index.ts
  packages/icons/src/components/CategoryIcon/assets/business-details.svg
  packages/icons/src/components/CategoryIcon/assets/interactive-demos.svg
  packages/icons/src/components/CategoryIcon/assets/key-manager.svg
  packages/icons/src/components/CategoryIcon/assets/organization-notifications.svg
  packages/icons/src/components/CategoryIcon/assets/organization.svg
  packages/icons/src/components/CategoryIcon/assets/privacy.svg
  packages/icons/src/components/CategoryIcon/assets/profile-notifications.svg
  packages/icons/src/components/CategoryIcon/assets/profile.svg
Labels: enhancement

#5304 fix(UnitInput): htmlFor and id match
  .changeset/cute-geese-reply.md
  packages/form/src/components/UnitInputField/__tests__/__snapshots__/index.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/CustomUnitInput.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Item.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Region.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Regular.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Stepper.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Strong.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Unit.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Zone.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/index.test.tsx.snap
  packages/plus/src/components/OrderSummary/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/UnitInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/UnitInput/index.tsx
Labels: bug
