Repository scaleway/ultraviolet, pull requests merged in 2025-08, with the labels that each got.

#5410 fix(OfferList): spacing between rows
  .changeset/green-cobras-smash.md
  packages/plus/src/components/OfferList/__tests__/__snapshots__/index.test.tsx.snap
  packages/plus/src/components/OfferList/components/Banner.tsx
  packages/plus/src/components/OfferList/components/Row.tsx
  packages/ui/src/components/List/Row.tsx
Labels: bug

#5415 fix(Table): padding on first column header
  .changeset/loud-eggs-smell.md
  packages/ui/src/components/Table/HeaderCell.tsx
  packages/ui/src/components/Table/HeaderRow.tsx
  packages/ui/src/components/Table/__stories__/SelectableColumn.stories.tsx
  packages/ui/src/components/Table/__tests__/__snapshots__/index.test.tsx.snap
Labels: bug

#5385 fix(Menu): overflow
  .changeset/few-experts-accept.md
  packages/ui/src/components/Menu/MenuContent.tsx
  packages/ui/src/components/Menu/__stories__/Shrink.stories.tsx
  packages/ui/src/components/Menu/__stories__/index.stories.tsx
  packages/ui/src/components/Menu/types.ts
  packages/ui/src/components/Tabs/__tests__/__snapshots__/index.test.tsx.snap
Labels: bug

#5413 fix(SelectInput): handle better tag display
  .changeset/two-goats-doubt.md
  packages/form/src/components/SelectInputField/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectInput/Dropdown.tsx
  packages/ui/src/components/SelectInput/SelectBar.tsx
  packages/ui/src/components/SelectInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectInput/__tests__/index.test.tsx
Labels: enhancement

#5432 chore: remove unused react-select
  .changeset/plain-games-invite.md
  packages/form/package.json
  pnpm-lock.yaml
  vite.config.ts
Labels: UPDATE-PATCH

#5435 fix: theme provider to inject theme in head
  .changeset/neat-regions-repair.md
  packages/ui/src/theme/ThemeProvider.tsx
Labels: bug

#5450 fix: select input ci
  packages/ui/src/components/SelectInput/__tests__/__snapshots__/index.test.tsx.snap
Labels: ci

#5437 fix(Snippet): remove after element on most of the lines
  .changeset/fluffy-bananas-type.md
  packages/ui/src/components/Snippet/__stories__/Multiline.stories.tsx
  packages/ui/src/components/Snippet/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Snippet/index.tsx
Labels: bug

#5439 fix(form): remove all emotion usages
  .changeset/deep-peas-live.md
  packages/form/src/components/CheckboxField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/CheckboxGroupField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/DateInputField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/Form/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/Form/index.tsx
  packages/form/src/components/KeyValueField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/NumberInputField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/RadioField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/RadioGroupField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/SelectInputField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/SelectableCardField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/SelectableCardGroupField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/SelectableCardOptionGroupField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/SliderField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/Submit/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/SubmitErrorAlert/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/SwitchButtonField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/TagInputField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/TextAreaField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/TextInputField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/TimeInputField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/ToggleField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/ToggleGroupField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/UnitInputField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/VerificationCodeField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/providers/ErrorContext/__tests__/__snapshots__/index.test.tsx.snap
Labels: enhancement, refactor

#5452 fix(button): wrong sizes
  packages/ui/src/components/Button/styles.css.ts
Labels: bug

#5465 fix: style on individual stories
  .storybook/preview.tsx
Labels: bug

#5424 feat: new component key
  .changeset/dark-masks-cry.md
  packages/ui/src/components/Key/__stories__/Disabled.stories.tsx
  packages/ui/src/components/Key/__stories__/Playground.stories.tsx
  packages/ui/src/components/Key/__stories__/Prominence.stories.tsx
  packages/ui/src/components/Key/__stories__/Sentiment.stories.tsx
  packages/ui/src/components/Key/__stories__/Size.stories.tsx
  packages/ui/src/components/Key/__stories__/SpeciaKeys.stories.tsx
  packages/ui/src/components/Key/__stories__/Template.stories.tsx
  packages/ui/src/components/Key/__stories__/Usage.stories.tsx
  packages/ui/src/components/Key/__stories__/index.stories.tsx
  packages/ui/src/components/Key/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Key/__tests__/index.test.tsx
  packages/ui/src/components/Key/index.tsx
  packages/ui/src/components/SearchInput/Key.tsx
  packages/ui/src/components/SearchInput/KeyGroup.tsx
  packages/ui/src/components/SearchInput/__stories__/CustomShortcut.stories.tsx
  packages/ui/src/components/SearchInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SearchInput/__tests__/index.test.tsx
  packages/ui/src/components/index.ts
Labels: enhancement

#5469 refactor: vanilla extract banner and theme on stories
  .changeset/strong-cats-float.md
  .storybook/preview.tsx
  packages/ui/src/components/Banner/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Banner/index.tsx
  packages/ui/src/components/Banner/styles.css.ts
Labels: refactor

#5467 feat(Avatar): use vanilla extract
  .changeset/rotten-coins-glow.md
  packages/ui/src/components/Avatar/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Avatar/index.tsx
  packages/ui/src/components/Avatar/styles.css.ts
  packages/ui/src/components/Avatar/variables.css.ts
Labels: refactor
