Repository scaleway/ultraviolet, pull requests merged in 2025-01, with the labels that each got.

#4614 fix(Modal): remove unecessary stop propagation
  .changeset/gorgeous-jokes-give.md
  packages/ui/src/components/Modal/__stories__/NestedModal.stories.tsx
  packages/ui/src/components/Modal/__stories__/WithSelectInput.stories.tsx
  packages/ui/src/components/Modal/__stories__/index.stories.tsx
  packages/ui/src/components/Modal/components/Dialog.tsx
Labels: bug

#4602 feat(icons): use rem on icons
  .changeset/stupid-teachers-jump.md
  packages/form/src/components/DateField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/SelectInputFieldV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/UnitInputField/__tests__/__snapshots__/index.test.tsx.snap
  packages/icons/src/components/Icon/Icon.tsx
  packages/icons/src/components/Logo/Icon.tsx
  packages/icons/src/components/ProductIcon/Icon.tsx
  packages/plus/src/components/FAQ/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/AvatarV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Chip/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SearchInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectableCard/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Table/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TextInputV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/UnitInput/__tests__/__snapshots__/index.test.tsx.snap
Labels: enhancement

#4595 fix(Text): add strike through on text
  .changeset/dry-fishes-allow.md
  packages/plus/src/components/EstimateCost/Components/Item.tsx
  packages/plus/src/components/EstimateCost/__stories__/NewPrice.stories.tsx
  packages/plus/src/components/EstimateCost/__stories__/index.stories.tsx
  packages/ui/src/components/Text/index.tsx
Labels: enhancement

#4604 feat(MenuV2): add search feature in menu
  .changeset/healthy-avocados-give.md
  packages/ui/src/components/Breadcrumbs/__stories__/AdvancedUsage.stories.tsx
  packages/ui/src/components/MenuV2/MenuContent.tsx
  packages/ui/src/components/MenuV2/MenuProvider.tsx
  packages/ui/src/components/MenuV2/__stories__/FunctionDisclosure.stories.tsx
  packages/ui/src/components/MenuV2/__stories__/Searchable.stories.tsx
  packages/ui/src/components/MenuV2/__stories__/index.stories.tsx
  packages/ui/src/components/MenuV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/MenuV2/__tests__/index.test.tsx
  packages/ui/src/components/MenuV2/components/Group.tsx
  packages/ui/src/components/MenuV2/components/Item.tsx
  packages/ui/src/components/MenuV2/constants.ts
  packages/ui/src/components/MenuV2/helpers.ts
  packages/ui/src/components/MenuV2/index.tsx
  packages/ui/src/components/MenuV2/types.ts
  packages/ui/src/components/Tabs/TabMenuItem.tsx
  packages/ui/src/components/Tabs/__tests__/__snapshots__/index.test.tsx.snap
Labels: enhancement

#4648 ci(storybook): fix not finishing build on ci
  package.json
  pnpm-lock.yaml
Labels: bug

#4650 docs(storybook): add dots in background for better visual
  .storybook/preview.tsx
Labels: documentation

#4653 fix(MenuV2): better search with groups and label description
  .changeset/giant-jobs-remember.md
  packages/ui/src/components/Breadcrumbs/__stories__/AdvancedUsage.stories.tsx
  packages/ui/src/components/MenuV2/MenuContent.tsx
  packages/ui/src/components/MenuV2/__stories__/Group.stories.tsx
  packages/ui/src/components/MenuV2/__stories__/Searchable.stories.tsx
  packages/ui/src/components/MenuV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/MenuV2/__tests__/index.test.tsx
  packages/ui/src/components/MenuV2/components/Group.tsx
  packages/ui/src/components/MenuV2/helpers.ts
  packages/ui/src/components/Tabs/__tests__/__snapshots__/index.test.tsx.snap
Labels: enhancement

#4664 fix(Modal): modal opened in select input is broken
  .changeset/late-tomatoes-raise.md
  packages/ui/src/components/Modal/__stories__/WithSelectInput.stories copy.tsx
  packages/ui/src/components/Modal/__stories__/WithSelectInputAsDisclosure.stories.tsx
  packages/ui/src/components/Modal/__stories__/index.stories.tsx
  packages/ui/src/components/SelectInputV2/Dropdown.tsx
Labels: bug

#4537 refactor: pagination
  .changeset/dirty-fishes-flash.md
  packages/ui/src/components/Pagination/PaginationButtons.tsx
  packages/ui/src/components/Pagination/PerPage.tsx
  packages/ui/src/components/Pagination/__stories__/Controlled.stories.tsx
  packages/ui/src/components/Pagination/__stories__/PerPage.stories.tsx
  packages/ui/src/components/Pagination/__stories__/Playground.stories.tsx
  packages/ui/src/components/Pagination/__stories__/index.stories.tsx
  packages/ui/src/components/Pagination/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Pagination/__tests__/getPageNumbers.test.ts
  packages/ui/src/components/Pagination/__tests__/index.test.tsx
  packages/ui/src/components/Pagination/getPageNumbers.ts
  packages/ui/src/components/Pagination/index.tsx
Labels: refactor

#4668 fix(NumberInputV2): styling when disabled
  .changeset/thirty-glasses-rush.md
  packages/form/src/components/NumberInputFieldV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/SliderField/__tests__/__snapshots__/index.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Stepper.test.tsx.snap
  packages/ui/src/components/NumberInputV2/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/NumberInputV2/index.tsx
  packages/ui/src/components/Slider/__tests__/__snapshots__/doubleSlider.test.tsx.snap
  packages/ui/src/components/Slider/__tests__/__snapshots__/singleSlider.test.tsx.snap
Labels: bug

#4669 fix(Slider): disable input on disabled sliders
  .changeset/weak-peas-marry.md
  packages/ui/src/components/Slider/components/DoubleSlider.tsx
  packages/ui/src/components/Slider/components/SingleSlider.tsx
Labels: bug

#4646 fix(Popover): to be attached in body when not in a modal
  .changeset/lovely-rocks-laugh.md
  packages/ui/src/components/Popover/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Popover/index.tsx
Labels: enhancement

#4690 fix(Tooltip): wrong arrow alignement due to popup
  .changeset/tasty-tables-help.md
  packages/ui/src/components/Popup/helpers.ts
Labels: bug

#4695 fix(Button): remove illegal div wrapping children
  .changeset/moody-yaks-watch.md
  packages/form/src/components/NumberInputField/__tests__/__snapshots__/index.test.tsx.snap
  packages/plus/src/components/Navigation/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Button/index.tsx
  packages/ui/src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/NumberInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Pagination/__tests__/__snapshots__/index.test.tsx.snap
Labels: bug

#4698 ci(themes): add theme in s3 and make it available via edge services
  .changeset/cyan-bulldogs-matter.md
  .github/workflows/theme-upload.yml
  packages/themes/README.md
Labels: enhancement

#4674 fix(DateInput): max date bug
  .changeset/eight-pugs-share.md
  packages/ui/src/components/DateInput/components/Popup.tsx
Labels: bug
