Repository scaleway/ultraviolet, pull requests merged in 2025-09, with the labels that each got.

#5527 fix(NumberInput): side buttons not working on re-render
  .changeset/eight-wings-add.md
  packages/ui/src/components/NumberInput/index.tsx
Labels: bug

#5546 fix(Navigation): add as prop on stack polymorphic component
  .changeset/good-hoops-invite.md
  packages/plus/src/components/Navigation/__tests__/__snapshots__/index.test.tsx.snap
  packages/plus/src/components/Navigation/components/Item.tsx
  packages/ui/src/components/ExpandableCard/index.tsx
  packages/ui/src/components/Stack/index.tsx
  packages/ui/src/components/Stack/types.ts
Labels: bug

#5560 fix(CodeEditor): to have fall back value when extension doesn't exists
  .changeset/puny-streets-smash.md
  packages/plus/src/components/CodeEditor/CodeEditor.tsx
Labels: bug

#5504 refactor: bullet and link vanilla extract
  .changeset/pretty-planes-ask.md
  packages/plus/src/components/FAQ/__tests__/__snapshots__/index.test.tsx.snap
  packages/plus/src/components/SteppedListCard/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Banner/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Breadcrumbs/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Bullet/__stories__/Disabled.stories.tsx
  packages/ui/src/components/Bullet/__stories__/index.stories.tsx
  packages/ui/src/components/Bullet/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Bullet/__tests__/index.test.tsx
  packages/ui/src/components/Bullet/constants.ts
  packages/ui/src/components/Bullet/index.tsx
  packages/ui/src/components/Bullet/styles.css.ts
  packages/ui/src/components/EmptyState/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/GlobalAlert/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Link/__stories__/OneLine.stories.tsx
  packages/ui/src/components/Link/__stories__/Prominence.stories.tsx
  packages/ui/src/components/Link/__stories__/styles.css.ts
  packages/ui/src/components/Link/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Link/__tests__/index.test.tsx
  packages/ui/src/components/Link/constants.ts
  packages/ui/src/components/Link/index.tsx
  packages/ui/src/components/Link/styles.css.ts
  packages/ui/src/components/StepList/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/StepList/index.tsx
  packages/ui/src/components/Stepper/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Tabs/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Toaster/__tests__/__snapshots__/index.test.tsx.snap
  pnpm-lock.yaml
Labels: refactor

#5576 refactor: card and tag vanilla extract
  .changeset/wild-houses-camp.md
  packages/form/src/components/TagInputField/__tests__/__snapshots__/index.test.tsx.snap
  packages/plus/src/components/Conversation/__tests__/__snapshots__/index.test.tsx.snap
  packages/plus/src/components/FAQ/__tests__/__snapshots__/index.test.tsx.snap
  packages/plus/src/components/SteppedListCard/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Card/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Card/index.tsx
  packages/ui/src/components/Card/styles.css.ts
  packages/ui/src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Tag/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Tag/index.tsx
  packages/ui/src/components/Tag/styles.css.ts
  packages/ui/src/components/TagInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/TagList/__tests__/__snapshots__/index.test.tsx.snap
Labels: refactor

#5593 fix: drawer animation
  .changeset/famous-stars-marry.md
  packages/ui/src/components/Drawer/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Drawer/index.tsx
Labels: bug

#5578 refactor: breadcrumbs vanilla extract and prop style to button
  .changeset/yummy-pets-draw.md
  packages/ui/src/components/Breadcrumbs/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Breadcrumbs/components/Item.tsx
  packages/ui/src/components/Breadcrumbs/components/styles.css.ts
  packages/ui/src/components/Breadcrumbs/index.tsx
  packages/ui/src/components/Breadcrumbs/styles.css.ts
  packages/ui/src/components/Button/index.tsx
  packages/ui/vitest.setup.ts
Labels: refactor

#5583 refactor(ExpandableCard): to use vanilla extract and drop emotion
  .changeset/fine-buttons-call.md
  packages/ui/src/components/ExpandableCard/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/ExpandableCard/index.tsx
  packages/ui/src/components/ExpandableCard/styles.css.ts
Labels: refactor

#5586 fix(SelectInput): html tag options
  .changeset/plain-windows-add.md
  packages/form/src/components/SelectInputField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/SelectableCardOptionGroupField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/UnitInputField/__tests__/__snapshots__/index.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/CustomUnitInput.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Item.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Region.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Regular.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Stepper.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Strong.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Unit.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Zone.test.tsx.snap
  packages/plus/src/components/EstimateCost/__tests__/__snapshots__/index.test.tsx.snap
  packages/plus/src/components/OrderSummary/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Pagination/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectInput/SelectBar.tsx
  packages/ui/src/components/SelectInput/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectableCardOptionGroup/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/UnitInput/__tests__/__snapshots__/index.test.tsx.snap
Labels: accessibility

#5596 refactor(SelectableCard): migration vanilla extract
  .changeset/wild-turkeys-mate.md
  packages/form/src/components/SelectableCardField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/SelectableCardGroupField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/SelectableCardOptionGroupField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/SwitchButtonField/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectableCard/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectableCard/index.tsx
  packages/ui/src/components/SelectableCard/styles.css.ts
  packages/ui/src/components/SelectableCard/variables.css.ts
  packages/ui/src/components/SelectableCardGroup/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectableCardOptionGroup/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SwitchButton/Option.tsx
  packages/ui/src/components/SwitchButton/__tests__/__snapshots__/index.test.tsx.snap
Labels: refactor
