Repository scaleway/ultraviolet, pull requests merged in 2025-07, with the labels that each got.

#5294 fix(Expandable): animation on first render
  .changeset/tender-regions-share.md
  packages/ui/src/components/Expandable/__stories__/NestedExpandable.stories.tsx
  packages/ui/src/components/Expandable/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Expandable/index.tsx
  packages/ui/src/components/Snippet/__tests__/__snapshots__/index.test.tsx.snap
Labels: bug

#5312 fix(Modal): disclosure onClick
  .changeset/fast-results-run.md
  packages/ui/src/components/Modal/components/Disclosure.tsx
Labels: bug

#5313 fix(SwitchButton): story and imports and disabled state
  .changeset/wild-facts-hide.md
  packages/form/src/components/SwitchButtonField/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SwitchButton/Option.tsx
  packages/ui/src/components/SwitchButton/__stories__/Disabled.stories.tsx
  packages/ui/src/components/SwitchButton/__stories__/index.stories.tsx
  packages/ui/src/components/SwitchButton/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SwitchButton/__tests__/index.test.tsx
  packages/ui/src/components/SwitchButton/index.tsx
Labels: enhancement

#5323 fix(link): add aria current
  .changeset/great-tables-kick.md
  packages/ui/src/components/Link/index.tsx
Labels: enhancement

#5306 feat: remove deprecated props Card, Checkbox and Copybutton
  .changeset/little-badgers-go.md
  packages/form/src/components/CheckboxField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/CheckboxGroupField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/SelectableCardField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/SelectableCardGroupField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/SelectableCardOptionGroupField/__tests__/__snapshots__/index.test.tsx.snap
  packages/form/src/components/SwitchButtonField/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Card/__stories__/Active.stories.tsx
  packages/ui/src/components/Card/index.tsx
  packages/ui/src/components/Checkbox/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Checkbox/__tests__/index.test.tsx
  packages/ui/src/components/Checkbox/index.tsx
  packages/ui/src/components/CheckboxGroup/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/CopyButton/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/CopyButton/__tests__/index.test.tsx
  packages/ui/src/components/CopyButton/index.tsx
  packages/ui/src/components/LineChart/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectableCard/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectableCardGroup/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SelectableCardOptionGroup/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Skeleton/Slider.tsx
  packages/ui/src/components/Skeleton/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SwitchButton/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Table/__tests__/__snapshots__/index.test.tsx.snap
Labels: breaking changes

#5334 feat(OrderSummary): new prop additional info
  .changeset/brave-suns-speak.md
  packages/plus/src/components/OrderSummary/NonScrollableContent.tsx
  packages/plus/src/components/OrderSummary/__tests__/__snapshots__/index.test.tsx.snap
  packages/plus/src/components/OrderSummary/__tests__/index.test.tsx
  packages/plus/src/components/OrderSummary/index.tsx
  packages/plus/src/components/OrderSummary/types.ts
  packages/ui/src/components/SwitchButton/__tests__/__snapshots__/index.test.tsx.snap
Labels: enhancement

#5344 fix: tests lint
  packages/form/src/components/SelectInputField/__tests__/index.test.tsx
  packages/ui/src/components/NumberInput/__tests__/index.test.tsx
  packages/ui/src/components/SelectInput/__tests__/index.test.tsx
Labels: bug

#5335 fix(SwitchButton): size when children changes
  .changeset/all-candies-spend.md
  packages/ui/src/components/SwitchButton/SwitchButtonContext.tsx
  packages/ui/src/components/SwitchButton/__stories__/UpdateChildren.stories.tsx
  packages/ui/src/components/SwitchButton/__stories__/index.stories.tsx
  packages/ui/src/components/SwitchButton/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/SwitchButton/__tests__/index.test.tsx
  packages/ui/src/components/SwitchButton/index.tsx
  pnpm-lock.yaml
Labels: bug

#5355 feat: new illustrations and icons
  .changeset/curly-ways-tell.md
  .changeset/pink-bats-grow.md
  packages/icons/src/components/Icon/__generated__/BoxEssentialsIcon.tsx
  packages/icons/src/components/Icon/__generated__/BoxEssentialsOutlineIcon.tsx
  packages/icons/src/components/Icon/__generated__/index.ts
  packages/icons/src/components/Icon/assets/default-outline/box-essentials.svg
  packages/icons/src/components/Icon/assets/default-solid/box-essentials.svg
  packages/icons/src/components/Icon/assets/small-outline/box-essentials.svg
  packages/icons/src/components/Icon/assets/small-solid/box-essentials.svg
  packages/icons/src/components/ProductIcon/__generated__/CloudEssentialsProductIcon.tsx
  packages/icons/src/components/ProductIcon/__generated__/CustomModelProductIcon.tsx
  packages/icons/src/components/ProductIcon/__generated__/index.ts
  packages/icons/src/components/ProductIcon/assets/cloud-essentials.svg
  packages/icons/src/components/ProductIcon/assets/custom-model.svg
  packages/illustrations/src/assets/products/cloudEssentials/cloud-essentials-content.webp
  packages/illustrations/src/assets/products/cloudEssentials/cloud-essentials-keyvisual.webp
  packages/illustrations/src/assets/products/cloudEssentials/cloud-essentials-original.webp
  packages/illustrations/src/assets/products/cloudEssentials/cloud-essentials-wire.svg
  packages/illustrations/src/assets/products/cloudEssentials/index.ts
  packages/illustrations/src/assets/products/dedilink/dedilink-content.webp
  packages/illustrations/src/assets/products/dedilink/dedilink-keyvisual.webp
  packages/illustrations/src/assets/products/dedilink/dedilink-original.webp
  packages/illustrations/src/assets/products/dedilink/dedilink-wire.svg
  packages/illustrations/src/assets/products/dedilink/index.ts
  packages/illustrations/src/assets/products/index.ts
  packages/illustrations/src/components/WireIllustration/__generated__/Illustrations.tsx
Labels: enhancement

#5357 Revert "fix(deps): update dependency react-hook-form to v7.56.3 (#5097)"
  .changeset/eighty-walls-greet.md
  packages/form/package.json
  pnpm-lock.yaml
Labels: bug

#5365 fix(checkbox): add missing tooltip prop
  .changeset/whole-wasps-cough.md
  packages/ui/src/components/CheckboxGroup/__stories__/Template.stories.tsx
  packages/ui/src/components/CheckboxGroup/index.tsx
Labels: bug

#5255 fix(Menu): accessibility
  .changeset/thick-dragons-rush.md
  packages/ui/src/components/Menu/MenuContent.tsx
  packages/ui/src/components/Menu/MenuProvider.tsx
  packages/ui/src/components/Menu/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Menu/__tests__/index.test.tsx
  packages/ui/src/components/Menu/components/Item.tsx
  packages/ui/src/components/Menu/helpers.ts
  packages/ui/src/components/Tabs/__tests__/__snapshots__/index.test.tsx.snap
Labels: accessibility

#5353 fix(TextArea): height without prop value
  .changeset/heavy-toys-tap.md
  packages/ui/src/components/TextArea/index.tsx
Labels: bug

#5377 fix(InfoTable): title type
  .changeset/ninety-coats-accept.md
  packages/plus/src/components/InfoTable/__stories__/ComplexExample.stories.tsx
  packages/plus/src/components/InfoTable/__tests__/__snapshots__/index.test.tsx.snap
  packages/plus/src/components/InfoTable/components/Cell.tsx
Labels: bug

#5366 fix(beta): final step
  .changeset/rude-jokes-cheer.md
  packages/ui/src/__stories__/Tools/ThemeGenerator/ThemeResult/CodeIntegration.tsx
  packages/ui/src/__stories__/Tools/ThemeGenerator/ThemeResult/index.tsx
  packages/ui/src/components/Dialog/__stories__/index.stories.tsx
  packages/ui/src/components/Menu/types.ts
  packages/ui/src/components/Toaster/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Toaster/index.tsx
  packages/ui/src/index.ts
  packages/ui/src/theme/index.ts
Labels: refactor

#5330 feat: offerList
  .changeset/whole-rules-march.md
  packages/plus/src/components/OfferList/OfferList.tsx
  packages/plus/src/components/OfferList/OfferListProvider.tsx
  packages/plus/src/components/OfferList/__stories__/Badge.stories.tsx
  packages/plus/src/components/OfferList/__stories__/Banner.stories.tsx
  packages/plus/src/components/OfferList/__stories__/Example.stories.tsx
  packages/plus/src/components/OfferList/__stories__/Expandable.stories.tsx
  packages/plus/src/components/OfferList/__stories__/Loading.stories.tsx
  packages/plus/src/components/OfferList/__stories__/OnChangeSelect.stories.tsx
  packages/plus/src/components/OfferList/__stories__/Playground.stories.tsx
  packages/plus/src/components/OfferList/__stories__/Template.stories.tsx
  packages/plus/src/components/OfferList/__stories__/Type.stories.tsx
  packages/plus/src/components/OfferList/__stories__/index.stories.tsx
  packages/plus/src/components/OfferList/__stories__/resources.ts
  packages/plus/src/components/OfferList/__tests__/__snapshots__/index.test.tsx.snap
  packages/plus/src/components/OfferList/__tests__/index.test.tsx
  packages/plus/src/components/OfferList/__tests__/resources.ts
  packages/plus/src/components/OfferList/components/Banner.tsx
  packages/plus/src/components/OfferList/components/Cell.tsx
  packages/plus/src/components/OfferList/components/Row.tsx
  packages/plus/src/components/OfferList/constants.ts
  packages/plus/src/components/OfferList/index.ts
  packages/plus/src/components/index.ts
  packages/ui/src/components/List/Row.tsx
  packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/List/index.tsx
Labels: enhancement

#5394 fix(Menu): menu closes when hover leaves
  .changeset/shaky-kings-deny.md
  packages/ui/src/components/Menu/MenuContent.tsx
Labels: bug

#5391 fix(Modal): remove id on modal and select input scrolll
  .changeset/tasty-tables-type.md
  packages/ui/src/components/Drawer/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Modal/ModalProvider.tsx
  packages/ui/src/components/Modal/__tests__/__snapshots__/index.test.tsx.snap
  packages/ui/src/components/Modal/components/Dialog.tsx
  packages/ui/src/components/SelectInput/Dropdown.tsx
Labels: bug

#5407 feat(Navigation): add prop label description on item
  .changeset/soft-pears-hammer.md
  packages/plus/src/components/Navigation/__stories__/Playground.stories.tsx
  packages/plus/src/components/Navigation/__tests__/__snapshots__/index.test.tsx.snap
  packages/plus/src/components/Navigation/components/Item.tsx
Labels: enhancement
